Repository goalgorilla/open_social, pull requests merged in 2018-03, with the labels that each got.

#756 Issue #2925751: add custom permission for administering navigation
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.permissions.yml
  modules/social_features/social_user/social_user.routing.yml
Labels: feature request

#767 #2949340: A node with URL Alias "/user-edit" causes page to crash
  themes/socialbase/src/Plugin/Preprocess/PageTitle.php
Labels: bug

#774 Issue #2950391 by jaapjan: user export should use offset method instead
  modules/social_features/social_user_export/src/ExportUser.php
Labels: bug

#775 Issue #2950411 by jaapjan: make state field available for closed group location
  modules/social_features/social_group/config/install/field.field.group.closed_group.field_group_address.yml
Labels: bug

#769 Issue #2949847 by ribel: Remove not needed |render filters in twig templates
  modules/social_features/social_landing_page/templates/profile--featured.html.twig
  modules/social_features/social_mentions/templates/profile--profile--autocomplete_item.html.twig
  themes/socialbase/templates/profile/profile--profile--compact_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--hero.html.twig
  themes/socialbase/templates/profile/profile--profile--medium_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--small_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--table.html.twig
  themes/socialbase/templates/profile/profile--profile--teaser--anonymous.html.twig
  themes/socialbase/templates/profile/profile--profile--teaser.html.twig
Labels: bug, eci

#731 GDPR Hide profile fields
  modules/social_features/social_group/social_group.module
  modules/social_features/social_mentions/social_mentions.tokens.inc
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.field.profile.profile.field_profile_nick_name.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.storage.profile.field_profile_nick_name.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/social_profile_fields.settings.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.info.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.links.menu.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.links.task.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.permissions.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.routing.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.services.yml
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsFlushForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsBatch.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_user/social_user.module
  tests/behat/features/capabilities/profile/hide-profile-fields.feature
Labels: eci

#781 DS-4503: enable inline form errors for new installs
  social.profile
Labels: feature request

#776 ECI-702 by serhiy-chornobay: Make the user menu like dropdown on mobile
  modules/custom/activity_creator/js/notifications.js
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
  modules/social_features/social_user/templates/account-header-links.html.twig
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/dropdown/dropdown.scss
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/dropdown.css
  themes/socialblue/assets/css/navbar.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/03-molecules/dropdown/dropdown.scss
  themes/socialblue/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialblue/components/brand.scss
Labels: eci

#786 ECI-706: Fix template for private's message members
  themes/socialbase/templates/private_message/field--private-message-thread--members.html.twig
Labels: SaaS

#729 Issue #2944720 by Kingdutch: Profile anonymous theme suggestion is to…
  themes/socialbase/src/Plugin/Alter/ThemeSuggestions.php
Labels: support

#766 2919743 - Improve accessibility of Open Social, so it complies with WCAG2.0 AA
  composer.json
  drupal-org.make
  modules/social_features/social_landing_page/css/social_landing_page.featured.css
  modules/social_features/social_landing_page/css/social_landing_page.featured.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.scss
  modules/social_features/social_landing_page/templates/group--featured.html.twig
  modules/social_features/social_landing_page/templates/node--book--featured.html.twig
  modules/social_features/social_landing_page/templates/node--event--featured.html.twig
  modules/social_features/social_landing_page/templates/node--featured.html.twig
  modules/social_features/social_landing_page/templates/node--landing-page--featured.html.twig
  modules/social_features/social_landing_page/templates/node--landing-page.html.twig
  modules/social_features/social_landing_page/templates/node--page--featured.html.twig
  modules/social_features/social_landing_page/templates/node--topic--featured.html.twig
  modules/social_features/social_landing_page/templates/profile--featured.html.twig
  modules/social_features/social_post/social_post.module
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.compact.yml
  modules/social_features/social_profile/social_profile.module
  themes/socialbase/assets/css/form-elements.css
  themes/socialbase/components/00-config/variables/_forms.scss
  themes/socialbase/templates/post/form-element--field-post.html.twig
  themes/socialbase/templates/profile/profile--compact.html.twig
  themes/socialbase/templates/system/html.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/button.css
  themes/socialblue/assets/css/ckeditor.css
  themes/socialblue/assets/css/comment.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/02-atoms/button/button.scss
  themes/socialblue/components/04-organisms/comment/comment.scss
  themes/socialblue/components/brand.scss
Labels: needs work

#752 Issue #2946771 by Kingdutch: Use version constraints instead of exact…
  composer.json
Labels: support

#755 Issue #2947934: Alternative frontpage settings permission
  modules/custom/alternative_frontpage/alternative_frontpage.install
  modules/custom/alternative_frontpage/alternative_frontpage.permissions.yml
  modules/custom/alternative_frontpage/alternative_frontpage.routing.yml
Labels: feature request
