Repository goalgorilla/open_social, pull requests merged in 2018-12, with the labels that each got.

#1093 DS - 5504 As a CM+ I want to be able to edit a Existing Group's Group Type
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.permissions.yml
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/Form/SocialGroupAddForm.php
  modules/social_features/social_group/src/GroupContentVisibilityUpdate.php
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_post/src/Entity/Post.php
  tests/behat/features/capabilities/group/group-edit-type.feature
  tests/behat/features/capabilities/search/search-groups.feature
  themes/socialbase/socialbase.theme
Labels: feature request, needs review

#1128 Issue #2989988 by KingDutch: socialbase grouphero block is outdated
  modules/social_features/social_group/config/optional/block.block.groupheroblock.yml
Labels: ext, needs review

#1045 Issue #3004857 by truls1502: Update block_field 1.0.0-alpha5 to 1.0.0-alpha8
  composer.json
  drupal-org.make
Labels: ext, needs review, update

#1121 Issue #3010778 by Kingdutch: Ensure group local tasks have proper weights
  modules/social_features/social_group/social_group.links.task.yml
Labels: code refactoring, ext

#1072 Issue #3010053 by truls1502: Update override_node_options 2.3 to 2.4
  composer.json
  drupal-org.make
Labels: needs review, update

#1047 Issue #3004859 by truls1502: Update entity_reference_revisions 1.4 to 1.6
  composer.json
  drupal-org.make
Labels: Needs MOSS work, needs review, update

#1041 Issue #3004788 by truls1502: Updated private_message from 1.0 to 1.2
  composer.json
  drupal-org.make
Labels: needs review, update

#1143 Issue #2976046: add pager to community activities block in landing page
  modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
Labels: bug

#1144 Issue #2976018 by jaapjan: reset page number when searching
  modules/social_features/social_search/src/Form/SearchContentForm.php
  modules/social_features/social_search/src/Form/SearchHeroForm.php
Labels: bug, needs review

#1044 Issue #3004855 by truls1502: Update addtoany 8.x-1.9 to 8.x-1.10
  composer.json
  drupal-org.make
Labels: update

#652 Issue #2927180: As a LU I want to get a notification when someone comments on a topic commented on
  modules/social_features/social_event/social_event.module
  modules/social_features/social_follow_content/social_follow_content.api.php
  modules/social_features/social_follow_content/social_follow_content.module
  modules/social_features/social_topic/social_topic.module
Labels: eci, feature request

#1142 #3017264 by bramtenhove: Reduce the amount of activity stream items
  modules/social_features/social_activity/config/install/views.view.activity_stream.yml
  modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
Labels: feature request

#967 Issue #2986904 by Kingdutch: Refactor the AccountHeaderBlock
  modules/custom/activity_creator/activity_creator.module
  modules/custom/social_language/src/Plugin/Block/LanguageSwitcherBlock.php
  modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_book/social_book.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_follow_content/social_follow_content.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_page/social_page.module
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_topic/social_topic.module
  modules/social_features/social_user/social_user.api.php
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Element/AccountHeaderElement.php
  modules/social_features/social_user/src/Element/UnwrappedContainer.php
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
  modules/social_features/social_user/templates/account-header-links.html.twig
  modules/social_features/social_user/templates/unwrapped-container.html.twig
  tests/behat/features/capabilities/language/change-language.feature
  themes/socialbase/templates/block/block--account-header-block.html.twig
  themes/socialbase/templates/views/views-view--activity-stream-notifications--block.html.twig
  themes/socialbase/templates/views/views-view-unformatted--activity-stream-notifications--block.html.twig
Labels: code refactoring, needs work

#1148 #3018168 - Hotfix 4.1 - Fix read count placement and updateReadCount on click.
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_user/src/Element/AccountHeaderElement.php
  themes/socialbase/templates/views/views-view--activity-stream-notifications--page.html.twig
  themes/socialbase/templates/views/views-view.html.twig
Labels: bug, code refactoring, needs review

#1147 Issue #3018215 by robertragas: Add context for comment button to aid …
  modules/social_features/social_comment/social_comment.module
Labels: bug, support

#1151 Issue #3018721 : As a SM, I want to send an e-mail to members via bulk operation
  composer.json
  drupal-org.make
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
  modules/social_features/social_user/social_user.info.yml
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  modules/social_features/social_user_export/js/social-user-export.js
  modules/social_features/social_user_export/social_user_export.info.yml
  modules/social_features/social_user_export/social_user_export.libraries.yml
  modules/social_features/social_user_export/social_user_export.module
  modules/social_features/social_user_export/social_user_export.routing.yml
  modules/social_features/social_user_export/src/Controller/DownloadController.php
  modules/social_features/social_user_export/src/ExportUser.php
  modules/social_features/social_user_export/src/Form/ExportUserConfirm.php
  modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
  modules/social_features/social_user_export/src/Plugin/views/field/UserBulkForm.php
  modules/social_features/social_user_export/src/SocialUserExportOverrides.php
  tests/behat/features/capabilities/administration/view-block-users.feature
Labels: feature request

#1165 Issue #3020961 : Filter on member by their last login date on people overview
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
  modules/social_features/social_user/social_user.module
Labels: feature request, needs review

#1158 #3020038 - Group content manage members tab order weight
  modules/social_features/social_group/social_group.module
Labels: bug, needs review

#1170 Issue #3021952 by truls1502: Update bower-asset/tablesaw from v3.0.9 to v3.1.0
  composer.json
Labels: update

#1138 DS-5959 Event Organizer recieves notification for Enrollments.
  modules/custom/activity_basics/activity_basics.api.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OrganizerActivityContext.php
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/custom/activity_creator/src/Entity/Activity.php
  modules/social_features/social_event/config/optional/message.template.activity_on_events_im_organizing.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.tokens.inc
Labels: feature request, needs language review, needs review

#1146 Issue #2994207: Checkboxes are not shown in the Social Blue theme because checkboxes need titles
  themes/socialbase/templates/form/form-element-label.html.twig
Labels: bug, ext, needs review

#1156 Move profile display 'Expertise' field above 'Interests'
  themes/socialbase/templates/profile/profile--profile--default.html.twig
Labels: ext, feature request, needs review

#1152 #3022657 / SHN-267: Add some predefined styles to the CKEditor (full_html)
  modules/social_features/social_editor/config/install/editor.editor.full_html.yml
Labels: eci, feature request

#1149 2928228 - Open Social (admin) configuration page category page
  modules/social_features/social_core/social_core.links.menu.yml
  modules/social_features/social_core/social_core.routing.yml
Labels: bug, eci

#1161 Issue #3020522: Read more link is shown twice in featured
  modules/social_features/social_landing_page/templates/node--event--featured.html.twig
  modules/social_features/social_landing_page/templates/node--landing-page--featured.html.twig
  modules/social_features/social_landing_page/templates/node--page--featured.html.twig
  modules/social_features/social_landing_page/templates/node--topic--featured.html.twig
  modules/social_features/social_landing_page/templates/profile--featured.html.twig
Labels: bug

#1166 Issue #3021140 by robertragas: relocate empty space to place where we…
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
Labels: Needs MOSS work, bug, support

#1160 Issue #3020084 by ribel: Replace hardcoded 'Data policy' page title with value from variable
  tests/behat/features/capabilities/gdpr/create-data-policy.feature
  themes/socialbase/templates/block/block--data-policy-page-title-block.html.twig
Labels: bug, eci

#1163 #3020575: Fix configuration schema for modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml
  modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml
Labels: bug, ext, needs review

#1173 Issue #3020007 : prevent error on post list when field_post does not exist
  modules/social_features/social_post/src/PostListBuilder.php
Labels: bug, needs review
