Repository goalgorilla/open_social, pull requests merged in 2018-07, with the labels that each got.

#935 #2983271: Fix default crops for square crop styles
  composer.json
  drupal-org.make
Labels: bug

#921 Issue #2980936 by Kingdutch: social_core_path_validate can break an e…
  modules/social_features/social_core/social_core.module
Labels: bug, support

#909 Issue #2979293 by Kingdutch: Change download hover text
  themes/socialbase/components/03-molecules/file/file-form.twig
  themes/socialbase/components/03-molecules/file/file-node.twig
  themes/socialbase/templates/file/download-count-file-field-formatter.html.twig
  themes/socialbase/templates/file/file-link--card.html.twig
Labels: feature request, support

#940 DS-5716 by bramtenhove: Update r4032login to 1.0
  composer.json
  drupal-org.make
Labels: update

#941 DS-5716 by bramtenhove: Update r4032login to 1.0 [1.x branch]
  composer.json
  drupal-org.make
Labels: update

#942 DS-5716: Update Drupal core to 8.5.5 [2.x]
  composer.json
  drupal-org-core.make
Labels: update

#943 DS-5716 by bramtenhove: Update Drupal core to 8.5.5 [1.x]
  composer.json
  drupal-org-core.make
Labels: update

#936 #2976586: The group tab on a users profile is positioned incorrect
  modules/social_features/social_profile/social_profile.links.task.yml
Labels: bug, support

#919 2980692 by robertragas: Use label of content-type so it takes transla…
  modules/social_features/social_like/social_like.tokens.inc
Labels: bug, support

#930 2936738: Make sure the local actions block is not displayed on admin/reports pages
  modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
Labels: bug, eci

#946 DS-5829 by serhiy-chornobay: Fixed styles/template for edit comment page
  modules/social_features/social_comment/config/install/core.entity_form_display.comment.comment.default.yml
  themes/socialbase/templates/comment/form--comment-edit.html.twig
Labels: bug

#915 2979817 by jochemvn: Make sure the priority is higher than the event type config override
  modules/social_features/social_group/social_group.services.yml
Labels: bug, eci

#945 DS-5802 by serhiy-chornobay: Fix links color for preview pages
  themes/socialblue/color/css/preview-base.css
Labels: bug

#954 2985342 by jochemvn: Make sure mentioning works with the nickname field
  modules/social_features/social_profile/src/SocialProfileTrait.php
Labels: bug, eci

#959 DS-3488 - Comment overview available for CM and SM
  modules/custom/mentions/mentions.module
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_comment/src/Form/SocialCommentAdminOverview.php
  modules/social_features/social_comment/src/Routing/RouteSubscriber.php
Labels: feature request

#760 Issue #2948787 by ribel: Add separate route for the group stream page
  modules/social_features/social_group/config/install/group.role.closed_group-outsider.yml
  modules/social_features/social_group/social_group.group.permissions.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.links.task.yml
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.permissions.yml
  modules/social_features/social_group/social_group.routing.yml
  modules/social_features/social_group/src/Controller/SocialGroupController.php
Labels: bug, code refactoring, eci, feature request, needs work, support

#944 2965655 by jochemvn: Make the group widget check for installed plugins.
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
Labels: bug, eci

#974 2988074 by jochemvn: Add fallback way to get the account
  modules/social_features/social_profile/social_profile.module
Labels: bug

#971 DS-5827 by jaapjan: update r4032login settings for destination parameter
  modules/social_features/social_core/social_core.install
Labels: bug

#955 2985353: Add nickname to the search index search_users
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
Labels: bug, eci

#759 DS-5912 - Include schema's for configurations defined in modules
  modules/custom/mentions/config/schema/mentions.schema.yml
  modules/social_features/social_comment/config/schema/social_comment.schema.yml
  modules/social_features/social_event/config/schema/social_event.schema.yml
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
Labels: code refactoring, support

#952 #2984188 - Create activity when content is moved outside of a Group.
  modules/custom/activity_basics/activity_basics.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/SetGroupsForNodeService.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
Labels: code refactoring
