Repository goalgorilla/open_social, pull requests merged in 2018-08, with the labels that each got.

#824 SHN-44: Add possibility to turn of the users' topic/event/group tabs on profile
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.permissions.yml
  modules/social_features/social_event/social_event.services.yml
  modules/social_features/social_event/src/Controller/SocialEventController.php
  modules/social_features/social_event/src/Routing/RouteSubscriber.php
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.permissions.yml
  modules/social_features/social_group/src/Controller/SocialGroupController.php
  modules/social_features/social_group/src/Routing/RouteSubscriber.php
  modules/social_features/social_topic/social_topic.install
  modules/social_features/social_topic/social_topic.module
  modules/social_features/social_topic/social_topic.permissions.yml
  modules/social_features/social_topic/src/Controller/SocialTopicController.php
  modules/social_features/social_topic/src/Routing/RouteSubscriber.php
Labels: don't merge, eci, feature request

#987 Issue #2990176 : User export extended
  modules/social_features/social_private_message/src/Plugin/UserExportPlugin/UserAnalyticsPrivateMessage.php
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.services.yml
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/UserExportPlugin/UserNickName.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsHelper.php
  modules/social_features/social_user_export/social_user_export.api.php
  modules/social_features/social_user_export/social_user_export.module
  modules/social_features/social_user_export/social_user_export.services.yml
  modules/social_features/social_user_export/src/Annotation/UserExportPlugin.php
  modules/social_features/social_user_export/src/ExportUser.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAccountName.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressAdministrative.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressCountryCode.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressLine1.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressLine2.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressLocality.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAddressPostalCode.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsCommentsCreated.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsEventEnrollments.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsEventsCreated.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsGroupsCreated.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsLikes.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsPostsCreated.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsTopicsCreated.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserDisplayName.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserEmail.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserFirstName.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserFunction.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserId.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserInterests.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserLastAccess.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserLastLogin.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserLastName.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserOrganization.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserPhoneNumber.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserProfileTag.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserRegistration.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserRoles.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserSkills.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserStatus.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserUuid.php
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
  modules/social_features/social_user_export/src/Plugin/UserExportPluginInterface.php
  modules/social_features/social_user_export/src/Plugin/UserExportPluginManager.php
Labels: don't merge, feature request, needs review

#993 DS-5832 - As a CM+ I want to recognise unpublished comments and (un)publish them
  modules/social_features/social_comment/config/install/core.entity_form_display.comment.comment.default.yml
  modules/social_features/social_comment/config/install/social_comment.comment_settings.yml
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/src/SocialCommentViewBuilder.php
  modules/social_features/social_like/social_like.module
  modules/social_features/social_mentions/social_mentions.module
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/assets/css/comment.css
  themes/socialbase/assets/css/nav-tabs.css
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/04-organisms/comment/comment.scss
  themes/socialbase/socialbase.theme
  themes/socialbase/templates/comment/comment.html.twig
  themes/socialbase/templates/comment/links--comment.html.twig
Labels: feature request, needs review

#992 2990496 by jochemvn: Better passthrough of variable in the form (static)
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
Labels: bug

#977 DS-5915 by serhiy-chornobay: Add behaviors for photo swipe script
  themes/socialbase/assets/js/photoswipe.min.js
  themes/socialbase/components/04-organisms/photoswipe/photoswipe.js
Labels: needs review

#920 Bugfix/2980661 gdpr inform brand color
  themes/socialbase/assets/css/block--informblock.css
  themes/socialbase/components/03-molecules/blocks/block--informblock/block--informblock.scss
  themes/socialbase/package.json
  themes/socialbase/yarn.lock
  themes/socialblue/assets/css/block--informblock.css
  themes/socialblue/assets/css/button.css
  themes/socialblue/assets/css/ckeditor.css
  themes/socialblue/assets/css/like.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/03-molecules/blocks/block--informblock/block--informblock.scss
  themes/socialblue/socialblue.info.yml
  themes/socialblue/socialblue.libraries.yml
Labels: bug, support

#1009 Issue #2989176 : Can't select myself in user reference fields / mentions
  modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
Labels: needs review

#983 Issue #2989731 : Added related "Create" permissions for block display
  modules/social_features/social_event/src/Plugin/Block/EventAddBlock.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddEventBlock.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddTopicBlock.php
  modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
  modules/social_features/social_topic/src/Plugin/Block/TopicAddBlock.php
Labels: bug, ext, needs review

#1005 Issue #2992979 : Blocked users should NOT be in the search
  modules/social_features/social_search/social_search.install
  modules/social_features/social_search/social_search.module
Labels: bug

#988 Issue #2991128 by Kingdutch: Check that the group_profile_names_image field_group exists before overriding.
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
Labels: bug, needs review, support

#1010 Fix race condition in group edit content test
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
Labels: code refactoring, needs review, support

#984 Issue #2989478 - only create messages once to prevent duplicates in streams
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  modules/social_features/social_group/src/SetGroupsForNodeService.php
Labels: bug

#1007 FOR-101 by serhiy-chornobay: Fix brand color for Social Vote widget
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: eci, feature request

#1002 NWO-26 by serhiy-chornobay: Fix brand color for Social Birthday widget
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: eci, feature request

#789 Improve social_comment_upload module quality
  modules/social_features/social_comment_upload/config/install/social_comment_upload.settings.yml
  modules/social_features/social_comment_upload/config/schema/social_comment_upload.schema.yml
  modules/social_features/social_comment_upload/social_comment_upload.install
  modules/social_features/social_comment_upload/social_comment_upload.module
  modules/social_features/social_comment_upload/social_comment_upload.services.yml
  modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
Labels: code refactoring, needs review

#694 Issue #2930486 Posts are orphaned when a user is deleted
  modules/social_features/social_post/social_post.admin.inc
  modules/social_features/social_post/social_post.module
  modules/social_features/social_post/social_post.post_update.php
  modules/social_features/social_post/src/PostAccessControlHandler.php
Labels: needs review, support

#1006 FOR-114 by serhiy-chornobay: Fix brand color for Social GTranslate widget
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: eci, feature request

#792 Issue #2953281 by ribel: Add Social Event AN Enroll module
  modules/social_features/social_core/config/optional/block.block.socialbase_pagetitleblock_2.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_pagetitleblock_2.yml
  modules/social_features/social_core/social_core.module
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.field.event_enrollment.event_enrollment.field_email.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.field.event_enrollment.event_enrollment.field_first_name.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.field.event_enrollment.event_enrollment.field_last_name.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.field.event_enrollment.event_enrollment.field_token.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.field.node.event.field_event_an_enroll.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.storage.event_enrollment.field_email.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.storage.event_enrollment.field_first_name.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.storage.event_enrollment.field_last_name.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.storage.event_enrollment.field_token.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/field.storage.node.field_event_an_enroll.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/social_event_an_enroll.settings.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/views.view.manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_an_enroll/css/event_an_enroll.css
  modules/social_features/social_event/modules/social_event_an_enroll/css/event_an_enroll.css.map
  modules/social_features/social_event/modules/social_event_an_enroll/css/event_an_enroll.scss
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.features.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.install
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.libraries.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.links.menu.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.permissions.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.routing.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.services.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.tokens.inc
  modules/social_features/social_event/modules/social_event_an_enroll/src/Controller/EventAnEnrollController.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollOverride.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollForm.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollSettingsForm.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/views/access/ManageEnrollmentAccess.php
  modules/social_features/social_event/modules/social_event_an_enroll/templates/event-an-enroll-dialog.html.twig
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  modules/social_features/social_follow_content/social_follow_content.module
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
  themes/socialbase/includes/form.inc
  themes/socialbase/templates/node/event/node--event--full.html.twig
Labels: eci, feature request

#981 OSSUPPORT-579 Improve the usability of login and register screens
  modules/custom/social_auth_extra/config/install/social_auth_extra.settings.yml
  modules/custom/social_auth_extra/config/schema/social_auth_extra.schema.yml
  modules/custom/social_auth_extra/social_auth_extra.info.yml
  modules/custom/social_auth_extra/social_auth_extra.install
  modules/custom/social_auth_extra/social_auth_extra.module
  modules/custom/social_gdpr/social_gdpr.module
  modules/social_features/social_user/config/install/social_user.settings.yml
  modules/social_features/social_user/config/schema/social_user.schema.yml
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Form/SocialUserLoginForm.php
  modules/social_features/social_user/src/Form/SocialUserPasswordForm.php
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/form-default.css
  themes/socialbase/assets/css/social-auth-buttons.css
  themes/socialbase/components/03-molecules/form-elements/social-auth-buttons/social-auth-buttons.scss
  themes/socialbase/components/04-organisms/forms/form-default.scss
  themes/socialbase/includes/form.inc
  themes/socialbase/socialbase.libraries.yml
Labels: feature request, support
