Repository goalgorilla/open_social, pull requests merged in 2018-05, with the labels that each got.

#794 check if entity is instance of FieldItemListInterface
  modules/custom/entity_access_by_field/entity_access_by_field.module
Labels: bug, ext

#853 #2960382: Make features profiles in landing page link to the user not the profile
  modules/social_features/social_landing_page/config/install/core.entity_view_display.profile.profile.featured.yml
  modules/social_features/social_landing_page/templates/profile--featured.html.twig
Labels: bug, eci

#818 Issue #2956971: TranslatableMarkup::toString - undefined function
  modules/custom/activity_creator/activity.page.inc
  themes/socialbase/src/Plugin/Preprocess/Activity.php
Labels: bug, ext

#851 Issue #2961977 by Makishima: Use autocomplete widget for topic authored by field
  modules/social_features/social_topic/config/install/core.entity_form_display.node.topic.default.yml
Labels: support

#826 Issue #2956718: Unavailable links in landing page hero still produce output
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/field--paragraph--field-hero-buttons.html.twig
Labels: bug, eci

#773 #2950337 by kala4ek: checkCreateAccess failed at PostAccessControlHandler
  modules/social_features/social_post/src/PostAccessControlHandler.php
Labels: bug, ext

#717 Issue #2936216 Cleanup mentions module
  modules/custom/mentions/mentions.routing.yml
  modules/custom/mentions/src/Form/MentionsSettingsForm.php
  modules/custom/mentions/src/Form/MentionsTypeForm.php
Labels: code refactoring, ext

#849 DS-5173 Give SM option to Enforce consent and send user to cancel if they dont wanna
  modules/custom/social_gdpr/social_gdpr.info.yml
  modules/custom/social_gdpr/social_gdpr.install
  modules/custom/social_gdpr/social_gdpr.module
  modules/social_features/social_user/social_user.api.php
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
  themes/socialbase/src/Plugin/Form/GdprConsentDataPolicyAgreement.php
  themes/socialbase/src/Plugin/Preprocess/FormElement.php
Labels: feature request

#847 Issue #2964699 by ribel: Rename 'Community events' to 'All events'
  modules/social_features/social_event/config/install/views.view.upcoming_events.yml
  tests/behat/features/capabilities/event/homepage-community-events.feature
Labels: bug, eci

#829 DS-5263 big pipe menu shift
  composer.json
  drupal-org-core.make
Labels: eci, feature request

#715 Feature 2940643 post publish status
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
  modules/social_features/social_activity/config/install/views.view.activity_stream_group.yml
  modules/social_features/social_post/config/install/core.entity_form_display.post.post.default.yml
  modules/social_features/social_post/config/install/core.entity_form_display.post.post.group.yml
  modules/social_features/social_post/config/install/core.entity_form_display.post.post.profile.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.default.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.group.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.profile.yml
  modules/social_features/social_post/social_post.install
  modules/social_features/social_post/social_post.permissions.yml
  modules/social_features/social_post/src/Entity/Post.php
  modules/social_features/social_post/src/Form/PostForm.php
  modules/social_features/social_post/src/PostAccessControlHandler.php
Labels: ext, feature request, needs work

#862 Value for post recipient get lost
  modules/social_features/social_post/src/Form/PostForm.php
Labels: bug, support

#861 DS-5049 - Set a default for "empty" author tokens in stream posts when it cannot be replaced
  modules/social_features/social_user/social_user.module
Labels: bug

#871 Issue #2960310: Post comment anchors obscured by main navigation
  themes/socialbase/assets/css/comment.css
  themes/socialbase/components/04-organisms/comment/comment.scss
Labels: bug

#876 Issue #2971992: update csv_serialization from 1.2 to 1.3
  composer.json
  drupal-org.make
Labels: update

#875 Issue #2971969 by jaapjan: update swiftmailer 1.0-beta1 to 1.0-beta2
  composer.json
  drupal-org.make
  modules/social_features/social_swiftmail/src/Plugin/Mail/SocialSwiftMailer.php
Labels: update

#868 DS-5351 GDPR Consent bugs and changes
  modules/custom/social_gdpr/social_gdpr.install
  modules/custom/social_gdpr/social_gdpr.links.menu.yml
  modules/custom/social_gdpr/social_gdpr.module
  modules/custom/social_gdpr/social_gdpr.routing.yml
  modules/custom/social_gdpr/social_gdpr.services.yml
  modules/custom/social_gdpr/src/Controller/DataPolicy.php
  modules/custom/social_gdpr/src/Plugin/Block/AddDataPolicyRevision.php
  modules/custom/social_gdpr/src/Subscriber/Redirect.php
  modules/custom/social_gdpr/src/Subscriber/Route.php
  modules/social_features/social_user/social_user.api.php
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
  themes/socialbase/assets/css/form-elements.css
  themes/socialbase/components/03-molecules/form-elements/form-elements.scss
  themes/socialbase/includes/form.inc
  themes/socialbase/src/Plugin/Form/GdprConsentDataPolicyAgreement.php
  themes/socialbase/src/Plugin/Preprocess/Block.php
Labels: code refactoring

#799 Add number of private messages to export if module exists
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user_export/social_user_export.module
  modules/social_features/social_user_export/src/ExportUser.php
Labels: feature request, support

#772 Add username and real name to export
  modules/social_features/social_user_export/social_user_export.info.yml
  modules/social_features/social_user_export/social_user_export.module
  modules/social_features/social_user_export/src/ExportUser.php
  modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
Labels: feature request, question, support

#880 IE11 by serhiy-chornobay: Fix styles for hero in IE11
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/assets/css/hero.css
  themes/socialbase/assets/css/nav-tabs.css
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/04-organisms/hero/hero.scss
Labels: bug

#859 Issue #2966862: LU should able to navigate easily form edit profile to profile page
  modules/social_features/social_profile/social_profile.module
Labels: bug, feature request

#873 2971260 by jochemvn: Remove fixed array key, so group roles can be overridden more easy
  modules/social_features/social_group/config/install/group.role.closed_group-83776d798.yml
  modules/social_features/social_group/config/install/group.role.closed_group-group_manager.yml
  modules/social_features/social_group/config/install/group.role.closed_group-outsider.yml
  modules/social_features/social_group/config/install/group.role.public_group-anonymous.yml
Labels: bug, eci

#881 DS-5048 Deleting users should not break the private message functionality
  composer.json
  drupal-org.make
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_private_message/config/install/core.entity_view_display.private_message.private_message.default.yml
  modules/social_features/social_private_message/config/install/core.entity_view_display.private_message_thread.private_message_thread.default.yml
  modules/social_features/social_private_message/social_private_message.install
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_private_message/social_private_message.services.yml
  modules/social_features/social_private_message/src/DeletedUser.php
  modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageOwnerFormatter.php
  modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageThreadMemberFormatter.php
  modules/social_features/social_private_message/src/Plugin/Field/Fieldformatter/SocialPrivateMessageMemberFormatter.php
  modules/social_features/social_private_message/src/Service/PrivateMessageMailer.php
  modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php
  modules/social_features/social_private_message/src/SocialPrivateMessageServiceProvider.php
  modules/social_features/social_user/social_user.module
  themes/socialbase/assets/css/message.css
  themes/socialbase/components/04-organisms/message/message.scss
  themes/socialbase/templates/private_message/private-message-thread.html.twig
Labels: code refactoring

#883 DS-5052 The visiblity of activity stream item should remain the same after the actor is deleted
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
Labels: bug

#878 Issue #2972959: disable public group permissions when public visibility is turned off
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/Block/GroupAddEventBlock.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddTopicBlock.php
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  modules/social_features/social_post/src/PostAccessControlHandler.php
Labels: bug

#891 2974599 Invalid HTML tags in \"[message:author:url:absolute]\
  modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
  modules/social_features/social_like/social_like.tokens.inc
Labels: bug

#890 DS-5302 As a blocked/deleted user I should not receive e-mails anymore
  .travis.yml
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/social_features/social_user/src/Plugin/Action/SocialBlockUser.php
Labels: bug, code refactoring

#892 Issue #2975731: Add alt text to demo content images
  modules/custom/social_demo/content/entity/event.yml
  modules/custom/social_demo/content/entity/group.yml
  modules/custom/social_demo/content/entity/page.yml
  modules/custom/social_demo/content/entity/topic.yml
  modules/custom/social_demo/content/entity/user.yml
  modules/custom/social_demo/eaa/content/entity/book.yml
  modules/custom/social_demo/eaa/content/entity/event.yml
  modules/custom/social_demo/eaa/content/entity/group.yml
  modules/custom/social_demo/eaa/content/entity/page.yml
  modules/custom/social_demo/eaa/content/entity/topic.yml
  modules/custom/social_demo/eaa/content/entity/user.yml
  modules/custom/social_demo/src/DemoContent.php
  modules/custom/social_demo/src/DemoGroup.php
  modules/custom/social_demo/src/DemoSystem.php
  modules/custom/social_demo/src/DemoUser.php
  modules/custom/social_demo/src/Plugin/DemoContent/Book.php
  modules/custom/social_demo/src/Plugin/DemoContent/Event.php
  modules/custom/social_demo/src/Plugin/DemoContent/Page.php
  modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
Labels: code refactoring, feature request

#893 Issue #2975745 : Add possibility to edit profile directly from People overview
  modules/social_features/social_profile/social_profile.module
Labels: feature request
