Repository goalgorilla/open_social, pull requests merged in 2018-04, with the labels that each got.

#580 2915997 Fix redirect to edit profile after edit account on register
  modules/social_features/social_user/social_user.module
Labels: eci

#816 Issue #2956115 by jaapjan: prevent error calling function on NULL
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
Labels: bug

#820 Issue #2930174: Fatal error: Call to a member function id() on NULL
  modules/social_features/social_post/src/Form/PostForm.php
Labels: bug, ext

#822 Issue #2948237: "Edit profile information" is not translatable
  themes/socialbase/templates/profile/profile--profile--hero.html.twig
Labels: bug, ext

#796 Bug/2938566 book module add comment link
  themes/socialbase/src/Plugin/Preprocess/Links.php
Labels: bug

#797 #2948653 by Heine. Fix create access check on group types select
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Form/SocialGroupAddForm.php
Labels: bug, ext

#833 Issue #2941204: Incorrect username when registering via social networks
  modules/custom/social_auth_extra/social_auth_extra.module
Labels: bug, ext

#804 Issue #2942231 by Makishima: Add year to the teaser and detail page for events
  modules/social_features/social_core/config/install/core.date_format.social_medium_extended_date.yml
  modules/social_features/social_event/social_event.module
Labels: eci, feature request

#835 Issue #2954924: lazy_builder in social_admin_menu_toolbar_alter causes DomainException
  modules/custom/social_admin_menu/social_admin_menu.module
Labels: bug, support

#843 Issue #2962743 : Make group selection optional when creating content
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
Labels: bug, code refactoring, support

#844 Issue #2964627 by Kingdutch, bramtenhove: Makes sure Mentions highlighter responds to textarea resize events
  modules/social_features/social_mentions/js/social_mentions.js
Labels: bug

#842 Issue #2962434: Not able to click on a post image on the post detail page
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.default.yml
Labels: bug

#845 Issue #2964690: update AddToAny 1.8 to 1.9.
  composer.json
  drupal-org.make
Labels: support
