Repository goalgorilla/open_social, pull requests merged in 2019-11, with the labels that each got.

#1568 Issue #3088530: make EventType::createContent() compatible with parent method
  modules/custom/social_demo/src/Plugin/DemoContent/EventType.php
Labels: bug, needs backport, needs review, shipsters

#1575 Issue #3089936: Select all of VBO and the selected member count in gr…
  modules/social_features/social_group/css/vbo_form.css
Labels: bananas, bug, needs backport, needs maintainer input, needs review

#1583 Issue #3090562 by rolki: Likes are not available for several users on IE11
  modules/social_features/social_comment_upload/js/comment-upload.js
Labels: bug, eci, medium, needs backport

#1509 Issue #3083976 by chmez: Push notifications provider
  composer.json
  drupal-org.make
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.info.yml
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.module
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.services.yml
  modules/custom/activity_send/modules/activity_send_push_notification/src/Annotation/Push.php
  modules/custom/activity_send/modules/activity_send_push_notification/src/PushBase.php
  modules/custom/activity_send/modules/activity_send_push_notification/src/PushInterface.php
  modules/custom/activity_send/modules/activity_send_push_notification/src/PushManager.php
Labels: code refactoring, eci, feature request, high, needs maintainer input, needs rebase, needs review, update

#1606 Updated the lastest patch from Drupal core.
  composer.json
  translations.php
Labels: bananas, bug, high, needs backport, needs maintainer input, needs review

#1591 Issue #3005853 by agami4: Disable autocomplete for date field
  themes/socialbase/templates/form/input--form-control--date.html.twig
Labels: bug, eci

#1585 #3091105: Prevent fatal error by checking if the commented entity still exists
  modules/social_features/social_comment/src/Form/SocialCommentAdminOverview.php
Labels: bananas, bug, needs review

#1563 Issue #3088371: Update views_bulk_operations from 3.2 to 3.3
  composer.json
  drupal-org.make
Labels: needs review, shipsters, update

#1574 Issue #3089919: Filters in admin people don't apply when using select…
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
Labels: bananas, bug, high, needs backport, needs maintainer input

#1547 Issue #3087083: One to many notification activities
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_creator/activity_creator.install
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_creator/activity_creator.post_update.php
  modules/custom/activity_creator/activity_creator.services.yml
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/custom/activity_creator/src/ActivityNotifications.php
  modules/custom/activity_creator/src/Controller/NotificationsController.php
  modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/custom/activity_send/src/Plugin/SendActivityDestinationBase.php
  modules/social_features/social_activity/config/install/field.storage.activity.field_activity_recipient_user.yml
Labels: bananas, code refactoring, needs maintainer input, needs review, performance

#1609 Travis issues occured due to core patch not working - Make it green again!
  .travis.yml
Labels: bug, needs backport, shipsters

#1603 Issue #3094453 by SV: Prevent error: Call to undefined method ContentBuilder::t()
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: bug, eci, medium, needs backport, needs maintainer input

#1607 Issue #3087870 by ribel: Add routes for redirect to the user groups and topics overview pages
  modules/social_features/social_event/src/Controller/SocialEventController.php
  modules/social_features/social_group/social_group.routing.yml
  modules/social_features/social_group/src/Controller/SocialGroupController.php
  modules/social_features/social_topic/social_topic.routing.yml
  modules/social_features/social_topic/src/Controller/SocialTopicController.php
Labels: eci, feature request, medium

#1613 Split up the one to many queue workers into batches of 50 for large groups
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
Labels: bananas, bug, needs drupal.org ticket, performance

#1602 Improved the bulk operation actions description text.
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  translations.php
Labels: bananas, low, needs backport

#1552 Issue #3087741: Color scheme should apply to ideation module
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: bug, eci, high, needs backport

#1553 Issue #3087778 by agami4: Add space between subtitle and buttons for the small hero banner
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
Labels: bug, eci, needs backport

#1594 Remove 'pages' component library definition
  themes/socialbase/socialbase.info.yml
  themes/socialblue/socialblue.info.yml
Labels: bug, medium, needs backport

#1608 Add untranslatable strings in a static PHP file so it can be imported…
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
  translations.php
Labels: bananas, translations
