Repository goalgorilla/open_social, pull requests merged in 2019-06, with the labels that each got.

#1366 Issue #3053044: Open Social 5.0 introduces incorrect dependencies in …
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.info.yml
  modules/social_features/social_event/modules/social_event_enrolments_export/social_event_enrolments_export.info.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.info.yml
  modules/social_features/social_event/social_event.info.yml
Labels: bananas, bug, needs backport

#1412 Update libraries in our yarn.lock files
  themes/socialbase/yarn.lock
  themes/socialblue/yarn.lock
Labels: update

#1406 #3056651 - Performance optimisation for counting group members
  modules/social_features/social_group/social_group.module
Labels: bananas, bug, performance

#1400 Fix Social module names for better consistency
  modules/custom/alternative_frontpage/alternative_frontpage.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.info.yml
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.info.yml
Labels: bug, code refactoring

#1387 Issue #3053687: update to 8.7.1
  composer.json
  drupal-org-core.make
  modules/custom/activity_creator/src/ActivityNotifications.php
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  modules/custom/social_demo/src/DemoNode.php
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_comment/src/Controller/SocialCommentController.php
  modules/social_features/social_core/config/optional/block.block.footer.yml
  modules/social_features/social_core/config/optional/block.block.mainnavigation.yml
  modules/social_features/social_core/config/optional/block.block.socialbase_account_menu.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_account_menu.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_footer.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_mainnavigation.yml
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_like/src/Plugin/ActivityContext/VoteActivityContext.php
  modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php
  modules/social_features/social_profile/config/install/taxonomy.vocabulary.expertise.yml
  modules/social_features/social_profile/config/install/taxonomy.vocabulary.interests.yml
  modules/social_features/social_profile/config/install/taxonomy.vocabulary.profile_tag.yml
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_topic/config/install/taxonomy.vocabulary.topic_types.yml
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  modules/social_features/social_user/tests/src/Unit/Validation/Constraint/SocialUserNameConstraintTest.php
Labels: needs review, update

#1392 Issue #3054121 by truls1502: Update drupal/pathauto from 1.3 to 1.4
  composer.json
  drupal-org.make
Labels: needs backport, update

#1421 DS-6635 - As a AN/LU I want to see the visibility type of content in overviews
  modules/social_features/social_landing_page/templates/node--featured.html.twig
  themes/socialbase/templates/node/node--teaser.html.twig
Labels: feature request, needs review

#1432 Issue #2983330 by kavbiswa, Eitisha: Rename "Swiftmailer settings" to…
  modules/social_features/social_swiftmail/social_swiftmail.links.menu.yml
Labels: bananas, feature request

#1416 Issue #3059892: Added the static keyword to the statically called function
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsBatch.php
Labels: bug, needs review

#1415 git commit -m 'Issue #3059829: Add patch: r4032login should perform a…
  composer.json
  drupal-org.make
Labels: bananas, bug, needs backport

#1422 Issue #3057217 by Salif, albertoalaejos: Notice: Undefined index: #id…
  modules/social_features/social_profile/social_profile.module
Labels: ext, needs review

#1431 Issue #2948979 - Improve search relevancy (node type, creation date and title boost)
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_search/config/install/views.view.search_all.yml
  modules/social_features/social_search/config/install/views.view.search_content.yml
  modules/social_features/social_search/config/install/views.view.search_groups.yml
  modules/social_features/social_search/config/install/views.view.search_users.yml
  modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
Labels: feature request, needs review

#1433 Issue #3063282 by truls1502: Update drupal/bootstrap from 3.19 to 3.20
  composer.json
  drupal-org.make
Labels: needs backport, needs review, update

#1413 Issue #3059404 by truls1502: Update drupal/address from 1.6 to 1.7
  composer.json
  drupal-org.make
Labels: needs backport, needs review, update

#1414 Issue #3059407 by truls1502: Update drupal/entity from 1.0-rc2 to 1.0-rc3
  composer.json
  drupal-org.make
Labels: needs backport, needs review, update

#1361 Issue #3019660 by agami4: Add a full width for content tagging filters
  themes/socialbase/assets/js/select2.init.min.js
  themes/socialbase/components/03-molecules/form-elements/multiselect/select2.init.js
Labels: bug, needs commit cleanup

#1420 Issue #3061282 by albertoalaejos: fix group redirecting issue
  modules/social_features/social_group/social_group.routing.yml
  modules/social_features/social_group/src/Controller/SocialGroupController.php
Labels: bug, medium, needs work

#1430 Issue #3062756 by chmez: As a CA I would like to set up the "Reply-to" email when emailing multiple users
  modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/Action/SocialEventAnEnrollSendEmail.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
  modules/social_features/social_event/social_event.module
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
Labels: Needs MOSS work, code refactoring, eci, feature request, medium, needs backport, needs review

#1337 3049398: SocialProfileFieldsOverride throws error during update to 5.x
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
Labels: low, needs commit cleanup, needs review

#1418 Issue #3060876 by chmez: All Day Event Time
  modules/social_features/social_event/social_event.module
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
Labels: Needs MOSS work, bug, eci, medium, needs review

#1395 Issue #3054419 by chmez: Tour pop-up isn't hidable
  modules/custom/social_tour/config/install/tour.tour.social_event_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_explore.yml
  modules/custom/social_tour/config/install/tour.tour.social_group.yml
  modules/custom/social_tour/config/install/tour.tour.social_group_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_home.yml
  modules/custom/social_tour/config/install/tour.tour.social_node_view.yml
  modules/custom/social_tour/config/install/tour.tour.social_profile.yml
  modules/custom/social_tour/config/install/tour.tour.social_topic_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_user.yml
  modules/custom/social_tour/js/social_tour.js
  modules/custom/social_tour/social_tour.install
  modules/custom/social_tour/social_tour.module
  modules/custom/social_tour/social_tour.services.yml
  modules/custom/social_tour/src/SocialTourController.php
Labels: Needs MOSS work, bug, eci, low, needs review

#1404 Issue #3056461 by truls1502: Update drupal/admin_toolbar from 1.26 to 1.27
  composer.json
  drupal-org.make
Labels: low, needs backport, needs review, update

#1302 #3045903 : Private messages permission improvements
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_private_message/src/Plugin/Block/PmAddBlock.php
  modules/social_features/social_profile/social_profile.module
Labels: code refactoring, ext, low, needs review

#1425 Issue #3062448 by truls1502: Update drupal/profile from 1.0-rc4 to 1.0-rc5
  composer.json
  drupal-org.make
  modules/social_features/social_profile/config/install/profile.type.profile.yml
  modules/social_features/social_user/config/install/core.entity_form_display.user.user.default.yml
  modules/social_features/social_user/config/install/core.entity_form_display.user.user.register.yml
  modules/social_features/social_user/config/install/core.entity_view_display.user.user.default.yml
  modules/social_features/social_user/config/install/core.entity_view_display.user.user.full.yml
Labels: medium, needs backport, needs review, update

#1435 issue #2882629 by albertoalaejos sort comments in ascending order
  modules/social_features/social_post/config/install/core.entity_view_display.post.post.activity.yml
  modules/social_features/social_post/config/install/core.entity_view_display.post.post.default.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.activity.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.default.yml
  modules/social_features/social_post/social_post.module
  modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostActivityFormatter.php
  modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostFormatter.php
  themes/socialbase/templates/post/field--field-post-comments.html.twig
Labels: feature request, high, needs review
