Repository goalgorilla/open_social, pull requests merged in 2019-08, with the labels that each got.

#1470 #3065010 - Lazy load images
  modules/custom/social_lazy_loading/README.txt
  modules/custom/social_lazy_loading/composer.json
  modules/custom/social_lazy_loading/social_lazy_loading.install
  modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.info.yml
  modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.services.yml
  modules/custom/social_lazy_loading/social_lazy_loading_images/src/SocialLazyLoadingImageDisplayOverride.php
Labels: feature request, high, needs backport, needs review, shipsters

#1458 DS-6666 As a LU I can filter events by date and users by registration date
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/views.view.search_content.yml
  modules/social_features/social_search/config/install/views.view.search_users.yml
  modules/social_features/social_search/config/schema/social_search.views.schema.yml
  modules/social_features/social_search/css/indent_filter.css
  modules/social_features/social_search/social_search.install
  modules/social_features/social_search/social_search.libraries.yml
  modules/social_features/social_search/social_search.module
  modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
Labels: feature request, needs review, shipsters

#1475 Issue #3073513 : prevent notices in the search when filter isn't used
  modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
Labels: needs backport, needs review

#1453 Issue #3067268: Add a .browserslistrc file to the repository
  .browserslistrc
Labels: medium, needs review

#1469 Issue by makishima: Fix failing behat tests related with /stream on enterprise sites
  tests/behat/features/capabilities/like/like-post-stream.feature
  tests/behat/features/capabilities/post/post-comments.feature
  tests/behat/features/capabilities/post/post-create.feature
  tests/behat/features/capabilities/post/post-photo-create.feature
Labels: code refactoring, eci, low, needs backport, verified-cherry-picks

#1474 Issue #3072888: Sorting on search content
  composer.json
  drupal-org.make
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_search/config/install/views.view.search_content.yml
  modules/social_features/social_search/config/optional/block.block.exposed_form_search_content_page_sidebar.yml
  modules/social_features/social_search/config/optional/block.block.exposed_form_search_groups_page_sidebar.yml
  modules/social_features/social_search/config/optional/block.block.socialblue_exposed_form_search_content_page_sidebar.yml
  modules/social_features/social_search/config/optional/block.block.socialblue_exposed_form_search_groups_page_sidebar.yml
  modules/social_features/social_search/css/indent_filter.css
  modules/social_features/social_search/css/sort_filter.css
  modules/social_features/social_search/social_search.info.yml
  modules/social_features/social_search/social_search.install
  modules/social_features/social_search/social_search.libraries.yml
  modules/social_features/social_search/social_search.module
  themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
Labels: feature request, needs work, shipsters

#1476 issue #3069288 edit profile - unexpected error
  themes/socialbase/src/Plugin/Preprocess/PageTitle.php
Labels: bug, needs review

#1480 Issue #3059996 by Kingdutch, sah62, luf: Update profile module to rc6
  composer.json
  drupal-org.make
  modules/social_features/social_profile/config/install/profile.type.profile.yml
Labels: bananas, bug, high, needs backport, needs review, update

#1482 Issue #3075758 by Kingdutch: Notification creation has fatal error if…
  modules/custom/activity_creator/src/ActivityFactory.php
Labels: bananas, bug, high, needs backport, needs review

#1484 Issue #3075854 by jaapjan: defensive coding in the activity token handling
  modules/social_features/social_activity/social_activity.tokens.inc
Labels: SaaS, bug, needs backport, needs review

#1461 Issue #3019458 by royharink: Skip group type selection page when creating a group for users that who can only add one group type
  modules/social_features/social_group/social_group.module
Labels: bananas, feature request, needs review

#1457 Issue #3059056 by agami4: Update display "Report" button on Book pages
  modules/social_features/social_book/config/install/node.type.book.yml
  themes/socialbase/templates/node/book/node--book--full.html.twig
Labels: bug, eci, needs review

#1450 #3066658: Add bottom space for private message button
  themes/socialbase/assets/css/hero.css
  themes/socialbase/components/04-organisms/hero/hero.scss
  themes/socialbase/templates/profile/profile--profile--hero.html.twig
Labels: eci, needs rebase, needs review

#1356 Issue #3051857 by agami4: show background image after saving on settings theme page
  themes/socialblue/color/preview.js
Labels: eci, feature request, low, needs backport, needs review
