Repository goalgorilla/open_social, pull requests merged in 2019-10, with the labels that each got.

#1525 Issue #3047912 by jaapjan: remove check text step in group-edit-type.feature
  tests/behat/features/capabilities/group/group-edit-type.feature
Labels: code refactoring, needs review, shipsters

#1429 Issue by ribel: Fix failing Landing Page behat tests on enterprise sites
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
  tests/behat/features/capabilities/landing-page/landing-page-create.feature
Labels: code refactoring, eci, medium, needs backport

#1519 Issue #3030233 Don't use existing configuration on Private text editor override class
  modules/custom/social_file_private/social_file_private.services.yml
  modules/custom/social_file_private/src/SocialFilePrivateTextEditorConfigOverride.php
Labels: code refactoring, ext, needs review

#1521 Issue #3084689 by agami4: Update color for title of course according to scheme color
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: eci, feature request, needs review

#1528 Add developer demo content folder and some demo files [skip ci]
  modules/custom/social_demo/developer/content/entity/event.yml
  modules/custom/social_demo/developer/content/entity/topic.yml
Labels: shipsters

#1529 Issue #3085176: move social_post_update hook to post_update
  modules/social_features/social_post/social_post.install
  modules/social_features/social_post/social_post.post_update.php
Labels: code refactoring, shipsters, verified-cherry-picks

#1531 Issue #3085242: remove obsolete font.page.inc and font.html.twig
  modules/custom/social_font/font.page.inc
  modules/custom/social_font/templates/font.html.twig
Labels: code refactoring, needs review, shipsters, verified-cherry-picks

#1540 DS-6910 by robertragas: remove styling of <em> so its default italic,…
  modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
  modules/social_features/social_follow_content/config/install/message.template.create_comment_following_node.yml
  modules/social_features/social_swiftmail/social_swiftmail.module
  themes/socialbase/templates/swiftmailer.html.twig
Labels: bananas, bug, needs review

#1532 Issue #3085504: Improve performance of ConfigOverrides in Social Lazy Load
  modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.services.yml
  modules/custom/social_lazy_loading/social_lazy_loading_images/src/SocialLazyLoadingImageDisplayOverride.php
  modules/custom/social_lazy_loading/src/SocialLazyLoadingTextFormatOverride.php
Labels: needs review, performance, shipsters

#1534 Issue #3086219: Prevent notice in social_group_secret_form_node_form_alter()
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
Labels: bug, needs backport, needs review, shipsters

#1526 #2994248 Make sure on install SM + CM also need to consent
  modules/custom/social_gdpr/social_gdpr.install
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/gdpr/create-data-policy.feature
  tests/behat/features/capabilities/gdpr/data-policy-revisions.feature
  tests/behat/features/capabilities/gdpr/inform-block.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
Labels: bug, low, shipsters

#1522 TB-2352 Move to Search API Processor for restricted names
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.install
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.post_update.php
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.services.yml
  modules/social_features/social_profile/modules/social_profile_privacy/src/EventSubscriber/ConfigEventsSubscriber.php
  modules/social_features/social_profile/modules/social_profile_privacy/src/Plugin/search_api/processor/RestrictedNameProcessor.php
  modules/social_features/social_profile/modules/social_profile_privacy/src/RestrictedNameProcessorOverride.php
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  tests/behat/features/capabilities/profile/restricted-full-name.feature
Labels: bananas, bug, code refactoring, medium, needs backport, needs review

#1545 Fix behat test create private message false negatives
  tests/behat/features/capabilities/private-message/create-private-message.feature
Labels: code refactoring, needs backport, needs review, shipsters

#1535 Issue #3086229: Download count: Invalidate file cache tags only when needed
  modules/custom/download_count/download_count.module
Labels: needs review, performance, shipsters

#1543 Issue #3087021: Allow to add page content attributes from modules
  modules/social_features/social_landing_page/social_landing_page.module
  themes/socialbase/src/Plugin/Preprocess/Page.php
Labels: code refactoring, eci, feature request, high, needs backport, needs review

#1362 Issue #3045773 by agami4: Add name and title attributes for dropdown button and link wrapped the teaser icon
  themes/socialbase/templates/comment/links--comment.html.twig
  themes/socialbase/templates/node/node--teaser.html.twig
  themes/socialbase/templates/system/links.html.twig
Labels: eci, feature request, low, needs review

#1539 Issue #3085806: Temporary solution pagination search users
  modules/social_features/social_search/social_search.services.yml
  modules/social_features/social_search/src/EventSubscriber/RedirectSubscriber.php
Labels: bug, needs backport, needs review, shipsters

#1491 Issue #3085248: Replaced individual ::load calls in loop with ::loadMultiple along with some code adjustments.
  .gitignore
  modules/custom/social_path_manager/social_path_manager.module
  modules/social_features/social_comment_upload/social_comment_upload.module
  modules/social_features/social_group/src/SetGroupsForNodeService.php
Labels: bananas, needs review, performance

#1548 Issue #3087098: Event date filter shouldn't apply to others.
  modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
Labels: bug, medium, needs backport, needs review, shipsters

#1549 issue #3087042 by albertoalaejos: email button for comment on comment…
  modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_follow_content/config/install/message.template.create_comment_following_node.yml
Labels: bug, medium, needs review

#1408 Issue #3056832 by robertragas: set activity messages to queue instead…
  modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
  modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
  modules/social_features/social_activity/config/install/message.template.join_to_group.yml
  modules/social_features/social_event/config/optional/message.template.activity_on_events_im_organizing.yml
  modules/social_features/social_event/modules/social_event_managers/config/optional/message.template.member_added_by_event_organiser.yml
  modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
  modules/social_features/social_mentions/config/install/message.template.create_comment_reply_mention.yml
  modules/social_features/social_mentions/config/install/message.template.create_mention_comment.yml
  modules/social_features/social_mentions/config/install/message.template.create_mention_post.yml
  tests/behat/features/capabilities/like/like-create-event.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
  tests/behat/features/capabilities/like/like-post-stream.feature
Labels: bananas, low, needs review, performance

#1544 Issue #3062452: Update drupal/group from 1.0-rc2 to 1.0-rc4
  composer.json
  drupal-org.make
  modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  modules/social_features/social_activity/config/install/views.view.activity_stream_group.yml
  modules/social_features/social_core/src/Plugin/Field/FieldFormatter/CommentNodeFormatter.php
  modules/social_features/social_group/config/install/group.role.closed_group-83776d798.yml
  modules/social_features/social_group/config/install/group.role.closed_group-a416e6833.yml
  modules/social_features/social_group/config/install/group.role.closed_group-ba5854c29.yml
  modules/social_features/social_group/config/install/group.role.closed_group-group_admin.yml
  modules/social_features/social_group/config/install/group.role.closed_group-group_manager.yml
  modules/social_features/social_group/config/install/group.role.closed_group-member.yml
  modules/social_features/social_group/config/install/group.role.closed_group-outsider.yml
  modules/social_features/social_group/config/install/group.role.open_group-83776d798.yml
  modules/social_features/social_group/config/install/group.role.open_group-a416e6833.yml
  modules/social_features/social_group/config/install/group.role.open_group-ba5854c29.yml
  modules/social_features/social_group/config/install/group.role.open_group-group_admin.yml
  modules/social_features/social_group/config/install/group.role.open_group-group_manager.yml
  modules/social_features/social_group/config/install/group.role.open_group-member.yml
  modules/social_features/social_group/config/install/group.role.open_group-outsider.yml
  modules/social_features/social_group/config/install/group.role.public_group-83776d798.yml
  modules/social_features/social_group/config/install/group.role.public_group-a416e6833.yml
  modules/social_features/social_group/config/install/group.role.public_group-anonymous.yml
  modules/social_features/social_group/config/install/group.role.public_group-ba5854c29.yml
  modules/social_features/social_group/config/install/group.role.public_group-group_admin.yml
  modules/social_features/social_group/config/install/group.role.public_group-group_manager.yml
  modules/social_features/social_group/config/install/group.role.public_group-member.yml
  modules/social_features/social_group/config/install/group.role.public_group-outsider.yml
  modules/social_features/social_group/config/install/views.view.group_events.yml
  modules/social_features/social_group/config/install/views.view.group_information.yml
  modules/social_features/social_group/config/install/views.view.group_managers.yml
  modules/social_features/social_group/config/install/views.view.group_members.yml
  modules/social_features/social_group/config/install/views.view.group_topics.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-83776d798.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-a416e6833.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-anonymous.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-ba5854c29.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_admin.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_manager.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-member.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-outsider.yml
  modules/social_features/social_group/social_group.module
  tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
  tests/behat/features/capabilities/activity-stream/create_topic_event.feature
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  tests/behat/features/capabilities/post/post-group.feature
Labels: needs review, shipsters, update

#1542 Issue #3087004: VBO - 7.0 - Updates
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollOverride.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.module
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_group/modules/social_group_members_export/src/SocialGroupMembersExportOverrides.php
Labels: bug, high, needs backport, needs review, shipsters

#1559 #1362 - follow up
  themes/socialbase/templates/node/node--teaser.html.twig
Labels: verified-cherry-picks
