Repository goalgorilla/open_social, pull requests merged in 2019-01, with the labels that each got.

#1175 #3021176 : Featuring a landing page without hero causes the image to show "Array"
  modules/social_features/social_landing_page/social_landing_page.module
Labels: bug

#1176 Issue #3018268 by jaapjan: don't send notification for liking own content
  modules/social_features/social_like/src/Plugin/ActivityContext/VoteActivityContext.php
Labels: bug

#1153 Issue #3019370: As a Group manager, I want to manage group members easily
  composer.json
  drupal-org.make
  modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
  modules/social_features/social_group/config/install/views.view.group_manage_members.yml
  modules/social_features/social_group/js/frontUi.js
  modules/social_features/social_group/modules/social_group_gvbo/social_group_gvbo.info.yml
  modules/social_features/social_group/modules/social_group_gvbo/social_group_gvbo.routing.yml
  modules/social_features/social_group/modules/social_group_gvbo/src/Form/SocialGroupViewsBulkOperationsConfigureAction.php
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.info.yml
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.module
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.services.yml
  modules/social_features/social_group/modules/social_group_members_export/src/Plugin/Action/ExportMember.php
  modules/social_features/social_group/modules/social_group_members_export/src/SocialGroupMembersExportOverrides.php
  modules/social_features/social_group/social_group.info.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.libraries.yml
  modules/social_features/social_group/social_group.links.action.yml
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.routing.yml
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/Access/SocialGroupViewsBulkOperationsAccess.php
  modules/social_features/social_group/src/Controller/SocialGroupContentListBuilder.php
  modules/social_features/social_group/src/Controller/SocialGroupController.php
  modules/social_features/social_group/src/Element/SocialGroupEntityAutocomplete.php
  modules/social_features/social_group/src/Form/SocialGroupViewsBulkOperationsConfirmAction.php
  modules/social_features/social_group/src/Plugin/Action/ChangeGroupMembershipRole.php
  modules/social_features/social_group/src/Plugin/Action/GroupContentEntityDeleteAction.php
  modules/social_features/social_group/src/Plugin/Action/SocialSendEmail.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/Routing/RouteSubscriber.php
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  tests/behat/features/capabilities/event/event-create.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/cards.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/assets/css/nav-tabs.css
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/01-base/tables/_tables.scss
  themes/socialbase/components/02-atoms/cards/cards.scss
  themes/socialbase/includes/form.inc
  themes/socialbase/includes/input.inc
  themes/socialbase/src/Plugin/Preprocess/Dropdown.php
  themes/socialbase/src/Plugin/Preprocess/DropdownActions.php
  themes/socialbase/src/Plugin/Preprocess/FormElementLabel.php
  themes/socialbase/src/Plugin/Preprocess/MenuLocalAction.php
  themes/socialbase/src/Plugin/Preprocess/Page.php
  themes/socialbase/templates/form/form-element-label.html.twig
  themes/socialbase/templates/form/input--button--split.html.twig
  themes/socialbase/templates/form/input.html.twig
  themes/socialbase/templates/views/views-view--group-manage-members.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/button.css
  themes/socialblue/assets/css/ckeditor.css
  themes/socialblue/assets/css/like.css
  themes/socialblue/assets/css/nav-tabs.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/color/preview.js
  themes/socialblue/components/brand.scss
Labels: feature request, needs work

#1178 Issue #2936146: Cannot save 'social_content' search_api index fields
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
Labels: bug, ext

#1177 Issue #3023428 by truls1502, zaporylie: Adding zaporylie/composer-drupal-optimizations
  composer.json
Labels: code refactoring, ext

#1069 Issue #3010020 by truls1502: Update image_effects 1.0 to 2.2
  composer.json
  drupal-org.make
Labels: Needs MOSS work, needs review, update

#1136 Issue #3015568 by serhiy-chornobay, ribel: As a LU I want the teasers to look complete even if no image is uploaded
  modules/social_features/social_landing_page/css/social_landing_page.featured.css
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.css
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.scss
  modules/social_features/social_landing_page/templates/node--featured.html.twig
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
  themes/socialbase/src/Plugin/Preprocess/Node.php
  themes/socialbase/templates/node/node--teaser.html.twig
Labels: eci, feature request

#1113 Issue #2946464 text capitalisation (3.x)
  tests/behat/features/capabilities/event/event-overview.feature
  tests/behat/features/capabilities/topic/topic-overview.feature
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/button.css
  themes/socialbase/assets/css/cards.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/like.css
  themes/socialbase/assets/css/offcanvas.css
  themes/socialbase/assets/js/autocomplete.min.js
  themes/socialbase/assets/js/autosize.init.min.js
  themes/socialbase/assets/js/imageWidgetCrop.min.js
  themes/socialbase/assets/js/navbar-collapse.min.js
  themes/socialbase/assets/js/navbar-resize.min.js
  themes/socialbase/assets/js/navbar-search.min.js
  themes/socialbase/assets/js/select2.init.min.js
  themes/socialbase/components/01-base/tables/_tables.scss
  themes/socialbase/components/02-atoms/button/button.scss
  themes/socialbase/components/02-atoms/cards/cards.scss
  themes/socialbase/components/03-molecules/like/like.scss
  themes/socialbase/components/04-organisms/offcanvas/offcanvas.scss
  themes/socialblue/assets/css/cards.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/02-atoms/cards/cards.scss
Labels: Needs MOSS work, needs review

#1141 Issue: #3012005 all day event timezones
  modules/social_features/social_event/social_event.module
  tests/behat/features/capabilities/event/all-day-timezone.feature
Labels: bug, ext, needs work

#1180 Fix styling for social sharing buttons
  modules/custom/improved_theme_settings/improved_theme_settings.module
  themes/socialbase/assets/css/button.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/components/02-atoms/button/button.scss
  themes/socialblue/assets/css/button.css
  themes/socialblue/assets/css/ckeditor.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/02-atoms/button/button.scss
Labels: bug, support

#1150 #3018558 by bramtenhove: Add group memberships to the user export
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsGroupMemberships.php
  modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserGroupMemberships.php
Labels: eci, feature request

#1182 Issue #3017245: set correct user status for new users when signing up via social login
  modules/custom/social_auth_extra/social_auth_extra.module
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
Labels: bug, needs review

#1187 Issue #3027247: Call to function isAnonymous() on null in template_preprocess_activity()
  modules/custom/activity_creator/activity.page.inc
Labels: bug, ext

#1190 Issue #2936477 : dependency declaration in social.info.yml
  social.info.yml
Labels: code refactoring, ext

#1179 Issue #3024525 by Kingdutch, bramtenhove: Fix project names in fully qualified dependencies
  modules/custom/activity_basics/activity_basics.info.yml
  modules/custom/activity_creator/activity_creator.info.yml
  modules/custom/activity_logger/activity_logger.info.yml
  modules/custom/activity_send/activity_send.info.yml
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.info.yml
  modules/custom/activity_viewer/activity_viewer.info.yml
  modules/custom/social_auth_extra/social_auth_extra.info.yml
  modules/custom/social_auth_facebook/social_auth_facebook.info.yml
  modules/custom/social_auth_google/social_auth_google.info.yml
  modules/custom/social_auth_linkedin/social_auth_linkedin.info.yml
  modules/custom/social_auth_twitter/social_auth_twitter.info.yml
  modules/social_features/social_activity/social_activity.info.yml
  modules/social_features/social_book/social_book.info.yml
  modules/social_features/social_comment_upload/social_comment_upload.info.yml
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_download_count/social_download_count.info.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.info.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.info.yml
  modules/social_features/social_event/social_event.info.yml
  modules/social_features/social_follow_content/social_follow_content.info.yml
  modules/social_features/social_group/modules/social_group_gvbo/social_group_gvbo.info.yml
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.info.yml
  modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.info.yml
  modules/social_features/social_group/social_group.info.yml
  modules/social_features/social_like/social_like.info.yml
  modules/social_features/social_mentions/social_mentions.info.yml
  modules/social_features/social_page/social_page.info.yml
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.info.yml
  modules/social_features/social_post/social_post.info.yml
  modules/social_features/social_private_message/social_private_message.info.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.info.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.info.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.info.yml
  modules/social_features/social_profile/social_profile.info.yml
  modules/social_features/social_search/social_search.info.yml
  modules/social_features/social_sso/social_sso.info.yml
  modules/social_features/social_topic/social_topic.info.yml
  modules/social_features/social_user_export/social_user_export.info.yml
Labels: code refactoring, needs work
