Repository goalgorilla/open_social, pull requests merged in 2019-04, with the labels that each got.

#1266 Issue #3041077 by ribel: As LU I want to be able to filter on tags on the all topics, events and groups overview pages
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: code refactoring, eci, feature request

#1285 Issue #3044698 by truls1502: Update drupal/dynamic_entity_reference from 1.6 to 1.7
  composer.json
  drupal-org.make
Labels: needs review, update

#1229 Add smaller hero as landing page section
  modules/social_features/social_landing_page/config/install/core.entity_form_display.paragraph.hero_small.default.yml
  modules/social_features/social_landing_page/config/install/core.entity_view_display.paragraph.hero_small.default.yml
  modules/social_features/social_landing_page/config/install/core.entity_view_display.paragraph.hero_small.preview.yml
  modules/social_features/social_landing_page/config/install/crop.type.hero_small_landing.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_buttons.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_image.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_subtitle.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.section.field_section_paragraph.yml
  modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_hero_small_buttons.yml
  modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_hero_small_image.yml
  modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_hero_small_subtitle.yml
  modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_hero_small_title.yml
  modules/social_features/social_landing_page/config/install/image.style.social_landing_hero_small.yml
  modules/social_features/social_landing_page/config/install/paragraphs.paragraphs_type.hero.yml
  modules/social_features/social_landing_page/config/install/paragraphs.paragraphs_type.hero_small.yml
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
  modules/social_features/social_landing_page/social_landing_page.libraries.yml
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/field--paragraph--field-hero-small-buttons.html.twig
  modules/social_features/social_landing_page/templates/paragraph--hero-small--default.html.twig
Labels: eci, feature request

#1197 3027295 - Alternative entry point for groups
  modules/custom/social_devel/social_devel.module
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.api.php
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.info.yml
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.install
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.routing.yml
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.services.yml
  modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/modules/social_group_default_route/src/RouteSubscriber/RouteSubscriber.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Routing/RouteSubscriber.php
Labels: eci, feature request

#1286 Fix circular reference dependency injection
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: bug, code refactoring

#1248 Issue by Kingdutch #3039150: SocialEmbedConfigOverride overrides are …
  modules/social_features/social_embed/src/SocialEmbedConfigOverride.php
Labels: bug, support

#1262 Issue #3042119 by Kingdutch: The socialbase like_and_dislike_service …
  themes/socialbase/components/03-molecules/like/like_and_dislike_service.js
Labels: bug, needs review, support

#1257 Issue #3040981 by Kingdutch: The event_an_enroll_email_notify setting…
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollForm.php
Labels: bug, needs review, support

#1268 Issue #3043086 by bramtenhove: Add extra check to prevent notice thrown in social_profile module
  modules/social_features/social_profile/social_profile.module
Labels: bug, needs review, support

#1290 Missing PRs For 4.x (and 5.x)
  modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
Labels: code refactoring, needs review

#1289 5.x Missing PRs
  modules/custom/activity_logger/activity_logger.module
  modules/custom/activity_logger/activity_logger.post_update.php
  modules/custom/activity_logger/config/schema/activity_logger.schema.yml
  modules/social_features/social_editor/config/install/editor.editor.full_html.yml
  modules/social_features/social_embed/social_embed.api.php
  modules/social_features/social_embed/social_embed.services.yml
  modules/social_features/social_embed/src/SocialEmbedConfigOverride.php
  modules/social_features/social_embed/src/SocialEmbedEditorConfigOverride.php
  modules/social_features/social_mentions/js/jquery.mentions.ckeditor.coffee
  modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js
  modules/social_features/social_mentions/js/jquery.mentions.coffee
  themes/socialbase/src/Plugin/Preprocess/Html.php
Labels: code refactoring, needs review

#1279 Update views_bulk_operations to 2.5
  composer.json
  drupal-org.make
  modules/social_features/social_event/modules/social_event_managers/config/install/views.view.event_manage_enrollments.yml
  modules/social_features/social_group/config/install/views.view.group_manage_members.yml
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
Labels: needs review, update, verified-cherry-picks

#1291 Issue #3045199 by bramtenhove: Fix possible fatal error can occur while generating activities
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
Labels: bug, needs review, support

#1297 Splitted the install_stability_3-4-5
  .travis.yml
Labels: needs release notes, needs review

#1294 Issue #3044815 by kavbiswa, xinyuma, jaapjan: The unfollow button on …
  modules/social_features/social_follow_content/config/install/views.view.following.yml
Labels: bug, ext

#1296 hotfix/4.8.0 into master branch
  composer.json
  drupal-org.make
  social.info.yml
Labels: needs review

#1295 Issue #3045716 by truls1502: Update drupal/address from 1.4 to 1.6
  composer.json
  drupal-org.make
Labels: update

#1265 Issue #2961232 change private message contact url when thread is deleted
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_profile/social_profile.module
Labels: bug, needs review

#1303 #3046585: Remove AddtoAny
  composer.json
  drupal-org.make
  modules/social_features/social_book/config/install/core.entity_view_display.node.book.activity.yml
  modules/social_features/social_book/config/install/core.entity_view_display.node.book.activity_comment.yml
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.activity.yml
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.activity_comment.yml
Labels: code refactoring, needs work

#1277 Issue #3043555 by truls1502: Update drupal/paragraphs from 1.6 to 1.8
  composer.json
  drupal-org.make
  themes/socialbase/templates/paragraphs-summary.html.twig
Labels: ext, needs review, update

#1309 Issue #3046633 by truls1502: Update drupal/addtoany from 1.11 to 1.12
  composer.json
  drupal-org.make
Labels: needs review, update

#1284 #3044337: Configurable landing point on profile
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.links.menu.yml
  modules/social_features/social_user/social_user.links.task.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/social_user.permissions.yml
  modules/social_features/social_user/social_user.routing.yml
  modules/social_features/social_user/social_user.services.yml
  modules/social_features/social_user/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_user/src/Form/SocialUserSettingsForm.php
  modules/social_features/social_user/src/Routing/RouteSubscriber.php
  themes/socialbase/templates/profile/profile--compact.html.twig
  themes/socialbase/templates/profile/profile--profile--compact_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--medium_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--small_teaser.html.twig
  themes/socialbase/templates/profile/profile--profile--table.html.twig
  themes/socialbase/templates/profile/profile--profile--teaser.html.twig
Labels: eci, needs review

#1313 #3047076: Featuring landing pages on a landing page, shows svg icon over the image
  modules/social_features/social_landing_page/social_landing_page.module
  themes/socialbase/src/Plugin/Preprocess/Node.php
Labels: bug, eci

#1287 Issue by ribel: Revert PSR-12 standard for PHP7 to avoid fatal error in classes that extend social_group RouteSubscriber
  modules/social_features/social_event/modules/social_event_managers/src/EventSubscriber/RouteSubscriber.php
  modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/modules/social_group_default_route/src/RouteSubscriber/RouteSubscriber.php
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  modules/social_features/social_group/src/Routing/RouteSubscriber.php
  modules/social_features/social_user/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_user/src/Routing/RouteSubscriber.php
Labels: bug, code refactoring, eci

#1312 #3019370: Use hook system for group management overview
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/SocialGroupAdminPeopleConfigOverride.php
Labels: verified-cherry-picks

#1311 Improve styles for "Featured Items" paragraph type
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.items.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.featured_items.css
  modules/social_features/social_landing_page/css/social_landing_page.section.featured_items.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.featured_items.scss
  modules/social_features/social_landing_page/social_landing_page.libraries.yml
  modules/social_features/social_landing_page/templates/paragraph--featured-item--default.html.twig
  modules/social_features/social_landing_page/templates/paragraph--featured-items--default.html.twig
Labels: bug, eci

#1316 Issue #3045772: Alter anonymous enrollment button texts
  modules/social_features/social_event/modules/social_event_an_enroll/templates/event-an-enroll-dialog.html.twig
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
Labels: feature request, support

#1237 DS-6376 - As a LU, I want to minimise the number of tabs in event.
  modules/social_features/social_core/config/optional/block.block.socialbase_pagetitleblock_2.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_pagetitleblock_2.yml
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollManager.php
  modules/social_features/social_event/modules/social_event_managers/config/install/views.view.event_manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.routing.yml
  modules/social_features/social_event/modules/social_event_managers/src/Controller/EventManagersController.php
  modules/social_features/social_event/modules/social_event_managers/src/EventSubscriber/RouteSubscriber.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/EventEnrollmentEntityDeleteAction.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_event/social_event.module
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
Labels: feature request, needs work

#1314 Issue #3047142: Prefer instanceof over method_exists in ActivityLoggerFactory::createMessages
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  modules/custom/mentions/src/Entity/Mentions.php
  modules/custom/mentions/src/MentionsInterface.php
Labels: needs review, support

#1255 Issue #3039084: Allow full name to be hidden
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.search_index.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.field.profile.profile.field_profile_nick_name.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.storage.profile.field_profile_nick_name.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
  modules/social_features/social_profile/modules/social_profile_privacy/config/install/social_profile_privacy.settings.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.permissions.yml
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/src/SocialProfileTrait.php
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_user/social_user.api.php
  modules/social_features/social_user/social_user.module
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/group/group-edit-type.feature
  tests/behat/features/capabilities/profile/restricted-full-name.feature
  tests/behat/features/capabilities/search/search-all.feature
  tests/behat/features/capabilities/search/search-content.feature
  tests/behat/features/capabilities/search/search-groups.feature
  tests/behat/features/capabilities/search/search-users.feature
Labels: feature request, needs LGOS documentation, needs test coverage, support

#1325 Issue #3045160 (and #3043714): Update search api 1.6 to 1.12
  composer.json
  drupal-org.make
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.server.social_database.yml
Labels: code refactoring, update

#1330 Update travis.yml for 4.x
  .travis.yml
Labels: needs review

#1331 Update travis.yml for 6.x
  .travis.yml
Labels: needs review

#1328 Update README.md for 5.x with two more badges
  README.md
Labels: feature request, needs review

#1332 Issue #3048992 by truls1502: Update Drupal Core to 8.6.15 for 4.10
  composer.json
  drupal-org-core.make
  social.info.yml
Labels: needs release notes, needs review, update

#1333 Issue #3048992 by truls1502: Update Drupal Core to 8.6.15 for 5.1
  composer.json
  drupal-org-core.make
  social.info.yml
Labels: needs release notes, needs review, update

#1340 3050155: Export user with deleted terms
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
Labels: Needs MOSS work, bug, needs backport, needs review

#1292 3045214: Destination parameter in login/signup destination is cached
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Form/SocialUserLoginForm.php
Labels: bug, needs backport, support
