Repository goalgorilla/open_social, pull requests merged in 2019-02, with the labels that each got.

#1206 DS - 6384 - As a LU, I want to see the event title in a map follow the platform colour configuration.
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/cards.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: code refactoring

#1201 Issue #3028980 by Kingdutch, bramtenhove: Search suggestions in search overlay
  composer.json
  modules/custom/social_react/social_react.info.yml
  modules/custom/social_react/social_react.libraries.yml
  modules/social_features/social_search/modules/social_search_autocomplete/.eslintrc.js
  modules/social_features/social_search/modules/social_search_autocomplete/babel.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
  modules/social_features/social_search/modules/social_search_autocomplete/css/search-suggestion.css
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js.map
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/SearchSuggestions.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/SearchSuggestions.test.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Spinner.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Suggestion.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Suggestion.test.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/__snapshots__/SearchSuggestions.test.jsx.snap
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/__snapshots__/Suggestion.test.jsx.snap
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/index.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/package.json
  modules/social_features/social_search/modules/social_search_autocomplete/prettier.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.info.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.libraries.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.module
  modules/social_features/social_search/modules/social_search_autocomplete/webpack.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/yarn.lock
  modules/social_features/social_search/src/Form/SearchContentForm.php
  social.profile
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: feature request, needs review, support

#1208 Issue #3024352 - do not override existing services as it will break comment upload
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.services.yml
Labels: bug

#1202 Issue #3028992: Mentions and embed media in the comment
  modules/social_features/social_mentions/js/jquery.mentions.ckeditor.coffee
  modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js
  modules/social_features/social_mentions/js/jquery.mentions.coffee
Labels: bug, support

#1200 Issue #3028367: Use filter for converting URL to embed for different text formats
  modules/social_features/social_embed/social_embed.api.php
  modules/social_features/social_embed/social_embed.services.yml
  modules/social_features/social_embed/src/SocialEmbedConfigOverride.php
  modules/social_features/social_embed/src/SocialEmbedEditorConfigOverride.php
Labels: feature request, support

#1209 DS-6371 - Let's connect with Open Social
  modules/custom/social_lets_connect/assets/css/toolbar.css
  modules/custom/social_lets_connect/assets/images/os_logo_darker.svg
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.info.yml
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml
  modules/custom/social_lets_connect/social_lets_connect.info.yml
  modules/custom/social_lets_connect/social_lets_connect.libraries.yml
  modules/custom/social_lets_connect/social_lets_connect.links.menu.yml
  modules/custom/social_lets_connect/social_lets_connect.module
  modules/custom/social_lets_connect/social_lets_connect.permissions.yml
  modules/custom/social_lets_connect/social_lets_connect.routing.yml
  modules/custom/social_lets_connect/src/Controller/LetsConnectController.php
  social.profile
Labels: feature request, needs review

#1112 DS-5914: Post comment size
  .travis.yml
  themes/socialbase/assets/js/autocomplete.min.js
  themes/socialbase/assets/js/autosize.init.min.js
  themes/socialbase/assets/js/date-picker-init.min.js
  themes/socialbase/assets/js/like_and_dislike_service.min.js
  themes/socialbase/assets/js/photoswipe.min.js
  themes/socialbase/assets/js/tabledrag.min.js
  themes/socialbase/components/02-atoms/form-controls/autosize.init.js
  themes/socialbase/components/03-molecules/form-elements/autocomplete/autocomplete.js
Labels: SaaS, bug, needs review

#1192 Issue #2948330: Distinguish between "Date Joined" and "Has joined"
  themes/socialbase/templates/group/group--hero.html.twig
  themes/socialbase/templates/group/group--teaser.html.twig
Labels: code refactoring, ext

#1189 Issue #3010782 Ensure search menu local tasks have proper weights
  modules/social_features/social_search/social_search.links.task.yml
Labels: code refactoring, ext

#1194 Issue #3027527 by truls1502: Update drupal/config_update from 1.5 to 1.6
  composer.json
  drupal-org.make
Labels: update

#1193 Issue #3027520 by truls1502: Update drupal/image_effects from 2.2 to 2.3
  composer.json
  drupal-org.make
Labels: update

#1185 Issue #2977782: My own Private Messages are marked as unread
  composer.json
  drupal-org.make
Labels: Needs MOSS work, bug

#1204 Issue #3029276: Error after change group type
  modules/social_features/social_group/src/GroupContentVisibilityUpdate.php
Labels: Needs MOSS work, bug

#1214 Issue #3031860 by truls1502: Update drupal/admin_toolbar from 1.25 to 1.26
  composer.json
  drupal-org.make
Labels: update

#1188 Issue #2968506 by uros.ceh, jaapjan, truls1502: When group is deleted the posts in this group should be deleted as well
  modules/social_features/social_group/social_group.module
  tests/behat/features/capabilities/group/group-edit-open.feature
Labels: bug, ext, needs review

#1213 Issue #3031858 by truls1502: Update bower-asset/highlight from 9.13.1 to 9.14.2
  composer.json
Labels: update

#1191 Issue #3027510 by truls1502: Update drupal/bootstrap from 3.15.0 to 3.17.0
  composer.json
  drupal-org.make
Labels: update

#1181 Issue #3026071: As a GM I want to get a notification when someone new joined my group
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_creator/src/Plugin/ActivityContextBase.php
  modules/custom/activity_logger/activity_logger.tokens.inc
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/social_features/social_activity/config/install/message.template.join_to_group.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
Labels: Needs MOSS work, feature request

#1216 Issue #3027339: The 'pill badge' style is not working properly in text editors
  modules/social_features/social_editor/config/install/editor.editor.full_html.yml
Labels: Needs MOSS work, bug

#1217 Issue #3032327: As a LU the tags block should be updated after I add a tag to a group/node
  modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
Labels: Needs MOSS work, bug

#1162 #3020571: Implement config schema for message.template.*.third_party.activity_logger
  modules/custom/activity_logger/activity_logger.module
  modules/custom/activity_logger/activity_logger.post_update.php
  modules/custom/activity_logger/config/schema/activity_logger.schema.yml
Labels: code refactoring, needs release notes

#1219 DS-4604 - Preview header image should be in the theme folder
  themes/socialblue/color/css/preview.css
  themes/socialblue/os-builder/kss-assets/homepage-block.jpg
Labels: bug

#1198 Issue #3028153: Profile Tag List not displaying correctly in filter on user search page
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/src/Plugin/Field/FieldWidget/CategorizedOptionsbuttonsWidget.php
  modules/social_features/social_search/config/install/views.view.search_users.yml
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/form-elements.css
  themes/socialbase/assets/css/nav-tabs.css
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/form-elements/form-elements.scss
Labels: bug, needs LGOS documentation, needs release notes, needs review

#1228 Issue #3034318 by jaapjan: prevent Notifications 500 errors after upd…
  modules/custom/activity_creator/activity.page.inc
Labels: bug, code refactoring

#1223 DS-6367 - Adding members to groups in bulk #52395
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/Plugin/Action/AddMembersToGroup.php
  modules/social_features/social_group/src/SocialGroupAdminPeopleConfigOverride.php
Labels: feature request

#1235 Issue #3035592: make sure event exists before calling toUrl method on it
  modules/social_features/social_event/social_event.tokens.inc
Labels: bug
