Repository goalgorilla/open_social, pull requests merged in 2019-05, with the labels that each got.

#1354 DS-6569 Minor textual change on Adding event enrollee submit message.
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
  modules/social_features/social_event/social_event.module
Labels: SaaS, feature request, needs backport, needs review

#1357 Issue #3052391 by jaapjan: make privacy setting description clearer
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
Labels: SaaS, needs review

#1353 DS-6570 - Improvement - Can’t find someone for adding to event
  modules/social_features/social_core/src/Entity/EntityAutocompleteMatcher.php
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
Labels: SaaS, feature request, needs backport, needs release notes, needs work

#1358 Update TAR dependency in yarn
  themes/socialbase/yarn.lock
  themes/socialblue/yarn.lock
Labels: bug, needs review

#1336 Issue #3000026 by mdeny: Add patch for message to fix Notice: 'Undefined index: value in MessageTemplate->getText()'
  composer.json
  drupal-org.make
Labels: bug, eci

#1349 Feature/3050093 create events after update
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/Service/SocialEventEnrollService.php
Labels: bug, needs backport, needs work

#1342 3050192: Check if Url is instanceof Url and check if the Url is routed
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
Labels: Needs MOSS work, bug, eci, needs backport, needs review

#1351 Issue #3051436 by Kingdutch: Sub-theme hero gradient broken
  modules/custom/improved_theme_settings/improved_theme_settings.module
Labels: bug, needs backport, needs review, support

#1343 DS-6572 in remembrance of Allo Allo - I shall attach the gallery / click handlers only ONCE
  modules/social_features/social_comment_upload/js/comment-upload.js
Labels: bug, needs review

#1344 3050377: Tags block on the group manage members page
  modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
Labels: Needs MOSS work, bug, needs backport, needs review

#1317 Issue #3035614 by agami4: Add the ability to move the text to a new line in the card block
  themes/socialbase/components/02-atoms/cards/cards.scss
  themes/socialbase/templates/views/views-view.html.twig
Labels: bug, needs review

#1352 Issue #3051679 by Kingdutch: Buttons for anonymous enroll form wrap o…
  modules/social_features/social_event/modules/social_event_an_enroll/css/event_an_enroll.css
  modules/social_features/social_event/modules/social_event_an_enroll/css/event_an_enroll.scss
Labels: bug, needs backport, support

#1367 Issue #3049363 by robertragas: Add social_path_manager missing depend…
  drupal-org.make
Labels: bug, needs backport, needs review

#1378 #3053234: Replaced incorrect route for default profile landing page at user settings
  modules/social_features/social_user/src/Form/SocialUserSettingsForm.php
Labels: bug, needs review, support

#1380 Issue #3050760: Ensure event max enroll limit takes anonymous enrollments into account
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.services.yml
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollService.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
Labels: bug, needs review, support

#1383 Issue #3053609 by Kingdutch: Default metatag configuration for topics…
  modules/custom/social_metatag/config/install/metatag.metatag_defaults.node__topic.yml
  modules/custom/social_metatag/social_metatag.post_update.php
Labels: bug, needs backport, needs review, support

#1386 Improve event-max-enroll and topic-download-count test
  tests/behat/features/capabilities/event-an-enroll/event-max-enroll.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
Labels: needs backport, needs review

#1389 Issue #3053953 by robertragas: fix enrollments export for event managers
  modules/social_features/social_user_export/social_user_export.module
Labels: bug, needs backport, support

#1393 Issue #3054123 by truls1502: Update drupal/search_api from 1.12 to 1.13
  composer.json
  drupal-org.make
Labels: needs review, update

#1391 Issue #3054120 by truls1502: Update drupal/ctools from 3.0 to 3.2
  composer.json
  drupal-org.make
Labels: needs review, update

#1363 Issue #3045770 by agami4: Add label to search forms
  modules/social_features/social_search/src/Form/SearchContentForm.php
  modules/social_features/social_search/src/Form/SearchHeroForm.php
  themes/socialbase/templates/form/form-element--search-input-content.html.twig
Labels: feature request, needs review

#1390 Issue #3054119 by truls1502: Update drupal/bootstrap from 3.17 to 3.19
  composer.json
  drupal-org.make
Labels: needs backport, update

#1360 Issue #3029706 by agami4: Add svg icon for search button
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialbase/includes/form.inc
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
Labels: bug

#1364 Issue #3029738 by agami4: Remove the duplicate buttons
  modules/social_features/social_follow_content/config/install/views.view.following.yml
Labels: bug, needs backport

#1373 Issue #2949011 by agami4: Add new styles for unread thread card on social base theme
  themes/socialbase/assets/css/message.css
  themes/socialbase/components/04-organisms/message/message.scss
Labels: feature request, needs backport

#1385 Issue #3053671 by robertragas: Check if the message thread exists bef…
  modules/social_features/social_private_message/src/Plugin/ActivityContext/PrivateMessageActivityContext.php
Labels: bug, verified-cherry-picks

#1384 Issue #3053668: Load all activity entities at once instead of one by one
  modules/custom/activity_creator/src/ActivityNotifications.php
Labels: needs review, support

#1370 Issue #2975701 by agami4: Add content variable without default fields
  themes/socialbase/templates/profile/profile--profile--default.html.twig
Labels: eci, feature request, needs backport

#1402 Bug 3055336 likes translation
  themes/socialbase/templates/node/node--full.html.twig
Labels: bug, ext, needs backport, needs release notes

#1382 TB-1894 - Auto login links
  modules/custom/social_magic_login/social_magic_login.info.yml
  modules/custom/social_magic_login/social_magic_login.module
  modules/custom/social_magic_login/social_magic_login.routing.yml
  modules/custom/social_magic_login/social_magic_login.services.yml
  modules/custom/social_magic_login/src/Controller/MagicLoginController.php
  modules/custom/social_magic_login/src/Service/MagicUrl.php
  modules/custom/social_magic_login/src/Service/MagicUrlInterface.php
Labels: bananas, feature request, needs backport

#1396 Issue #3054601: VBO Javascript for Manage Members and Enrollees is attached too often
  modules/social_features/social_event/modules/social_event_managers/js/frontUi.js
  modules/social_features/social_group/js/frontUi.js
Labels: bananas, bug, needs backport, needs review

#1397 Issue #3054534 by robertragas: add patch to remove group machine name…
  composer.json
Labels: bananas, bug, needs backport

#1405 Issue #3056603: Increased performance for marking notifications as read
  modules/custom/activity_creator/js/notifications.js
Labels: bananas, bug, needs review

#1403 Issue #3056298: Removed group content causes error in GroupContentInM…
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
Labels: bananas, bug, needs backport

#1281 Issue #2898087: Create "secret" group type/Private groups
  composer.json
  modules/social_features/social_group/config/install/group.type.closed_group.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_form_display.group.secret_group.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_form_display.group_content.secret_group-group_membership.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group.secret_group.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group.secret_group.hero.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group.secret_group.small_teaser.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group.secret_group.stream.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group.secret_group.teaser.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_membership.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-event.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-event.teaser.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-topic.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-topic.teaser.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/field.field.group.secret_group.field_group_address.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/field.field.group.secret_group.field_group_description.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/field.field.group.secret_group.field_group_image.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/field.field.group.secret_group.field_group_location.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/field.field.group_content.secret_group-group_membership.group_roles.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.content_type.secret_group-group_membership.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.content_type.secret_group-group_node-event.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.content_type.secret_group-group_node-topic.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-83776d798.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-a416e6833.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-anonymous.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-ba5854c29.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-group_admin.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-group_manager.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-member.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.role.secret_group-outsider.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/group.type.secret_group.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.features.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.info.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.services.yml
  modules/social_features/social_group/modules/social_group_secret/src/EventSubscriber/SocialGroupSecretSubscriber.php
  modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  themes/socialbase/assets/icons/icons.svg
  themes/socialbase/components/06-libraries/icons/source/icon-shield.svg
  themes/socialbase/templates/group/group--teaser.html.twig
Labels: bananas, feature request, needs release notes, needs review
