Repository goalgorilla/open_social, pull requests merged in 2019-12, with the labels that each got.

#1508 Issue #3083874 by ribel, agami4: As a SM I want to switch to different flavors of my Social Blue theme
  themes/socialbase/templates/block/block--views-block--sidebar.html.twig
  themes/socialblue/assets/css/badge.css
  themes/socialblue/assets/css/base.css
  themes/socialblue/assets/css/brand--sky.css
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/assets/css/form-controls.css
  themes/socialblue/assets/css/form-elements.css
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/assets/css/hero.css
  themes/socialblue/assets/css/input-groups.css
  themes/socialblue/assets/css/kss.css
  themes/socialblue/assets/css/navbar--sky.css
  themes/socialblue/assets/css/navbar.css
  themes/socialblue/assets/css/pagination.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/assets/css/site-footer--sky.css
  themes/socialblue/assets/css/stream--sky.css
  themes/socialblue/assets/css/styleguide.css
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/assets/css/toc.css
  themes/socialblue/assets/css/waves.css
  themes/socialblue/components/00-config/_mixins.scss
  themes/socialblue/components/00-config/mixins/_card.scss
  themes/socialblue/components/00-config/variables/_colors.scss
  themes/socialblue/components/02-atoms/cards/cards--sky.scss
  themes/socialblue/components/03-molecules/navigation/navbar/navbar--sky.scss
  themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
  themes/socialblue/components/04-organisms/site-footer/site-footer--sky.scss
  themes/socialblue/components/04-organisms/stream/stream--sky.scss
  themes/socialblue/components/brand--sky.scss
  themes/socialblue/socialblue.theme
  themes/socialblue/src/Plugin/Alter/ThemeSuggestions.php
  themes/socialblue/src/Plugin/Preprocess/Html.php
  themes/socialblue/src/Plugin/Preprocess/Links.php
  themes/socialblue/theme-settings.php
Labels: eci, feature request, high, needs rebase, needs review

#1629 #3098456: Add language as a column to the user export
  modules/custom/social_language/src/Plugin/UserExportPlugin/UserLanguage.php
  modules/custom/social_language/src/Plugin/UserExportPlugin/UserLanguageCode.php
Labels: bananas, feature request, needs backport

#1592 Issue #3055752 by agami4: Remove styles for range input
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/components/00-config/variables/_forms.scss
  themes/socialbase/components/02-atoms/form-controls/_range.scss
  themes/socialbase/components/02-atoms/form-controls/form-controls.scss
  themes/socialblue/assets/css/badge.css
  themes/socialblue/assets/css/base.css
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/assets/css/form-controls.css
  themes/socialblue/assets/css/form-elements.css
  themes/socialblue/assets/css/hero.css
  themes/socialblue/assets/css/input-groups.css
  themes/socialblue/assets/css/kss.css
  themes/socialblue/assets/css/navbar--sky.css
  themes/socialblue/assets/css/navbar.css
  themes/socialblue/assets/css/pagination.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/assets/css/stream--sky.css
  themes/socialblue/assets/css/styleguide.css
  themes/socialblue/assets/css/toc.css
  themes/socialblue/assets/css/waves.css
  themes/socialblue/components/00-config/variables/_forms.scss
  themes/socialblue/components/02-atoms/form-controls/_input.scss
Labels: bug, eci, needs review

#1628 Add untranslatable string to the list
  translations.php
Labels: bananas, needs review, translations

#1631 Issue #3099682 by Kingdutch: Update Javascript dependencies
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js.map
  modules/social_features/social_search/modules/social_search_autocomplete/yarn.lock
  themes/socialbase/yarn.lock
  themes/socialblue/yarn.lock
Labels: low, needs review, shipsters, update

#1622 Issue #3097343 by Kingdutch: Social Core should not depend on the hel…
  config/optional/block.block.seven_help.yml
  config/optional/block.block.socialbase_help.yml
  config/optional/block.block.socialblue_help.yml
  modules/social_features/social_core/social_core.info.yml
Labels: bug, low, needs review, shipsters

#1633 Issue #2929368 by Kingdutch, ozin, left, ronaldtebrake, albertoalaejo…
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
Labels: bug, low, needs review, shipsters

#1627 Updated the logic to render notification colors and added a method in notifications service to get status of a notification.
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_creator/src/ActivityNotifications.php
  modules/custom/activity_creator/src/Controller/NotificationsController.php
Labels: bananas, bug, code refactoring, medium, needs maintainer input, needs review

#1636 Add untranslatable strings to work-around
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  translations.php
Labels: bananas, translations

#1626 Issue #3098046 by Kingdutch, robertragas: Replace SocialLanguageMetadataBubblingUrlGenerator by Entity::toUrl implementations
  composer.json
  drupal-org.make
  modules/custom/social_language/social_language.module
  modules/custom/social_language/social_language.services.yml
  modules/custom/social_language/src/Plugin/Block/LanguageSwitcherBlock.php
  modules/custom/social_language/src/SocialLanguageMetadataBubblingUrlGenerator.php
  modules/custom/social_language/src/SocialLanguageServiceProvider.php
  modules/social_features/social_book/social_book.info.yml
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/src/Entity/Comment.php
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.module
  modules/social_features/social_core/src/EntityUrlLanguageTrait.php
  modules/social_features/social_event/social_event.info.yml
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Entity/Group.php
  modules/social_features/social_landing_page/social_landing_page.info.yml
  modules/social_features/social_node/social_node.info.yml
  modules/social_features/social_node/social_node.module
  modules/social_features/social_node/src/Entity/Node.php
  modules/social_features/social_node/src/NodeViewBuilder.php
  modules/social_features/social_page/social_page.info.yml
  modules/social_features/social_post/src/Entity/Post.php
  modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js.map
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/TranslationContext.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/SearchSuggestions.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/index.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.module
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.post_update.php
  modules/social_features/social_topic/social_topic.info.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Entity/User.php
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialbase/src/Plugin/Preprocess/LanguageLinks.php
  themes/socialbase/templates/system/links--language-block.html.twig
Labels: bananas, bug, medium

#1637 Issue #3100539 by sjoerdvandervis: Make the description of the Reply-to field more explanatory
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  translations.php
Labels: bananas, feature request, low, needs backport, translations

#1567 Issue #3088507 by agami4: Update small hero banner on the group page
  themes/socialbase/assets/css/hero.css
  themes/socialbase/components/04-organisms/hero/hero.scss
Labels: bug, eci, needs backport

#1643 Issue #3101360 by chmez: Push notification providers description
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.module
  modules/custom/activity_send/modules/activity_send_push_notification/src/Annotation/Push.php
Labels: bug, eci, medium

#1610 Issue #3095296 by agami4: Add primary color for links on the paragraphs on the landing page
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/page-node.css
  themes/socialblue/components/05-templates/page-node/page-node.scss
  themes/socialblue/components/brand.scss
Labels: eci, feature request

#1571 #3102347 - As SM I want to be albe to add a remark to a Users profile for other SM's on the site
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/comment.type.comment_profile.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/core.entity_form_display.comment.comment_profile.default.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/core.entity_view_display.comment.comment_profile.default.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/field.field.comment.comment_profile.field_comment_body.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/field.field.profile.profile.field_manager_notes.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/config/install/field.storage.profile.field_manager_notes.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/css/manager_notes.css
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.info.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.install
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.libraries.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.module
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.permissions.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.services.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/src/SocialProfileManagerNotesConfigOverride.php
  modules/social_features/social_profile/modules/social_profile_manager_notes/templates/field--profile--type--comment.html.twig
  tests/behat/features/capabilities/profile/profile-manager-notes.feature
  themes/socialbase/templates/profile/profile--profile--default.html.twig
Labels: feature request, medium, shipsters

#1649 Issue #3102731 by Kingdutch: Cover image for nodes doesn't receive pr…
  themes/socialbase/templates/node/node--hero.html.twig
Labels: bananas, bug, medium, needs backport, needs review

#1650 Issue #3086434 by sjoerdvandervis: Flexible groups on landing pages
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_landing_page/config/optional/core.entity_view_display.group.flexible_group.featured.yml
Labels: bananas, needs backport

#1644 Issue #3101762 by Kingdutch: social_sharing_update_8001 can fail if b…
  modules/social_features/social_sharing/social_sharing.install
Labels: bug, low, needs backport, needs review, shipsters
