Repository goalgorilla/open_social, pull requests merged in 2019-07, with the labels that each got.

#1345 by robertragas: add the social_content_block module to be able to cre…
  composer.json
  drupal-org.make
  modules/social_features/social_content_block/config/install/block_content.type.custom_content_list.yml
  modules/social_features/social_content_block/config/install/core.entity_form_display.block_content.custom_content_list.default.yml
  modules/social_features/social_content_block/config/install/core.entity_view_display.block_content.custom_content_list.default.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_content_tags.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_group.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_item_amount.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_link.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_sorting.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_subtitle.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_topic_type.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_content_tags.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_group.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_item_amount.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_link.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_sorting.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_subtitle.yml
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_topic_type.yml
  modules/social_features/social_content_block/social_content_block.api.php
  modules/social_features/social_content_block/social_content_block.info.yml
  modules/social_features/social_content_block/social_content_block.module
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_content_block/src/ContentBuilderInterface.php
  modules/social_features/social_content_block/src/SocialContentBlockOverride.php
  modules/social_features/social_content_block/templates/social-content-block.html.twig
Labels: Needs MOSS work, eci, feature request, medium

#1239 Give possibility to add additional header and footer to emails
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/templates/digestmail.html.twig
  modules/custom/activity_send/modules/activity_send_email/templates/directmail.html.twig
  modules/social_features/social_editor/config/install/editor.editor.mail_html.yml
  modules/social_features/social_editor/config/install/filter.format.mail_html.yml
  modules/social_features/social_swiftmail/config/schema/social_swiftmail.schema.yml
  modules/social_features/social_swiftmail/social_swiftmail.module
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  themes/socialbase/templates/swiftmailer.html.twig
Labels: bananas, eci, feature request, medium, needs work

#1437 Issue #3065237 by truls1502: Update drupal/views_infinite_scroll from 1.5 to 1.6
  composer.json
  drupal-org.make
Labels: Needs MOSS work, needs backport, needs review, update

#1436 Issue #3065039 by truls1502: Update drupal/redirect from 1.3 to 1.4
  composer.json
  drupal-org.make
Labels: Needs MOSS work, needs backport, needs review, update

#1369 Issue #2984283 by agami4: Add loader indicator when loading image
  themes/socialbase/assets/css/ajax.css
  themes/socialbase/assets/css/comment.css
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/assets/css/form-post-create.css
  themes/socialbase/components/02-atoms/form-controls/_input.scss
  themes/socialbase/components/03-molecules/form-elements/autocomplete/ajax.scss
  themes/socialbase/components/04-organisms/comment/comment.scss
  themes/socialbase/components/04-organisms/forms/form-post-create.scss
Labels: feature request, medium, needs review, performance

#1377 Issue #3052572 by agami4: Add classes for preview button on edit node page
  themes/socialbase/includes/form.inc
Labels: bug, low, needs review

#1438 Issue #2983330: rename description for e-mail settings (Remove Swiftmail reference)
  modules/social_features/social_swiftmail/social_swiftmail.links.menu.yml
Labels: needs review

#1365 Issue #3029695 by agami4: Open navigation menu on focus and hover without js
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/assets/js/navbar-search.min.js
  themes/socialbase/components/03-molecules/dropdown/dropdown.scss
  themes/socialbase/components/03-molecules/navigation/navbar/navbar-search.js
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialbase/templates/block/block--system-menu-block--main.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: feature request, low

#1388 Issue #289670 by agami4: Add sorting option for topics on group and community level
  modules/social_features/social_group/config/install/views.view.group_topics.yml
  modules/social_features/social_topic/config/install/views.view.latest_topics.yml
Labels: eci, feature request, low, needs review

#1411 Issue #3065011 Lazy loading - Embedded media
  composer.json
  drupal-org.make
  modules/custom/social_lazy_loading/composer.json
  modules/custom/social_lazy_loading/social_lazy_loading.api.php
  modules/custom/social_lazy_loading/social_lazy_loading.info.yml
  modules/custom/social_lazy_loading/social_lazy_loading.module
  modules/custom/social_lazy_loading/social_lazy_loading.services.yml
  modules/custom/social_lazy_loading/src/SocialLazyLoadingTextFormatOverride.php
  modules/social_features/social_embed/src/SocialEmbedConfigOverride.php
  modules/social_features/social_mentions/src/SocialMentionsConfigOverride.php
Labels: feature request, high, performance

#1427 Issue #3065016 issue with node add/edit/delete pages and pathauto
  modules/custom/social_path_manager/social_path_manager.info.yml
  modules/custom/social_path_manager/social_path_manager.module
  modules/social_features/social_core/config/optional/block.block.socialblue_pagetitleblock_content.yml
  modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
  themes/socialbase/src/Plugin/Preprocess/PageTitle.php
Labels: bug, medium, needs work

#1439 #3063713 - bulk actions on all pages fails for event enrollments
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
Labels: bananas, bug, high, needs backport

#1417 #3060226 - The Data Policy module overrides the destination given in the auto login url
  composer.json
  drupal-org.make
  modules/custom/social_magic_login/social_magic_login.module
  modules/custom/social_magic_login/src/Controller/MagicLoginController.php
  modules/custom/social_magic_login/src/Service/MagicUrl.php
Labels: bananas, bug, low, needs release notes, needs work, update

#1410 #3066419 - Make the cron more stable by adding defensive checks
  modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/custom/activity_creator/src/Plugin/ActivityContextBase.php
  modules/custom/activity_logger/activity_logger.tokens.inc
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
Labels: bananas, bug, high, needs backport, needs commit cleanup, performance

#1446 Issue #3066600 make sure EO can add enrollees to their event
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.routing.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.services.yml
  modules/social_features/social_event/modules/social_event_managers/src/Access/AddEnrolleeAccessCheck.php
Labels: bug, needs backport, needs review

#1448 #3063713 - bulk actions on all pages fails for Group Members
  composer.json
  modules/social_features/social_group/config/install/views.view.group_manage_members.yml
  modules/social_features/social_group/modules/social_group_gvbo/src/Form/SocialGroupViewsBulkOperationsConfigureAction.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Controller/GroupManagersController.php
  modules/social_features/social_group/src/Plugin/views/access/ManageByGroupManagersOnlyAccess.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
Labels: bug, needs backport, needs work

#1220 Issue #3032407 by ribel: Refactor page hero block
  modules/social_features/social_core/social_core.module
  modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.hero.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollForm.php
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/topic/topic-create.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
  tests/behat/features/capabilities/topic/topic-follow-content.feature
  themes/socialbase/src/Plugin/Preprocess/Node.php
  themes/socialbase/templates/node/node--hero.html.twig
  themes/socialbase/templates/node/page-hero-data.html.twig
Labels: code refactoring, eci, high

#1443 by robertragas: add description fields to explain what they do
  modules/social_features/social_content_block/social_content_block.module
Labels: bug

#1304 Issue #3046160 by ribel: As a LU I want to see more information about the item in email notifications I get
  modules/custom/activity_send/modules/activity_send_email/templates/digestmail.html.twig
  modules/custom/activity_send/modules/activity_send_email/templates/directmail.html.twig
  modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
  modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
  modules/social_features/social_activity/config/install/message.template.create_post_profile.yml
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_activity/templates/message-node-teaser.html.twig
  modules/social_features/social_activity/templates/message-post-teaser.html.twig
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_follow_content/config/install/message.template.create_comment_following_node.yml
  themes/socialbase/templates/swiftmailer.html.twig
Labels: eci, feature request, high

#1441 Issue #3019458 by royharink: Issue with Custom email header footer settings page
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/templates/digestmail.html.twig
  modules/custom/activity_send/modules/activity_send_email/templates/directmail.html.twig
  modules/social_features/social_swiftmail/config/schema/social_swiftmail.schema.yml
  modules/social_features/social_swiftmail/social_swiftmail.install
  modules/social_features/social_swiftmail/social_swiftmail.module
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  themes/socialbase/templates/swiftmailer.html.twig
Labels: bananas, bug, needs review

#1455 Feature/unpublished posts reachable by site manager
  modules/custom/activity_creator/src/Entity/Activity.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
  modules/social_features/social_post/social_post.install
  modules/social_features/social_post/social_post.module
  modules/social_features/social_post/src/PostListBuilder.php
  themes/socialbase/assets/css/post.css
  themes/socialbase/assets/css/stream.css
  themes/socialbase/components/04-organisms/post/post.scss
  themes/socialbase/components/04-organisms/stream/stream.scss
  themes/socialbase/socialbase.libraries.yml
  themes/socialbase/templates/activity/activity.html.twig
  themes/socialbase/templates/post/post--activity.html.twig
  themes/socialbase/templates/post/post.html.twig
Labels: feature request, medium, needs release notes, needs work

#1462 Issue #3070309 by truls1502: Update drupal/metatag from 1.8 to 1.9
  composer.json
  drupal-org.make
Labels: needs backport, needs review, update

#1463 Issue #3067525 search autocomplete separator comma
  modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.post_update.php
Labels: bug, high, needs backport, needs review

#1466 Issue #3071335 by ronaldtebrake: implement patch for lazy loading
  composer.json
  drupal-org.make
Labels: bug, high, needs backport, needs release notes, needs review, shipsters

#1464 Issue #3071035 by Kingdutch: Geolocation Maps Markers use incorrect c…
  themes/socialblue/assets/css/badge.css
  themes/socialblue/assets/css/base.css
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/dropdown.css
  themes/socialblue/assets/css/form-controls.css
  themes/socialblue/assets/css/form-elements.css
  themes/socialblue/assets/css/hero.css
  themes/socialblue/assets/css/input-groups.css
  themes/socialblue/assets/css/kss.css
  themes/socialblue/assets/css/navbar.css
  themes/socialblue/assets/css/pagination.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/assets/css/styleguide.css
  themes/socialblue/assets/css/toc.css
  themes/socialblue/assets/css/waves.css
  themes/socialblue/components/brand.scss
Labels: bananas, bug, medium, verified-cherry-picks

#1465 DS-6013 As a CM+, I want to unpublish a comment easily.
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/social_comment.routing.yml
  modules/social_features/social_comment/src/Controller/SocialCommentController.php
Labels: feature request, medium, needs review, shipsters
