Repository goalgorilla/open_social, pull requests merged in 2019-09, with the labels that each got.

#1454 #3061418: Update "Data policy" block on IE11
  themes/socialblue/assets/css/cards.css
  themes/socialblue/components/02-atoms/cards/cards.scss
Labels: bug, eci, needs rebase, needs review

#1440 issue #2998508 by albertoalaejos: Comment unpublished status translat…
  themes/socialbase/templates/comment/comment.html.twig
Labels: bug, needs review, shipsters

#1496 Issue #3065169 - Header menu hidden in PhotoSwipe [Tested and rebased]
  themes/socialbase/assets/css/layout.css
  themes/socialbase/assets/js/autocomplete.min.js
  themes/socialbase/assets/js/imageWidgetCrop.min.js
  themes/socialbase/assets/js/informblock.min.js
  themes/socialbase/assets/js/photoswipe.min.js
  themes/socialbase/components/04-organisms/photoswipe/photoswipe.js
  themes/socialbase/components/05-templates/layout/layout.scss
Labels: bug, eci

#1492 TB-2773: Replaced triple for each loop with a database query to extract file's parent properties.
  modules/custom/download_count/download_count.module
Labels: bananas

#1479 Feature/3056821 ajaxify notification centre
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_creator/activity_creator.routing.yml
  modules/custom/activity_creator/activity_creator.tokens.inc
  modules/custom/activity_creator/js/notifications.js
  modules/custom/activity_creator/src/ActivityNotifications.php
  modules/custom/activity_creator/src/Controller/NotificationsController.php
  modules/social_features/social_activity/social_activity.module
Labels: bananas, code refactoring, needs change record, needs maintainer input, needs release notes, needs review, performance

#1500 Issue #3081555 by jaapjan: add BubbleableMetadata.
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/social_features/social_event/social_event.tokens.inc
Labels: needs review, shipsters

#1501 DS-6717: demo content generator + Group Patches + Webprofiler compatibility
  composer.json
  drupal-org.make
  modules/custom/social_demo/social_demo.drush.inc
  modules/custom/social_demo/src/DemoComment.php
  modules/custom/social_demo/src/DemoContent.php
  modules/custom/social_demo/src/DemoContentInterface.php
  modules/custom/social_demo/src/DemoEntity.php
  modules/custom/social_demo/src/DemoGroup.php
  modules/custom/social_demo/src/DemoNode.php
  modules/custom/social_demo/src/DemoSystem.php
  modules/custom/social_demo/src/DemoTaxonomyTerm.php
  modules/custom/social_demo/src/DemoUser.php
  modules/social_features/social_activity/config/install/views.view.activity_stream_group.yml
  modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
  modules/social_features/social_activity/config/install/views.view.activity_stream_profile.yml
  modules/social_features/social_post/src/PostAccessControlHandler.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsHelper.php
Labels: feature request, needs review, performance

#1505 Update php in Travis configuration to 7.3.
  .travis.yml
Labels: needs review, performance, shipsters

#1478 Flexible group several fixes see issue for d.org issues & Optional UI install.
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.hero.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.small_teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.stream.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_address.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_description.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_image.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_location.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group_content.flexible_group-group_membership.group_roles.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-83776d798.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-a416e6833.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-anonymous.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-ba5854c29.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_admin.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_manager.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-member.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-outsider.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.api.php
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
  modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
  social.profile
Labels: bug, feature request, high, shipsters

#1483 Issue #3075818 by Kingdutch: Exports don't support applications runni…
  modules/social_features/social_event/modules/social_event_enrolments_export/src/Plugin/Action/ExportEnrolments.php
  modules/social_features/social_group/modules/social_group_members_export/src/Plugin/Action/ExportMember.php
  modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
Labels: bananas, bug, medium, needs backport, needs review

#1428 Issue #3062477 by chmez: Allow rich text formatting when sending bulk emails to group members or event enrollees
  modules/social_features/social_core/social_core.install
  modules/social_features/social_editor/config/install/editor.editor.mail_html.yml
  modules/social_features/social_editor/config/install/filter.format.mail_html.yml
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
  modules/social_features/social_swiftmail/social_swiftmail.install
  modules/social_features/social_swiftmail/social_swiftmail.module
  modules/social_features/social_swiftmail/src/Element/SocialSwiftmailTextFormat.php
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  themes/socialbase/src/Plugin/Preprocess/FormElement.php
Labels: code refactoring, eci, feature request, high, needs backport, needs review

#1499 issue #3081129 by albertoalaejos: Event enrollment list shows the sam…
  modules/custom/social_demo/content/entity/event-enrollment.yml
Labels: bug, medium, needs review

#1516 Issue #3054708: Add validation to check for unique nick names
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNickname.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNicknameValidator.php
  tests/behat/features/capabilities/profile/unique-nickname.feature
Labels: bananas, feature request

#1513 Issue #3084268 by robertragas: Optimize group membership count
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/Controller/SocialGroupListBuilder.php
  modules/social_features/social_group/src/SocialGroupMembersCount.php
Labels: bananas

#1497 Issue #3080318 by chmez: Lazy Loading Image module installation
  modules/custom/social_lazy_loading/social_lazy_loading.info.yml
  modules/custom/social_lazy_loading/social_lazy_loading.install
  modules/custom/social_lazy_loading/social_lazy_loading.services.yml
  modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.services.yml
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.module
Labels: bug, code refactoring, eci, medium, needs backport, needs review

#1502 Update drupal/csv_serialization + league/csv to 9.2
  composer.json
  drupal-org.make
Labels: needs review, shipsters, update

#1495 issue #3031547 by albertoalaejos, jaapjan: Unpublished event is not showing in…
  modules/social_features/social_event/config/install/views.view.upcoming_events.yml
Labels: bug, needs review, shipsters, verified-cherry-picks

#1504 Issue #3082600 by robertragas: replace html escape with xss filter as…
  modules/social_features/social_search/src/Form/SearchContentForm.php
  modules/social_features/social_search/src/Form/SearchHeroForm.php
Labels: bananas, needs review

#1485 Issue #3076279 by agami4: Update dropdown width
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/components/03-molecules/dropdown/dropdown.scss
Labels: bug, eci, needs review

#1514 #3077289 - Secret group doesnt have defaults for visbility settings
  modules/social_features/social_group/social_group.module
Labels: bug, medium, needs backport, needs review, shipsters

#1517 Issue #3062716 by mdeny, agami4: Collapse email notification digest settings by default
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.libraries.yml
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.css
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.css.map
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.scss
  modules/custom/activity_send/modules/activity_send_email/js/collapse.js
  tests/behat/features/capabilities/notifications/notification-emails.feature
Labels: eci, feature request, high, needs backport, needs review

#1473 Issue #3071038 by agami4: Update color for clusters
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: bug, eci, needs backport, needs work

#1489 #3077364 by agami4: Update height of small hero banner for IE
  themes/socialbase/assets/css/hero.css
  themes/socialbase/components/04-organisms/hero/hero.scss
Labels: bug, eci, medium, needs backport
