Repository goalgorilla/open_social, pull requests merged in 2020-02, with the labels that each got.

#1699 Issue #3109219 by bramtenhove: Prevent a welcome message being sent to the owner of the group
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
Labels: action: testing day, prio: medium, team: shipsters, type: bug

#1702 YANG-2093: Add min-height for the teaser__image on the join group popup
  modules/custom/group_core_comments/assets/css/group_core_comments.css
  modules/custom/group_core_comments/assets/css/group_core_comments.css.map
  modules/custom/group_core_comments/assets/css/group_core_comments.scss
Labels: action: testing day, status: needs review, team: eci, type: bug

#1703 YANG-2111: Add reset styles for the select widget on the IE11 browser
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/components/02-atoms/form-controls/_select.scss
Labels: action: testing day, status: needs review, team: eci, type: bug

#1704 YANG-2107: Update "Edit profile" button on the IE11
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/components/02-atoms/cards/cards--sky.scss
Labels: action: testing day, status: needs review, team: eci, type: bug

#1708 Issue #3098031 by Kingdutch, ronaldtebrake: Evaluate which modules sh…
  modules/custom/social_ajax_comments/social_ajax_comments.info.yml
  modules/custom/social_queue_storage/social_queue_storage.info.yml
  modules/custom/social_react/social_react.info.yml
  modules/social_features/social_embed/social_embed.info.yml
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.info.yml
  modules/social_features/social_private_message/social_private_message.info.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.info.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.info.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.info.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.info.yml
Labels: prio:low, status: needs review, team: shipsters, type: feature request

#1698 Issue #3110127 by Kingdutch: Allow modules to declare themselves as optional features
  modules/custom/social_file_private/social_file_private.installer_options.yml
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.installer_options.yml
  modules/custom/social_lets_connect/modules/social_lets_connect_usage/social_lets_connect_usage.installer_options.yml
  modules/social_features/social_book/social_book.installer_options.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.installer_options.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.installer_options.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.installer_options.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.installer_options.yml
  modules/social_features/social_sharing/social_sharing.installer_options.yml
  modules/social_features/social_sso/social_sso.installer_options.yml
  social.installer_options_list.yml
  src/Exception/SocialFeatureDataException.php
  src/Installer/Form/ModuleConfigureForm.php
  src/Installer/OptionalModuleManager.php
  yaml_translation_patterns.yml
Labels: prio:low, team: shipsters, type: feature request

#1710 Update VBO to Fix SA-CONTRIB-2020-003
  composer.json
  drupal-org.make
Labels: prio: high, team: shipsters, type: update

#1706 Issues #3109076: Added cache context to node edit url link.
  modules/social_features/social_core/social_core.module
Labels: SaaS, action: testing day, team: bananas, type: bug

#1715 Issue #3112434 Behat test for GDPR inform block fails
  tests/behat/features/capabilities/gdpr/inform-block.feature
Labels: status: needs backport, status: needs review, team: shipsters, type: bug

#1713 #3111961: Make sure the post, comment and node entities have the correct view mode in the stream after the update to 8.x
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_core/social_core.install
  modules/social_features/social_post/social_post.install
Labels: prio: high, team: shipsters, type: bug

#1717 Issue #3112823 by Kingdutch, navneet0693: Typo in service restore of …
  modules/social_features/social_core/social_core.install
Labels: prio:low, status: needs backport, status: needs review, team: shipsters, type: bug

#1711 Issue #3111591 - Fixed an issue with LU users with group manager roles not being able to download an exported CSV from group members
  modules/social_features/social_event/modules/social_event_enrolments_export/src/Plugin/Action/ExportEnrolments.php
  modules/social_features/social_group/modules/social_group_members_export/src/Plugin/Action/ExportMember.php
  modules/social_features/social_user_export/social_user_export.module
  modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
Labels: prio: medium, status: needs backport, status: needs review, team: bananas, type: bug

#1725 Issue #3114669: Update Profile to 1.1
  composer.json
  drupal-org.make
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
  modules/social_features/social_profile/social_profile.module
  tests/behat/features/capabilities/profile/hide-profile-field-groups.feature
Labels: status: needs backport, team: shipsters, type: update

#1723 Issue #3114278: Default social_event.settings.enroll is not an array
  modules/social_features/social_event/config/features_removal/social_event.settings.yml
  modules/social_features/social_event/config/install/social_event.settings.yml
  modules/social_features/social_event/social_event.install
Labels: prio: medium, status: needs backport, status: needs review, team: shipsters, type: bug

#1731 Support 7.x now in travis for ensuring security checks work
  .travis.yml
Labels: prio: high, status: needs backport, status: needs review, team: shipsters

#1721 Issue #3112214 by kokrull, dalfa, sjoerdvandervis: Hidden dependency …
  modules/social_features/social_core/social_core.module
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_featured/config/install/core.entity_view_display.group.flexible_group.featured.yml
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_featured/social_flexible_group_featured.info.yml
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1724 YANG-2458: Update template and styles for the information block
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
  themes/socialbase/templates/profile/profile--profile--default.html.twig
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/components/02-atoms/cards/cards--sky.scss
  themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
  themes/socialblue/templates/profile/profile--profile--default--sky.html.twig
Labels: blocked: maintainer input, prio: high, team: eci, type: bug

#1727 Issue #3113150 by robertragas: since the feature removal failed for t…
  modules/social_features/social_private_message/social_private_message.install
Labels: status: needs backport, status: needs work, team: bananas, type: bug
