Repository goalgorilla/open_social, pull requests merged in 2020-09, with the labels that each got.

#1973 Issue #3169519 by tBKoT: Remove the 'Ongoing' label on main event page
  themes/socialbase/templates/node/event/node--event--full.html.twig
  themes/socialblue/templates/node/node--full--sky.html.twig
Labels: prio: high, team: eci, type: bug

#1972 Issue #3169448 by agami4: Fix color for the badge label on the group teasers
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/assets/css/teaser.css
  themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
  themes/socialblue/components/03-molecules/teaser/teaser.scss
Labels: prio: medium, team: eci, type: bug

#1963 Issue #3168176: Change sorting label for Custom content list block from Creation date to Last created
  modules/social_features/social_content_block/config/install/field.storage.block_content.field_sorting.yml
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/src/ContentBlockBase.php
Labels: prio: high, team: eci, type: feature request

#1961 Fix issues with long teaser tags and landing page introduction block space
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.css
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.scss
  modules/social_features/social_landing_page/templates/paragraph--introduction--default.html.twig
  themes/socialbase/assets/css/badge.css
  themes/socialbase/components/02-atoms/badge/badge.scss
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
Labels: team: eci, type: bug

#1959 Issue #3166552 by rolki: Issue with empty blocks in entity form display
  themes/socialbase/templates/card/bootstrap-panel.html.twig
Labels: prio:low, team: eci, type: bug

#1965 Issue #3162557 by tBKoT, Kingdutch: Update delete notification condition
  modules/custom/activity_creator/activity_creator.install
  modules/custom/activity_creator/src/ActivityNotifications.php
Labels: team: eci, type: bug

#1968 YANG-3478: Allow to use social activity token in other content types, like Discussion
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_comment/social_comment.tokens.inc
Labels: prio: medium, team: eci, type: bug

#1957 Issue #3166522: Sky theme - Render blocks on user edit and profile edit on the right side.
  themes/socialblue/src/Plugin/Preprocess/Html.php
  themes/socialblue/src/Plugin/Preprocess/Page.php
  themes/socialblue/templates/layout/page--user--edit--sky.html.twig
  themes/socialblue/templates/layout/page--user--profile--sky.html.twig
Labels: prio: medium, status: needs backport, status: needs review, team: shipsters, type: bug

#1955 Issue #3144847: Groups about page shows entity label/title
  themes/socialbase/templates/group/group--default.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1914 Issue #3160720 Add expertise and interests as full text indexed fields on the search_user index
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_search/config/update/social_search_update_8901.yml
  modules/social_features/social_search/social_search.install
Labels: SaaS, prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1920 Issue #3159259: Book pages need to be available in the search all and search autocomplete
  modules/social_features/social_book/social_book.install
  modules/social_features/social_book/src/SocialBookConfigOverride.php
Labels: SaaS, prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1958 Issue #3166533: SKY theme on public content with social sharing enabled the share buttons dont get rendered for AN
  themes/socialbase/src/Plugin/Preprocess/Node.php
Labels: SaaS, prio: medium, status: needs backport, status: needs review, team: shipsters, type: bug

#1980 Issue #3170776 by sjoerdvandervis: Do not set template variable to TRUE when Gin admin menu is handled
  themes/socialbase/src/Plugin/Preprocess/Container.php
Labels: status: needs review, team: bananas

#1966 Issue #3168287 by robertragas: replace addmember query with mention v…
  modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
Labels: status: needs review, team: bananas

#1964 TB-4603 - "All my upcoming events" is not translatable correctly
  modules/social_features/social_core/social_core.module
Labels: team: bananas

#1953 Issue #3165299 by navneet0693: Upgrade the url_embed module version.
  composer.json
Labels: prio: high, status: needs backport, team: bananas, type: bug, type: update

#1701 Issue #3110341 by royharink: Embedded Vimeo videos are sometimes blocked when hosted on cloud hosting
  composer.json
Labels: prio:low, status: needs backport, team: bananas

#1971 Issue #3169069 by navneet0693: Add options to open links in new tab.
  composer.json
  modules/social_features/social_editor/config/install/filter.format.basic_html.yml
  modules/social_features/social_editor/config/install/filter.format.mail_html.yml
  modules/social_features/social_editor/config/update/social_editor_update_8902.yml
  modules/social_features/social_editor/social_editor.info.yml
  modules/social_features/social_editor/social_editor.install
  modules/social_features/social_editor/social_editor.module
Labels: prio: medium, status: needs backport, team: bananas, type: feature request

#1891 Issue #3155587 by robertragas: alter the config override for paths to…
  modules/social_features/social_core/social_core.api.php
  modules/social_features/social_core/social_core.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.services.yml
  modules/social_features/social_event/src/EventEnrollmentConfigOverride.php
Labels: status: needs backport, status: needs review, team: bananas

#1733 As a LU I can see the language of another user in his profile
  modules/social_features/social_profile/config/install/social_profile.settings.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/social_profile.permissions.yml
  modules/social_features/social_profile/src/Form/SocialProfileSettingsForm.php
  themes/socialbase/templates/profile/profile--profile--default.html.twig
Labels: prio: medium, status: needs backport, status: needs review, team: bananas, type: code refactoring, type: feature request

#1978 Issue #3162557: Increase number of activities per one batch operation
  modules/custom/activity_creator/activity_creator.install
Labels: prio: critical, status: needs work, team: eci, type: bug

#1975 YANG-3671: Fix text copy and styles for event date & time fields
  modules/social_features/social_event/assets/css/social-event--admin.css
  modules/social_features/social_event/assets/css/social-event--admin.scss
  modules/social_features/social_event/social_event.module
Labels: prio: critical, team: eci, type: bug

#1946 Issue #3164733 by SV: Allow modules to override default filter format of elements
  modules/social_features/social_core/social_core.api.php
  modules/social_features/social_core/social_core.module
Labels: prio: medium, team: eci, type: bug, type: code refactoring, type: feature request

#1948 Issue #3164825 by tBKoT: Add lazy builder for commeents field
  modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  modules/social_features/social_comment/social_comment.services.yml
  modules/social_features/social_comment/src/Plugin/Field/FieldFormatter/SocialLazyCommentDefaultFormatter.php
  modules/social_features/social_comment/src/SocialCommentLazyRenderer.php
  modules/social_features/social_core/src/Plugin/Field/FieldFormatter/CommentNodeFormatter.php
Labels: prio: high, team: eci, type: performance

#1954 Issue #3165476 by tBKoT: Add lazy_builder for custom content block
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_activity/social_activity.services.yml
  modules/social_features/social_activity/src/SocialActivityLazyBuilder.php
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: prio: high, status: needs review, team: eci, type: performance

#1990 Don't invoke a separate shell to run unit-tests
  .travis.yml
Labels: prio: critical, status: needs backport, status: needs review, team: shipsters

#1854 Issue 3139151 by tBKoT: Fix AcitivityFactory service usage
  modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/EventRequestActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OrganizerActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/PlatformActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/ProfileActivityContext.php
  modules/custom/activity_creator/activity_creator.api.php
  modules/custom/activity_creator/activity_creator.services.yml
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/custom/activity_creator/src/Plugin/ActivityContextBase.php
  modules/social_features/social_event/modules/social_event_invite/src/Plugin/ActivityContext/EventInviteActivityContext.php
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/ActivityContext/InvitedToGroupActivityContext.php
  modules/social_features/social_group/modules/social_group_request/src/Plugin/ActivityContext/ApprovedRequestJoinGroupActivityContext.php
  modules/social_features/social_private_message/src/Plugin/ActivityContext/PrivateMessageActivityContext.php
Labels: blocked: release notes, team: eci, type: code refactoring

#1977 Issue #3169982 by chmez: Make the redirect subscriber service of the flexible group module more expandable
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.services.yml
  modules/social_features/social_group/modules/social_group_flexible_group/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/social_group.module
Labels: prio: high, team: eci, type: code refactoring

#1985 Issue #3162222 by tBKoT: Change timezone label from the city name to the timezone's abbreviation
  modules/social_features/social_event/social_event.module
Labels: prio: medium, team: eci, type: feature request

#1984 Issue #3171507 by tBKoT: Rename file and hook update
  modules/social_features/social_editor/config/update/social_editor_update_8903.yml
  modules/social_features/social_editor/social_editor.install
Labels: prio: critical, team: eci, type: bug

#1996 Issue #3172705 by agami4: Remove bootstrap attributes from second level menu if this level has children elements
  themes/socialbase/assets/js/navbar-main-menu.min.js
  themes/socialbase/components/03-molecules/navigation/navbar/navbar-main-menu.js
  themes/socialbase/socialbase.libraries.yml
Labels: status: needs review, team: eci, type: bug

#1987 Issue #3171841 by chmez: As a CM+ I want to have the possibility to create a button in the "Hero" section to the sign-up page
  modules/social_features/social_landing_page/social_landing_page.install
Labels: prio: medium, status: needs backport, team: eci, type: bug

#1983 Issue #3170824 by agami4: Update margin-bottom for the "card" class for both themes
  themes/socialbase/assets/css/cards.css
  themes/socialbase/components/02-atoms/cards/cards.scss
  themes/socialblue/assets/css/stream--sky.css
  themes/socialblue/components/04-organisms/stream/stream--sky.scss
Labels: prio: medium, team: eci, type: bug

#1979 Issue #3170484 by chmez: Undefined index errors on the manage enrollments tab of the event
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
Labels: prio:low, team: eci, type: bug

#1988 Issue #3171563 by navneet0693: Moved logic from activity_creator_update_8802 to hook_post_update_name and refactored.
  modules/custom/activity_creator/activity_creator.install
  modules/custom/activity_creator/activity_creator.post_update.php
Labels: prio: high, status: needs backport, team: bananas, type: bug, type: code refactoring, type: performance
