Repository goalgorilla/open_social, pull requests merged in 2020-11, with the labels that each got.

#2044 Issue #3177932 by Kingdutch, ronaldtebrake: Allow modules to add cust…
  modules/custom/improved_theme_settings/improved_theme_settings.api.php
  modules/custom/improved_theme_settings/improved_theme_settings.module
  themes/socialblue/assets/css/tokens.css
  themes/socialblue/color/color.inc
  themes/socialblue/components/tokens.scss
Labels: prio: medium, prio:low, status: needs backport, team: shipsters, type: feature request

#1950 Issue #3162344, #3165009 by robertragas, navneet0693: Taxonomy terms should appear in site's current language.
  composer.json
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/SocialTaggingService.php
Labels: prio: high, status: needs backport, team: bananas, type: bug, type: code refactoring

#2043 Issue #3177673 by chmez: As a AN I want to have a media tab in a Group so I can view all media items in one place
  modules/social_features/social_album/config/install/core.entity_form_display.node.album.default.yml
  modules/social_features/social_album/config/install/core.entity_view_display.node.album.default.yml
  modules/social_features/social_album/config/install/core.entity_view_display.node.album.teaser.yml
  modules/social_features/social_album/config/install/field.field.node.album.field_album_creators.yml
  modules/social_features/social_album/config/install/field.storage.node.field_album_creators.yml
  modules/social_features/social_album/config/install/group.content_type.closed_group-group_node-album.yml
  modules/social_features/social_album/config/install/group.content_type.open_group-group_node-album.yml
  modules/social_features/social_album/config/install/group.content_type.public_group-group_node-album.yml
  modules/social_features/social_album/config/install/views.view.albums.yml
  modules/social_features/social_album/config/optional/block.block.socialblue_albums_count_and_add.yml
  modules/social_features/social_album/config/optional/block.block.socialblue_group_album_creation_page_title.yml
  modules/social_features/social_album/config/optional/group.content_type.flexible_group-group_node-album.yml
  modules/social_features/social_album/config/optional/group.content_type.secret_group-group_node-album.yml
  modules/social_features/social_album/social_album.info.yml
  modules/social_features/social_album/social_album.install
  modules/social_features/social_album/social_album.links.task.yml
  modules/social_features/social_album/social_album.module
  modules/social_features/social_album/social_album.routing.yml
  modules/social_features/social_album/src/Controller/SocialAlbumController.php
  modules/social_features/social_album/src/Plugin/Block/SocialAlbumCountAndAddBlock.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumGroupAccess.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumUserAccess.php
  modules/social_features/social_album/src/Plugin/views/field/SocialAlbumEntityOperations.php
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.scss
  modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--popup-slider.js
  modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--post-loading.js
  themes/socialbase/src/Plugin/Preprocess/PageTitle.php
  themes/socialblue/src/Plugin/Preprocess/Page.php
Labels: prio: medium, team: eci, type: feature request

#1889 Feature/3113181 drupal composer update
  composer.json
Labels: prio: high, status: needs review, team: shipsters, type: dependencies

#2058 Travis self-updates to v2 of composer while we don't support it (yet).
  .travis.yml
Labels: prio: high, team: nucleus

#2054 Issue #3178204 by Kingdutch: Allow account header menu items to be bu…
  modules/social_features/social_user/src/Element/AccountHeaderElement.php
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/navbar--sky.css
  themes/socialblue/assets/css/navbar.css
  themes/socialblue/components/03-molecules/navigation/navbar/navbar--sky.scss
  themes/socialblue/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialblue/components/brand.scss
Labels: prio: medium, status: needs backport, status: needs review, team: shipsters, type: feature request

#2085 Issue #3183500: Update drupal core to 8.9^
  .travis.yml
  composer.json
  tests/behat/features/capabilities/topic/topic-overview-filter.feature
Labels: prio: high, status: needs backport, status: needs review, team: nucleus, type: update
