Repository goalgorilla/open_social, pull requests merged in 2020-06, with the labels that each got.

#1864 Issue #3143546 by agami4: Fix filter button on mobile in sky style
  themes/socialblue/assets/css/layout--sky.css
  themes/socialblue/assets/css/offcanvas--sky.css
  themes/socialblue/components/04-organisms/offcanvas/offcanvas--sky.scss
  themes/socialblue/components/05-templates/layout/layout--sky.scss
Labels: team: eci, type: bug

#1868 Issue #3144445 by rolki: Add extra conditions to the AccountHeaderBlock plugin
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
Labels: prio: medium, team: eci, type: bug

#1860 #3120797: Make sure Max Enroll plays nicely with the Request to Event feature
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.module
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/modules/social_event_max_enroll/src/Service/EventMaxEnrollService.php
Labels: status: needs review

#1867 Issue #3144424 by ribel: Re-arrange the order of the group statistics block
  modules/social_features/social_group/social_group.module
  themes/socialblue/templates/group/group--statistic.html.twig
Labels: prio: medium, team: eci, type: code refactoring, type: feature request

#1871 Issue #3136540 by navneet0693: Added a defensive of user authentication in user mail queue processor.
  modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
Labels: blocked: maintainer input, prio: critical, status: needs backport, status: needs review, team: bananas, type: bug

#1712 Issue #3089112 by royharink: Registration field specific validation error messages
  modules/social_features/social_user/social_user.module
  translations.php
Labels: prio: medium, prio:low, status: needs backport, team: bananas, translations, type: bug

#1870 Issue #3145315 Add filter to the explore events page for enrollment method
  modules/social_features/social_event/config/install/views.view.upcoming_events.yml
  modules/social_features/social_event/config/update/social_event_update_8810.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
Labels: prio: high, team: bananas, team: shipsters, type: feature request

#1872 fix multiple issues with event invite
  modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteEnrollActionForm.php
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  modules/social_features/social_event/src/Service/SocialEventEnrollService.php
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
Labels: prio: medium, team: bananas, type: bug

#1836 Issue #3136472 by Kingdutch, ronaldtebrake: Group comment join pop-over breaks with event organisers
  modules/custom/group_core_comments/assets/css/group_core_comments.css
  modules/custom/group_core_comments/assets/css/group_core_comments.css.map
  modules/custom/group_core_comments/assets/css/group_core_comments.scss
  modules/custom/group_core_comments/templates/comments-join-group.html.twig
Labels: prio: medium, status: needs backport, team: bananas, team: shipsters, type: bug

#1869 Issue #3143273 - Add filter with group join methods for flexible groups
  composer.json
  drupal-org.make
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
Labels: prio: high, team: bananas, team: shipsters, type: feature request

#1880 Issue #3152005 by chmez: The field label is visible when the label display type is visibility hidden
  themes/socialbase/templates/field/field.html.twig
Labels: prio: medium, team: eci, type: bug

#1848 Issue #2995501: Group filters show values that a user does not need access to
  modules/social_features/social_group/social_group.module
Labels: prio: medium, status: needs backport, team: bananas, team: shipsters, type: bug

#1875 Issue #3150640 by Kingdutch: Content tagging filters on search and ov…
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: prio: medium, status: needs backport, status: needs review, team: shipsters, type: bug

#1882 Updated Drupal Core to 8.8.8
  composer.json
  drupal-org-core.make
Labels: status: needs backport, status: needs review, team: shipsters, type: update

#1786 Issue #3123861 by Kingdutch: Image label is visible on basic page tea…
  config/optional/core.entity_view_display.node.book.teaser.yml
  modules/social_features/social_book/config/update/social_book_update_8802.yml
  modules/social_features/social_book/social_book.install
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.teaser.yml
  modules/social_features/social_page/config/update/social_page_update_8002.yml
  modules/social_features/social_page/social_page.install
Labels: prio: medium, status: needs backport, team: shipsters, type: bug

#1862 by robertragas: add defensive check for mentions in social tokens
  modules/social_features/social_mentions/social_mentions.tokens.inc
Labels: prio: critical, status: needs review, team: bananas, type: bug

#1877 Issue 3151179 by frankgraave - Fix flexible group with only public content visibility
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: high, team: bananas, type: bug

#1884 Issue 3154067 by frankgraave: use the display name instead of usernam…
  modules/social_features/social_event/modules/social_event_invite/config/install/social_event_invite.settings.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
Labels: status: needs review, team: bananas, type: bug

#1879 by robertragas: replace select2 from theme for contrib module by remo…
  composer.json
  drupal-org.make
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_core/social_core.post_update.php
  modules/social_features/social_tagging/social_tagging.module
  themes/socialbase/assets/css/select2.css
  themes/socialbase/assets/js/select2.init.min.js
  themes/socialbase/components/03-molecules/form-elements/multiselect/select2.init.js
  themes/socialbase/components/03-molecules/form-elements/multiselect/select2.scss
  themes/socialbase/socialbase.libraries.yml
  themes/socialblue/assets/css/select2.css
Labels: status: needs backport, status: needs review, team: bananas

#1886 Issue #3120797: Update user event overview after event request or invite is accepted
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/Entity/EventEnrollment.php
  modules/social_features/social_event/src/Plugin/views/filter/EventEnrolledOrCreated.php
Labels: team: shipsters, type: bug

#1883 Feature/3152934 invite preview
  modules/social_features/social_event/modules/social_event_invite/config/install/social_event_invite.settings.yml
  modules/social_features/social_event/modules/social_event_invite/config/schema/social_event_invite.schema.yml
  modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_8002.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc
  modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
  modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteSettingsForm.php
  modules/social_features/social_group/modules/social_group_invite/config/optional/social_group_invite.settings.yml
  modules/social_features/social_group/modules/social_group_invite/config/schema/social_group_invite.schema.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Menu/LocalTask/GroupInviteLocalTask.php
  themes/socialbase/assets/css/email-preview.css
  themes/socialbase/components/04-organisms/email/email-preview.scss
  themes/socialbase/socialbase.libraries.yml
  themes/socialbase/socialbase.theme
  themes/socialbase/templates/email/invite-email-preview.html.twig
  themes/socialbase/templates/email/swiftmailer.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio: medium, team: eci, type: feature request

#1890 #3155032: Group join method CTA buttons caching issue
  modules/custom/social_node_statistics/social_node_statistics.module
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/social_group.module
Labels: prio: high, status: needs review, type: bug

#1888 Featured view mode for flexible group and social_book
  modules/social_features/social_landing_page/social_landing_page.install
Labels: status: needs backport, status: needs review, team: bananas
