Repository goalgorilla/open_social, pull requests merged in 2020-10, with the labels that each got.

#1970 Issue #3169027 - Add to calendar button
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.info.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.installer_options.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.links.menu.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.routing.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.services.yml
  modules/social_features/social_event/modules/social_event_addtocal/src/Annotation/SocialAddToCalendar.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Form/SocialAddToCalendarSettingsForm.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToGoogle.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOutlook.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToYahoo.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarInterface.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarManager.php
  modules/social_features/social_event/social_event.install
  themes/socialbase/assets/css/meta.css
  themes/socialbase/components/04-organisms/meta/meta.scss
  themes/socialbase/templates/node/event/node--event--full.html.twig
  themes/socialbase/templates/node/node--full.html.twig
  themes/socialblue/assets/css/button.css
  themes/socialblue/assets/css/dropdown.css
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/components/02-atoms/button/button.scss
  themes/socialblue/components/03-molecules/dropdown/dropdown.scss
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
  themes/socialblue/templates/node/node--full--sky.html.twig
  themes/socialblue/templates/node/node--hero--sky.html.twig
Labels: prio: high, team: eci, type: feature request

#1991 Issue #2947668 by agami4: Check and add updates to focus links [Accessibility]
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/like.css
  themes/socialbase/components/01-base/links/_links.scss
  themes/socialbase/components/03-molecules/like/like.scss
Labels: prio: high, status: needs backport, team: eci, type: bug

#1992 Issue 3171630 by agami4: Update styles for the teaser__body
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
Labels: prio: high, status: needs backport, team: eci, type: bug

#2004 Issue #2947667 by ok_lyndsey, Kingdutch: Style skip to content so it …
  themes/socialbase/assets/css/base.css
  themes/socialbase/assets/css/ckeditor.css
  themes/socialbase/components/01-base/root/_root.scss
  themes/socialbase/templates/system/html--node--preview.html.twig
  themes/socialbase/templates/system/html.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/preview.css
  themes/socialblue/components/brand.scss
  themes/socialblue/os-builder/index.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1993 Issue #3171792 by agami4: Update styles for the show/hide search popup
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
Labels: prio: high, status: needs backport, team: eci, type: bug

#2001 Issue #3174311 by sjoerdvandervis: Invite local actions not showing up when view is overriden in custom module
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_group/social_group.module
Labels: status: needs review, team: bananas

#2006 Issue #3174646 - impoved colors gin theme based on social blue
  modules/social_features/social_core/social_core.install
  themes/socialblue/theme-settings.php
Labels: SaaS, prio: high, status: needs backport, status: needs review, team: shipsters, type: feature request

#2005 Issue #3174638 - Make sure links in a post get the correct configured theme color applied
  themes/socialbase/templates/post/post--activity.html.twig
  themes/socialbase/templates/post/post.html.twig
  themes/socialblue/color/preview.html
Labels: SaaS, prio:low, status: needs backport, status: needs review, team: shipsters, type: bug

#2002 Issue #3174369 by laykin: There is no check for module exists in the function _social_group_request_set_permissions (.install file for module social group request)
  modules/social_features/social_group/modules/social_group_request/social_group_request.install
Labels: team: eci, type: bug

#2000 Issue #3174062 by tBKoT: Can't leave a comment when the big_pipe module is enabled
  modules/social_features/social_mentions/js/social_mentions.js
Labels: prio: high, team: eci, type: bug

#2003 Issue #3164294: Make sure we render the group_type field on group edit as part of a fieldset
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Form/SocialGroupAddForm.php
Labels: SaaS, prio: critical, status: needs backport, team: shipsters

#2009 Issue #3174889 by tBKoT: Bug with only one selected calendar in settings
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.links.menu.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
  modules/social_features/social_event/modules/social_event_addtocal/src/Form/SocialAddToCalendarSettingsForm.php
Labels: prio: critical, status: needs review, team: eci, type: bug

#1942 Issue #3164579 by SV: Add Explore activity stream block on the dashboard page
  modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
  modules/social_features/social_activity/config/update/social_activity_update_8804.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_comment/social_comment.module
Labels: blocked: maintainer input, prio: medium, team: eci, type: bug, type: feature request

#2010 Issue #3171778 by agami4: Add url to the notification center button(icon ring bell)
  modules/social_features/social_activity/social_activity.module
Labels: prio: high, status: needs backport, team: eci, type: bug

#2011 Issue #3171498 by agami4: Add title to edit content svg icon on the all pages
  themes/socialbase/templates/group/group--hero.html.twig
  themes/socialbase/templates/node/node--hero.html.twig
  themes/socialbase/templates/profile/profile--profile--hero.html.twig
  themes/socialblue/templates/group/group--hero--sky.html.twig
  themes/socialblue/templates/node/node--hero--sky.html.twig
  themes/socialblue/templates/profile/profile--profile--hero--sky.html.twig
Labels: prio: high, status: needs backport, team: eci, type: bug

#2014 Issue #3171566 by agami4: Make back infobox icon not visible for the accessibility tree and add title to button
  themes/socialbase/templates/private_message/private-message-thread.html.twig
Labels: prio: high, status: needs backport, team: eci, type: bug

#1998 Issue #3173585 by navneet0693: Added condition to activity post visibility filter for restricting activities created for the private content.
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
Labels: blocked: maintainer input, prio: high, status: needs review, team: bananas, type: bug

#2012 Issue #3171502 by agami4: Make post remove image button not visible for the accessibility tree
  modules/social_features/social_post/modules/social_post_photo/js/post-widget.js
  themes/socialbase/assets/css/image-widget.css
  themes/socialbase/components/03-molecules/form-elements/image-widget/image-widget.scss
  themes/socialbase/templates/file/image-widget.html.twig
Labels: prio: high, status: needs backport, team: eci, type: bug

#2024 Issue #3171606 by agami4: Add "legend" HTML tag to the fieldset
  themes/socialbase/assets/css/form-elements.css
  themes/socialbase/components/03-molecules/form-elements/form-elements.scss
  themes/socialbase/templates/card/bootstrap-panel.html.twig
  themes/socialbase/templates/form/fieldset.html.twig
  themes/socialbase/templates/form/form--group.html.twig
Labels: prio: high, status: needs review, team: eci, type: bug

#2013 Issue #3171785 by agami4: Make help text search button not visible for the accessibility tree
  themes/socialbase/templates/block/block--system-menu-block--main.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: eci, type: bug

#2021 Issue #3171577 by Kingdutch: Landing pages contain empty links in fea…
  modules/social_features/social_featured_content/templates/group--featured.html.twig
  modules/social_features/social_featured_content/templates/node--featured.html.twig
  modules/social_features/social_featured_content/templates/profile--featured.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#2025 Issue #3171613 by dspachos: Views exposed filter block doesn't have a…
  themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
Labels: prio: high, status: needs backport, team: shipsters, type: bug

#2026 Issue #3171587 by dspachos, Kingdutch: Login error message uses a fak…
  modules/social_features/social_user/src/Form/SocialUserLoginForm.php
  translations.php
Labels: prio: high, team: external, team: shipsters, verified-cherry-picks

#2016 Issue #3171814 by agami4: Replace id with class and update js behavior
  modules/social_features/social_post/js/visibility-settings.js
  themes/socialbase/templates/file/image-widget.html.twig
  themes/socialbase/templates/form/dropdown.html.twig
Labels: prio: high, team: eci, type: bug

#2022 Issue #3175438 by agami4: Update max-height for the teaser title
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
Labels: prio: medium, status: needs backport, team: eci, type: bug

#2032 Issue #3171775 by Megha_kundar, Kingdutch: Alert messages in Open Soc…
  themes/socialbase/components/03-molecules/form-elements/inline-form-error.twig
  themes/socialbase/templates/form/datetime-wrapper.html.twig
  themes/socialbase/templates/form/fieldset.html.twig
  themes/socialbase/templates/form/form-element.html.twig
  themes/socialbase/templates/system/status-messages.html.twig
Labels: prio: high, team: shipsters, type: bug

#2029 Issue #3171617 by Kingdutch: SocialUserLoginForm should use autocompl…
  modules/social_features/social_user/src/Form/SocialUserLoginForm.php
Labels: prio: high, status: needs review, team: shipsters, type: bug

#2030 Issue #3171844 by Kingdutch: The required marker in forms (*) should …
  themes/socialbase/templates/form/form-element-label--switch.html.twig
  themes/socialbase/templates/form/form-element-label.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#2028 Issue #3171503 by Kingdutch: The SVG icon on the actions dropdown for…
  themes/socialbase/templates/system/links.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#2027 Issue #3175829 by Kingdutch: It's unclear that dropdown menu items ar…
  themes/socialbase/templates/navigation/menu.html.twig
Labels: prio: high, status: needs backport, status: needs review, type: bug

#2031 Issue #3171767 by Kingdutch: Post visibility radios are not keyboard …
  modules/social_features/social_post/js/visibility-settings.js
  tests/behat/features/bootstrap/FeatureContext.php
  themes/socialbase/assets/css/list.css
  themes/socialbase/components/02-atoms/list/list.scss
  themes/socialbase/templates/form/dropdown.html.twig
  themes/socialblue/assets/css/list.css
  themes/socialblue/components/02-atoms/list/list.scss
Labels: prio: high, team: shipsters, type: bug

#2019 Issue #3171763 by agami4: Change icon and focus behavior for edit button
  themes/socialbase/assets/css/button.css
  themes/socialbase/components/02-atoms/button/button.scss
Labels: status: needs review, team: eci, type: bug

#2034 Issue #2946442 by basvanos, Kingdutch, xinyuma, ok_lyndsey, agami4: I…
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.module
Labels: prio: high, status: needs backport, team: shipsters

#2037 Issue #3176585 by tBKoT: Out of memory on search indexing
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_search/social_search.install
Labels: prio: high, team: eci, type: bug

#2038 Issue #3176619 by robertragas: Enable redirect module to prevent inde…
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_core/social_core.install
Labels: status: needs backport, status: needs review, team: gravitiers

#2023 Issue #3171512 by agami4: Add title to SVG elements for all type of the teasers
  modules/social_features/social_featured_content/templates/group--featured.html.twig
  modules/social_features/social_featured_content/templates/node--event--featured.html.twig
  modules/social_features/social_featured_content/templates/node--featured.html.twig
  themes/socialbase/assets/js/navbar-collapse.min.js
  themes/socialbase/components/03-molecules/navigation/navbar/navbar-collapse.js
  themes/socialbase/templates/group/group--teaser.html.twig
  themes/socialbase/templates/node/event/node--event--teaser.html.twig
  themes/socialbase/templates/node/node--teaser.html.twig
  themes/socialbase/templates/node/node--teaser__field.html.twig
  themes/socialbase/templates/profile/profile--profile--teaser.html.twig
  themes/socialblue/templates/node/event/node--event--featured--sky.html.twig
  themes/socialblue/templates/node/event/node--event--teaser--sky.html.twig
  themes/socialblue/templates/node/node--featured--sky.html.twig
  themes/socialblue/templates/node/node--teaser--sky.html.twig
Labels: prio: high, team: eci, type: bug

#2045 Issue #3171502 by Kingdutch, robertragas: Change the js of uploading …
  modules/social_features/social_post/modules/social_post_photo/js/post-widget.js
Labels: status: needs backport, team: gravitiers

#2033 Issue #3108608 - Stability of Ajax comments
  composer.json
  modules/custom/social_ajax_comments/social_ajax_comments.info.yml
  modules/custom/social_ajax_comments/social_ajax_comments.module
  modules/custom/social_ajax_comments/social_ajax_comments.routing.yml
  modules/custom/social_ajax_comments/social_ajax_comments.services.yml
  modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
  modules/custom/social_ajax_comments/src/Routing/RouteSubscriber.php
  modules/social_features/social_comment/src/SocialCommentLazyRenderer.php
  modules/social_features/social_mentions/js/social_mentions.js
  themes/socialbase/includes/form.inc
  themes/socialbase/socialbase.theme
  themes/socialbase/src/Plugin/Preprocess/Field.php
  themes/socialbase/src/Plugin/Preprocess/Node.php
  themes/socialbase/templates/comment/field--comment.html.twig
  themes/socialbase/templates/comment/form--comment.html.twig
Labels: prio: high, status: needs review, team: shipsters, type: bug, type: update
