Repository goalgorilla/open_social, pull requests merged in 2020-12, with the labels that each got.

#2091 Reporting (ajax) comments leads to white screen
  modules/social_features/social_content_report/social_content_report.module
  modules/social_features/social_content_report/social_content_report.services.yml
  modules/social_features/social_content_report/src/ContentReportService.php
Labels: status: needs backport, team: gravitiers

#2090 Issue #3186003 - Part 1: Enabler - Create re-usable details element, which is collapsible.
  themes/socialbase/src/Plugin/Alter/ThemeSuggestions.php
  themes/socialbase/templates/system/details--collapsible.html.twig
Labels: prio: high, team: nucleus, type: feature request

#2088 Issue #3185615 by agami4: Fix alignment of footer menu if site logo block is added
  themes/socialblue/assets/css/site-footer.css
  themes/socialblue/components/04-organisms/site-footer/site-footer.scss
Labels: team: eci, type: bug

#2077 Issue #3178408 - As a LU, I want to configure groups more easily - Add group visibility field
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css.map
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.scss
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.hero.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.small_teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.stream.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_flexible_group_visibility.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.group.field_flexible_group_visibility.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8901.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8902.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8903.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.api.php
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.libraries.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
  modules/social_features/social_group/social_group.module
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/group/group-create-flexible.feature
  tests/behat/features/capabilities/group/group-edit-join-method-flexible.feature
  themes/socialbase/assets/js/popover_svg.min.js
  themes/socialbase/socialbase.libraries.yml
  themes/socialbase/socialbase.theme
  themes/socialbase/src/Plugin/Preprocess/FormElementLabel.php
  themes/socialbase/templates/form/fieldset.html.twig
  themes/socialbase/templates/form/form-element-label.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio: high, team: nucleus, type: feature request

#2101 Developer task - Use github actions for coding standards check on a PR.
  .github/workflows/drupalCodingStandards.yml
  .travis.yml
  composer.json
  modules/custom/activity_creator/activity_creator.post_update.php
  modules/custom/dropdown/src/Plugin/Field/FieldType/Dropdown.php
  modules/social_features/social_event/src/Plugin/views/sort/EventPassedDesc.php
  modules/social_features/social_like/social_like.module
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_search/social_search.module
  phpcs.xml
  themes/socialbase/src/Plugin/Preprocess/SocialBaseImageWidget.php
Labels: prio: critical, status: needs review, team: nucleus, type: update

#2068 Issue #3182132 by agami4: Update dropdown-menu block on the mobile mode
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/components/03-molecules/dropdown/dropdown.scss
Labels: team: eci, type: bug

#2020 Issue #3175203 by tBKoT: Create an alter hook to modify the list of content type where need to hide the default title block
  modules/social_features/social_core/social_core.api.php
  themes/socialbase/src/Plugin/Preprocess/Page.php
Labels: prio: high, team: eci, type: bug, type: code refactoring

#2040 Issue #3176854 by tBKoT: Add iCal option to the 'Add to calendar' feature
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.routing.yml
  modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
Labels: prio: medium, team: eci, type: feature request

#2042 Issue #3177350 by agami4: Fix display of button to send a private message on /user/inbox page
  themes/socialblue/assets/css/layout--sky.css
  themes/socialblue/components/05-templates/layout/layout--sky.scss
Labels: team: eci, type: bug

#2049 Issue #3180197 by agami4: Remove an extra linear-background from mini-pager
  themes/socialblue/assets/css/pagination.css
  themes/socialblue/components/03-molecules/navigation/pagination/pagination.scss
Labels: team: eci, team: external, type: bug

#2052 Issue #3180468 by tBKoT: Change redirection for Social Login from profile to the front page
  modules/custom/social_auth_facebook/src/Controller/FacebookAuthController.php
  modules/custom/social_auth_google/src/Controller/GoogleAuthController.php
  modules/custom/social_auth_linkedin/src/Controller/LinkedInAuthController.php
  modules/custom/social_auth_twitter/src/Controller/TwitterAuthController.php
Labels: prio: high, team: eci, type: feature request

#2081 Issue #3184207 by tBKoT: Update morris.js library from version 0.5 to 0.6
  composer.json
  themes/socialbase/socialbase.libraries.yml
Labels: prio: high, team: eci, type: feature request

#2061 Issue #3181608 by mdeny: Improve PostAccessControlHandler for update operation
  modules/social_features/social_post/src/PostAccessControlHandler.php
Labels: prio: medium, team: eci, type: bug, type: code refactoring

#2055 Issue #3181424 by agami4: UI issue with Accept invite button on event page
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
Labels: status: needs review, team: eci, type: bug

#2093 Issue #3186442 by agami4: Fix styles for the tag select on the filter form and fix position for the filter button on the mobile screen
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/components/02-atoms/form-controls/form-controls.scss
  themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
  themes/socialblue/assets/css/offcanvas--sky.css
  themes/socialblue/components/04-organisms/offcanvas/offcanvas--sky.scss
Labels: prio: medium, team: eci, type: bug

#1866 Issue #3144386 by agami4: Horizontal scroll always visible on the landing page
  modules/social_features/social_featured_content/css/featured.css
  modules/social_features/social_featured_content/css/featured.css.map
  modules/social_features/social_featured_content/css/featured.scss
  modules/social_features/social_featured_items/css/paragraph.featured_items.css
  modules/social_features/social_featured_items/css/paragraph.featured_items.css.map
  modules/social_features/social_featured_items/css/paragraph.featured_items.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.block.css
  modules/social_features/social_landing_page/css/social_landing_page.section.block.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.block.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.hero.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.hero.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.css
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.scss
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/page--node--landing-page.html.twig
  modules/social_features/social_landing_page/templates/paragraph--accordion--default.html.twig
  themes/socialbase/assets/css/layout.css
  themes/socialbase/components/05-templates/layout/layout.scss
Labels: prio: medium, team: eci, type: bug

#2066 by robertragas: for the search overlay add the white color to the pla…
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: status: needs backport, status: needs review, team: gravitiers

#2051 Issue #3180255 by agami4: Data usage explanation block is not responding to the main colors of the site
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio:low, team: eci, type: bug

#2106 Issue #3188242 by rolki: Add filter to display only ongoing events and fix issue with end event date
  modules/social_features/social_content_block/modules/social_event_content_block/config/install/field.storage.block_content.field_event_date.yml
  modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.install
  modules/social_features/social_content_block/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php
Labels: prio: medium, team: eci, type: bug, type: feature request

#2064 by robertragas: add pagination a white background instead of transpar…
  themes/socialbase/assets/css/pagination.css
  themes/socialbase/components/03-molecules/navigation/pagination/pagination.scss
Labels: status: needs backport, status: needs review, team: gravitiers

#2063 by robertragas: add a white color for the badge-accent to increase re…
  modules/social_features/social_core/social_core.install
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/dropdown.css
  themes/socialblue/color/color.inc
  themes/socialblue/color/preview.js
  themes/socialblue/components/00-config/variables/_colors.scss
  themes/socialblue/components/03-molecules/dropdown/dropdown.scss
  themes/socialblue/components/brand.scss
  themes/socialblue/config/install/socialblue.settings.yml
Labels: status: needs backport, status: needs review

#2062 by robertragas: override the metadata info block to remove the creati…
  themes/socialblue/templates/node/event/node--event--hero--sky.html.twig
Labels: status: needs backport, status: needs review, team: gravitiers

#2074 by robertragas: organize the group statistics in blocks so we can bet…
  themes/socialblue/templates/group/group--statistic.html.twig
Labels: status: needs backport, status: needs review, team: gravitiers

#2050 Issue #3180228 by tBKoT: Split permissions for private messages
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_private_message/config/install/views.view.inbox.yml
  modules/social_features/social_private_message/social_private_message.install
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_private_message/social_private_message.permissions.yml
  modules/social_features/social_private_message/src/Plugin/Block/PmAddBlock.php
  themes/socialbase/templates/private_message/private-message-thread.html.twig
Labels: prio: medium, team: eci, type: feature request

#2071 Issue #3182368 by tBKoT: Don't send any message if user don't have permission to view it
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_private_message/src/Plugin/ActivityContext/PrivateMessageActivityContext.php
  modules/social_features/social_private_message/src/Plugin/EntityReferenceSelection/UserSelection.php
  modules/social_features/social_private_message/src/Plugin/Field/FieldWidget/SocialPrivateMessageThreadMemberWidget.php
  modules/social_features/social_private_message/src/Service/PrivateMessageMailer.php
  modules/social_features/social_profile/social_profile.module
Labels: prio: medium, team: eci, type: feature request

#2089 TB-5244 by jochemvn: improve JS, so profile tag hover doesn't break
  modules/social_features/social_profile/modules/social_profile_organization_tag/js/social_profile_tag.js
Labels: status: needs backport, status: needs review, team: gravitiers

#2099 Issue #3188292 by rolki: Add featured view mode template for the landing page
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/node--landing-page--featured.html.twig
  themes/socialbase/assets/icons/icons.svg
  themes/socialbase/assets/images/icons/icon-dashboard.svg
  themes/socialbase/components/06-libraries/icons/source/icon-dashboard.svg
Labels: prio: medium, status: needs review, team: eci, type: bug

#2079 Issue #3183708 by SV: Groups do not show up in the discussions for administrator
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  translations.php
Labels: prio: medium, team: eci, type: bug

#1999 Issue #3183704 by agami4: The hyperlinks have not the correct styles on the body/description block.
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/page-node.css
  themes/socialblue/components/05-templates/page-node/page-node.scss
  themes/socialblue/components/brand.scss
Labels: team: eci, type: feature request

#2047 Issue #3179128 by Kingdutch: Teasers contain inaccessible image links
  modules/social_features/social_core/assets/js/accessibility.js
  modules/social_features/social_core/social_core.libraries.yml
  modules/social_features/social_core/social_core.module
  tests/behat/features/capabilities/embed/embed.feature
  themes/socialbase/templates/activity/activity.html.twig
  themes/socialbase/templates/group/group--small-teaser.html.twig
  themes/socialbase/templates/node/node--small-teaser.html.twig
  themes/socialbase/templates/node/node--teaser.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#2046 #3179190: With the Sky theme flavour the image label for books is now hidden by default
  modules/social_features/social_book/config/optional/core.entity_view_display.node.book.hero.yml
  modules/social_features/social_book/config/update/social_book_update_8804.yml
  modules/social_features/social_book/social_book.install
Labels: prio: medium, status: needs backport, status: needs review, type: bug

#2098 Event - Update enrollment method, show inline and add popover with explanation
  modules/social_features/social_event/config/install/field.field.node.event.field_enroll_method.yml
  modules/social_features/social_event/config/install/field.storage.node.field_enroll_method.yml
  modules/social_features/social_event/config/update/social_event_update_8909.yml
  modules/social_features/social_event/social_event.api.php
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2102 Issue #3186003 by navneet0693: DS-7431 - Updated fieldsets with new labels and re-arranged fields in CT Topic
  .github/workflows/drupalCodingStandards.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_topic/config/install/core.entity_form_display.node.topic.default.yml
  modules/social_features/social_topic/config/install/field.field.node.topic.field_files.yml
  modules/social_features/social_topic/config/update/social_topic_update_8904.yml
  modules/social_features/social_topic/config/update/social_topic_update_8905.yml
  modules/social_features/social_topic/social_topic.install
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  themes/socialblue/theme-settings.php
Labels: prio: medium, status: needs review, team: shipsters, type: feature request

#2115 Issue #3186003 by navneet0693: DS-7442 - Updated fieldsets and re-arranged fields in new order for "Basic Page" CT
  modules/social_features/social_core/social_core.module
  modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml
  modules/social_features/social_page/config/install/field.field.node.page.field_files.yml
  modules/social_features/social_page/config/update/social_page_update_8905.yml
  modules/social_features/social_page/social_page.install
  modules/social_features/social_tagging/social_tagging.module
Labels: status: needs review, team: nucleus, type: feature request

#2119 Issue #3186003 by navneet0693: DS-7435 - Updated fieldsets with new labels and re-arranged fields in CT Event
  modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
  modules/social_features/social_event/config/install/field.field.node.event.body.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_files.yml
  modules/social_features/social_event/config/update/social_event_update_8911.yml
  modules/social_features/social_event/config/update/social_event_update_8912.yml
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollOverride.php
  modules/social_features/social_event/modules/social_event_max_enroll/src/EventMaxEnrollOverride.php
  modules/social_features/social_event/social_event.install
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2121 Issue #3186003 by navneet0693: DS-7438 - Updated fieldsets with new labels and re-arranged fields in Flexible group.
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8904.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8905.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2125 Issue #3186003 by navneet0693: DS-7438 - Updated fieldsets with new labels and re-arranged fields in Flexible group.
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_image.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8904.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_welcome_message/src/SocialGroupWelcomeMessageConfigOverride.php
  modules/social_features/social_tagging/social_tagging.module
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2124 Issue #3186003 by navneet0693: DS-7435 - Update entity form of events content type as per new changes.
  modules/social_features/social_core/social_core.module
  modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
  modules/social_features/social_event/config/update/social_event_update_8911.yml
  modules/social_features/social_event/config/update/social_event_update_8912.yml
  modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollOverride.php
  modules/social_features/social_event/modules/social_event_managers/config/install/field.field.node.event.field_event_managers.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
  modules/social_features/social_event/modules/social_event_managers/src/SocialEventManagersConfigOverride.php
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/modules/social_event_max_enroll/src/EventMaxEnrollOverride.php
  modules/social_features/social_event/modules/social_event_type/config/install/field.field.node.event.field_event_type.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.install
  modules/social_features/social_event/social_event.install
  themes/socialbase/src/Plugin/Preprocess/Details.php
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2107 Issue #3189507 by agami4: Fix alignment for the hero banner on the sky theme
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
Labels: team: eci, type: bug

#2120 Issue #3189777 by agami4: Add horizontal scroll for the comment-content block
  themes/socialbase/assets/css/comment.css
  themes/socialbase/components/04-organisms/comment/comment.scss
Labels: team: eci, type: bug

#2094 Issue #3189783 by agami4: Add extra wrappers for the body on the post featured
  modules/social_features/social_post/templates/post--featured.html.twig
Labels: team: eci, type: bug

#2132 Issue #3189693 by tBKoT: Fix pagination text on invitation views
  modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_invitations.yml
  modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_user_invitations.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
Labels: prio: medium, team: eci, type: bug

#2110 Issue #3188332 by tBKoT: As a SM I should be able to edit the invite message for a group
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
Labels: prio: high, team: eci, type: feature request

#2087 Issue #3185627 by tBKoT: Add the settings form for email notification frequency
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/social_features/social_swiftmail/social_swiftmail.links.menu.yml
  modules/social_features/social_swiftmail/social_swiftmail.routing.yml
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
Labels: prio: high, team: eci, type: feature request

#2092 Issue #3185840 by rolki: All topic in the all-topics view have the same number of comment
  themes/socialbase/socialbase.theme
  themes/socialbase/src/Plugin/Preprocess/Field.php
  themes/socialbase/src/Plugin/Preprocess/Node.php
Labels: prio: high, team: eci, type: bug, type: code refactoring

#2069 Issue #3117677 by mdeny: Completion Social Follow Taxonomy module
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/block_content.type.follow_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_form_display.block_content.follow_tags.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_form_display.paragraph.tag.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_view_display.block_content.follow_tags.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_view_display.paragraph.tag.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.field.block_content.follow_tags.field_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.field.paragraph.tag.field_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.storage.block_content.field_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.storage.paragraph.field_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/paragraphs.paragraphs_type.tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/templates/block--inline-block--follow-tags.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagOverrides.php
Labels: prio: medium, team: eci, type: code refactoring

#2053 Issue #3180663 by tBKoT: Improve caching for Invite group members block
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialInviteLocalActionsBlock.php
Labels: prio: high, team: eci, type: bug

#2122 Issue #3187257 by sjoerdvandervis: add stylesheet of files when files are attached
  modules/social_features/social_event/social_event.install
  themes/socialbase/templates/node/field--node--field-files.html.twig
Labels: status: needs review, team: nucleus

#2134 Issue #3189847 by tBKoT: Generate consistent aliases for all group tabs
  modules/custom/social_devel/social_devel.module
  modules/custom/social_path_manager/social_path_manager.module
  modules/social_features/social_group/social_group.module
Labels: prio: high, team: eci, type: bug

#2133 Issue #3189814 by agami4: Add indication for comments section that comments are loading
  themes/socialbase/assets/css/comment.css
  themes/socialbase/components/04-organisms/comment/comment.scss
  themes/socialbase/templates/comment/field--comment.html.twig
Labels: prio: medium, team: eci, type: feature request

#2126 Issue #3189520 by chmez: As a user I want to see logo in the footer
  modules/social_features/social_footer/assets/css/social_footer.css
  modules/social_features/social_footer/assets/css/social_footer.css.map
  modules/social_features/social_footer/assets/css/social_footer.scss
  modules/social_features/social_footer/config/optional/block.block.footer_powered.yml
  modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
  modules/social_features/social_footer/config/schema/social_footer.schema.yml
  modules/social_features/social_footer/social_footer.info.yml
  modules/social_features/social_footer/social_footer.installer_options.yml
  modules/social_features/social_footer/social_footer.libraries.yml
  modules/social_features/social_footer/social_footer.module
  modules/social_features/social_footer/src/Plugin/Block/SocialFooterPoweredByBlock.php
  social.info.yml
Labels: prio: medium, team: eci, type: feature request

#2136 Issue #3190090 by agami4: Update download link color for the social_certificate module
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio:low, team: eci, type: feature request

#2111 Issue #3188391 by mdeny: Change Text on Group Join Confirmation Page
  modules/social_features/social_group/social_group.module
  translations.php
Labels: prio: medium, status: needs review, team: eci, type: feature request

#2137 Issue #3189003 by mdeny: Expand Social Tagging feature on user profiles
  modules/social_features/social_profile/modules/social_profile_organization_tag/src/SocialProfileOrgTagConfigOverride.php
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  themes/socialbase/templates/profile/profile--profile--default.html.twig
  themes/socialblue/templates/profile/profile--profile--default--sky.html.twig
Labels: prio: medium, team: eci, type: feature request

#2067 Issue #3181951 by chmez: As a CM+ I want to have exclusive right to create groups
  modules/social_features/social_group/config/install/social_group.settings.yml
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.permissions.yml
  modules/social_features/social_group/src/Entity/Access/SocialGroupAccessControlHandler.php
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
Labels: prio: medium, team: eci, type: code refactoring, type: feature request

#2080 Issue #3171622 - Fix logic errors due to invalid tokens in cache contexts
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: prio: medium, status: needs backport, team: external, team: nucleus, type: bug

#2135 Issue #3186003 by navneet0693: DS-7420 - Update the behat tests according to new form design changes.
  modules/social_features/social_core/social_core.module
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
  tests/behat/features/capabilities/activity-stream/create_topic_event.feature
  tests/behat/features/capabilities/book/book-create.feature
  tests/behat/features/capabilities/contentmanagement/node-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/embed/embed.feature
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
  tests/behat/features/capabilities/event-management/event-management.feature
  tests/behat/features/capabilities/event/all-day-timezone.feature
  tests/behat/features/capabilities/event/event-create.feature
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
  tests/behat/features/capabilities/event/eventenrollment.feature
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
  tests/behat/features/capabilities/landing-page/landing-page-create.feature
  tests/behat/features/capabilities/like/like-create-event.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
  tests/behat/features/capabilities/page/page-create.feature
  tests/behat/features/capabilities/profile/click-avatar.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
  tests/behat/features/capabilities/sharing/share.feature
  tests/behat/features/capabilities/topic/topic-create.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
  tests/behat/features/capabilities/topic/topic-follow-content.feature
  tests/behat/features/capabilities/topic/topic-preview.feature
Labels: prio: medium, status: needs review, team: nucleus, type: performance

#2118 Issue #3189030: Dependencies added in config override may not contain dots
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
Labels: blocked: release notes, prio: medium, status: needs backport, status: needs review, team: shipsters, type: bug

#2017 Issue 3175191 by makkus183: Added EntityInterface to inherited isVali…
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/ActivityContext/InvitedToGroupActivityContext.php
  modules/social_features/social_group/modules/social_group_request/src/Plugin/ActivityContext/ApprovedRequestJoinGroupActivityContext.php
Labels: prio: high, status: needs backport, team: external, team: nucleus, type: bug
