Repository goalgorilla/open_social, pull requests merged in 2020-05, with the labels that each got.

#1817 Issue #3131506 by robertragas: add the post profile view to the check…
  modules/social_features/social_post/src/Form/PostForm.php
Labels: status: needs backport, status: needs review, team: bananas

#1819 Issue #3132452 by agami4: Change title color in the accordion block
  modules/social_features/social_landing_page/css/social_landing_page.section.accordion.css
  modules/social_features/social_landing_page/css/social_landing_page.section.accordion.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.accordion.scss
  modules/social_features/social_landing_page/templates/paragraph--accordion-item--default.html.twig
Labels: prio:low, team: eci, type: bug, type: feature request

#1826 Issue #3133763 by rolki: Add an extra condition before invalidating cache tags
  modules/social_features/social_group/social_group.module
Labels: prio: medium, team: eci, type: bug

#1822 Issue #3132783 by chmez: Fix issue with showing few fields with the same name on the Custom content list block
  modules/social_features/social_content_block/social_content_block.module
Labels: prio: medium, team: eci, type: bug

#1821 Issue #3134118 by agami4: Update styles for the newest members block and profile small teasers
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.small_teaser.yml
  modules/social_features/social_profile/config/update/social_profile_update_8010.yml
  modules/social_features/social_profile/social_profile.install
  themes/socialbase/assets/css/list.css
  themes/socialbase/components/02-atoms/list/list.scss
  themes/socialbase/templates/profile/profile--profile--small_teaser.html.twig
Labels: prio: medium, team: eci, type: feature request

#1825 Issue #3134069 by agami4: Add styles to the 'teaser__label' and 'hero-header' block
  themes/socialblue/assets/css/badge.css
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/assets/css/teaser.css
  themes/socialblue/components/03-molecules/teaser/teaser.scss
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
Labels: prio: medium, team: eci, type: feature request

#1829 Issue TB-4384 by frankgraave: put original route and behaviour back f…
  modules/social_features/social_event/modules/social_event_invite/src/Plugin/Block/SocialEventInviteLocalActionsBlock.php
Labels: status: needs review, team: bananas, type: bug

#1828 Issue #3134100 by navneet0693: Add Group block on user profile's group doesn't takes "create group" permissions in context
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
  modules/social_features/social_group/src/SocialGroupHelperService.php
Labels: status: needs backport, team: bananas

#1830 Issue TB-4358 by frankgraave: refactor the event enrollment options a…
  modules/social_features/social_event/config/update/social_event_update_8806.yml
  modules/social_features/social_event/config/update/social_event_update_8808.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/EventEnrollmentInterface.php
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  tests/behat/features/capabilities/event-an-enroll/event-max-enroll.feature
Labels: team: bananas, type: code refactoring, type: feature request

#1824 Feature/tb 3755 update linkedin api
  composer.json
  modules/custom/social_auth_linkedin/composer.json
  modules/custom/social_auth_linkedin/social_auth_linkedin.install
  modules/custom/social_auth_linkedin/src/Controller/LinkedInAuthController.php
  modules/custom/social_auth_linkedin/src/LinkedInAuthManager.php
  modules/custom/social_auth_linkedin/src/Plugin/Network/LinkedInAuth.php
  social.profile
Labels: status: needs backport, status: needs review, team: bananas

#1838 Issue #3136540 by navneet0693: Added configuration override for sending notification to group manager in flexible & secret groups.
  modules/social_features/social_core/social_core.install
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
  modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
Labels: prio: high, status: needs review, team: bananas, type: bug

#1849 Elaborate in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: prio:low, status: needs review, team: shipsters

#1834 Issue #3136154 by chmez: Text format switcher pop-up has a transparent background
  themes/socialbase/socialbase.info.yml
Labels: prio: high, team: eci, type: bug

#1837 Issue #3136493 by chmez: Absent post visibility label in the custom content list block
  modules/social_features/social_post/post.page.inc
  modules/social_features/social_post/social_post.api.php
  modules/social_features/social_post/social_post.module
Labels: prio: medium, team: eci, type: bug, type: code refactoring

#1840 Issue #3136973 by agami4: Decrease min-height of teaser title
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
Labels: prio: medium, team: eci, type: bug

#1844 Issue #3137787 by chmez: Modules for groups/events content block still exists in an old location
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_content_tag.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_group.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.storage.block_content.field_event_content_tag.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.storage.block_content.field_event_group.yml
  modules/social_features/social_event/modules/social_event_content_block/config/optional/field.field.block_content.custom_content_list.field_event_type.yml
  modules/social_features/social_event/modules/social_event_content_block/config/optional/field.storage.block_content.field_event_type.yml
  modules/social_features/social_event/modules/social_event_content_block/social_event_content_block.info.yml
  modules/social_features/social_event/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.field.block_content.custom_content_list.field_group_content_tag.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.field.block_content.custom_content_list.field_group_type.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.storage.block_content.field_group_content_tag.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.storage.block_content.field_group_type.yml
  modules/social_features/social_group/modules/social_group_content_block/social_group_content_block.info.yml
  modules/social_features/social_group/modules/social_group_content_block/src/Plugin/ContentBlock/GroupContentBlock.php
Labels: prio: high, team: eci, type: bug, type: code refactoring

#1839 Issue #3138858 by Agami4: Revert color changes for the footer in sky style
  themes/socialblue/assets/css/brand--sky.css
  themes/socialblue/assets/css/site-footer--sky.css
  themes/socialblue/components/04-organisms/site-footer/site-footer--sky.scss
  themes/socialblue/components/brand--sky.scss
Labels: prio: medium, team: eci, type: bug

#1845 Issue #3137793 by rolki: Add extra conditions to theme block preprocess
  themes/socialbase/src/Plugin/Preprocess/Block.php
Labels: prio: high, team: eci, type: bug

#1820 Issue #3132494 by chmez: Add ability to disable posts on streams with permissions
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.install
  modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoBlock.php
  modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoGroupBlock.php
  modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoProfileBlock.php
  modules/social_features/social_post/social_post.install
  modules/social_features/social_post/social_post.permissions.yml
  modules/social_features/social_post/social_post.services.yml
  modules/social_features/social_post/src/Plugin/Block/PostBlock.php
  modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
  modules/social_features/social_post/src/Plugin/Block/PostProfileBlock.php
  modules/social_features/social_post/src/PostAccessControlHandler.php
  modules/social_features/social_post/src/Service/PostPermissions.php
  modules/social_features/social_post/src/Service/PostPermissionsInterface.php
Labels: blocked: maintainer input, prio: high, team: eci, type: code refactoring, type: feature request

#1835 Issue #3136189 by rolki: Changing visibility of content items for group doesn't work correctly with social_role_visibility because of hard-coded visibility options
  modules/social_features/social_group/modules/social_group_flexible_group/src/FlexibleGroupContentVisibilityUpdate.php
  modules/social_features/social_post/src/Entity/Post.php
Labels: blocked: maintainer input, prio: high, team: eci, type: bug

#1811 Issue #3130311 by SV: Override default view mode for activity stream views block if it was added via layout builde
  modules/social_features/social_activity/config/install/core.entity_view_display.activity.activity.featured.yml
  modules/social_features/social_activity/config/install/core.entity_view_mode.activity.featured.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_activity/src/Plugin/views/display/ModeBlock.php
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_post/config/install/core.entity_view_display.post.post.featured.yml
  modules/social_features/social_post/config/install/core.entity_view_mode.post.featured.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.featured.yml
  modules/social_features/social_post/social_post.module
  modules/social_features/social_post/templates/post--featured.html.twig
Labels: prio: high, team: eci, type: bug, type: feature request

#1842 TB-4383: Added cache context of current node to social invite action block
  modules/social_features/social_event/modules/social_event_invite/config/optional/block.block.socialeventinviteblock.yml
  modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_8001.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.module
  modules/social_features/social_event/modules/social_event_invite/src/Plugin/Block/SocialEventInviteLocalActionsBlock.php
Labels: team: bananas, type: bug

#1851 #3119327: Make the confirmation join text more meaningful for users accepting an invite to a group
  modules/social_features/social_group/social_group.module
Labels: team: shipsters

#1852 TB-4416 - Add directly page access
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupJoinPermissionAccessCheck.php
Labels: prio: high, team: bananas, type: bug

#1859 Bugfix/tb 4481 request to join hero blocks
  modules/social_features/social_sharing/social_sharing.module
Labels: team: bananas

#1846 Issue #3137523 by agami4: Add styles for the second level main menu
  themes/socialbase/assets/css/dropdown.css
  themes/socialbase/assets/css/navbar.css
  themes/socialbase/components/00-config/_mixins.scss
  themes/socialbase/components/00-config/mixins/_dropdown-menu.scss
  themes/socialbase/components/03-molecules/dropdown/dropdown.scss
  themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
  themes/socialbase/templates/navigation/menu.html.twig
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio: medium, status: needs work, team: eci, type: feature request
