Repository goalgorilla/open_social, pull requests merged in 2020-04, with the labels that each got.

#1785 Issue #3123549 by ribel: Hide tabs from /user/x/profile page
  modules/social_features/social_core/config/optional/block.block.socialbase_local_tasks.yml
  modules/social_features/social_core/config/optional/block.block.socialblue_local_tasks.yml
  modules/social_features/social_core/config/update/social_core_update_8808.yml
  modules/social_features/social_core/social_core.install
Labels: prio: medium, status: needs backport, team: eci, type: bug

#1787 Issue #3124378 by rolki: Add an extra condition for commented entity
  modules/custom/group_core_comments/src/GroupCommentAccessControlHandler.php
Labels: prio: medium, status: needs review, type: bug

#1791 Issue #3125249 by ribel: Fix complementary region moving page content to the side
  modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
  modules/social_features/social_core/config/update/social_core_update_8809.yml
  modules/social_features/social_core/social_core.install
  themes/socialblue/templates/layout/page--sky.html.twig
Labels: blocked: maintainer input, prio: medium, team: eci, type: bug

#1615 Issue #3096602 by agami4: Update position of css style for menu on the mobile
  themes/socialbase/assets/css/admin-toolbar.css
  themes/socialbase/components/00-config/_variables.scss
  themes/socialbase/components/04-organisms/admin-toolbar/admin-toolbar.scss
  themes/socialbase/templates/block/block--system-branding-block.html.twig
  themes/socialbase/templates/block/block--system-menu-block--main.html.twig
Labels: prio: high, status: needs backport, status: needs review, team: eci, team: shipsters, type: bug

#1792 Issue #3125295 by Kingdutch: There is space beneath teaser images in …
  themes/socialbase/assets/css/stream.css
  themes/socialbase/components/04-organisms/stream/stream.scss
  themes/socialblue/assets/css/stream--sky.css
  themes/socialblue/components/04-organisms/stream/stream--sky.scss
Labels: prio:low, status: needs backport, status: needs review, team: shipsters, type: bug

#1796 Issue #3126265 by ribel: Fix behat test for group access roles when Contextual Links are enabled
  tests/behat/features/capabilities/group/group-access-roles.feature
Labels: blocked: maintainer input, status: needs review, team: eci, type: code refactoring

#1700 YANG-1860: Update styles for marker clusters
  themes/socialblue/assets/css/brand.css
  themes/socialblue/components/brand.scss
Labels: prio: medium, team: eci, type: feature request

#1794 Issue #3125325 by Agami4: Fix vertical distance between cards in Sky style
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/components/02-atoms/cards/cards--sky.scss
Labels: team: eci, type: bug

#1790 Issue #3125226 by agami4: Update info tab layout on the profile and group page
  themes/socialblue/templates/group/group--default--sky.html.twig
  themes/socialblue/templates/profile/profile--profile--default--sky.html.twig
Labels: team: eci, type: feature request

#1797 issue #3116229 by robertragas: also apply hide content fixes to sky t…
  themes/socialblue/templates/node/node--full--sky.html.twig
Labels: status: needs backport, team: bananas

#1803 Issue #3128174 - Ensure filter works for multilingual sites regardless of language detection
  composer.json
  drupal-org-core.make
  modules/social_features/social_search/social_search.module
Labels: SaaS, prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1795 Issue #3125680 by navneet0693: Removed title property of field_profile_image.
  modules/social_features/social_profile/config/install/field.field.profile.profile.field_profile_image.yml
  modules/social_features/social_profile/config/update/social_profile_update_8008.yml
  modules/social_features/social_profile/social_profile.install
Labels: prio: medium, status: needs review, team: bananas, type: bug, type: code refactoring

#1806 Issue #3128589 by SV: Comments created with a WYSIWYG editor can not be edited
  modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js
Labels: prio: medium, team: eci, type: bug

#1716 Issue #3111945 by frankgraave: SM should not be able to grant/revoke the administrator role
  composer.json
  drupal-org.make
  modules/social_features/social_user/social_user.info.yml
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Plugin/Action/SocialAddRoleUser.php
  modules/social_features/social_user/src/Plugin/Action/SocialRemoveRoleUser.php
  tests/behat/features/capabilities/administration/revoke-or-grant-roles-by-permission.feature
Labels: prio: high, status: needs review, team: bananas, team: shipsters

#1802 Issue #3127937 update field_group and paragraphs
  composer.json
  drupal-org.make
  modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
  themes/socialbase/src/Plugin/Alter/ThemeSuggestions.php
Labels: prio: high, status: needs backport, team: shipsters, type: update

#1812 Issue #3111945 by frankgraave: fix dependency of role delegation modu…
  modules/social_features/social_core/social_core.install
  modules/social_features/social_user/social_user.info.yml
Labels: prio: high, status: needs review, team: bananas, type: bug

#1810 Issue #3125732 Ensure cardinality for user recipients in activities is unlimited
  modules/custom/activity_creator/activity_creator.install
  modules/custom/activity_creator/config/install/field.storage.activity.field_activity_recipient_user.yml
  modules/custom/activity_creator/config/update/activity_creator_update_8801.yml
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1808 Issue #3128618 by frankgraave: refactor if statement to separate func…
  modules/social_features/social_profile/social_profile.module
Labels: prio: high, status: needs backport, status: needs review, team: bananas, type: bug

#1815 Issue #3089990 - When a group has no members, the Manage Members page errors
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
Labels: prio:low, status: needs backport, status: needs review, team: external

#1816 Issue #3035308 Fix fatal error when editing content with a custom content type
  modules/social_features/social_group/social_group.module
Labels: prio: medium, status: needs backport, status: needs review, team: external

#1807 Issue #3129496 by navneet0693: Update update_helper module to 1.3.
  composer.json
  drupal-org.make
Labels: prio: high, prio: medium, status: needs review, type: dependencies, type: update

#1805 Issue #3099608 by robertragas: Add patch to fix time() callback filling up logs for the votingapi module
  composer.json
  drupal-org.make
Labels: prio: high, team: bananas, team: eci, type: bug

#1776 Issue #3120072 Fix featured items config update, by usage of FieldStorage and FieldConfig
  modules/social_features/social_landing_page/social_landing_page.install
Labels: prio: high, status: needs backport, status: needs review, team: shipsters

#1753 Issue #3118987 by chmez: As a CM I want to customise Events and Groups for the custom content block according to my specific use case
  modules/social_features/social_content_block/config/install/core.entity_form_display.block_content.custom_content_list.default.yml
  modules/social_features/social_content_block/config/update/social_content_block_update_8005.yml
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_content_block/src/Plugin/Field/FieldWidget/ContentBlockPluginFieldWidget.php
  modules/social_features/social_content_block/src/Plugin/Field/FieldWidget/ContentBlockPluginIdWidget.php
  modules/social_features/social_content_block/src/SocialContentBlockOverride.php
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.small_teaser.yml
  modules/social_features/social_event/config/update/social_event_update_8804.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_content_tag.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_group.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.storage.block_content.field_event_content_tag.yml
  modules/social_features/social_event/modules/social_event_content_block/config/install/field.storage.block_content.field_event_group.yml
  modules/social_features/social_event/modules/social_event_content_block/config/optional/field.field.block_content.custom_content_list.field_event_type.yml
  modules/social_features/social_event/modules/social_event_content_block/config/optional/field.storage.block_content.field_event_type.yml
  modules/social_features/social_event/modules/social_event_content_block/social_event_content_block.info.yml
  modules/social_features/social_event/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php
  modules/social_features/social_event/social_event.install
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.field.block_content.custom_content_list.field_group_content_tag.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.field.block_content.custom_content_list.field_group_type.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.storage.block_content.field_group_content_tag.yml
  modules/social_features/social_group/modules/social_group_content_block/config/install/field.storage.block_content.field_group_type.yml
  modules/social_features/social_group/modules/social_group_content_block/social_group_content_block.info.yml
  modules/social_features/social_group/modules/social_group_content_block/src/Plugin/ContentBlock/GroupContentBlock.php
  themes/socialbase/templates/group/group--small-teaser.html.twig
Labels: blocked: commit cleanup, blocked: maintainer input, prio: high, prio: medium, team: eci, type: code refactoring, type: feature request

#1799 Issue #3127555 by Kingdutch, ronaldtebrake: Like buttons have gone mi…
  modules/social_features/social_like/social_like.module
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: bug

#1689 Issue #3109219 by robertragas: Update the user data of the recipient …
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
Labels: status: needs backport, team: bananas

#1758 Issue #3119338 by agami4: Add margin to the region content if sidebar is not display
  themes/socialbase/assets/css/base.css
  themes/socialbase/components/01-base/tables/_tables.scss
Labels: prio:low, team: eci, type: bug

#1813 Issue #3130548 by rolki: Remove OR conditions for node comments and likes to fix performance issues with "Last interacted sorting"
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: prio: medium, status: needs backport, team: eci, type: bug

#1755 Issue #3119193 by agami4: Add styles to the icon in the title on the custom content block
  themes/socialblue/assets/css/cards.css
  themes/socialblue/components/02-atoms/cards/cards.scss
Labels: prio: medium, team: eci, type: bug

#1814 Issue 3130599 by AlanHDev: Fix typos in translatable strings and comm…
  modules/custom/social_tour/src/Form/SocialTourSettings.php
  modules/social_features/social_comment_upload/src/Form/SocialCommentUploadSettingsForm.php
  modules/social_features/social_event/modules/social_event_type/src/Form/SocialEventTypeSettings.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  themes/socialbase/components/03-molecules/navigation/nav-book/nav-book.scss
  translations.php
  translations/ca_gpi.po
  translations/de.po
  translations/de_CH_gpi.po
  translations/en.pot
  translations/en_GB.po
  translations/es.po
  translations/es_MX_gpi.po
  translations/es_gpi.po
  translations/eu_gpi.po
  translations/fr.po
  translations/fr_CH_gpi.po
  translations/fr_GPI.po
  translations/gl_gpi.po
  translations/it.po
  translations/it_CH_gpi.po
  translations/nl.po
  translations/pt-br.po
  translations/ru.po
Labels: prio:low, status: needs backport, team: external, translations, type: bug

#1793 Issue #3125293 by SV: Create "Medium Teaser" view mode for profile.
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.medium_teaser.yml
  modules/social_features/social_profile/config/install/core.entity_view_mode.profile.medium_teaser.yml
  modules/social_features/social_profile/social_profile.install
Labels: prio: medium, status: needs backport, team: eci, type: feature request

#1667 #3102763 - Add new Views Filter for flexible group content
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/Plugin/views/filter/FlexibleGroupNodeAccess.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: high, status: needs backport, team: bananas, team: shipsters, type: bug

#1804 Issue #3127105 by agami4: Fix course "Create Section" button in sky style
  themes/socialblue/assets/css/cards--sky.css
  themes/socialblue/components/02-atoms/cards/cards--sky.scss
Labels: prio: medium, team: eci, type: bug

#1569 Issue #3083890 by agami4: Add styles to forum table
  themes/socialbase/assets/css/forum.css
  themes/socialbase/components/04-organisms/forum/forum.scss
  themes/socialbase/socialbase.libraries.yml
  themes/socialbase/templates/forum/forum-list.html.twig
  themes/socialbase/templates/forum/table--forum-topic-list.html.twig
Labels: prio:low, team: eci, type: feature request

#1809 Issue #3129931 by agami4: Add organization and function fields to profile featured teasers
  modules/social_features/social_landing_page/config/update/social_landing_page_update_8804.yml
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.css
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.scss
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_landing_page/templates/profile--featured.html.twig
Labels: prio: medium, team: eci, type: feature request

#1788 update search_api to 8.x-1.15
  composer.json
  drupal-org.make
Labels: prio: medium, status: needs backport, team: external, type: dependencies, type: update

#1779 Issue #3122686 by chmez: Move featured content to a separate module
  modules/social_features/social_featured_content/config/install/block_content.type.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_form_display.block_content.featured.default.yml
  modules/social_features/social_featured_content/config/install/core.entity_form_display.paragraph.featured.default.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.block_content.featured.default.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.group.closed_group.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.group.open_group.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.group.public_group.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.node.event.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.node.page.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.node.topic.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.paragraph.featured.default.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.paragraph.featured.preview.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_display.profile.profile.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_mode.group.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_mode.node.featured.yml
  modules/social_features/social_featured_content/config/install/core.entity_view_mode.profile.featured.yml
  modules/social_features/social_featured_content/config/install/field.field.block_content.featured.field_featured.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_description.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_items.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_link.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_title.yml
  modules/social_features/social_featured_content/config/install/field.storage.block_content.field_featured.yml
  modules/social_features/social_featured_content/config/install/field.storage.paragraph.field_featured_description.yml
  modules/social_features/social_featured_content/config/install/field.storage.paragraph.field_featured_items.yml
  modules/social_features/social_featured_content/config/install/field.storage.paragraph.field_featured_link.yml
  modules/social_features/social_featured_content/config/install/field.storage.paragraph.field_featured_title.yml
  modules/social_features/social_featured_content/config/install/image.style.social_featured.yml
  modules/social_features/social_featured_content/config/install/paragraphs.paragraphs_type.featured.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_content_reference.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_group_reference.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_profile_reference.yml
  modules/social_features/social_featured_content/config/optional/language.content_settings.paragraph.featured.yml
  modules/social_features/social_featured_content/css/featured.css
  modules/social_features/social_featured_content/css/featured.css.map
  modules/social_features/social_featured_content/css/featured.scss
  modules/social_features/social_featured_content/css/paragraph.featured.css
  modules/social_features/social_featured_content/css/paragraph.featured.css.map
  modules/social_features/social_featured_content/css/paragraph.featured.scss
  modules/social_features/social_featured_content/social_featured_content.info.yml
  modules/social_features/social_featured_content/social_featured_content.libraries.yml
  modules/social_features/social_featured_content/social_featured_content.module
  modules/social_features/social_featured_content/templates/field--paragraph--field-featured-items.html.twig
  modules/social_features/social_featured_content/templates/group--featured.html.twig
  modules/social_features/social_featured_content/templates/node--event--featured.html.twig
  modules/social_features/social_featured_content/templates/node--featured.html.twig
  modules/social_features/social_featured_content/templates/paragraph--featured--default.html.twig
  modules/social_features/social_featured_content/templates/profile--featured.html.twig
  modules/social_features/social_landing_page/config/update/social_landing_page_update_8807.yml
  modules/social_features/social_landing_page/css/social_landing_page.section.featured.css.map
  modules/social_features/social_landing_page/social_landing_page.info.yml
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_landing_page/social_landing_page.libraries.yml
  modules/social_features/social_landing_page/social_landing_page.module
  tests/behat/features/capabilities/landing-page/landing-page-create.feature
  themes/socialbase/templates/block/block--featured.html.twig
  themes/socialblue/templates/node/event/node--event--featured--sky.html.twig
  themes/socialblue/templates/node/node--featured--sky.html.twig
  themes/socialblue/templates/profile/profile--featured--sky.html.twig
Labels: prio: high, prio: medium, team: eci, type: feature request
