Repository goalgorilla/open_social, pull requests merged in 2021-02, with the labels that each got.

#2203 [GraphQL] Implement dedicated viewer producer
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/Viewer.php
  modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php
Labels: prio:low, team: shipsters, type: code refactoring

#2206 Remove social_graphql_devel module
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.info.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.links.task.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.routing.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.services.yml
  modules/custom/social_graphql/modules/social_graphql_devel/src/Controller/ValidationController.php
  modules/custom/social_graphql/modules/social_graphql_devel/src/GraphQL/Validator.php
  modules/custom/social_graphql/modules/social_graphql_devel/src/GraphQL/ValidatorInterface.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  modules/social_features/social_profile/tests/src/Kernel/GraphQLUsersEndpointTest.php
  modules/social_features/social_user/tests/src/Kernel/GraphQLUsersEndpointTest.php
Labels: prio:low, team: shipsters, type: code refactoring

#2193 Issue #3172477 by agami4: Album theming fixes
  modules/social_features/social_album/social_album.module
  modules/social_features/social_post/modules/social_post_album/assets/css/.sass-cache/030311e4187feca6ab76e2dfb40f5158847a4c6b/social-post-album--form.scssc
  modules/social_features/social_post/modules/social_post_album/assets/css/.sass-cache/030311e4187feca6ab76e2dfb40f5158847a4c6b/social-post-album--popup.scssc
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--popup-slider.js
  themes/socialblue/assets/css/brand.css
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/assets/css/waves.css
  themes/socialblue/components/02-atoms/waves/waves.scss
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
  themes/socialblue/components/brand.scss
  themes/socialblue/templates/node/album/node--album--hero--sky.html.twig
Labels: action: testing day, prio: medium, status: needs review, team: eci

#2195 Issue #3172477 by chmez: Add page title when adding post to image to explain users what they are doing
  modules/social_features/social_album/social_album.module
  modules/social_features/social_core/social_core.api.php
  modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
  modules/social_features/social_node/social_node.api.php
  modules/social_features/social_node/social_node.module
  modules/social_features/social_node/social_node.services.yml
  modules/social_features/social_node/src/Service/SocialNodeMessenger.php
  modules/social_features/social_node/src/Service/SocialNodeMessengerInterface.php
  modules/social_features/social_node/src/SocialNodeForm.php
Labels: action: testing day, prio: medium, status: needs review, team: eci, type: bug, type: code refactoring

#2184 Issue #3193963 by tBKoT: Fixes for follow taxonomy
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.info.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/templates/paragraph--tag--default.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag_stream.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.update_node_following_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/optional/block.block.followtag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.info.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/ActivityContext/FollowTagActivityContext.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagOverrides.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/search-follow-tag.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-nosplit.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-split.html.twig
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.install
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.module
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
  modules/social_features/social_tagging/social_tagging.module
Labels: action: testing day, status: needs review, team: eci, type: bug

#2211 Issue #3177902 by chmez: When you delete an image from a form post, the form has a wrong layout
  modules/social_features/social_post/modules/social_post_album/src/Element/SocialPostAlbumManagedFile.php
  themes/socialbase/src/Plugin/Form/SocialAlbumPostForm.php
Labels: action: testing day, prio: medium, status: needs work, team: eci, type: bug

#2200 Issue #3177673 by chmez: WSOD when user creates an album and assigns it to course or challenge
  modules/social_features/social_album/social_album.routing.yml
  modules/social_features/social_album/src/Controller/SocialAlbumController.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumGroupAccess.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumUserAccess.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/EntityReferenceSelection/SocialGroupSelection.php
Labels: action: testing day, prio: high, status: needs work, team: eci, type: bug

#2202 Issue #3172477 by ronaldtebrake: Fix albums with one image and demo content
  modules/social_features/social_post/modules/social_post_album/assets/css/.sass-cache/030311e4187feca6ab76e2dfb40f5158847a4c6b/social-post-album--form.scssc
  modules/social_features/social_post/modules/social_post_album/assets/css/.sass-cache/030311e4187feca6ab76e2dfb40f5158847a4c6b/social-post-album--popup.scssc
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--post.scss
  modules/social_features/social_post/modules/social_post_album/social_post_album.module
  modules/social_features/social_post/modules/social_post_album/src/Plugin/Field/FieldFormatter/AlbumImageFormatter.php
  modules/social_features/social_post/modules/social_post_album/templates/field--post--type--image--album.html.twig
Labels: action: testing day, prio: high, status: needs work, type: bug

#2212 DS-7491 - Issues with Albums added to existing albums from the post form
  composer.json
  modules/social_features/social_album/social_album.module
  modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
  modules/social_features/social_album/src/SocialAlbumConfigOverride.php
  modules/social_features/social_post/src/Form/PostForm.php
Labels: action: testing day, status: needs review

#2178 Issue/3194216 by navneet0693: Remove social_node_statistics from Distro.
  modules/custom/social_node_statistics/config/install/social_node_statistics.settings.yml
  modules/custom/social_node_statistics/config/schema/social_node_statistics.schema.yml
  modules/custom/social_node_statistics/content/block/social_kpi_lite_node_views.yml
  modules/custom/social_node_statistics/content/block_content/social_kpi_lite_node_views.yml
  modules/custom/social_node_statistics/social_node_statistics.info.yml
  modules/custom/social_node_statistics/social_node_statistics.install
  modules/custom/social_node_statistics/social_node_statistics.links.menu.yml
  modules/custom/social_node_statistics/social_node_statistics.module
  modules/custom/social_node_statistics/social_node_statistics.permissions.yml
  modules/custom/social_node_statistics/social_node_statistics.routing.yml
  modules/custom/social_node_statistics/social_node_statistics.services.yml
  modules/custom/social_node_statistics/src/EventSubscriber/NodeViewSubscriber.php
  modules/custom/social_node_statistics/src/Form/NodeStatisticsSettingsForm.php
Labels: prio: high, status: needs review, team: nucleus, type: code refactoring, type: dependencies, type: performance

#2113 Issue #3189357 by rolki: Add the ability to invite users via email
  modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteUserForm.php
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
Labels: prio: medium, team: eci, type: bug, type: feature request

#2188 Issue #3194809 by agami4: Improve teaser tag for the teasers in SKY style
  themes/socialbase/assets/css/teaser.css
  themes/socialbase/components/03-molecules/teaser/teaser.scss
  themes/socialblue/assets/css/teaser--sky.css
  themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
Labels: team: eci, type: bug

#2176 Issue/3165299 by navneet0693: Add latest patches in url_embed module.
  composer.json
Labels: prio:low, status: needs backport, status: needs review, team: nucleus, type: code refactoring, type: dependencies

#2215 Rename `currentUser` field to `viewer`
  modules/social_features/social_user/graphql/social_user_schema_extension.extension.graphqls
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
  modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLViewerEndpointTest.php
Labels: team: shipsters, type: code refactoring

#2201 Issue #3195438 by tBKoT: Improves entity validation in the follow tag activity context
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
  modules/social_features/social_activity/config/update/social_activity_update_8807.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/ActivityContext/FollowTagActivityContext.php
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.api.php
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
Labels: action: testing day, prio: high, status: needs review, team: eci, type: bug, type: code refactoring

#2214 DS-7491 - Post Album - fix voting / liking in a modal
  themes/socialbase/assets/js/like_and_dislike_service.min.js
  themes/socialbase/components/03-molecules/like/like_and_dislike_service.js
Labels: action: testing day, status: needs review

#2217 Issue #3196323 - Remove Social Search Autocomplete
  modules/social_features/social_search/modules/social_search_autocomplete/.eslintrc.js
  modules/social_features/social_search/modules/social_search_autocomplete/babel.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
  modules/social_features/social_search/modules/social_search_autocomplete/config/update/social_search_autocomplete_update_8001.yml
  modules/social_features/social_search/modules/social_search_autocomplete/css/search-suggestion.css
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js
  modules/social_features/social_search/modules/social_search_autocomplete/js/dist/index.js.map
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/TranslationContext.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/SearchSuggestions.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/SearchSuggestions.test.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Spinner.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Suggestion.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/Suggestion.test.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/__snapshots__/SearchSuggestions.test.jsx.snap
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/components/__snapshots__/Suggestion.test.jsx.snap
  modules/social_features/social_search/modules/social_search_autocomplete/js/src/index.jsx
  modules/social_features/social_search/modules/social_search_autocomplete/package.json
  modules/social_features/social_search/modules/social_search_autocomplete/prettier.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.info.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.install
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.installer_options.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.libraries.yml
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.module
  modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.post_update.php
  modules/social_features/social_search/modules/social_search_autocomplete/webpack.config.js
  modules/social_features/social_search/modules/social_search_autocomplete/yarn.lock
Labels: prio: high, team: nucleus

#2226 [Internal] - Fix phpstan latest issues + stability on the private file upload test
  modules/custom/activity_creator/activity_creator.tokens.inc
  modules/social_features/social_private_message/src/Plugin/UserExportPlugin/UserAnalyticsPrivateMessage.php
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
  tests/behat/features/capabilities/security/private-file-uploads.feature
Labels: prio: medium, status: needs review, team: nucleus, type: bug, type: code refactoring

#2216 Issue #3197265 by chmez: An error on group page after adding images to the post and deleting the first image
  modules/social_features/social_album/social_album.module
  modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
  modules/social_features/social_album/src/SocialAlbumConfigOverride.php
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/post/post-album.feature
Labels: action: testing day, prio: high, team: eci, type: bug, type: code refactoring

#2220 Issue #3197227 by chmez: Issue with Ajax commenting in album on the stream
  modules/custom/activity_creator/activity_creator.tokens.inc
  modules/social_features/social_post/modules/social_post_album/social_post_album.module
  modules/social_features/social_post/modules/social_post_album/src/Controller/SocialPostAlbumAjaxCommentsController.php
  modules/social_features/social_private_message/src/Plugin/UserExportPlugin/UserAnalyticsPrivateMessage.php
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
  tests/behat/config/behat.yml
  tests/behat/features/bootstrap/SocialMessageContext.php
  tests/behat/features/capabilities/post/post-modal-comments.feature
Labels: action: testing day, prio: medium, status: needs review, team: eci, type: bug, type: code refactoring

#2222 Issue #3196762 by agami4: Improve pagination block on the album user page
  modules/social_features/social_album/assets/css/social-album--teaser.css
  modules/social_features/social_album/assets/css/social-album--teaser.css.map
  modules/social_features/social_album/assets/css/social-album--teaser.scss
Labels: team: eci, type: bug

#2224 Issue #3197235 by SV: Display featured profile section for anonymous users
  modules/social_features/social_profile/social_profile.module
  tests/behat/features/capabilities/landing-page/featured-profile-create.feature
Labels: prio: medium, team: eci, type: bug, type: feature request

#2243 Issue #3199146: [GraphQL] Improve Violation representation
  modules/custom/social_graphql/graphql/open_social.graphqls
  modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
  modules/custom/social_graphql/src/GraphQL/Violation.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Payload/PayloadViolations.php
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/UserFromWrapper.php
  modules/social_features/social_user/src/Wrappers/UserAwareInterface.php
Labels: prio: medium, team: shipsters, type: feature request

#2244 Capitalise MadeToShare hashtag
  modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
  modules/social_features/social_swiftmail/social_swiftmail.module
Labels: prio: medium, status: needs backport, team: shipsters, type: bug

#2227 Issue #3197706 by rolki: Provide a method to alter array of group types used in social group request
  modules/social_features/social_group/modules/social_group_request/social_group_request.api.php
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
  modules/social_features/social_group/social_group.module
Labels: prio: medium, team: eci, type: code refactoring, type: feature request

#2229 Issue #3197794 by tBKoT: Improve the personalised homepage activity filter and allow to alter the query
  modules/custom/activity_viewer/activity_viewer.api.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
  phpstan-baseline.neon
Labels: optional: review requested, team: eci, type: bug, type: code refactoring

#2239 Issue #3199157 by rolki: Use group_content storage instead of groupInvitationLoader service for checking invitation
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
Labels: prio: high, team: eci, type: bug

#2236 Issue #3198706 by Ressinel: Fix fatal error in ajax comment module.
  composer.json
Labels: prio: high, team: eci, type: bug

#2234 Issue #3198521 by Ressinel: Fix PHP warning when add event enrollees
  modules/social_features/social_event/modules/social_event_managers/src/Element/SocialEnrollmentAutocomplete.php
Labels: prio: medium, team: eci, type: bug

#2235 Issue #3198528 by tBKoT: Improve Follow taxonomy block performance
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-nosplit.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-popup.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-split.html.twig
Labels: prio: medium, team: eci

#2246 Issue #3199893 by rolki: Notifications don't work for the group types that install the "Group request membership" plugin except for flexible group
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
  modules/social_features/social_group/modules/social_group_request/src/Plugin/Block/SocialGroupRequestMembershipNotification.php
Labels: prio: medium, team: eci, type: bug
