Repository goalgorilla/open_social, pull requests merged in 2021-03, with the labels that each got.

#2245 Issue #3199367 by SV: Allow member to add a table in the description of node
  modules/social_features/social_editor/config/install/editor.editor.basic_html.yml
  modules/social_features/social_editor/config/install/filter.format.basic_html.yml
  modules/social_features/social_editor/config/update/social_editor_update_8904.yml
  modules/social_features/social_editor/social_editor.install
Labels: prio: medium, team: eci, type: feature request

#2228 Issue #3197712 by Ressinel: Improve ActivityDigestWorker getRelatedEntity() method to prevent block of other queues on cron run.
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/notifications/notification-emails.feature
Labels: blocked: maintainer input, prio: medium, status: needs backport, team: eci, type: bug

#2247 Issue #3199704 by SV: URL-link is broken in the e-mail notification
  modules/social_features/social_comment/social_comment.tokens.inc
Labels: optional: review requested, prio: medium, team: eci, type: bug

#2232 Issue #3197989 by chmez: Issue with pagination when Ajax Comments module is enabled
  modules/custom/social_ajax_comments/social_ajax_comments.module
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/src/SocialCommentViewBuilder.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/comment/comment-ajax.feature
Labels: action: testing day, prio: medium, team: eci, type: bug, type: code refactoring

#2248 Issue #3200113 by rolki: Allow extending group and content visibilities to other group types
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/FlexibleGroupContentVisibilityUpdate.php
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/GroupContentVisibilityUpdate.php
  modules/social_features/social_topic/social_topic.module
Labels: blocked: release notes, optional: review requested, prio: high, team: eci, type: code refactoring, type: feature request

#2258 Issue #3201182 by Kingdutch: [GraphQL] Introduce an Actor interface
  modules/custom/social_graphql/graphql/open_social.graphqls
  modules/custom/social_graphql/src/GraphQL/DecoratableTypeResolver.php
  modules/social_features/social_user/graphql/social_user_schema_extension.base.graphqls
  modules/social_features/social_user/graphql/social_user_schema_extension.extension.graphqls
  modules/social_features/social_user/src/GraphQL/UserActorTypeResolver.php
  modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php
Labels: prio: medium, team: shipsters, type: feature request

#2260 Issue #3203499: As a developer I want to have precise control over how cronjobs and queue items are processed
  composer.json
  modules/custom/social_advanced_queue/social_advanced_queue.info.yml
  modules/custom/social_advanced_queue/social_advanced_queue.module
  modules/custom/social_advanced_queue/src/Plugin/Action/SocialSendEmailAdvancedQueue.php
  modules/social_features/social_core/social_core.install
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  modules/social_features/social_user/src/Plugin/AdvancedQueue/JobType/UserMailQueueJob.php
  social.info.yml
  tests/behat/features/bootstrap/EmailContext.php
Labels: prio: high, team: nucleus, type: feature request

#2252 Issue #3202292 by vnech: Fix hiding of "Tagging" field in the Inline Entity Form
  modules/social_features/social_tagging/social_tagging.module
Labels: prio: medium, team: eci, type: bug

#2269 Issue #3204775 - Update patch for ajax comments based on beta 3
  composer.json
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/social_event.module
  tests/behat/features/capabilities/security/private-file-uploads.feature
Labels: prio: high, status: needs backport, team: nucleus, type: update

#2233 Issue #3198244 by SV: Redirect invited new users to the event/group pages.
  modules/social_features/social_event/modules/social_event_invite/config/install/social_event_invite.settings.yml
  modules/social_features/social_event/modules/social_event_invite/config/schema/social_event_invite.schema.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.services.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc
  modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteSettingsForm.php
  modules/social_features/social_event/modules/social_event_invite/src/SocialEventInviteConfigOverride.php
  modules/social_features/social_group/modules/social_group_invite/config/optional/message.template.invited_to_join_group.yml
  modules/social_features/social_group/modules/social_group_invite/config/update/social_group_invite_update_8007.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.routing.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.services.yml
  modules/social_features/social_group/modules/social_group_invite/src/Controller/SocialGroupInvitationOperations.php
  modules/social_features/social_group/modules/social_group_invite/src/SocialGroupInviteConfigOverride.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/event/event-invite-members.feature
  tests/behat/features/capabilities/group/group-invite-members.feature
Labels: prio: high, team: eci, type: feature request

#2187 Issue #3194775 by Ressinel: Search does not show all results on the same page.
  modules/custom/entity_access_by_field/src/Plugin/search_api/processor/EntityAccessByField.php
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/update/social_search_update_8904.yml
  modules/social_features/social_search/social_search.install
  tests/behat/features/capabilities/search/search-all.feature
  tests/behat/features/capabilities/search/search-content.feature
Labels: prio: high, team: eci, type: bug, type: code refactoring

#2262 Issue #3203588 by laykin: Fix ability to invite members in custom groups (like Challenges)
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/social_group.module
Labels: team: eci, type: bug

#2163 Issue #3193302 by tBKoT: Add books and pages to select list of custom content list block
  modules/social_features/social_book/config/optional/core.entity_view_display.node.book.small_teaser.yml
  modules/social_features/social_book/config/static/social_book_static_update_8903.yml
  modules/social_features/social_book/social_book.install
  modules/social_features/social_content_block/modules/social_book_content_block/social_book_content_block.info.yml
  modules/social_features/social_content_block/modules/social_book_content_block/src/Plugin/ContentBlock/BookContentBlock.php
  modules/social_features/social_content_block/modules/social_page_content_block/social_page_content_block.info.yml
  modules/social_features/social_content_block/modules/social_page_content_block/src/Plugin/ContentBlock/PageContentBlock.php
  modules/social_features/social_content_block/src/Plugin/Field/FieldWidget/ContentBlockPluginFieldWidget.php
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.small_teaser.yml
  modules/social_features/social_page/config/static/social_page_static_update_8908.yml
  modules/social_features/social_page/social_page.install
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
  tests/behat/features/capabilities/landing-page/custom-content-list.feature
Labels: prio: high, team: eci, type: feature request

#2274 Issue #3205787 by Kingdutch: Default permissions don't allow the Open…
  modules/custom/social_graphql/social_graphql.install
Labels: prio: medium, status: needs review, team: shipsters, type: bug

#2259 Issue #3203225 by Kingdutch, ronaldtebrake: Standardise package name …
  .travis.yml
  composer.json
Labels: blocked: maintainer input, prio: high, status: needs review, team: shipsters, type: code refactoring

#2240 Issue #3198953 by ribel: As a LU I want to be able to filter on the all members overview page
  modules/social_features/social_profile/config/install/views.view.newest_users.yml
  modules/social_features/social_profile/config/optional/block.block.exposedformnewest_userspage_newest_users.yml
  modules/social_features/social_profile/config/optional/block.block.socialblue_exposedformnewest_userspage_newest_users.yml
  modules/social_features/social_profile/config/static/block.block.exposedformnewest_userspage_newest_users_8901.yml
  modules/social_features/social_profile/config/static/block.block.socialblue_exposedformnewest_userspage_newest_users_8901.yml
  modules/social_features/social_profile/config/update/social_profile_update_8902.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: optional: review requested, team: eci, type: feature request

#2223 Issue #3196173 - Fix Expected argument of type "array or Traversable and ArrayAccess"
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.routing.yml
  modules/social_features/social_event/social_event.routing.yml
Labels: prio: medium, status: needs backport, team: nucleus, type: bug
