Repository goalgorilla/open_social, pull requests merged in 2021-08, with the labels that each got.

#2396 Issue #3123493 by AlanHDev: Resolve missing/broken view filter on activity stream
  modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
  modules/social_features/social_activity/social_activity.install
Labels: prio: medium, team: external, team: nucleus, type: bug

#2445 Issue #3225518 by tBKoT: Allow SM to disable specific email notifications
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/None.php
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  tests/behat/features/bootstrap/EmailContext.php
  tests/behat/features/capabilities/notifications/notification-emails.feature
Labels: team: eci, type: feature request, prio: medium

#2433 Issue #3224886 by tBKoT: Fix redirect for the group home route
  modules/custom/social_path_manager/social_path_manager.module
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.services.yml
  modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/social_group.services.yml
Labels: type: bug, team: eci, prio: medium

#2440 Issue #3225331 by Ressinel: Update the Token module from 1.5 to 1.9
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2439 Issue #3225319 by Ressinel: Update the Shariff Social Media Buttons module from 1.5 to 1.7
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2435 Issue #3224713 by Ressinel: Update the Paragraphs module from 1.11 to 1.12
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2422 Issue #3224278 by Ressinel: Update the Configuration Update Manager module from 1.6 to 1.7
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2430 Issue #3224698 by Ressinel: Update the Metatag module from 1.11 to 1.16
  composer.json
Labels: type: update, status: needs review, prio: medium, type: dependencies, team: nucleus

#2429 Issue #3224677 by Ressinel: Update the Message module from 1.0 to 1.2
  composer.json
Labels: type: update, status: needs review, prio: medium, type: dependencies, team: nucleus

#2442 Issue #3225340 by Ressinel: Update the Views Infinite Scroll module from 1.6 to 1.8
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2459 Internal - Lock versions of our contrib modules & themes
  composer.json
Labels: status: needs review, prio: medium, blocked: maintainer input, type: dependencies, team: nucleus

#2209 Issue #3195983 by mdeny: Provide possibility for SM to not send email notifications to users who have never logged in
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/social_features/social_swiftmail/config/schema/social_swiftmail.schema.yml
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  tests/behat/features/capabilities/notifications/notification-emails.feature
Labels: team: eci, type: feature request, prio: high, optional: review requested

#2457 Issue #3227326 by vnech: Add missed translation support for "Landing Page" content type
  modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion.field_accord_description.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion.field_accord_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion_item.field_accord_item_description.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion_item.field_accord_item_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_link.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.button.field_button_link_an.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.button.field_button_link_lu.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_image.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_subtitle.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_image.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_subtitle.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_title.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_link_an.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_link_lu.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_text.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_title.yml
  modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.accordion.yml
  modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.accordion_item.yml
  modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.hero_small.yml
  modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.section.yml
  modules/social_features/social_landing_page/config/update/social_landing_page_update_10302.yml
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_landing_page/src/ContentTranslationDefaultsConfigOverride.php
Labels: type: bug, team: eci, prio: medium

#2434 Issue #3224974 by vnech: "Social Language - Content Translation" change fields definition to untranslatable
  modules/custom/social_language/modules/social_content_translation/social_content_translation.install
  modules/social_features/social_topic/config/optional/language.content_settings.node.topic.yml
Labels: type: bug, team: eci, prio: high

#2450 Issue #3226318 by tBKoT: Update possibly translated field group labels
  modules/social_features/social_album/config/update/social_album_update_10201.yml
  modules/social_features/social_album/social_album.install
  modules/social_features/social_book/config/update/social_book_update_10201.yml
  modules/social_features/social_book/social_book.install
  modules/social_features/social_event/config/update/social_event_update_10201.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_landing_page/config/update/social_landing_page_update_10201.yml
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_page/config/update/social_page_update_10201.yml
  modules/social_features/social_page/social_page.install
  modules/social_features/social_profile/config/update/social_profile_update_10201.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_topic/config/update/social_topic_update_10201.yml
  modules/social_features/social_topic/social_topic.install
Labels: type: bug, team: eci, prio: high

#2393 Issue #3220779 by vnech: Add translations support for custom blocks
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_link.yml
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_subtitle.yml
  modules/social_features/social_content_block/config/optional/language.content_settings.block_content.custom_content_list.yml
  modules/social_features/social_content_block/config/update/social_content_block_update_10300.yml
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_content_block/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_core/config/install/field.field.block_content.basic.field_basic_link.yml
  modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_call_to_action_link.yml
  modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_hero_image.yml
  modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_text_block.yml
  modules/social_features/social_core/config/install/field.field.block_content.platform_intro.field_text_block.yml
  modules/social_features/social_core/config/optional/language.content_settings.block_content.basic.yml
  modules/social_features/social_core/config/optional/language.content_settings.block_content.hero_call_to_action_block.yml
  modules/social_features/social_core/config/optional/language.content_settings.block_content.platform_intro.yml
  modules/social_features/social_core/config/update/social_core_update_10300.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_event/config/optional/block.block.socialblue_views_block__event_enrollments_event_enrollments_socialbase.yml
  modules/social_features/social_event/config/update/social_event_update_10304.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_description.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_link.yml
  modules/social_features/social_featured_content/config/install/field.field.paragraph.featured.field_featured_title.yml
  modules/social_features/social_featured_content/config/optional/language.content_settings.block_content.featured.yml
  modules/social_features/social_featured_content/config/update/social_featured_content_update_10300.yml
  modules/social_features/social_featured_content/social_featured_content.install
  modules/social_features/social_featured_content/social_featured_content.services.yml
  modules/social_features/social_featured_content/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_item.field_featured_item_description.yml
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_item.field_featured_item_image.yml
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_item.field_featured_item_link.yml
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_item.field_featured_item_title.yml
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_items.field_featured_items_description.yml
  modules/social_features/social_featured_items/config/install/field.field.paragraph.featured_items.field_featured_items_title.yml
  modules/social_features/social_featured_items/config/optional/language.content_settings.block_content.featured_items.yml
  modules/social_features/social_featured_items/config/optional/language.content_settings.paragraph.featured_item.yml
  modules/social_features/social_featured_items/config/optional/language.content_settings.paragraph.featured_items.yml
  modules/social_features/social_featured_items/config/update/social_featured_items_update_10300.yml
  modules/social_features/social_featured_items/social_featured_items.install
  modules/social_features/social_featured_items/social_featured_items.services.yml
  modules/social_features/social_featured_items/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/optional/language.content_settings.block_content.follow_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.services.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/src/ContentTranslationDefaultsConfigOverride.php
Labels: team: eci, type: feature request, prio: high

#2452 Issue #3226672 by nkoporec: Overwrite title field for blocks does not work in Landing Page form
  modules/social_features/social_landing_page/social_landing_page.module
Labels: type: bug, status: needs review, status: needs backport, team: gravitiers

#2415 Issue #3206847 by navneet0693: Added accessCheck(FALSE) property to entity query for enabling event enrolment by default.
  modules/social_features/social_event/social_event.post_update.php
Labels: type: bug, status: needs backport, prio: high, team: nucleus

#2426 Issue #3224552 by Ressinel: Update the Flag module from 4.0-alpha3 to 4.0-beta2
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2438 Issue #3209094 by Ressinel: Private group member doesn’t see group content on the search page (revert)
  modules/custom/entity_access_by_field/entity_access_by_field.module
  modules/custom/entity_access_by_field/entity_access_by_field.post_update.php
Labels: type: bug, prio: medium, team: nucleus

#2427 Issue #3224631 by navneet0693: Removed config override from social_group_welcome_message module.
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.services.yml
  modules/social_features/social_group/modules/social_group_welcome_message/src/SocialGroupWelcomeMessageConfigOverride.php
Labels: type: code refactoring, status: needs backport, prio: high, team: nucleus

#2374 Issue #3217389 by robertragas: add administrative area as an option f…
  modules/social_features/social_profile/modules/social_profile_fields/config/install/social_profile_fields.settings.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsFlushForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsHelper.php
Labels: status: needs backport, team: gravitiers

#2356 Issue 3216000 by nkoporec: Remove body field from Outlook add to calendar link
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOutlook.php
Labels: type: bug, status: needs backport, team: gravitiers

#2408 Remove css classes from Ajax Comments, when comment is unpublishev
  modules/social_features/social_comment/social_comment.module
Labels: type: bug, team: external, prio: high

#2416 Issue #3223589 by Ressinel: Facebook embed content not working.
  composer.json
  modules/social_features/social_embed/social_embed.install
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlFilter.php
Labels: type: bug, prio: medium, team: nucleus

#2394 Issue #3221056 by nkoporec: Don't cache the number of event enrollments
  modules/social_features/social_event/src/Form/EnrollActionForm.php
Labels: type: bug, status: needs backport, team: gravitiers

#2467 Issue #3222835 by mparker17,navneet0693: Removed layout_builder settings from small_teaser view mode for page.
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.small_teaser.yml
  modules/social_features/social_page/social_page.install
Labels: team: external, prio: medium

#2473 Issue 3229797 by nachosalvador: Fix Inbox link disappears from the us…
  modules/social_features/social_private_message/social_private_message.module
Labels: type: bug, prio: high, team: gravitiers

#2479 [GraphQL] Implement community name querying in the Graph
  modules/social_features/social_branding/graphql/social_branding_schema_extension.base.graphqls
  modules/social_features/social_branding/graphql/social_branding_schema_extension.extension.graphqls
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/AboutName.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/BrandingColorScheme.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/BrandingColorSchemeLoadColorByName.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/BrandingLogoUrl.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/CommunityAbout.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/CommunityBranding.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/FeatureMachineName.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/PreferredFeatures.php
  modules/social_features/social_branding/src/Plugin/GraphQL/SchemaExtension/AppSchemaExtension.php
  modules/social_features/social_branding/src/PreferredFeature.php
  modules/social_features/social_branding/src/PreferredFeatureInterface.php
  modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.module
  modules/social_features/social_branding/tests/src/Kernel/GraphQL/BrandingGraphQLTest.php
  modules/social_features/social_branding/tests/src/Unit/PreferredFeatureTest.php
Labels: status: needs review, team: gravitiers

#2468 Issue #3228885 by vnech: Type filter doesn't work correctly on search groups page
  modules/social_features/social_search/config/install/views.view.search_groups.yml
  modules/social_features/social_search/config/update/social_search_update_10302.yml
  modules/social_features/social_search/social_search.install
  modules/social_features/social_search/social_search.module
Labels: type: bug, team: eci, prio: medium
