Repository goalgorilla/open_social, pull requests merged in 2021-07, with the labels that each got.

#2295 Issue #3209094 by Ressinel: Private group member doesn’t see group content on the search page
  modules/custom/entity_access_by_field/entity_access_by_field.module
  modules/custom/entity_access_by_field/entity_access_by_field.post_update.php
Labels: optional: review requested, prio: medium, team: eci, team: nucleus

#2384 Issue #3219282 by vnech: Add missed translation support for search and groups overview pages
  modules/social_features/social_group/config/install/views.view.groups.yml
  modules/social_features/social_group/config/install/views.view.newest_groups.yml
  modules/social_features/social_group/config/update/social_group_update_10201.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_search/config/install/views.view.search_all.yml
  modules/social_features/social_search/config/install/views.view.search_content.yml
  modules/social_features/social_search/config/install/views.view.search_groups.yml
  modules/social_features/social_search/config/update/social_search_update_10201.yml
  modules/social_features/social_search/social_search.install
Labels: prio: medium, team: eci, type: feature request

#2060 Issue #3181482 by rolki: As a LU I want to have clear overview on each activity item on dashboard stream
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment_upload/social_comment_upload.module
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.featured.yml
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.install
  modules/social_features/social_post/modules/social_post_photo/src/SocialPostPhotoConfigOverride.php
  modules/social_features/social_post/social_post.module
  modules/social_features/social_post/templates/post--featured.html.twig
  translations.php
Labels: prio: high, team: eci, type: bug, type: code refactoring

#2401 Issue #3222350 by navneet0693: Locked gin_toolbar version to 1.0-beta17.
  composer.json
Labels: prio: high, status: needs review, team: nucleus

#2389 Issue #3220085 by Ressinel: Fixes when not all followers receive (email) notifications of content they are following.
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
  tests/behat/features/capabilities/topic/topic-follow-content.feature
Labels: prio: medium, status: needs review, team: nucleus, type: bug

#2306 Issue #3210717 - As a LU, I want my group membership count to show only active & correct group memberships
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_profile/social_profile.module
  tests/behat/features/capabilities/group/group-invite-members.feature
Labels: blocked: commit cleanup, prio: medium, status: needs backport, team: nucleus, type: bug

#2406 DS-7613 - 1: Short-cut UserQuery for anonymous users
  modules/custom/social_graphql/src/GraphQL/EmptyEntityConnection.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionEdges.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionPageInfo.php
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
Labels: prio: high, status: needs backport, status: needs review, team: shipsters, type: performance

#2387 Issue #3219417 by SV: Add translation support for Topic content type
  modules/custom/social_language/modules/social_content_translation/config/install/social_content_translation.settings.yml
  modules/custom/social_language/modules/social_content_translation/social_content_translation.install
  modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_image.yml
  modules/social_features/social_topic/config/install/views.view.latest_topics.yml
  modules/social_features/social_topic/config/install/views.view.topics.yml
  modules/social_features/social_topic/config/update/social_topic_update_10301.yml
  modules/social_features/social_topic/social_topic.install
  modules/social_features/social_topic/social_topic.services.yml
  modules/social_features/social_topic/src/ContentTranslationDefaultsConfigOverride.php
Labels: prio: medium, team: eci, type: feature request

#2412 Issue #3223299 by tBKoT: Add Office 365 support for Add to calendar
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOffice365.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOutlook.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToYahoo.php
Labels: prio: medium, team: eci, type: bug

#2417 Issue #3223639 by SV: Error after adding a parent of tag for translated nodes
  modules/social_features/social_tagging/src/SocialTaggingService.php
Labels: prio: medium, team: eci, type: bug

#2404 Issue #3222538 by vnech: Allow "Content Manager" role to translate content
  modules/custom/social_language/social_language.install
  modules/custom/social_language/social_language.module
  modules/custom/social_language/src/Routing/RouteSubscriber.php
  modules/social_features/social_book/social_book.install
  modules/social_features/social_event/social_event.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_page/social_page.install
  modules/social_features/social_topic/social_topic.install
Labels: prio: high, team: eci, type: feature request

#2418 [Internal] - Fix PHPStan errors.
  modules/custom/activity_creator/src/ActivityNotifications.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
Labels: prio: high, team: nucleus, type: bug

#2403 Issue #3222386 by nachosalvador: Implement preferred features querying in the Graph
  modules/social_features/social_branding/graphql/social_branding_schema_extension.base.graphqls
  modules/social_features/social_branding/social_branding.api.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/PlatformBrandingPreferredFeatures.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/PlatformFeatureMachineName.php
  modules/social_features/social_branding/src/Plugin/GraphQL/SchemaExtension/AppSchemaExtension.php
  modules/social_features/social_branding/src/PreferredPlatformFeature.php
  modules/social_features/social_branding/src/PreferredPlatformFeatureInterface.php
  modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.info.yml
  modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.module
  modules/social_features/social_branding/tests/src/Kernel/GraphQL/BrandingGraphQLTest.php
  modules/social_features/social_branding/tests/src/Unit/PreferredPlatformFeatureTest.php
Labels: prio: medium, team: gravitiers, type: feature request

#2400 Issue #3222148: Fix schema errors in social_topic, social_event, social_node and social_group
  composer.json
  modules/custom/entity_access_by_field/entity_access_by_field.install
  modules/custom/group_core_comments/config/schema/group_core_comments.schema.yml
  modules/social_features/social_core/config/schema/social_core.schema.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_content_visibility.yml
  modules/social_features/social_event/config/install/views.view.events.yml
  modules/social_features/social_event/config/install/views.view.upcoming_events.yml
  modules/social_features/social_event/config/schema/social_event.schema.yml
  modules/social_features/social_event/config/update/social_event_update_10302.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_group/config/install/views.view.group_events.yml
  modules/social_features/social_group/config/install/views.view.group_manage_members.yml
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/config/update/social_group_update_10301.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_node/config/install/field.storage.node.field_content_visibility.yml
  modules/social_features/social_node/config/install/field.storage.node.field_files.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.medium_teaser.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/config/update/social_profile_update_10301.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.activity.yml
  modules/social_features/social_topic/config/install/field.field.node.topic.field_content_visibility.yml
  modules/social_features/social_topic/config/schema/social_topic.schema.yml
  modules/social_features/social_topic/config/update/social_topic_update_10301.yml
  modules/social_features/social_topic/config/update/social_topic_update_10303.yml
  modules/social_features/social_topic/social_topic.install
Labels: prio: high, team: eci, type: bug

#2368 Issue #3185497 by rolki: Implement basic event querying in the Graph
  modules/social_features/social_event/graphql/social_event_schema_extension.base.graphqls
  modules/social_features/social_event/graphql/social_event_schema_extension.extension.graphqls
  modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/EventManagers.php
  modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/Field/DateToTimestamp.php
  modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/QueryEvent.php
  modules/social_features/social_event/src/Plugin/GraphQL/QueryHelper/EventManagersQueryHelper.php
  modules/social_features/social_event/src/Plugin/GraphQL/QueryHelper/EventQueryHelper.php
  modules/social_features/social_event/src/Plugin/GraphQL/SchemaExtension/EventSchemaExtension.php
  modules/social_features/social_event/tests/src/Kernel/GraphQL/QueryEventTest.php
  modules/social_features/social_event/tests/src/Kernel/GraphQL/QueryEventsTest.php
Labels: prio: medium, team: eci, type: feature request

#2419 Issue #3223946 by vnech: Add missed content translation config for Flexible Group
  modules/social_features/social_group/modules/social_group_flexible_group/config/optional/language.content_settings.group.flexible_group.yml
Labels: prio: medium, team: eci, type: bug

#2431 Issue #3224828 by tBKoT: Fix profile save process when profile tagging is enabled
  modules/social_features/social_profile/src/Plugin/Field/FieldWidget/SocialProfileTagSplitWidget.php
Labels: prio: high, team: eci, type: bug

#2424 Issue #3224507 by Ressinel: Update the CSV Serialization module from 2.0-beta1 to 2.0
  composer.json
Labels: prio: medium, status: needs review, team: nucleus, type: dependencies

#2436 Issue #3225297 by vnech: Remove "all languages" suffix from field group labels
  modules/custom/social_language/social_language.module
Labels: prio: medium, team: eci, type: bug

#2441 Issue #3225336 by vnech: Move "Translations" fieldset to "Settings" fields group
  modules/custom/social_language/social_language.install
  modules/custom/social_language/social_language.module
Labels: prio: medium, team: eci, type: bug

#2405 Issue #3222539 by tBKoT: Allow users to add profile tags to the profile
  modules/social_features/social_profile/config/install/social_profile.settings.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/src/Form/SocialProfileSettingsForm.php
Labels: prio: medium, team: eci, type: bug

#2402 Issue #3222381 by agami4: Improve elements where right-to-left alignment is off
  modules/custom/improved_theme_settings/improved_theme_settings.module
  modules/custom/social_lets_connect/assets/css/toolbar.css
  modules/social_features/social_core/assets/css/admin-toolbar.css
  modules/social_features/social_core/assets/css/admin-toolbar.css.map
  modules/social_features/social_core/assets/css/admin-toolbar.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.scss
  modules/social_features/social_profile/modules/social_profile_organization_tag/css/social_profile_tag.css
  modules/social_features/social_profile/modules/social_profile_organization_tag/css/social_profile_tag.css.map
  modules/social_features/social_profile/modules/social_profile_organization_tag/css/social_profile_tag.scss
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
Labels: team: eci, type: bug

#2292 Issue #3208696 by nkoporec: I shouldn’t be able to share the 'Delete node' page
  modules/social_features/social_sharing/social_sharing.module
Labels: status: needs review, team: gravitiers

#2344 Issue #3214731 by nkoporec: As an authenticated user I should not see the revision log field when editing my profile
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
Labels: status: needs backport, status: needs review, team: gravitiers

#2358 Issue #3216202 by nkoporec: Missing translations for access permissions on flexible groups form
  translations.php
Labels: status: needs review, team: gravitiers, translations

#2432 Issue #3224859 by nkoporec: Flexible groups with visibility set to secret, should not show up in views results
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
Labels: status: needs backport, status: needs work, team: gravitiers, type: bug
