Repository goalgorilla/open_social, pull requests merged in 2021-06, with the labels that each got.

#2362 Issue #3208208 by vnech: Fix annoying error message
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
Labels: prio: medium, team: eci, type: bug

#2361 Fix PHP warning when add user to group directly
  modules/social_features/social_group/src/Element/SocialGroupEntityAutocomplete.php
Labels: prio: medium, status: needs backport, team: external, type: bug

#2298 Issue #3209766 by tBKoT: Improve access for unpublished content
  modules/custom/entity_access_by_field/src/EntityAccessHelper.php
  tests/behat/features/capabilities/contentmanagement/unpublished-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: medium, team: eci, type: bug

#2241 Issue #3198737: Ensure content within a group can be translated
  modules/social_features/social_group/social_group.module
Labels: needs: test, team: external, team: nucleus

#2359 [WIP] - Internal - Fix behat test
  modules/social_features/social_group/social_group.module
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: high, team: nucleus, type: test

#2354 Issue #3215464 by vnech: Add ability for CM+ to remove "Group Admin" role for members
  modules/social_features/social_group/config/install/group.type.closed_group.yml
  modules/social_features/social_group/config/install/group.type.open_group.yml
  modules/social_features/social_group/config/install/group.type.public_group.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.type.flexible_group.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
Labels: prio: medium, team: eci, type: bug

#2360 Issue #3216240 by SV: Improve visibility of tags in content creation
  modules/social_features/social_tagging/social_tagging.module
Labels: prio: medium, team: eci, type: feature request

#2375 Issue #3217678 by vnech: Remove group admins as recipient for sending message when a new member is added
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
Labels: prio: medium, team: eci, type: feature request

#2207 Update GraphQL module to 4.1
  composer.json
  modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
Labels: prio: high, status: needs review, team: shipsters, type: dependencies

#2365 Issue #3216573 by tBKoT: Fix notification issue for follow tag activity
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag_stream.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/ActivityContext/FollowTagActivityContext.php
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.module
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
  tests/behat/features/capabilities/follow-taxonomy/follow-tags.feature
Labels: prio: high, team: eci, type: bug

#2266 Issue #3204071 by rolki: Remove all deprecated things from the social_gdpr accordingly with the data_policy
  composer.json
  modules/custom/social_gdpr/config/optional/block.block.add_data_policy_revision.yml
  modules/custom/social_gdpr/config/optional/block.block.data_policy_page_title_block.yml
  modules/custom/social_gdpr/config/optional/block.block.socialblue_add_data_policy_revision.yml
  modules/custom/social_gdpr/config/optional/block.block.socialblue_data_policy_page_title_block.yml
  modules/custom/social_gdpr/social_gdpr.info.yml
  modules/custom/social_gdpr/social_gdpr.install
  modules/custom/social_gdpr/social_gdpr.links.task.yml
  modules/custom/social_gdpr/social_gdpr.module
  modules/custom/social_gdpr/social_gdpr.routing.yml
  modules/custom/social_gdpr/social_gdpr.services.yml
  modules/custom/social_gdpr/src/Controller/DataPolicy.php
  modules/custom/social_gdpr/src/Form/DataPolicyRevisionDeleteForm.php
  modules/custom/social_gdpr/src/Form/DataPolicyRevisionRevertForm.php
  modules/custom/social_gdpr/src/Form/DataPolicyRevisionRevertTranslationForm.php
  modules/custom/social_gdpr/src/Plugin/Block/AddDataPolicyRevision.php
  modules/custom/social_gdpr/src/Subscriber/Redirect.php
  modules/custom/social_gdpr/src/Subscriber/Route.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/gdpr/create-data-policy.feature
  tests/behat/features/capabilities/gdpr/data-policy-revisions.feature
  tests/behat/features/capabilities/gdpr/inform-block.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
Labels: prio: high, team: eci, type: code refactoring, type: feature request

#2373 [GraphQL] Move addMutationResolver into trait for schema extension
  modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
  modules/custom/social_graphql/src/GraphQL/StandardisedMutationSchemaTrait.php
  modules/custom/social_graphql/src/Plugin/GraphQL/SchemaExtension/SchemaExtensionPluginBase.php
  modules/social_features/social_comment/src/Plugin/GraphQL/SchemaExtension/CommentSchemaExtension.php
  modules/social_features/social_profile/src/Plugin/GraphQL/SchemaExtension/ProfileSchemaExtension.php
  modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php
Labels: prio: medium, status: needs review, type: code refactoring

#2381 Issue #3218656 by agami4: Content isn't centred on landing page translations page
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/page--node--landing-page.html.twig
Labels: team: eci, type: bug

#2309 Issue #3211565 by Ressinel: Sort users in Group view.
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.services.yml
  modules/social_features/social_profile/modules/social_profile_privacy/src/Service/SocialProfilePrivacyBatchHelper.php
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/social_profile.post_update.php
  modules/social_features/social_profile/social_profile.services.yml
  modules/social_features/social_profile/src/Plugin/views/field/ProfileEntitySortable.php
  modules/social_features/social_profile/src/SocialProfileNameService.php
  tests/behat/features/capabilities/profile/restricted-full-name.feature
Labels: blocked: commit cleanup, prio: medium, status: needs review, team: nucleus, type: feature request

#2382 Issue #3219037 by vnech: Add permission for SM to edit Data Policy translations
  modules/custom/social_gdpr/social_gdpr.install
Labels: prio: medium, team: eci, type: bug

#2370 Issue #3217219 by vnech: Set correct langcode when create a content in other then default language first
  modules/custom/social_language/modules/social_content_translation/social_content_translation.module
Labels: prio: high, team: eci, type: bug

#2369 Issue #3217132 by vnech: Translation support for "Flexible Group" group type
  modules/custom/social_language/modules/social_content_translation/config/install/social_content_translation.settings.yml
  modules/custom/social_language/modules/social_content_translation/social_content_translation.install
  modules/social_features/social_group/config/install/views.view.group_information.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_address.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_description.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_image.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_location.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8912.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.services.yml
  modules/social_features/social_group/modules/social_group_flexible_group/src/ContentTranslationDefaultsConfigOverride.php
Labels: prio: high, team: eci, type: feature request

#2379 Issue #3216884 by vnech: Improve translation support for "Event" content type
  modules/social_features/social_event/config/install/field.field.node.event.field_event_address.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_event_image.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_event_location.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_files.yml
  modules/social_features/social_event/config/install/views.view.event_enrollments.yml
  modules/social_features/social_event/config/install/views.view.event_manage_enrollment_requests.yml
  modules/social_features/social_event/config/install/views.view.events.yml
  modules/social_features/social_event/config/install/views.view.upcoming_events.yml
  modules/social_features/social_event/config/update/social_event_update_8919.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/views.view.manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/update/social_event_an_enroll_update_8005.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.install
  modules/social_features/social_event/modules/social_event_invite/config/install/views.view.event_manage_enrollment_invites.yml
  modules/social_features/social_event/modules/social_event_invite/config/install/views.view.user_event_invites.yml
  modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_8006.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_managers/config/install/views.view.event_manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_managers/config/update/social_event_managers_update_8006.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_group/config/install/views.view.group_events.yml
  modules/social_features/social_group/config/update/social_group_update_8907.yml
  modules/social_features/social_group/social_group.install
Labels: prio: medium, team: eci, type: bug, type: code refactoring

#2383 Issue #3219123 by Kingdutch: [GraphQL] Allow EntityConnectionQueryHelper to change sorting direction
  modules/custom/social_graphql/src/GraphQL/ConnectionQueryHelperBase.php
  modules/custom/social_graphql/src/GraphQL/ConnectionQueryHelperInterface.php
  modules/custom/social_graphql/src/GraphQL/EntityConnection.php
  modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/QueryComments.php
  modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/SocialCommentAttachments.php
  modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentAttachmentsQueryHelper.php
  modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentQueryHelper.php
  modules/social_features/social_user/src/GraphQL/QueryHelper/UserQueryHelper.php
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
Labels: prio: high, status: needs review, team: shipsters, type: feature request

#2385 Update ctools to 3.7
  composer.json
Labels: prio: critical, status: needs backport, team: nucleus, type: update

#2392 Issue #3211565 by Ressinel: Sort users in Group view (improvements).
  modules/social_features/social_profile/social_profile.post_update.php
  modules/social_features/social_profile/src/Plugin/views/field/ProfileEntitySortable.php
Labels: prio: medium, team: nucleus

#2355 Issue #3215978 by nkoporec: Administer social_footer settings permission is missing
  modules/social_features/social_footer/social_footer.permissions.yml
Labels: team: gravitiers, type: bug

#2391 Issue #3220277 by nkoporec: Fix the error message, when sending out emails to event enrollees.
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
Labels: status: needs backport, status: needs review, team: gravitiers, type: bug
