Repository goalgorilla/open_social, pull requests merged in 2021-05, with the labels that each got.

#2315 Create dependabot.yml
  .github/dependabot.yml
Labels: team: nucleus, type: feature request

#2325 Issue #3212793 by Kingdutch: Remove drupal/file_mdm dependency
  composer.json
Labels: prio: high, status: needs review, team: shipsters, type: update

#2294 Issue #3208745 by agami4: Update GIN theme to newer version
  composer.json
Labels: status: needs review, team: nucleus, type: dependencies

#2291 [Internal] Change link from getopensocial.com/services to Review Open Social on Capterra
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml
Labels: prio:low, team: external

#2312 Issue #3210685 by rolki: Add a query_access handler to the comment entity type
  modules/social_features/social_comment/config/schema/social_comment.schema.yml
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/src/Entity/Access/CommentQueryAccessHandler.php
  modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
  modules/social_features/social_core/social_core.info.yml
Labels: prio: high, status: needs review, team: eci, type: code refactoring

#2330 Issue #3212188 by agami4: Improve logos on the gin toolbar
  modules/custom/social_lets_connect/assets/css/toolbar.css
  modules/custom/social_lets_connect/assets/images/os-logo.svg
  modules/social_features/social_core/assets/css/admin-toolbar.css
  modules/social_features/social_core/assets/css/admin-toolbar.css.map
  modules/social_features/social_core/assets/css/admin-toolbar.scss
  modules/social_features/social_core/config/install/gin.settings.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.module
Labels: prio: high, status: needs review, team: nucleus, type: bug

#2333 Issue #3213804 by ronaldtebrake: Update ctools to 3.6
  composer.json
Labels: prio: high, team: nucleus, type: dependencies, type: update

#2307 Issue #3171966 - Update search_api to latest version to allow usage of current solr submodule
  composer.json
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/search_api.index.social_content.yml
  modules/social_features/social_search/config/install/search_api.index.social_groups.yml
  modules/social_features/social_search/config/install/search_api.index.social_users.yml
  modules/social_features/social_search/social_search.module
Labels: team: nucleus

#2283 Issue #3206847 by tBKoT: Allow event organizers to disable event enrolments
  modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity_comment.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.hero.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.search_index.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.small_teaser.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.teaser.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_event_enable_enrollment.yml
  modules/social_features/social_event/config/install/field.storage.node.field_event_enable_enrollment.yml
  modules/social_features/social_event/config/install/social_event.settings.yml
  modules/social_features/social_event/config/schema/social_event.schema.yml
  modules/social_features/social_event/config/static/field.field.node.event.field_event_enable_enrollment_8916.yml
  modules/social_features/social_event/config/static/field.storage.node.field_event_enable_enrollment_8916.yml
  modules/social_features/social_event/config/update/social_event_update_8917.yml
  modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteEnrollActionForm.php
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.post_update.php
  modules/social_features/social_event/social_event.services.yml
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  modules/social_features/social_event/src/Form/EventSettingsForm.php
  modules/social_features/social_event/src/Service/SocialEventEnrollService.php
Labels: prio: high, team: eci, type: feature request

#2271 Issue #3204322 by tBKoT: Allow flexible tagging structure for profiles tags
  modules/social_features/social_profile/config/install/social_profile.settings.yml
  modules/social_features/social_profile/config/install/taxonomy.vocabulary.profile_tag.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/social_profile.info.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/social_profile.links.menu.yml
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/social_profile.services.yml
  modules/social_features/social_profile/src/Form/SocialProfileSettingsForm.php
  modules/social_features/social_profile/src/Plugin/Field/FieldWidget/SocialProfileTagSplitWidget.php
  modules/social_features/social_profile/src/Plugin/views/filter/SocialSearchApiSplitProfileTerms.php
  modules/social_features/social_profile/src/SocialProfileTagService.php
  modules/social_features/social_profile/src/SocialProfileTagServiceInterface.php
  tests/behat/features/capabilities/profile/profile-tags.feature
Labels: prio: medium, team: eci, type: feature request

#2334 Issue #3214024 by agami4: Fix album popup with after update of the Gin theme
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
Labels: team: eci, type: bug

#2335 Issue #3214049 by chmez: As a LU I want to see all fields split by sections
  composer.json
  modules/social_features/social_core/social_core.module
Labels: prio: medium, team: eci, type: bug

#2346 Issue #3205376: Make sure mentions and background tasks are working in the notification center
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/administration/export-users.feature
  tests/behat/features/capabilities/administration/mail-users.feature
  tests/behat/features/capabilities/mention/mention-post.feature
Labels: prio: high, status: needs backport, status: needs review, team: nucleus, type: bug

#2332 Issue #3210685 by rolki: Add a query_access handler to the comment entity type
  modules/custom/social_graphql/social_graphql.install
  modules/social_features/social_comment/config/schema/social_comment.schema.yml
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/src/Entity/Access/CommentQueryAccessHandler.php
  modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
  modules/social_features/social_core/config/install/social_core.settings.yml
  modules/social_features/social_core/config/schema/social_core.schema.yml
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_core/social_core.install
Labels: prio: high, team: eci, type: feature request

#2285 Issue #3207791 by rolki: Implement basic comment querying in the Graph
  modules/custom/social_graphql/graphql/open_social.graphqls
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Entity/EntityDataProducerPluginBase.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Field/FieldRenderer.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Media/FileUrl.php
  modules/custom/social_graphql/src/Plugin/GraphQL/Schema/OpenSocialBaseSchema.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  modules/social_features/social_comment/config/schema/social_comment.schema.yml
  modules/social_features/social_comment/graphql/social_comment_schema_extension.base.graphqls
  modules/social_features/social_comment/graphql/social_comment_schema_extension.extension.graphqls
  modules/social_features/social_comment/social_comment.info.yml
  modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/QueryComments.php
  modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/SocialCommentAttachments.php
  modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentAttachmentsQueryHelper.php
  modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentQueryHelper.php
  modules/social_features/social_comment/src/Plugin/GraphQL/SchemaExtension/CommentSchemaExtension.php
  modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentTest.php
  modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentsTest.php
Labels: optional: review requested, prio: high, team: eci, type: feature request

#2353 Issue #3215409 by ronaldtebrake: update creation of email notifications on the advanced queue
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
  modules/custom/social_advanced_queue/social_advanced_queue.info.yml
  modules/custom/social_advanced_queue/social_advanced_queue.install
  modules/custom/social_advanced_queue/social_advanced_queue.module
  modules/custom/social_advanced_queue/src/Plugin/ActivitySend/EmailActivitySendAdvancedQueue.php
  modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/Action/SocialEventAnEnrollSendEmail.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
Labels: prio: high, team: nucleus, type: feature request

#2255 Issue #3202830 by sjoerdvandervis: Group creator that leaves group still receives welcome message
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
Labels: prio:low, status: needs backport, team: nucleus, type: bug

#2351 Issue #3215151 by SV: Display "Join" button for anonymous user on the public flexible groups
  modules/social_features/social_group/social_group.module
Labels: prio: high, team: eci, type: bug

#2348 Issue #3214990 by SV: Redirect user to the group if he is already a member of invited group
  modules/social_features/social_group/modules/social_group_invite/src/Controller/SocialGroupInvitationOperations.php
Labels: prio: high, team: eci, type: bug

#2336 Issue #3204850: Make sure SM / Admin can still visit flexible groups marked as secret
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: medium, status: needs backport, team: nucleus

#2350 Issue #3215132 by agami4: Fix gin toolbar settings
  modules/social_features/social_core/social_core.install
Labels: team: eci, team: nucleus, type: bug
