Repository goalgorilla/open_social, pull requests merged in 2021-12, with the labels that each got.

#2632 Issue #3252054 by Ressinel: Search all results should show correct information.
  modules/social_features/social_book/src/SocialBookConfigOverride.php
Labels: type: bug, status: needs review, prio: medium, team: nucleus

#2453 Issue #3232309 by navneet0693, ronaldtebrake, Ressinel, Kingdutch: Granular control over embedded content.
  composer.json
  modules/social_features/social_embed/assets/css/consent-placeholder.css
  modules/social_features/social_embed/assets/css/consent-placeholder.css.map
  modules/social_features/social_embed/assets/css/consent-placeholder.scss
  modules/social_features/social_embed/assets/icons/urlembed.png
  modules/social_features/social_embed/config/install/field.field.user.user.field_user_embed_content_consent.yml
  modules/social_features/social_embed/config/install/field.storage.user.field_user_embed_content_consent.yml
  modules/social_features/social_embed/config/install/social_embed.settings.yml
  modules/social_features/social_embed/config/schema/social_embed.schema.yml
  modules/social_features/social_embed/social_embed.info.yml
  modules/social_features/social_embed/social_embed.install
  modules/social_features/social_embed/social_embed.libraries.yml
  modules/social_features/social_embed/social_embed.links.menu.yml
  modules/social_features/social_embed/social_embed.module
  modules/social_features/social_embed/social_embed.permissions.yml
  modules/social_features/social_embed/social_embed.post_update.php
  modules/social_features/social_embed/social_embed.routing.yml
  modules/social_features/social_embed/social_embed.services.yml
  modules/social_features/social_embed/src/Controller/EmbedController.php
  modules/social_features/social_embed/src/Form/EmbedConsentForm.php
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlFilter.php
  modules/social_features/social_embed/src/Service/SocialEmbedHelper.php
  modules/social_features/social_embed/src/SocialEmbedConfigOverride.php
  modules/social_features/social_embed/tests/src/Kernel/SocialUserEmbedTest.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/embed/embed-consent.feature
  tests/behat/features/capabilities/embed/embed.feature
Labels: type: feature request, blocked: commit cleanup, status: needs review, prio: medium, team: nucleus

#2593 Issue #3248205 by nkoporec: Group managers should not be allowed to send invitations to users that are already part of the group
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
Labels: status: needs review, status: needs backport, team: gravitiers

#2645 Issue #3254082 - Update Drupal Core to 9.2.x
  .travis.yml
  .tugboat/composer.json
  composer.json
  modules/custom/activity_creator/src/ActivityListBuilder.php
  modules/custom/social_font/src/FontListBuilder.php
  modules/social_features/social_comment/src/SocialCommentBreadcrumbBuilder.php
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_event/src/EventEnrollmentListBuilder.php
  modules/social_features/social_group/src/Plugin/EntityReferenceSelection/SocialGroupSelection.php
  modules/social_features/social_post/social_post.admin.inc
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
  modules/social_features/social_topic/social_topic.module
  tests/composer.json
Labels: type: update, status: needs review, prio: critical, team: nucleus

#2641 [Internal] Improved defensive checks in ActivityDigestWorker queueworker.
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
Labels: type: code refactoring, status: needs review, prio: medium, team: nucleus

#2653 Issue #3254503 by nkoporec: iCal is not importing to Calendar (Mac OSX) if the event contains emojis
  modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php
Labels: type: bug, status: needs backport, team: gravitiers

#2649 Issue #3254114 by tbsiqueira: Wrong UuidInterface instance on SocialEmbedHelper
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
  modules/social_features/social_embed/src/Service/SocialEmbedHelper.php
Labels: status: needs work, team: nucleus

#2661 [Internal] - Fix PHPCS errors.
  phpstan-baseline.neon
Labels: status: needs review, prio: high, team: nucleus

#2654 3254530 | Removing deprecated calls on hook_file_download()
  .travis.yml
  composer.json
  modules/social_features/social_core/social_core.install
  modules/social_features/social_event/modules/social_event_enrolments_export/social_event_enrolments_export.module
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.module
  modules/social_features/social_group/modules/social_group_secret/src/EventSubscriber/SocialGroupSecretSubscriber.php
  modules/social_features/social_user_export/social_user_export.module
  phpstan-baseline.neon
  tests/composer.json
Labels: blocked: commit cleanup, status: needs review, team: nucleus

#2657 INTERNAL | Update data_policy to 2.0.0 for Drupal 9.2 compatibility
  composer.json
Labels: type: update, status: needs review, team: nucleus

#2664 [Internal] Remove un-required code.
  modules/social_features/social_core/social_core.module
  modules/social_features/social_tagging/social_tagging.module
Labels: type: code refactoring, prio: high, team: nucleus

#2622 Issue #3251374 by Ressinel: Rename topic type Discussions.
  modules/custom/social_demo/content/entity/topic.yml
  modules/custom/social_demo/developer/content/entity/topic.yml
  modules/custom/social_demo/eaa/content/entity/topic.yml
  modules/social_features/social_topic/social_topic.install
  tests/behat/features/capabilities/contentmanagement/node-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/embed/embed-consent.feature
  tests/behat/features/capabilities/embed/embed.feature
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  tests/behat/features/capabilities/group/group-mute-notify.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
  tests/behat/features/capabilities/notifications/notification-emails.feature
  tests/behat/features/capabilities/profile/click-avatar.feature
  tests/behat/features/capabilities/profile/restricted-full-name.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
  tests/behat/features/capabilities/sharing/share.feature
  tests/behat/features/capabilities/topic/newest-topics.feature
  tests/behat/features/capabilities/topic/topic-create.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
  tests/behat/features/capabilities/topic/topic-follow-content.feature
Labels: prio: medium, team: nucleus

#2650 Issue #3254196 by ribel: Fix mention link output to work with the installation under a subdirectory
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/custom/mentions/templates/mention-link.html.twig
Labels: type: bug, team: eci

#2624 Issue #3251540 by tBKoT: Allows anonymous users viewing comments
  modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_mentions/social_mentions.module
  modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostFormatter.php
Labels: team: eci, type: feature request, prio: high

#2668 [Internal] Update PHPStan.neon
  phpstan-baseline.neon
  phpstan.neon
Labels: prio: medium, team: nucleus

#2672 Issue #3222835 by curriedn, Ressinel: GroupRequestMembershipForm was using non-existing constant
  modules/custom/grequest/src/Form/GroupRequestMembershipForm.php
  phpstan-baseline.neon
Labels: type: bug, team: external, prio: medium

#2633 Issue #3246751 by milos.kroulik, Ressinel: Add extra check for Message entity.
  modules/custom/activity_creator/activity_creator.tokens.inc
  modules/custom/activity_logger/activity_logger.tokens.inc
  modules/custom/social_queue_storage/social_queue_storage.tokens.inc
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_content_report/social_content_report.tokens.inc
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
  modules/social_features/social_group/modules/social_group_request/social_group_request.tokens.inc
  modules/social_features/social_group/social_group.tokens.inc
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_mentions/social_mentions.tokens.inc
  modules/social_features/social_user/social_user.tokens.inc
Labels: type: bug, team: external, status: needs work, prio: medium

#2631 Issue #3252050 by nkoporec: Ajax error when exporting event enrollments
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.libraries.yml
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
Labels: type: bug, status: needs backport, team: gravitiers, team: nucleus

#2671 Issue #3255928 by tBKoT: Fix enity autocomplete when views is using
  modules/social_features/social_core/src/Entity/EntityAutocompleteMatcher.php
Labels: type: bug, team: eci, status: needs review, prio: medium

#2670 Issue #3255823 by SV: Hide "Private message" button if user doesn't have "create private messages thread" permission.
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, team: eci, prio: medium

#2665 Issue #3255434 by SV: Token [message:preview] includes not translatable node type string
  modules/social_features/social_activity/src/EmailTokenServices.php
Labels: type: bug, team: eci, status: needs backport, prio:low

#2523 Issue #3239372 by agami4: Add new colours to the colour theme settings
  composer.json
  modules/custom/improved_theme_settings/improved_theme_settings.install
Labels: team: eci, type: feature request, status: needs work, prio: critical
