Repository goalgorilla/open_social, pull requests merged in 2021-11, with the labels that each got.

#2545 Issue 3241569 by nachosalvador: Add setting to control magic login me…
  modules/custom/social_magic_login/config/install/social_magic_login.settings.yml
  modules/custom/social_magic_login/config/schema/social_magic_login.schema.yml
  modules/custom/social_magic_login/social_magic_login.install
  modules/custom/social_magic_login/src/Controller/MagicLoginController.php
Labels: status: needs review, prio: medium, team: gravitiers

#1881 Issue #3151112 by rolki: I wanna be able to use the latest version of Infinite Scroll
  composer.json
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  modules/social_features/social_topic/social_topic.module
Labels: team: eci, type: feature request, prio: medium, optional: review requested

#2571 Issue #3246407 by tBKoT: Check if parent term exist on the Follow Tag on the Landing Page
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
Labels: type: bug, team: eci, prio: high

#2540 Issue #3241316 by SV: Landing Page template applies to any node type when using it as 404 page
  modules/social_features/social_landing_page/social_landing_page.module
Labels: type: bug, team: eci, prio: medium

#2570 Issue #3246398 by tbsiqueira: Social Tag Settings not working on a new installation
  modules/social_features/social_tagging/config/install/social_tagging.settings.yml
  modules/social_features/social_tagging/config/schema/social_tagging.schema.yml
Labels: type: bug, status: needs backport, prio: medium, team: nucleus

#2577 Issue #3247237 by rolki: Custom content list block not working with Mysql 5.7 and ONLY_FULL_GROUP_BY
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: type: bug, team: eci, prio: high, optional: review requested

#2576 Issue #3247222 by ribel: Fix fatal error in activity tokens when related object doesn't exist
  modules/custom/activity_logger/activity_logger.tokens.inc
  modules/social_features/social_activity/social_activity.tokens.inc
Labels: type: bug, team: eci, prio: high, optional: review requested

#2569 Issue #3246384 by vnech: Move unapplied code from Album config override
  modules/social_features/social_post/modules/social_post_album/social_post_album.module
  modules/social_features/social_post/modules/social_post_album/social_post_album.services.yml
  modules/social_features/social_post/modules/social_post_album/src/SocialPostPhotoAlbumConfigOverride.php
Labels: type: bug, team: eci, prio: critical, optional: review requested

#2586 Issue #3247723 by tBKoT: Fix missing tags in edit form of Follow tag block
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  phpstan-baseline.neon
Labels: type: bug, team: eci, prio: high

#2594 Issue #3248383 by Ressinel: Open Social version 10.3.1 is not supported by PHP 7.3 - It works good with PHP 7.4
  modules/social_features/social_activity/src/EmailTokenServices.php
Labels: type: bug, status: needs review, prio: critical, team: nucleus

#2589 Issue #3247742 by tBKoT: Disallow to use unpublished content tags
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
  modules/social_features/social_tagging/src/Plugin/Block/SocialTagsBlock.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  phpstan-baseline.neon
Labels: type: bug, team: eci, prio: high, optional: review requested

#2591 Issue #3247896 by tBKoT: Fix errors with activity tokens when the related object does not exist
  modules/custom/activity_creator/activity_creator.tokens.inc
  modules/custom/activity_logger/activity_logger.tokens.inc
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
  modules/social_features/social_group/social_group.tokens.inc
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_mentions/social_mentions.tokens.inc
Labels: type: bug, team: eci, prio: critical

#2596 Issue #3248515 by SV: Comments do not load when there is unpublished item in the thread
  modules/social_features/social_like/social_like.module
Labels: type: bug, team: eci, prio: high

#2579 Issue #3247243 by agami4: Add collapse behaviour to the privacy settings block on the profile settings page
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
  modules/social_features/social_profile/modules/social_profile_privacy/assets/js/collapse.js
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.libraries.yml
  modules/social_features/social_profile/social_profile.module
Labels: team: eci, type: feature request, prio: medium

#2595 Issue #3248421 by SV: As LU+ I can not like any content
  composer.json
Labels: type: bug, team: eci, prio: high, optional: review requested

#2588 Issue #3247843 by nkoporec: Don't override the group types on search view if the filter is not active
  modules/social_features/social_search/social_search.module
Labels: team: gravitiers

#2585 Issue #3247700 by agami4: Add data-title attribute to the icon of the featured item
  modules/social_features/social_featured_items/templates/paragraph--featured-item--default.html.twig
Labels: type: bug, team: eci, prio: high

#2602 Issue #3248947: Added missing library for drupal/jquery_ui_touch_punch.
  composer.json
Labels: status: needs review, prio:low, type: dependencies, team: nucleus

#2601 Issue #3248515 by SV: Add attributes only for existing elements to fix voting
  modules/social_features/social_like/social_like.module
Labels: type: bug, team: eci, prio: high

#2598 Issue #3228303 by tBKoT: Use event type label instead of 'Event'
  modules/social_features/social_event/modules/social_event_type/social_event_type.module
Labels: type: bug, team: eci, prio: medium, optional: review requested

#2607 Issue #3249894 by navneet0693: Added patch on redirect module for allowing redirection when the interface language is different from content language.
  composer.json
Labels: status: needs backport, prio: medium, team: nucleus

#2609 Update patch for VBO module.
  composer.json
Labels: status: needs review, prio: medium, team: nucleus

#2539 Issue #3241260: Event Date pushes back one day when someone edits the all-day event
  modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity_comment.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.hero.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.search_index.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.small_teaser.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.teaser.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_event_all_day.yml
  modules/social_features/social_event/config/install/field.storage.node.field_event_all_day.yml
  modules/social_features/social_event/config/static/field.field.node.event.field_event_all_day_10310.yml
  modules/social_features/social_event/config/static/field.storage.node.field_event_all_day_10310.yml
  modules/social_features/social_event/config/update/social_event_update_10311.yml
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.post_update.php
  phpstan-baseline.neon
  tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
  tests/behat/features/capabilities/activity-stream/create_topic_event.feature
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
  tests/behat/features/capabilities/event-management/event-management.feature
  tests/behat/features/capabilities/event/all-day-timezone.feature
  tests/behat/features/capabilities/event/event-create.feature
  tests/behat/features/capabilities/event/eventenrollment.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  tests/behat/features/capabilities/like/like-create-event.feature
Labels: type: bug, type: code refactoring, team: eci, prio: high

#2606 Issue #3249659 by SV: Immediate mails sent to people who have settings on daily for the follow tag activity
  modules/custom/activity_logger/activity_logger.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag_stream.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.install
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
Labels: type: bug, team: eci, type: revert, prio: high

#2600 Issue #3248897 by agami4: Improve alignment comment block on the album popup for RTL layout
  modules/social_features/social_album/assets/css/social-album--post.css
  modules/social_features/social_album/assets/css/social-album--post.css.map
  modules/social_features/social_album/assets/css/social-album--post.scss
  modules/social_features/social_album/templates/social-album-post.html.twig
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_post/modules/social_post_album/templates/album-post-popup.html.twig
Labels: type: bug, team: eci, prio:low

#2603 Issue #3102720 by epapaniko, Ressinel: Search form submit redirects to the wrong path when the installation is under a subdirectory.
  modules/social_features/social_search/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_search/src/Form/SearchContentForm.php
  modules/social_features/social_search/src/Form/SearchHeroForm.php
Labels: type: bug, team: external, prio: medium

#2614 [Internal] - Remove unneeded code.
  modules/social_features/social_group/social_group.module
Labels: prio: high, team: nucleus

#2399 Issue #3222130 by nkoporec: Can't filter by content tags on /all-topics page
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: type: bug, status: needs review, team: gravitiers

#2620 [Internal] - Make sure we run our tests on the old theme.
  composer.json
  tests/behat/features/bootstrap/FeatureContext.php
Labels: status: needs review, prio: medium, team: nucleus

#2627 Issue #3251664 by SV: Intro text of the "followed" items is not translatable on the stream
  modules/social_features/social_follow_taxonomy/templates/activity--followed.html.twig
  modules/social_features/social_follow_taxonomy/templates/activity--node--followed.html.twig
Labels: type: bug, team: eci, status: needs backport, prio: medium, translations

#2623 Issue #3251371 by SV: Token [social_taxonomy:content_type] is not translatable
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
Labels: type: bug, team: eci, status: needs backport, prio: medium, translations

#2612 Issue #3250345 by tBKoT: Changes the process of converting a term name to a machine-readable name
  modules/social_features/social_tagging/social_tagging.module
Labels: type: bug, team: eci, prio: high, optional: review requested
