Repository goalgorilla/open_social, pull requests merged in 2021-01, with the labels that each got.

#2140 Issue #3178408 - Add group type field in flexible groups.
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.hero.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.small_teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.stream.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_type.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.group.field_group_type.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/taxonomy.vocabulary.group_type.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8908.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8909.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  themes/socialblue/socialblue.theme
  themes/socialblue/templates/group/group--teaser--sky.html.twig
Labels: status: needs review, team: nucleus, type: code refactoring, type: feature request

#2131 Issue #3188183 by aangel: Update Swiftmailer
  .travis.yml
  composer.json
  modules/social_features/social_swiftmail/src/Plugin/Mail/SocialSwiftMailer.php
Labels: prio: medium, status: needs review, team: external, team: nucleus, type: update

#1783 Issue #3123324 by SV: As a CM I want to filter items relevant to a specific tag on the stream block
  modules/social_features/social_activity/config/update/social_activity_update_8005.yml
  modules/social_features/social_activity/modules/social_activity_filter/config/install/social_activity_filter.settings.yml
  modules/social_features/social_activity/modules/social_activity_filter/config/schema/social_activity_filter.settings.yml
  modules/social_features/social_activity/modules/social_activity_filter/config/update/social_activity_filter_update_8002.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.info.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.install
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.installer_options.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.links.menu.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.module
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.permissions.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.routing.yml
  modules/social_features/social_activity/modules/social_activity_filter/src/Form/FilterSettingsForm.php
  modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/display/FilterBlock.php
  modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/filter/ActivityFilterTags.php
  modules/social_features/social_activity/social_activity.info.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_activity/src/SocialActivityLazyBuilder.php
  modules/social_features/social_comment/config/install/core.entity_view_display.comment.comment.activity_comment.yml
  modules/social_features/social_comment/config/update/social_comment_update_8803.yml
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.install
  modules/social_features/social_post/social_post.install
Labels: prio: high, status: needs work, team: eci, type: feature request

#1572 Issue #3087026 by mdeny: As a CM+ I want to be able set a icon for new topic and event types
  modules/social_features/social_event/modules/social_event_type/config/install/core.entity_form_display.taxonomy_term.event_types.default.yml
  modules/social_features/social_event/modules/social_event_type/config/install/field.field.taxonomy_term.event_types.field_event_type_icon.yml
  modules/social_features/social_event/modules/social_event_type/config/install/field.storage.taxonomy_term.field_event_type_icon.yml
  modules/social_features/social_event/modules/social_event_type/config/static/social_event_type_update_8902.yml
  modules/social_features/social_event/modules/social_event_type/css/social_event_type.admin.css
  modules/social_features/social_event/modules/social_event_type/css/social_event_type.admin.css.map
  modules/social_features/social_event/modules/social_event_type/css/social_event_type.admin.scss
  modules/social_features/social_event/modules/social_event_type/social_event_type.install
  modules/social_features/social_event/modules/social_event_type/social_event_type.libraries.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.module
  modules/social_features/social_topic/config/install/core.entity_form_display.taxonomy_term.topic_types.default.yml
  modules/social_features/social_topic/config/install/field.field.taxonomy_term.topic_types.field_topic_type_icon.yml
  modules/social_features/social_topic/config/install/field.storage.taxonomy_term.field_topic_type_icon.yml
  modules/social_features/social_topic/config/static/social_topic_update_8907.yml
  modules/social_features/social_topic/css/social_topic.admin.css
  modules/social_features/social_topic/css/social_topic.admin.css.map
  modules/social_features/social_topic/css/social_topic.admin.scss
  modules/social_features/social_topic/social_topic.install
  modules/social_features/social_topic/social_topic.libraries.yml
  modules/social_features/social_topic/social_topic.module
  themes/socialbase/assets/icons/icons.svg
  themes/socialbase/assets/images/icons/icon-blog.svg
  themes/socialbase/assets/images/icons/icon-discussion.svg
  themes/socialbase/assets/images/icons/icon-news.svg
  themes/socialbase/assets/images/icons/icon-resource.svg
  themes/socialbase/components/06-libraries/icons/source/icon-blog.svg
  themes/socialbase/components/06-libraries/icons/source/icon-discussion.svg
  themes/socialbase/components/06-libraries/icons/source/icon-news.svg
  themes/socialbase/components/06-libraries/icons/source/icon-resource.svg
  themes/socialbase/templates/node/event/node--event--teaser.html.twig
  themes/socialbase/templates/node/node--teaser.html.twig
Labels: prio: medium, status: needs work, team: eci, type: feature request

#2138 #3190319 by jochemvn: add 'featured' view mode for secret groups
  modules/social_features/social_group/modules/social_group_secret/modules/social_secret_group_featured/config/install/core.entity_view_display.group.secret_group.featured.yml
  modules/social_features/social_group/modules/social_group_secret/modules/social_secret_group_featured/social_secret_group_featured.info.yml
  modules/social_features/social_landing_page/social_landing_page.install
Labels: status: needs backport, status: needs review, team: gravitiers, type: bug

#2141 correct permission
  modules/custom/social_font/social_font.routing.yml
Labels: status: needs review, team: external, type: bug

#2082 Issue #3184175 by Kingdutch: move from bower to npm
  composer.json
  themes/socialblue/socialblue.libraries.yml
Labels: prio: medium, team: shipsters, type: dependencies

#1762 add [social_user:recepient] token
  modules/social_features/social_user/social_user.tokens.inc
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
Labels: team: external, type: feature request

#2143 Issue #3191206 by navneet0693: Updated weight of banner image field on profile.
  modules/social_features/social_profile/config/install/core.entity_form_display.profile.profile.default.yml
  modules/social_features/social_profile/config/update/social_profile_update_8803.yml
  modules/social_features/social_profile/social_profile.install
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2039 Issue #3173585 - Private content explore
  modules/custom/activity_viewer/activity_viewer.module
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityExploreVisibilityAccess.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
  modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
  modules/social_features/social_activity/config/update/social_activity_update_8806.yml
  modules/social_features/social_activity/social_activity.install
Labels: prio: high, status: needs backport, status: needs review, status: needs work, team: nucleus, type: bug, type: revert

#2146 Issue #3178408 - Add group settings to the hero on the detail page.
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.api.php
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.module
  themes/socialbase/assets/icons/icons.svg
  themes/socialbase/assets/images/icons/icon-cog.svg
  themes/socialbase/templates/group/group--teaser.html.twig
  themes/socialblue/templates/group/group--hero--sky.html.twig
Labels: prio: high, team: nucleus, type: bug

#2150 Issue #3186003 by navneet0693: DS-7506 Added new 'group_settings' fieldset to landing page content type.
  modules/social_features/social_landing_page/config/install/core.entity_form_display.node.landing_page.default.yml
  modules/social_features/social_landing_page/config/update/social_landing_page_update_8811.yml
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_landing_page/social_landing_page.module
Labels: action: testing day, prio: high, status: needs review, team: nucleus, type: feature request

#2152 Issue #3186003 - Update form submit label to use Create -> node type label
  modules/social_features/social_core/social_core.module
  tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
  tests/behat/features/capabilities/landing-page/landing-page-create.feature
  tests/behat/features/capabilities/page/page-create.feature
Labels: action: testing day

#2148 Issue #3186003 by navneet0693: Enable extension to declare list of nodes to be presented in new content form style.
  modules/social_features/social_book/social_book.module
  modules/social_features/social_core/social_core.api.php
  modules/social_features/social_core/social_core.module
  modules/social_features/social_landing_page/social_landing_page.module
  themes/socialblue/theme-settings.php
Labels: prio: high, team: nucleus, type: feature request

#2075 Issue #3183029 by chmez: As a SM I want to be able to limit profile visibility
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
  modules/social_features/social_profile/modules/social_profile_privacy/config/install/social_profile_privacy.settings.yml
  modules/social_features/social_profile/modules/social_profile_privacy/config/schema/social_profile_privacy.schema.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.install
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.libraries.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.services.yml
  modules/social_features/social_profile/modules/social_profile_privacy/src/Service/SocialProfilePrivacyHelper.php
  modules/social_features/social_profile/modules/social_profile_privacy/src/Service/SocialProfilePrivacyHelperInterface.php
  modules/social_features/social_profile/social_profile.module
  tests/behat/features/capabilities/profile/hide-profile-field-groups.feature
Labels: prio: high, team: eci, type: code refactoring, type: feature request

#1748 Issue #3117677 by makishima: Add Follow taxonomy functionality and Follow tag module
  modules/social_features/social_follow_taxonomy/assets/css/activity-followed.css
  modules/social_features/social_follow_taxonomy/assets/css/activity-followed.css.map
  modules/social_features/social_follow_taxonomy/assets/css/activity-followed.scss
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css.map
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.scss
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css.map
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.scss
  modules/social_features/social_follow_taxonomy/assets/js/follow-action_link.js
  modules/social_features/social_follow_taxonomy/assets/js/follow_popup.js
  modules/social_features/social_follow_taxonomy/config/install/flag.flag.follow_term.yml
  modules/social_features/social_follow_taxonomy/config/install/views.view.following_tags.yml
  modules/social_features/social_follow_taxonomy/images/star.svg
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.css
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.css.map
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.scss
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/block_content.type.follow_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_form_display.block_content.follow_tags.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_form_display.paragraph.tag.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_view_display.block_content.follow_tags.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/core.entity_view_display.paragraph.tag.default.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.field.block_content.follow_tags.field_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.field.paragraph.tag.field_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.storage.block_content.field_tags.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/field.storage.paragraph.field_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/config/install/paragraphs.paragraphs_type.tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.info.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.libraries.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.services.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/src/SocialFollowLandingPageOverrides.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/templates/block--inline-block--follow-tags.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/templates/paragraph--tag--default.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag_stream.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.update_node_following_tag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/optional/block.block.followtag.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.info.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.services.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/ActivityContext/FollowTagActivityContext.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/Block/FollowTagBlock.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagOverrides.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/search-follow-tag.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-nosplit.html.twig
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-split.html.twig
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.api.php
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.info.yml
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.install
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.libraries.yml
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.module
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
  modules/social_features/social_follow_taxonomy/templates/activity--followed.html.twig
  modules/social_features/social_follow_taxonomy/templates/activity--node--followed.html.twig
  modules/social_features/social_follow_taxonomy/templates/flag--follow-term.html.twig
Labels: blocked: release notes, prio: high, status: needs work, team: eci, type: feature request

#2127 Issue #3189637 by rolki: Add comments pagination to the LazyRenderer social service
  composer.json
  modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/social_comment.services.yml
  modules/social_features/social_comment/src/SocialCommentLazyRenderer.php
Labels: prio: medium, team: eci, type: bug, type: feature request

#2147 Issue #3192078 by laykin: Fatal errors after added custom content list block to a landing page
  modules/social_features/social_content_block/modules/social_content_block_landing_page/src/Service/SocialContentBlockLandingPageContentBuilder.php
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: prio: medium, team: eci, type: bug

#2142 Issue #3191063 by SV: Allow use a parent of categories in tag filter on search content page
  modules/social_features/social_tagging/config/install/social_tagging.settings.yml
  modules/social_features/social_tagging/config/schema/social_tagging.schema.yml
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
Labels: prio: medium, team: eci, type: bug, type: feature request

#2161 [GraphQL] pageInfo cursors are incorrect for `last` based queries
  modules/custom/social_graphql/src/GraphQL/EntityConnection.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  modules/social_features/social_profile/tests/src/Kernel/GraphQLUsersEndpointTest.php
  modules/social_features/social_user/tests/src/Kernel/GraphQLUsersEndpointTest.php
Labels: prio: medium, status: needs review, team: shipsters, type: bug

#2162 Issue #3192988 by Kingdutch: Expose primary platform color as CSS var…
  themes/socialblue/assets/css/tokens.css
  themes/socialblue/components/tokens.scss
  themes/socialblue/socialblue.libraries.yml
Labels: prio:low, team: shipsters

#2159 Internal - Update rebranding
  .travis.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.module
  modules/social_features/social_footer/config/optional/block.block.footer_powered.yml
  modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
  modules/social_features/social_swiftmail/social_swiftmail.module
  tests/behat/features/capabilities/event/all-day-timezone.feature
  themes/socialbase/templates/email/swiftmailer.html.twig
  themes/socialblue/favicon.ico
  themes/socialblue/logo.svg
  themes/socialblue/logo_email.png
Labels: prio: high, status: needs review, team: nucleus

#2145 Issue #3191823 by agami4: UI issues with popover and modal close button
  themes/socialbase/assets/css/modal.css
  themes/socialbase/assets/css/popover.css
  themes/socialbase/components/03-molecules/popover/popover.scss
  themes/socialbase/components/04-organisms/modal/modal.scss
Labels: team: eci, team: nucleus, type: bug

#2158 DS-7430-7439: Add updates for the radio buttons
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/components/02-atoms/form-controls/_radio-checkbox.scss
Labels: status: needs review, team: nucleus, type: feature request

#2157 DS-7429: Add updates for the field and fieldset labels
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/assets/css/form-elements.css
  themes/socialbase/assets/css/image-widget.css
  themes/socialbase/components/02-atoms/form-controls/_radio-checkbox.scss
  themes/socialbase/components/03-molecules/form-elements/form-elements.scss
  themes/socialbase/components/03-molecules/form-elements/image-widget/image-widget.scss
  themes/socialblue/assets/css/form-elements.css
  themes/socialblue/components/03-molecules/form-elements/form-elements.scss
Labels: status: needs review, team: nucleus, type: feature request

#2166 Issue #3172477 by nachosalvador: DS-7488 Modify add image button text.
  modules/social_features/social_post/modules/social_post_album/templates/image-widget--album.html.twig
Labels: action: testing day, prio: medium, status: needs review, team: gravitiers

#2165 Issue #3189520 by navneet0693: Add default logo to social footer & settings form for Site Manager.
  modules/social_features/social_footer/config/optional/block.block.footer_powered.yml
  modules/social_features/social_footer/config/static/block.block.socialblue_footer_powered.yml
  modules/social_features/social_footer/open_social_logo.png
  modules/social_features/social_footer/social_footer.info.yml
  modules/social_features/social_footer/social_footer.install
  modules/social_features/social_footer/social_footer.links.menu.yml
  modules/social_features/social_footer/social_footer.routing.yml
  modules/social_features/social_footer/src/Form/FooterSettingsForm.php
Labels: action: testing day, prio: medium, status: needs review, team: nucleus, type: feature request

#2171 Issue/319393 by navneet0693: Remove social_footer_powered block from gin header region.
  modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
  modules/social_features/social_footer/social_footer.install
  modules/social_features/social_footer/src/Plugin/Block/SocialFooterPoweredByBlock.php
Labels: action: testing day, prio: high, status: needs review, team: nucleus, type: bug

#2172 Issue#3177902 - Album content form design changes.
  modules/social_features/social_album/config/install/core.entity_form_display.node.album.default.yml
  modules/social_features/social_album/social_album.module
Labels: action: testing day, prio: medium, status: needs review, team: nucleus

#2170 DS-7517: Add styles for the access popover on the group page
  themes/socialbase/assets/icons/icons.svg
  themes/socialbase/assets/images/icons/icon-cog.svg
  themes/socialbase/components/06-libraries/icons/source/icon-cog.svg
  themes/socialblue/assets/css/hero--sky.css
  themes/socialblue/assets/css/hero.css
  themes/socialblue/assets/css/popover.css
  themes/socialblue/components/03-molecules/popover/icon-cog.svg
  themes/socialblue/components/03-molecules/popover/popover.scss
  themes/socialblue/components/04-organisms/hero/hero--sky.scss
  themes/socialblue/components/04-organisms/hero/hero.scss
Labels: status: needs review, team: nucleus, type: feature request

#2160 Issue #3192752 by rolki: Fix issue with incorrect number of comments
  themes/socialbase/socialbase.theme
Labels: prio: medium, team: eci, type: bug

#2164 Issue #3193329: Add updates for the radio buttons on the profile privacy settings
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
Labels: status: needs review, team: eci, type: bug

#2168 Issue #3177673 by chmez: As outsider you can create / see albums on closed group you're not a member off
  modules/social_features/social_album/config/install/views.view.albums.yml
  modules/social_features/social_album/config/update/social_album_update_8901.yml
  modules/social_features/social_album/social_album.install
  modules/social_features/social_album/src/Controller/SocialAlbumController.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumGroupAccess.php
  modules/social_features/social_album/src/Plugin/views/access/SocialAlbumUserAccess.php
Labels: action: testing day, blocked: maintainer input, prio: critical, team: eci, type: bug

#2175 YANG-4746: Improve follow tag dropdown and follow tag search block
  modules/social_features/social_follow_taxonomy/assets/css/.sass-cache/519f5ea7b2a3ca03477ef20e66da86fb42ae3784/paragraph_tag.scssc
  modules/social_features/social_follow_taxonomy/assets/css/.sass-cache/519f5ea7b2a3ca03477ef20e66da86fb42ae3784/social_follow_taxonomy.scssc
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css.map
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.scss
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css.map
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.scss
  modules/social_features/social_follow_taxonomy/templates/flag--follow-term.html.twig
Labels: action: testing day, team: eci, type: bug

#2173 YANG-4717 by tBKoT: Add ability to follow a parent tag and improve star icon appearing
  modules/social_features/social_follow_taxonomy/assets/js/follow_popup.js
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: action: testing day, team: eci, type: bug

#2180 Require minimum 14.5.0 of webonyx/graphql-php
  composer.json
Labels: prio: high, status: needs review, team: shipsters, type: dependencies

#2153 Issue #3192493 by sjoerdvandervis: Canonical URL for flexible group points to stream
  modules/social_features/social_group/social_group.module
  themes/socialblue/templates/group/group--statistic.html.twig
Labels: prio: medium, status: needs backport, team: nucleus, type: bug

#2181 Issue #3178408 by nachosalvador, robertragas, navneet0693: As a CM+ I want to be able set a icon for new group types.
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css.map
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.scss
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.taxonomy_term.group_type.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.taxonomy_term.group_type.field_group_type_icon.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.taxonomy_term.field_group_type_icon.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8910.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.module
  themes/socialbase/templates/group/group--teaser.html.twig
  themes/socialblue/templates/group/group--teaser--sky.html.twig
Labels: action: testing day, prio: medium, status: needs review, team: nucleus, type: feature request

#2183 Issue #3191632 by Kingdutch: [GraphQL] Current cursor support is not …
  modules/custom/social_graphql/src/GraphQL/ConnectionQueryHelperInterface.php
  modules/custom/social_graphql/src/GraphQL/EntityConnection.php
  modules/custom/social_graphql/src/Wrappers/Cursor.php
  modules/custom/social_graphql/src/Wrappers/Edge.php
  modules/custom/social_graphql/src/Wrappers/EdgeInterface.php
  modules/custom/social_graphql/src/Wrappers/EntityEdge.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  modules/social_features/social_user/src/GraphQL/QueryHelper/UserQueryHelper.php
Labels: prio: medium, status: needs review, team: shipsters, type: bug

#2185 [GraphQL] Improve nested pagination and sorting tests
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
Labels: prio: medium, status: needs review, team: shipsters, type: code refactoring

#2194 Issue #3194938 by Kingdutch: [GraphQL] As a developer I want insight …
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.info.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.links.task.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.routing.yml
  modules/custom/social_graphql/modules/social_graphql_devel/social_graphql_devel.services.yml
  modules/custom/social_graphql/modules/social_graphql_devel/src/Controller/ValidationController.php
  modules/custom/social_graphql/modules/social_graphql_devel/src/GraphQL/Validator.php
  modules/custom/social_graphql/modules/social_graphql_devel/src/GraphQL/ValidatorInterface.php
  modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
Labels: prio: medium, status: needs review, team: shipsters, type: feature request

#2196 Remove unimplemented GraphQL schema definitions
  modules/custom/social_graphql/graphql/open_social.graphqls
  modules/custom/social_graphql/modules/social_graphql_devel/src/Controller/ValidationController.php
  modules/social_features/social_profile/graphql/social_profile_schema_extension.base.graphqls
  modules/social_features/social_profile/src/Plugin/GraphQL/SchemaExtension/ProfileSchemaExtension.php
  modules/social_features/social_user/graphql/social_user_schema_extension.base.graphqls
Labels: prio:low, team: shipsters, type: code refactoring

#2174 Issue #3177673 by chmez: WSOD when commenting on an album in a group
  modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
  modules/social_features/social_album/social_album.install
  modules/social_features/social_album/social_album.module
  modules/social_features/social_post/modules/social_post_album/social_post_album.module
  modules/social_features/social_post/modules/social_post_album/social_post_album.services.yml
  modules/social_features/social_post/modules/social_post_album/src/Controller/SocialPostAlbumAjaxCommentsController.php
  modules/social_features/social_post/modules/social_post_album/src/Routing/RouteSubscriber.php
Labels: action: testing day, prio: critical, team: eci, type: bug

#2190 Issue #3172477 by chmez: Reporting an post album renders the pop-up full screen
  modules/social_features/social_album/config/install/views.view.albums.yml
  modules/social_features/social_album/config/update/social_album_update_8902.yml
  modules/social_features/social_album/social_album.install
  modules/social_features/social_content_report/social_content_report.module
  modules/social_features/social_content_report/src/ContentReportService.php
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_post/modules/social_post_album/social_post_album.module
  modules/social_features/social_post/modules/social_post_album/templates/field--post--type--image--album.html.twig
Labels: action: testing day, prio: medium, team: eci, type: bug

#2192 Issue #3177673 by chmez: Double title when adding album to group
  modules/social_features/social_album/social_album.install
Labels: action: testing day, prio: medium, team: eci, type: bug

#2169 DS-7450: Add general styles for the popover
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css.map
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.scss
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.css.map
  modules/social_features/social_group/modules/social_group_flexible_group/assets/css/admin.scss
  themes/socialbase/assets/css/form-controls.css
  themes/socialbase/components/02-atoms/form-controls/_radio-checkbox.scss
  themes/socialblue/assets/css/popover.css
  themes/socialblue/components/03-molecules/popover/popover.scss
Labels: team: nucleus, type: feature request

#1640 Follow content types are never actually checked
  modules/social_features/social_follow_content/social_follow_content.module
Labels: prio: medium, team: external, type: bug

#2177 Issue #3123324 by SV: Set delta of multiple form elements.
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.install
  modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/display/FilterBlock.php
Labels: action: testing day, prio:low, team: eci, type: bug

#2186 YANG-4838 by tBKoT: Issue with non-existent field 'field_event_type_icon'
  modules/social_features/social_event/modules/social_event_type/social_event_type.module
Labels: action: testing day, type: bug

#2198 Issue #3177902 by chmez: Placeholder text of post form should reflect you can add multiple photos
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.default.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.group.yml
  modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_form_display.post.photo.profile.yml
  modules/social_features/social_post/modules/social_post_photo/config/update/social_post_photo_update_8901.yml
  modules/social_features/social_post/modules/social_post_photo/js/post-widget.js
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.install
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.module
  tests/behat/features/capabilities/post/post-photo-create.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
Labels: action: testing day, prio: medium, status: needs review, team: eci, type: bug

#2197 Issue #3195069 by navneet0693: Link account display name in account header block to user profile page.
  modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
Labels: action: testing day, prio: medium, status: needs review, team: nucleus, type: feature request

#2199 Issue #3195131 by navneet0693: Remove status messages from image_widget_crop module.
  modules/social_features/social_core/social_core.module
Labels: prio: medium, status: needs review, team: nucleus, type: feature request

#2191 Issue #3187257 by navneet0693: Update the size of thumbnails of files & images on content forms
  modules/social_features/social_core/config/install/image.style.social_file_thumbnails.yml
  modules/social_features/social_core/config/static/image.style.social_file_thumbnails_8908.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
  modules/social_features/social_event/config/static/core.entity_view_display.node.event.default_8915.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_page/config/install/core.entity_view_display.node.page.default.yml
  modules/social_features/social_page/config/static/core.entity_view_display.node.page.default_8907.yml
  modules/social_features/social_page/social_page.install
  modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.default.yml
  modules/social_features/social_topic/config/static/core.entity_view_display.node.topic.default_8909.yml
  modules/social_features/social_topic/social_topic.install
  themes/socialbase/socialbase.theme
  themes/socialbase/templates/node/image-formatter--node--field-files.html.twig
Labels: prio: medium, status: needs review, team: nucleus, type: feature request
