Repository goalgorilla/open_social, pull requests merged in 2021-04, with the labels that each got.

#2280 Issue #3203225: revert the package name to goalgorilla/open_social and use an updated travis config
  .travis.yml
  composer.json
Labels: prio: critical, status: needs review, team: shipsters, type: revert

#2282 Issue #3200113 by rolki: Enable visibility states only for the flexible group
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
Labels: prio: medium, team: eci, type: bug

#2265 Issue #3203940 by agami4: Improve inline styles for the `input-group-addon` element and remove extra files and styles from social_event module
  modules/custom/improved_theme_settings/improved_theme_settings.module
  modules/social_features/social_event/assets/css/social-event--admin.css
  modules/social_features/social_event/assets/css/social-event--admin.css.map
  modules/social_features/social_event/assets/css/social-event--admin.scss
  modules/social_features/social_event/social_event.libraries.yml
  modules/social_features/social_event/social_event.module
Labels: team: eci, type: feature request

#2268 Issue #3197794 by tBKoT: Fix regression on activity stream
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
Labels: prio: high, team: eci, type: bug

#2275 Issue #3205805 by ribel: Add request event enrollment message template to email notification settings
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
Labels: prio: medium, team: eci, type: bug

#2251 Issue #3201678 by chmez: As a user I want to be able to provide the details about my nationality
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.field.profile.profile.field_profile_nationality.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/field.storage.profile.field_profile_nationality.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/social_profile_fields.settings.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/taxonomy.vocabulary.nationality.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/static/field.field.profile.profile.field_profile_nationality_8003.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/static/field.storage.profile.field_profile_nationality_8003.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/static/taxonomy.vocabulary.nationality_8003.yml
  modules/social_features/social_profile/modules/social_profile_fields/content/nationalities.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
  modules/social_features/social_profile/modules/social_profile_fields/templates/field--field-profile-nationality--sky.html.twig
  modules/social_features/social_profile/modules/social_profile_fields/templates/field--field-profile-nationality.html.twig
Labels: prio: medium, team: eci, type: feature request

#2288 Issue #3208055 by Kingdutch: [GraphQL] Provide UUIDv4 scalar type
  modules/custom/social_graphql/graphql/open_social.graphqls
  modules/custom/social_graphql/src/Wrappers/InputBase.php
Labels: prio: medium, status: needs review, team: shipsters, type: feature request

#2272 Issue #3205376 - The activity notification filter for follow taxonomy filters out content related to group_content / event_enrollment
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
Labels: prio: high, status: needs backport, team: nucleus, type: bug

#2287 Issue #3207983 by agami4: Increase min-height of the subtitle
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
Labels: team: eci, type: bug

#2256 Issue #3208583: Optimize Email notifications work flow for direct emails.
  modules/custom/activity_creator/src/Entity/Activity.php
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.routing.yml
  modules/custom/activity_send/modules/activity_send_email/src/Controller/ActivitySendEmailController.php
  modules/custom/activity_send/modules/activity_send_email/src/EmailFrequencyBase.php
  modules/custom/activity_send/modules/activity_send_email/src/EmailFrequencyInterface.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivityDestination/EmailActivityDestination.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/None.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/custom/activity_send/src/Plugin/SendActivityDestinationBase.php
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/social_event.module
Labels: blocked: drupal.org ticket, prio: high, status: needs work, team: nucleus, type: code refactoring, type: performance

#2296 Issue #3195082 by Kingdutch: [GraphQL] Use dependency injection for e…
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Entity/EntityDataProducerPluginBase.php
  modules/social_features/social_user/src/GraphQL/QueryHelper/UserQueryHelper.php
  modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
Labels: prio:low, status: needs review, team: shipsters, type: code refactoring

#2290 Issue #3203750 by robertragas: set max height to the photo album pop-…
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
Labels: status: needs backport, team: gravitiers

#2297 Issue #3209694 by Kingdutch: [GraphQL] PayloadInterface return type a…
  modules/custom/social_graphql/src/GraphQL/Payload/PayloadInterface.php
Labels: prio:low, team: shipsters, type: bug

#2293 Issue #3208734 by vnech: Update form display configuration for Public, Open, Closed and Secret group types
  modules/social_features/social_group/config/install/core.entity_form_display.group.closed_group.default.yml
  modules/social_features/social_group/config/install/core.entity_form_display.group.open_group.default.yml
  modules/social_features/social_group/config/install/core.entity_form_display.group.public_group.default.yml
  modules/social_features/social_group/config/update/social_group_update_8905.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_form_display.group.secret_group.default.yml
  modules/social_features/social_group/modules/social_group_secret/config/update/social_group_secret_update_8901.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
  modules/social_features/social_group/social_group.install
Labels: prio: medium, team: eci, type: bug

#2286 Issue #3207801 by vnech: Display error messages (if exist) on Ajax Comments
  modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
Labels: prio: medium, team: eci, type: bug

#2284 Issue #3207259 by chmez: Pagination doesn't work for AJAX comments on topic page
  modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  modules/custom/social_ajax_comments/social_ajax_comments.module
  modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
  tests/behat/features/capabilities/comment/comment-ajax.feature
Labels: action: testing day, prio: high, team: eci, type: bug

#2303 [Internal] - Add extra cron run statement for fixing test
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
Labels: team: nucleus, type: bug

#2270 Issue #3204850 by rolki: Handling the visibility of a the about / members tab
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
Labels: optional: review requested, team: eci, type: bug

#2305 Issue #3210690 by agami4: Improve album teasers
  modules/social_features/social_album/assets/css/social-album--teaser.css
  modules/social_features/social_album/assets/css/social-album--teaser.css.map
  modules/social_features/social_album/assets/css/social-album--teaser.scss
Labels: prio: medium, status: needs review, team: nucleus, type: bug

#2302 Issue #3210411 by chmez: When visiting and clicking on a notification in the Notification Center it does not go away
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_creator/src/ActivityNotifications.php
Labels: prio: medium, team: eci, type: bug

#2304 Issue #3210686 by chmez: As a SM I want to be able to export the details about user nationality
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/UserExportPlugin/UserNationality.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsHelper.php
Labels: prio: medium, team: eci, type: feature request
