Repository goalgorilla/open_social, pull requests merged in 2021-09, with the labels that each got.

#2337 Issue #3214317 by nkoporec: As a site manager I want to preview the alternative frontpage for anonymous users
  modules/custom/alternative_frontpage/alternative_frontpage.services.yml
  modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
  phpstan-baseline.neon
Labels: status: needs backport, team: gravitiers

#2425 Issue #3224512 by Ressinel: Update the Dynamic Entity Reference module from 1.7 to 1.12
  composer.json
Labels: type: update, status: needs review, prio: medium, type: dependencies, team: nucleus

#2483 Internal - Fix PHPStan error
  modules/social_features/social_core/src/InviteService.php
Labels: prio: high, team: nucleus

#2482 Issue #3230885 by vnech: Automate translation fields definitions updates
  modules/custom/social_language/social_language.module
Labels: type: bug, team: eci, prio: medium

#2313 Issue #3212327 by nkoporec: Implement AND condition when filtering with multiple terms
  modules/social_features/social_tagging/config/install/social_tagging.settings.yml
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
Labels: status: needs backport, team: gravitiers

#2357 Issue #3215146 by Ressinel: As a LU I want to be able to mute and unmute Group notifications.
  modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/Service/ConfigurationsService.php
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
  modules/social_features/social_group/config/install/core.entity_view_display.group.closed_group.default.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.closed_group.hero.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.closed_group.small_teaser.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.closed_group.stream.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.closed_group.teaser.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.open_group.default.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.open_group.hero.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.open_group.small_teaser.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.open_group.stream.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.open_group.teaser.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.public_group.default.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.public_group.hero.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.public_group.small_teaser.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.public_group.stream.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group.public_group.teaser.yml
  modules/social_features/social_group/config/install/flag.flag.mute_group_notifications.yml
  modules/social_features/social_group/config/install/views.view.groups.yml
  modules/social_features/social_group/config/optional/block.block.exposed_form_groups_page_user_groups.yml
  modules/social_features/social_group/config/static/block.block.exposed_form_groups_page_user_groups_10306.yml
  modules/social_features/social_group/config/static/flag.flag.mute_group_notifications_10303.yml
  modules/social_features/social_group/config/update/social_group_update_10305.yml
  modules/social_features/social_group/config/update/social_group_update_10307.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.hero.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.small_teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.stream.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.teaser.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_10302.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_group/social_group.info.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/GroupMuteNotify.php
  modules/social_features/social_group/templates/flag--mute-group-notifications.html.twig
  modules/social_features/social_like/src/Plugin/ActivityContext/VoteActivityContext.php
  modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php
  tests/behat/features/capabilities/group/group-mute-notify.feature
Labels: type: feature request, blocked: commit cleanup, prio: medium, team: nucleus

#2485 Issue #3231551 by Kingdutch, ronaldtebrake: Do not install `page_cache` by default
  social.installer_options_list.yml
Labels: status: needs review, type: performance, prio: medium, team: shipsters

#2444 Issue #3225497 by Ressinel: Update the Lazy-load module from 2.0 to 3.10
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2437 Issue #3225295 by Ressinel: Update the Redirect 403 to User Login module from 1.1 to 2.1.0
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2421 Issue #3224268 by Ressinel: Update the Block field module from 1.0-alpha8 to 1.0-rc1
  composer.json
  modules/social_features/social_content_block/src/SocialContentBlockOverride.php
  modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_reference.yml
  modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_reference_secondary.yml
  modules/social_features/social_landing_page/config/update/social_landing_page_update_10303.yml
  modules/social_features/social_landing_page/social_landing_page.install
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2300 Issue #3007303 by vnech: Cross-posting nodes in multiple groups
  modules/custom/activity_basics/src/Plugin/ActivityContext/CommunityActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/ProfileActivityContext.php
  modules/custom/activity_creator/activity.page.inc
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
  modules/custom/entity_access_by_field/src/EntityAccessHelper.php
  modules/custom/entity_access_by_field/tests/src/Unit/EntityAccessTest.php
  modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
  modules/social_features/social_activity/config/install/message.template.create_event_gc.yml
  modules/social_features/social_activity/config/install/message.template.create_event_group.yml
  modules/social_features/social_activity/config/install/message.template.create_topic_gc.yml
  modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
  modules/social_features/social_activity/config/install/message.template.moved_content_between_groups.yml
  modules/social_features/social_activity/config/static/message.template.create_event_gc_10302.yml
  modules/social_features/social_activity/config/static/message.template.create_topic_gc_10302.yml
  modules/social_features/social_activity/config/update/social_activity_update_10302.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_activity/src/Plugin/ActivityEntityCondition/GroupContentSingleActivityEntityCondition.php
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.closed_group-group_node-event.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.closed_group-group_node-topic.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.open_group-group_node-event.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.open_group-group_node-topic.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.public_group-group_node-event.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_display.group_content.public_group-group_node-topic.activity.yml
  modules/social_features/social_group/config/install/core.entity_view_mode.group_content.activity.yml
  modules/social_features/social_group/config/install/social_group.settings.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.closed_group-group_node-event.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.closed_group-group_node-topic.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.open_group-group_node-event.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.open_group-group_node-topic.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.public_group-group_node-event.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_display.group_content.public_group-group_node-topic.activity_10308.yml
  modules/social_features/social_group/config/static/core.entity_view_mode.group_content.activity_10308.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group_content.flexible_group-group_node-event.activity.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group_content.flexible_group-group_node-topic.activity.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/static/core.entity_view_display.group_content.flexible_group-group_node-event.activity_10303.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/static/core.entity_view_display.group_content.flexible_group-group_node-topic.activity_10303.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-event.activity.yml
  modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_view_display.group_content.secret_group-group_node-topic.activity.yml
  modules/social_features/social_group/modules/social_group_secret/config/static/core.entity_view_display.group_content.secret_group-group_node-event.activity_10301.yml
  modules/social_features/social_group/modules/social_group_secret/config/static/core.entity_view_display.group_content.secret_group-group_node-topic.activity_10301.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
  modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.info.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.permissions.yml
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/CrossPostingService.php
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  modules/social_features/social_group/src/SocialGroupHelperService.php
  phpstan-baseline.neon
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-invite-members.feature
Labels: team: eci, type: feature request, prio: high

#2446 Issue #3225521 by Ressinel: Update the Update helper module from 1.3 to 2.0.0
  composer.json
Labels: type: update, prio: medium, type: dependencies, team: nucleus

#2499 Issue #3007303 by Ressinel: Fix issue with group post notifications.
  modules/social_features/social_activity/src/Plugin/ActivityEntityCondition/GroupContentSingleActivityEntityCondition.php
Labels: type: bug, prio: high, team: nucleus

#2498 Issue #3232812 - Add core version requirements in all info.yml files of all modules in Open Social and remove the old core: key.
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.info.yml
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.info.yml
  modules/custom/social_font/social_font.info.yml
  modules/custom/social_gdpr/social_gdpr.info.yml
  modules/custom/social_graphql/social_graphql.info.yml
  modules/custom/social_language/modules/social_content_translation/social_content_translation.info.yml
  modules/custom/social_language/social_language.info.yml
  modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.info.yml
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.info.yml
  modules/custom/social_lets_connect/modules/social_lets_connect_usage/social_lets_connect_usage.info.yml
  modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.info.yml
  modules/social_features/social_album/social_album.info.yml
  modules/social_features/social_book/modules/social_book_featured/social_book_featured.info.yml
  modules/social_features/social_branding/social_branding.info.yml
  modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.info.yml
  modules/social_features/social_content_block/modules/social_book_content_block/social_book_content_block.info.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/social_content_block_landing_page.info.yml
  modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.info.yml
  modules/social_features/social_content_block/modules/social_group_content_block/social_group_content_block.info.yml
  modules/social_features/social_content_block/modules/social_page_content_block/social_page_content_block.info.yml
  modules/social_features/social_content_report/config/install/views.view.report_overview.yml
  modules/social_features/social_editor/social_editor.info.yml
  modules/social_features/social_embed/social_embed.info.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/views.view.manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.info.yml
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.info.yml
  modules/social_features/social_event/modules/social_event_enrolments_export/social_event_enrolments_export.info.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.info.yml
  modules/social_features/social_event/modules/social_event_managers/config/install/views.view.managers.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.info.yml
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.info.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.info.yml
  modules/social_features/social_event/social_event.info.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_content_reference.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_group_reference.yml
  modules/social_features/social_featured_content/config/install/views.view.featured_profile_reference.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.info.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.info.yml
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.info.yml
  modules/social_features/social_footer/social_footer.info.yml
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.info.yml
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_featured/social_flexible_group_featured.info.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.info.yml
  modules/social_features/social_group/modules/social_group_gvbo/social_group_gvbo.info.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.info.yml
  modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.info.yml
  modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.info.yml
  modules/social_features/social_group/modules/social_group_request/social_group_request.info.yml
  modules/social_features/social_group/modules/social_group_secret/modules/social_secret_group_featured/social_secret_group_featured.info.yml
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.info.yml
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.info.yml
  modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
  modules/social_features/social_post/modules/social_post_album/social_post_album.info.yml
  modules/social_features/social_post/modules/social_post_photo/social_post_photo.info.yml
  modules/social_features/social_private_message/config/install/views.view.inbox.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.info.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.info.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.info.yml
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.info.yml
Labels: type: update, team: nucleus

#2484 Issue #3179167 by agami4: Add and improve title on the svg icons and …
  modules/social_features/social_featured_content/templates/group--featured.html.twig
  modules/social_features/social_featured_content/templates/node--event--featured.html.twig
  modules/social_features/social_featured_content/templates/node--featured.html.twig
Labels: type: bug, status: needs backport, prio: medium, team: nucleus

#2490 Issue #3231998 by Ressinel: Add tests covering for group activities.
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
Labels: status: needs backport, prio: high, team: nucleus, type: test

#2506 Revert "Issue #3232350 by rolki: Not possible to add new images to the existing album from the stream page"
  modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
Labels: team: eci, type: revert, status: needs backport

#2505 Issue #3233546 by agami4: Content on add new landing page translation has no wrapper
  modules/social_features/social_landing_page/social_landing_page.module
Labels: type: bug, team: eci

#2486 Issue #3231572 by tBKoT: Fix CM+ link view access
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/src/Plugin/Validation/Constraint/SocialAnLinkAccess.php
  modules/social_features/social_landing_page/src/Plugin/Validation/Constraint/SocialAnLinkAccessValidator.php
Labels: type: bug, team: eci, status: needs backport, prio: medium

#2509 Uninstall `social_demo` in Tugboat after setup
  .tugboat/config.yml
Labels: status: needs review, team: shipsters

#2458 Issue #3227356 by Ressinel: Remove the unnecessary langcode filter from events enrollments views.
  modules/social_features/social_event/config/install/views.view.event_enrollments.yml
  modules/social_features/social_event/config/install/views.view.event_manage_enrollment_requests.yml
  modules/social_features/social_event/config/update/social_event_update_10305.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/install/views.view.manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_an_enroll/config/update/social_event_an_enroll_update_10201.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.install
  modules/social_features/social_event/modules/social_event_invite/config/install/views.view.event_manage_enrollment_invites.yml
  modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_10201.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_managers/config/install/views.view.event_manage_enrollments.yml
  modules/social_features/social_event/modules/social_event_managers/config/update/social_event_managers_update_10201.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
  modules/social_features/social_event/social_event.install
  tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
  tests/behat/features/capabilities/private-message/create-private-message.feature
Labels: type: bug, blocked: commit cleanup, prio: high, team: nucleus

#2500 Issue #3232875: The Nodes tab should not be among other group tabs
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: eci, status: needs backport, prio: medium

#2513 Issue #3227356 by navneet0693,ronaldtebrake,Ressinel: Changed the update hook numbers to 10301.
  modules/social_features/social_event/modules/social_event_an_enroll/config/update/social_event_an_enroll_update_10301.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.install
  modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_10301.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_managers/config/update/social_event_managers_update_10301.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
Labels: type: code refactoring, status: needs backport, prio: high, team: nucleus

#2510 [Internal] - Remove unnecessary configurations service.
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/Service/ConfigurationsService.php
  modules/social_features/social_group/social_group.install
Labels: type: code refactoring, prio: medium, team: nucleus

#2512 Fix coding standards where time permits
  composer.json
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
  modules/custom/activity_viewer/src/Plugin/views/argument/ActivityProfileArgument.php
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  modules/custom/entity_access_by_field/src/Plugin/search_api/processor/EntityAccessByField.php
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/custom/mentions/src/Plugin/Mentions/Entity.php
  modules/custom/social_demo/src/DemoGroup.php
  modules/custom/social_gdpr/social_gdpr.module
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionEdges.php
  modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionPageInfo.php
  modules/custom/social_language/modules/social_content_translation/social_content_translation.install
  modules/custom/social_language/social_language.module
  modules/custom/social_language/src/Routing/RouteSubscriber.php
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_content_block/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_core/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.install
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/Action/ExportAllEnrolments.php
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_event/src/Form/EnrollActionForm.php
  modules/social_features/social_event/src/Form/EventSettingsForm.php
  modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/EventManagers.php
  modules/social_features/social_featured_content/social_featured_content.install
  modules/social_features/social_featured_content/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_featured_items/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/Plugin/ActivityContext/FollowTagActivityContext.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupJoinPermissionAccessCheck.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/FlexibleGroupContentVisibilityUpdate.php
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
  modules/social_features/social_group/src/GroupContentVisibilityUpdate.php
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  modules/social_features/social_group/src/SocialGroupHero.php
  modules/social_features/social_post/src/Form/PostForm.php
  modules/social_features/social_search/social_search.module
  modules/social_features/social_user/social_user.api.php
  modules/social_features/social_user/src/Plugin/Validation/Constraint/SocialUserNameConstraint.php
  modules/social_features/social_user/src/Plugin/Validation/Constraint/SocialUserNameConstraintValidator.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLViewerEndpointTest.php
  phpcs.xml
Labels: type: code refactoring, prio: medium, team: shipsters

#2511 Issue #3236733 by chmez: Improve copy of Custom content list sorting options
  modules/social_features/social_content_block/config/install/core.entity_form_display.block_content.custom_content_list.default.yml
  modules/social_features/social_content_block/config/update/social_content_block_update_10303.yml
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/src/ContentBlockBase.php
  modules/social_features/social_content_block/src/ContentBlockPluginInterface.php
  modules/social_features/social_content_block/src/Plugin/Field/FieldWidget/ContentBlockSortingWidget.php
Labels: team: eci, type: feature request, prio: medium

#2487 Issue #3229480 by navneet0693: Update drush commands found in Open Social to be compatible with Drush 10
  .travis.yml
  .tugboat/composer.json
  .tugboat/config.yml
  modules/custom/social_demo/drush.services.yml
  modules/custom/social_demo/social_demo.drush.inc
  modules/custom/social_demo/social_demo.drush_testing.inc
  modules/custom/social_demo/src/Commands/SocialDemoDrushCommands.php
  modules/custom/social_demo/src/DemoComment.php
  modules/custom/social_demo/src/DemoContent.php
  modules/custom/social_demo/src/DemoContentInterface.php
  modules/custom/social_demo/src/DemoContentManager.php
  modules/custom/social_demo/src/DemoContentParser.php
  modules/custom/social_demo/src/DemoContentParserInterface.php
  modules/custom/social_demo/src/DemoEntity.php
  modules/custom/social_demo/src/DemoFile.php
  modules/custom/social_demo/src/DemoGroup.php
  modules/custom/social_demo/src/DemoNode.php
  modules/custom/social_demo/src/DemoSystem.php
  modules/custom/social_demo/src/DemoTaxonomyTerm.php
  modules/custom/social_demo/src/DemoUser.php
  modules/custom/social_demo/src/Plugin/DemoContent/Book.php
  modules/custom/social_demo/src/Plugin/DemoContent/Event.php
  modules/custom/social_demo/src/Plugin/DemoContent/EventType.php
  modules/custom/social_demo/src/Plugin/DemoContent/Page.php
  modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
Labels: type: code refactoring, status: needs review, prio: medium, team: nucleus

#2496 Issue #3232648 by nkoporec: Social footer inline images are deleted after a certain time
  modules/social_features/social_footer/src/Form/FooterSettingsForm.php
Labels: type: bug, status: needs review, status: needs backport, team: gravitiers

#2378 Issue #3218415 by chmez: ActivitySend plugin doesn't support injected services
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivitySend/EmailActivitySend.php
  modules/custom/activity_send/src/Plugin/ActivitySendInterface.php
  modules/custom/social_advanced_queue/src/Plugin/ActivitySend/EmailActivitySendAdvancedQueue.php
Labels: type: bug, type: code refactoring, team: eci, prio: medium

#2526 Fine-tune PHPStan config
  composer.json
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivitySend/EmailActivitySend.php
  modules/custom/activity_send/src/Plugin/ActivitySendInterface.php
  modules/custom/social_advanced_queue/src/Plugin/ActivitySend/EmailActivitySendAdvancedQueue.php
  modules/social_features/social_footer/src/Form/FooterSettingsForm.php
  phpstan-baseline.neon
  phpstan.neon
Labels: status: needs review, prio: high, team: shipsters, type: test

#2376 Move PHPUnit testing from Travis to GitHub Actions
  .github/workflows/phpunit.yml
  .travis.yml
  modules/custom/social_graphql/tests/src/Kernel/FieldDataProducerAccessTest.php
  phpunit.xml.dist
  tests/composer.json
Labels: status: needs review, prio: medium, team: shipsters, type: test

#2518 Issue #3238766 by Kingdutch: Require at least PHP 7.4
  .travis.yml
  composer.json
Labels: type: code refactoring, status: needs review, prio: high, team: shipsters

#2516 Use own copy of `GraphQLTestBase` in tests
  modules/custom/social_graphql/tests/src/Kernel/GraphQLTestBase.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  modules/social_features/social_profile/tests/src/Kernel/GraphQLUsersEndpointTest.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLViewerEndpointTest.php
  phpstan-baseline.neon
Labels: prio: medium, type: test

#2529 New email call to actions are not translatable
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_activity/src/EmailTokenServices.php
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_content_report/social_content_report.tokens.inc
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
  modules/social_features/social_group/modules/social_group_request/social_group_request.tokens.inc
  modules/social_features/social_group/social_group.tokens.inc
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_mentions/social_mentions.tokens.inc
  modules/social_features/social_private_message/social_private_message.tokens.inc
Labels: type: bug, prio: critical, team: nucleus

#2528 Fix PHPCS configuration
  .github/workflows/drupalCodingStandards.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
  phpcs.xml
Labels: prio: high, team: shipsters, type: test
