Repository goalgorilla/open_social, pull requests merged in 2022-08, with the labels that each got.

#3010 Internal: Migrating behat to headless chrome
  .github/workflows/behat-stability-1-basic-installation.yml
  .github/workflows/behat-stability-1-upgrade-path.yml
  .github/workflows/behat-stability-1.yml
  .github/workflows/behat-stability-2.yml
  .github/workflows/behat-stability-3.yml
  .github/workflows/behat-stability-4.yml
  tests/behat/README.md
  tests/behat/behat.yml
  tests/behat/config/behat.yml
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/administration/export-users.feature
  tests/behat/features/capabilities/administration/mail-users.feature
  tests/behat/features/capabilities/administration/view-filtered-users.feature
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/event-management/event-management.feature
  tests/behat/features/capabilities/event/event-invite-members.feature
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  tests/behat/features/capabilities/group/group-edit-type.feature
  tests/behat/features/capabilities/group/group-invite-members.feature
  tests/behat/features/capabilities/install/install.feature
  tests/behat/features/capabilities/landing-page/featured-profile-create.feature
  tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
  tests/behat/features/capabilities/landing-page/landing-page-create.feature
  tests/behat/features/capabilities/like/like-create-event.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
  tests/behat/features/capabilities/private-message/create-private-message.feature
  tests/behat/features/capabilities/profile/restricted-full-name.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
  tests/behat/logs/.gitignore
Labels: type: feature request, type: performance, prio: medium, team: nucleus, internal, status: no action needed, type: improvement

#2859 Issue #3265651 by belatrix22, Agami4, T2L: As a Logged User I want to add an emoji to a post or comment
  composer.json
  modules/social_features/social_emoji/assets/css/social_emoji.css
  modules/social_features/social_emoji/assets/css/social_emoji.scss
  modules/social_features/social_emoji/assets/icons/icon-emoji.svg
  modules/social_features/social_emoji/assets/js/social_emoji_picker.js
  modules/social_features/social_emoji/config/schema/social_emoji.schema.yml
  modules/social_features/social_emoji/social_emoji.info.yml
  modules/social_features/social_emoji/social_emoji.install
  modules/social_features/social_emoji/social_emoji.installer_options.yml
  modules/social_features/social_emoji/social_emoji.libraries.yml
  modules/social_features/social_emoji/social_emoji.module
Labels: team: external, type: feature request, status: needs review, prio: high

#3054 Issue #3300210 by tBKoT: Fix broken post update with search re-index
  modules/custom/entity_access_by_field/entity_access_by_field.post_update.php
Labels: type: bug, team: enterprise, status: needs backport, prio: medium, optional: review requested, team: falcon

#3061 Issue #3301083 by rolki: Event invites do not disappear from the notification center
  modules/social_features/social_event/src/Form/EnrollActionForm.php
Labels: type: bug, team: enterprise, status: needs backport, prio: medium, optional: review requested, team: falcon

#3067 Issue #3247457 by latinyanin, tbsiqueira, navneet0693: Confirmation message for bulk actions on enrollments management doesn't display correct selected users
  modules/social_features/social_event/src/Entity/EventEnrollment.php
Labels: type: bug, status: needs review, status: needs backport, prio: medium, team: nucleus

#3001 Issue #2845325: Incorrect display of mention when editing comment/post
  modules/custom/activity_basics/src/Plugin/ActivityContext/CommunityActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/EventRequestActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OrganizerActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/PlatformActivityContext.php
  modules/custom/activity_basics/src/Plugin/ActivityContext/ProfileActivityContext.php
  modules/custom/activity_creator/src/Plugin/ActivityContextBase.php
  modules/custom/activity_creator/src/Plugin/ActivityContextInterface.php
  modules/custom/mentions/mentions.install
  modules/custom/mentions/mentions.module
  modules/custom/mentions/src/Entity/Mentions.php
  modules/custom/mentions/src/Entity/MentionsType.php
  modules/custom/mentions/src/Entity/MentionsTypeInterface.php
  modules/custom/mentions/src/MentionsController.php
  modules/custom/mentions/src/MentionsInterface.php
  modules/custom/mentions/src/MentionsPluginInterface.php
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/custom/mentions/src/Plugin/Mentions/Entity.php
  modules/social_features/social_content_report/src/Plugin/ActivityContext/ContentReportActivityContext.php
  modules/social_features/social_event/modules/social_event_invite/src/Plugin/ActivityContext/EventInviteActivityContext.php
  modules/social_features/social_event/src/Plugin/ActivityContext/OwnerEventEnrollmentActivityContext.php
  modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
  modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/ActivityContext/InvitedToGroupActivityContext.php
  modules/social_features/social_group/modules/social_group_request/src/Plugin/ActivityContext/ApprovedRequestJoinGroupActivityContext.php
  modules/social_features/social_like/src/Plugin/ActivityContext/VoteActivityContext.php
  modules/social_features/social_mentions/js/social_mentions.js
  modules/social_features/social_mentions/social_mentions.module
  modules/social_features/social_mentions/social_mentions.tokens.inc
  modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php
  modules/social_features/social_private_message/src/Plugin/ActivityContext/PrivateMessageActivityContext.php
  phpstan-baseline.neon
Labels: type: feature request, status: needs work, prio:low, team: nucleus, needs: test

#3070 Internal: Updated drupal_social to 6.1.0 in the github workflows
  .github/workflows/behat-stability-1-basic-installation.yml
  .github/workflows/behat-stability-1-upgrade-path.yml
  .github/workflows/behat-stability-1.yml
  .github/workflows/behat-stability-2.yml
  .github/workflows/behat-stability-3.yml
  .github/workflows/behat-stability-4.yml
Labels: type: update, status: needs review, prio:low, team: nucleus, internal

#3074 Don't check for invitations when users has no email (anonymous)
  modules/custom/ginvite/ginvite.module
Labels: type: bug, status: needs review, prio: high, team: gravitiers

#3071 Issue #3303840 by navneet0693: Actions on event enrollment pages gets removed
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.services.yml
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/Action/ExportAllEnrolments.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php
Labels: type: bug, status: needs backport, prio: high, team: nucleus

#3078 Issue #3305919 by nkoporec: User does not receive email notification when added directly to a event
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  phpstan-baseline.neon
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3079 Revert "Issue #3305919 by nkoporec: User does not receive email notification when added directly to a event"
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  phpstan-baseline.neon
Labels: blocked: mergeable

#3082 Issue #3306207 by navneet0693, robertragas, ronaldtebrake: Tag categories do not appear on add/edit page on multilingual websites
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/Service/MachineName.php
  modules/social_features/social_tagging/social_tagging.module
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, prio: high, blocked: mergeable, team: guardians
