Repository goalgorilla/open_social, pull requests merged in 2022-05, with the labels that each got.

#2913 Issue #3232309 by navneet0693: Switched if-else condition in social_embed_post_update_11001_populate_field_embed_content_settings.
  modules/social_features/social_embed/social_embed.post_update.php
Labels: type: bug, prio: medium, team: nucleus

#2903 Issue #3277621: Update socialblue dependency to 2.1.5
  composer.json
Labels: prio: high, type: dependencies, team: nucleus

#2917 Issue #3278347 by navneet0693: Junk plugin data can crash activity entity related view
  modules/custom/activity_basics/activity_basics.module
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
  modules/custom/activity_logger/src/Plugin/QueueWorker/MessageQueueCreator.php
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/custom/activity_viewer/src/Plugin/views/row/ActivityRow.php
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/custom/social_queue_storage/social_queue_storage.module
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/social_content_block.module
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, prio: high, team: nucleus

#2918 Issue #3278347 by navneet0693: Junk plugin data can crash activity entity related view.
  modules/custom/activity_basics/activity_basics.module
  modules/custom/activity_creator/activity_creator.module
  modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
  modules/custom/activity_logger/src/Plugin/QueueWorker/MessageQueueCreator.php
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
  modules/custom/activity_viewer/src/Plugin/views/row/ActivityRow.php
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/custom/social_queue_storage/social_queue_storage.module
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/social_content_block.module
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_event/social_event.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: type: bug, type: code refactoring, prio: high, team: nucleus

#2892 Issue #3275980 by navneet0693: Switching language on multilingual platform leads to unexpected error
  modules/social_features/social_core/social_core.module
Labels: type: bug, prio: critical, team: gravitiers, team: nucleus

#2909 Issue #3277470 by SV: The "Followers" title is displayed on the followers page on Mobile
  modules/social_features/social_follow_user/config/install/views.view.followers_user.yml
  modules/social_features/social_follow_user/config/update/social_follow_user_update_11203.yml
  modules/social_features/social_follow_user/social_follow_user.install
Labels: type: bug, team: enterprise, prio: medium, team: finalizer

#2921 Issue #3278471 by alex.ksis: Do now allow to fill non existing username.
  modules/social_features/social_core/assets/js/invite-form.js
  modules/social_features/social_core/social_core.libraries.yml
  modules/social_features/social_core/src/Form/InviteEmailBaseForm.php
Labels: type: bug, team: enterprise, prio: medium, team: finalizer

#2886 Issue #3275467 by chmez: Profile preview for event organizers
  composer.json
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelperInterface.php
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, team: enterprise, prio: medium, optional: review requested, team: finalizer

#2922 Issue #3278697 by SV: Fix a bug with profile preview on the Inbox page and disable it in notification popup
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module
Labels: type: bug, team: enterprise, prio: medium, team: finalizer

#2865 Issue #3273994 by agami4: Improve font type
  modules/social_features/social_core/social_core.install
  modules/social_features/social_featured_content/css/paragraph.featured.css
  modules/social_features/social_featured_content/css/paragraph.featured.css.map
  modules/social_features/social_featured_content/css/paragraph.featured.scss
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css.map
  modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.scss
  modules/social_features/social_footer/assets/css/social_footer.css
  modules/social_features/social_footer/assets/css/social_footer.css.map
  modules/social_features/social_footer/assets/css/social_footer.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.accordion.css
  modules/social_features/social_landing_page/css/social_landing_page.section.accordion.scss
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.css
  modules/social_features/social_landing_page/css/social_landing_page.section.introduction.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.scss
Labels: team: enterprise, type: feature request, prio: medium, team: finalizer

#2881 Issue #3045872 by colan, Resssinel: Message related object entity type is randomly empty
  modules/social_features/social_activity/src/EmailTokenServices.php
Labels: type: bug, team: external, prio: medium

#2893 Issue #3276000 by SV: AJAXify Follow button on Profile preview
  modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
Labels: type: bug, team: enterprise, prio: medium, team: finalizer

#2911 Issue #3277686 by chmez, agami4: Bypass access to display username
  composer.json
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css.map
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.scss
  modules/social_features/social_profile/modules/social_profile_preview/config/install/core.entity_view_display.profile.profile.preview.yml
  modules/social_features/social_profile/modules/social_profile_preview/config/update/social_profile_preview_update_11301.yml
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.install
  modules/social_features/social_profile/modules/social_profile_preview/src/Plugin/Field/FieldFormatter/SocialProfilePreviewFormatter.php
  modules/social_features/social_profile/src/Plugin/Field/FieldFormatter/SocialProfileAvatarFormatter.php
Labels: type: bug, team: enterprise, prio: medium, optional: review requested, team: finalizer

#2927 Issue #3279904 by Ressinel: Notice: Undefined index: bulk_form_keys
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
Labels: type: bug, prio: medium, team: nucleus

#2847 Issue #3272750 by chmez: As a LU I want to have an information rich profile preview
  composer.json
  modules/social_features/social_profile/modules/social_profile_preview/config/install/core.entity_view_display.profile.profile.preview.yml
  modules/social_features/social_profile/modules/social_profile_preview/config/update/social_profile_preview_update_11302.yml
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.install
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelperInterface.php
  modules/social_features/social_profile/modules/social_profile_preview/templates/profile--profile--preview.html.twig
  modules/social_features/social_user/social_user.module
Labels: team: enterprise, type: feature request, prio: medium, optional: review requested, team: finalizer

#2837 Issue #3272028 by tBKoT: Removes the 'View' action on the 'Manage members' page
  modules/social_features/social_group/social_group.module
Labels: team: enterprise, type: feature request, prio: medium, optional: review requested, team: falcon

#2824 Issue #3270853 by vnech: Redesign "add to Calendar" button on events
  modules/social_features/social_event/modules/social_event_addtocal/assets/css/social_event_addtocal.css
  modules/social_features/social_event/modules/social_event_addtocal/assets/css/social_event_addtocal.css.map
  modules/social_features/social_event/modules/social_event_addtocal/assets/css/social_event_addtocal.scss
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/default-calendar.svg
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/google.svg
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/ical.svg
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/office_365.svg
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/outlook.svg
  modules/social_features/social_event/modules/social_event_addtocal/assets/icons/yahoo.svg
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.libraries.yml
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
  modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarInterface.php
  translations/ar.po
  translations/de.po
  translations/en.pot
  translations/es.po
  translations/fr.po
  translations/gpbe/fr.po
  translations/gpbe/nl.po
  translations/gpbr/pt_BR.po
  translations/gpcee/bg.po
  translations/gpcee/de.po
  translations/gpcee/en_GB.po
  translations/gpcee/hr.po
  translations/gpcee/hu.po
  translations/gpcee/pl.po
  translations/gpcee/ro.po
  translations/gpcee/sk.po
  translations/gpcee/sl.po
  translations/gpch/de_CH.po
  translations/gpch/fr_CH.po
  translations/gpch/it_CH.po
  translations/gpde/de.po
  translations/gpes/ca.po
  translations/gpes/es.po
  translations/gpes/eu.po
  translations/gpes/gl.po
  translations/gpfr/fr.po
  translations/gpit/it.po
  translations/gpmx/es_MX.po
  translations/gpru/ru.po
  translations/ja.po
  translations/nl.po
  translations/uk.po
Labels: team: enterprise, type: feature request, prio: medium, team: falcon

#2799 Issue #3267712 by vnech: Add ability to filter users by following tags
  modules/social_features/social_follow_taxonomy/config/schema/social_follow_taxonomy.views.schema.yml
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.install
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.info.yml
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.views.inc
  modules/social_features/social_follow_taxonomy/src/Plugin/views/filter/FollowTaxonomyViewsFilter.php
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css.map
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.scss
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, prio: medium, team: falcon

#2905 Issue #3277125 by agami4: Add improvements to the follow and message buttons
  modules/social_features/social_follow_user/assets/css/social_follow_user.button.css
  modules/social_features/social_follow_user/assets/css/social_follow_user.button.css.map
  modules/social_features/social_follow_user/assets/css/social_follow_user.button.scss
  modules/social_features/social_follow_user/social_follow_user.module
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css.map
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.scss
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
Labels: team: enterprise, type: feature request, prio: medium, team: finalizer

#2460 Issue #3179171 by agami4: Add autocomplete attr to the profile edit fields
  modules/social_features/social_profile/social_profile.module
Labels: type: feature request, prio: medium, team: nucleus

#2894 Issue #3276049 by tBKoT: Disallow AN users inviting to the event
  modules/social_features/social_core/src/Form/InviteEmailBaseForm.php
  modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, prio: medium, team: falcon

#2924 Issue #3279897: Update socialblue dependency to 2.2.2
  composer.json
Labels: prio: high, type: dependencies, team: nucleus

#2916 Issue #3278356 by nkoporec: Missing data policy explanation link in the new dashboard
  modules/custom/social_gdpr/social_gdpr.links.menu.yml
Labels: type: bug, prio:low, team: gravitiers

#2933 Issue #3197241 by yasmeensalah, Ressinel: Call to a member function bundle() onnull in social_group/src/Plugin/EntityReferenceSelection/SocialGroupSelection.php
  modules/social_features/social_group/src/Plugin/EntityReferenceSelection/SocialGroupSelection.php
Labels: type: bug, team: external, prio: medium

#2926 Issue #3274219 by tbsiqueira: New Dashboard throws fatal errors
  modules/social_features/social_core/social_core.links.menu.yml
  modules/social_features/social_core/src/Plugin/Menu/HomepageConfigurationHeroBlockLink.php
Labels: type: bug, prio: high, team: nucleus

#2935 Issue #3281332 by rolki: Fix sorting options for custom content list block on dashboard when choose events
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: type: bug, status: needs review, prio: medium, team: falcon

#2946 Issue #3282031 by navneet0693: Email subjects in message templates are not translatable.
  modules/custom/activity_logger/config/schema/activity_logger.schema.yml
Labels: type: bug, prio: high, translations, team: nucleus

#2853 Issue #3273219 by vnech: Make it possible for users to receive the email after enrolling in the event
  composer.json
  modules/custom/activity_logger/activity_logger.module
  modules/custom/activity_send/modules/activity_send_email/templates/digestmail.html.twig
  modules/custom/activity_send/modules/activity_send_email/templates/directmail.html.twig
  modules/social_features/social_core/config/install/core.entity_view_mode.node.email_card.yml
  modules/social_features/social_core/config/static/core.entity_view_mode.node.email_card_11401.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_event/assets/css/event.css
  modules/social_features/social_event/assets/icons/location.svg
  modules/social_features/social_event/assets/icons/time.svg
  modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity_comment.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.hero.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.search_index.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.small_teaser.yml
  modules/social_features/social_event/config/install/core.entity_view_display.node.event.teaser.yml
  modules/social_features/social_event/config/install/field.field.node.event.field_event_send_confirmation.yml
  modules/social_features/social_event/config/install/field.storage.node.field_event_send_confirmation.yml
  modules/social_features/social_event/config/optional/core.entity_view_display.node.event.email_card.yml
  modules/social_features/social_event/config/optional/message.template.user_was_enrolled_to_event.yml
  modules/social_features/social_event/config/static/core.entity_view_display.node.event.email_card_11401.yml
  modules/social_features/social_event/config/static/field.field.node.event.field_event_send_confirmation_11401.yml
  modules/social_features/social_event/config/static/field.storage.node.field_event_send_confirmation_11401.yml
  modules/social_features/social_event/config/static/message.template.user_was_enrolled_to_event_11401.yml
  modules/social_features/social_event/config/update/social_event_update_11402.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_event/social_event.libraries.yml
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.theme.inc
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_event/src/Entity/EventEnrollment.php
  modules/social_features/social_event/src/EventEnrollmentInterface.php
  modules/social_features/social_event/src/Plugin/ActivityContext/OwnerEventEnrollmentActivityContext.php
  modules/social_features/social_event/src/Plugin/ActivityEntityCondition/EventEnrollmentStandaloneEnrollActivityEntityCondition.php
  modules/social_features/social_event/templates/event-date-advanced.html.twig
  modules/social_features/social_event/templates/event-location-address.html.twig
  modules/social_features/social_event/templates/node--event--email-card.html.twig
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, prio: medium, team: falcon

#2945 Update PHPStan to 1.7.1
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  tests/composer.json
Labels: status: needs work, prio: medium, team: shipsters, type: dependencies

#2954 [Internal] Fix behat test after new release for the Embed module
  tests/behat/features/capabilities/embed/embed-consent.feature
  tests/behat/features/capabilities/embed/embed.feature
Labels: type: bug, prio: high, team: nucleus

#2934 Do not use ajax comments on standalone comment reply/edit page
  modules/custom/social_ajax_comments/social_ajax_comments.module
Labels: type: bug, status: needs review, status: needs backport, team: gravitiers

#2951 Issue #3279787 by colan, tbsiqueira, Ressinel: Authenticated non-member users can no longer find closed groups
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: external, status: needs review, prio: medium, team: nucleus

#2959 Fix enroll button parameter conversion logic
  modules/social_features/social_event/src/Form/EnrollActionForm.php
Labels: type: bug, status: needs review, team: shipsters, prio: critical

#2966 Issue #3283306: Update socialblue version to 2.2.3
  composer.json
Labels: prio: critical, team: nucleus
