Repository goalgorilla/open_social, pull requests merged in 2022-04, with the labels that each got.

#2849 Issue #3272898 by navneet0693: Use Batch API in update hook to process events.
  composer.json
  modules/social_features/social_event/social_event.install
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, prio: high, team: nucleus

#2852 Issue #3273182 by Ressinel, dmytriikaiun, navneet0693: Fix wrong functions names of update hooks in social_group_flexible_group
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11002.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Labels: type: bug, prio: high, team: nucleus

#2855 [Internal] Backport of PR #2849.
  modules/social_features/social_event/social_event.install
Labels: type: code refactoring, prio: high, team: nucleus

#2851 Issue #3272941 by nijuley, tbsiqueria, Ressinel: PHP warning for event enrollment listing (with no-enrollment)
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php
Labels: type: bug, prio: high, team: nucleus

#2831 Issue #3271644 by nkoporec: Don't allow deleting menu links that ships with Open Social
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_core/social_core.api.php
  modules/social_features/social_core/social_core.module
  modules/social_features/social_core/social_core.permissions.yml
  modules/social_features/social_event/social_event.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_topic/social_topic.module
  phpstan-baseline.neon
Labels: type: feature request, status: needs review, prio:low, team: gravitiers

#2819 Issue #3270158 by tBKoT: Remove useless fields
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: enterprise, prio: high, optional: review requested

#2857 Issue #3273357 by Ressinel: Fix issue where translated topic is displayed twice on the group topics page
  modules/social_features/social_group/config/install/views.view.group_topics.yml
  modules/social_features/social_group/config/update/social_group_update_11004.yml
  modules/social_features/social_group/social_group.install
Labels: type: bug, prio: medium, team: nucleus

#2820 Issue #3270363 by chmez: As a LU I want to add a short description about myself
  modules/social_features/social_profile/config/install/core.entity_form_display.profile.profile.default.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.compact.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.compact_notification.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.compact_teaser.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.default.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.hero.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.medium_teaser.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.name.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.search_index.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.small.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.small_teaser.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.statistic.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.table.yml
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.teaser.yml
  modules/social_features/social_profile/config/install/field.field.profile.profile.field_profile_summary.yml
  modules/social_features/social_profile/config/install/field.storage.profile.field_profile_summary.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/config/static/field.field.profile.profile.field_profile_summary_11201.yml
  modules/social_features/social_profile/config/static/field.storage.profile.field_profile_summary_11201.yml
  modules/social_features/social_profile/config/update/social_profile_update_11201.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/install/social_profile_fields.settings.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/src/Plugin/Field/FieldWidget/SocialProfileStringTextareaWidget.php
Labels: team: enterprise, type: feature request, prio: high

#2861 Issue #3272437 by CurriedN, Ressinel: Check if the Social Flexible Group module is enabled before adding a new field to the flexible group.
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
Labels: type: bug, team: external, prio: medium

#2848 Issue #3272707 by tBKoT: Allows GMs to decide if group members can leave a post
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_posts_enabled.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.group.field_group_posts_enabled.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/static/field.field.group.field_group_posts_enabled_11201.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/static/field.storage.group.field_group_posts_enabled_11201.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11202.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
  phpstan-baseline.neon
  tests/behat/features/capabilities/post/post-create-disabled.feature
Labels: team: enterprise, type: feature request, status: needs review, prio: high

#2864 Issue #3202509 by drasgardian, Ressinel: Wrong group-ID when adding a member to a group
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialInviteLocalActionsBlock.php
Labels: type: bug, team: external, prio: medium

#2868 Issue #3266571 by szato, Ressinel: Fix fatal errors
  modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
  modules/social_features/social_activity/src/EmailTokenServices.php
Labels: type: bug, team: external, prio:low, team: nucleus

#2856 Issue #3273311 by nkoporec: AS CM+ I want to have a link to the social_event_invite settings
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.links.menu.yml
Labels: status: needs review, team: gravitiers

#2874 Issue #3272898 by navneet0693: Add a default of 50 if the entity_update_batch_size is not defined.
  modules/social_features/social_event/social_event.install
Labels: type: bug, prio: high, team: nucleus

#2875 Issue #3274572 by Ressinel: Refactor social_group_entity_base_field_info_alter
  modules/social_features/social_group/social_group.module
Labels: type: code refactoring, prio: medium, team: nucleus

#2879 Issue #3274890 by Ressinel: Notice: Undefined index: description in activity_send_push_notification_form_user_form_alter()
  modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.module
Labels: type: bug, prio: medium, team: nucleus

#2858 Issue #3273470 by Kingdutch: Installer options data is not translatable
  yaml_translation_patterns.yml
Labels: type: bug, team: bananas, status: needs review, prio:low

#2845 Issue #3270733 by Ressinel: Move social_tour out of the Distro
  composer.json
  modules/custom/social_tour/config/install/tour.tour.social_event_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_explore.yml
  modules/custom/social_tour/config/install/tour.tour.social_group.yml
  modules/custom/social_tour/config/install/tour.tour.social_group_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_home.yml
  modules/custom/social_tour/config/install/tour.tour.social_node_view.yml
  modules/custom/social_tour/config/install/tour.tour.social_profile.yml
  modules/custom/social_tour/config/install/tour.tour.social_topic_overview.yml
  modules/custom/social_tour/config/install/tour.tour.social_user.yml
  modules/custom/social_tour/js/social_tour.js
  modules/custom/social_tour/social_tour.info.yml
  modules/custom/social_tour/social_tour.install
  modules/custom/social_tour/social_tour.libraries.yml
  modules/custom/social_tour/social_tour.links.menu.yml
  modules/custom/social_tour/social_tour.module
  modules/custom/social_tour/social_tour.permissions.yml
  modules/custom/social_tour/social_tour.routing.yml
  modules/custom/social_tour/social_tour.services.yml
  modules/custom/social_tour/src/Form/SocialTourSettings.php
  modules/custom/social_tour/src/SocialTourController.php
  phpstan-baseline.neon
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/tour/tour.feature
Labels: status: needs review, type: performance, prio: medium, team: nucleus

#2533 Issue #3240115 by vnech: Make possible to translate taxonomy terms (and vocabularies)
  modules/social_features/social_content_report/config/optional/language.content_settings.taxonomy_term.report_reasons.yml
  modules/social_features/social_content_report/config/static/language.content_settings.taxonomy_term.report_reasons_11201.yml
  modules/social_features/social_content_report/social_content_report.install
  modules/social_features/social_content_report/social_content_report.services.yml
  modules/social_features/social_content_report/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_event/modules/social_event_type/config/optional/language.content_settings.taxonomy_term.event_types.yml
  modules/social_features/social_event/modules/social_event_type/config/static/language.content_settings.taxonomy_term.event_types_11201.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.install
  modules/social_features/social_event/modules/social_event_type/social_event_type.services.yml
  modules/social_features/social_event/modules/social_event_type/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_group/modules/social_group_flexible_group/config/optional/language.content_settings.taxonomy_term.group_type.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/static/language.content_settings.taxonomy_term.group_type_11203.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_profile/config/optional/language.content_settings.taxonomy_term.expertise.yml
  modules/social_features/social_profile/config/optional/language.content_settings.taxonomy_term.interests.yml
  modules/social_features/social_profile/config/optional/language.content_settings.taxonomy_term.profile_tag.yml
  modules/social_features/social_profile/config/static/language.content_settings.taxonomy_term.expertise_11203.yml
  modules/social_features/social_profile/config/static/language.content_settings.taxonomy_term.interests_11203.yml
  modules/social_features/social_profile/config/static/language.content_settings.taxonomy_term.profile_tag_11203.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/optional/language.content_settings.taxonomy_term.nationality.yml
  modules/social_features/social_profile/modules/social_profile_fields/config/static/language.content_settings.taxonomy_term.nationality_11201.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.services.yml
  modules/social_features/social_profile/modules/social_profile_fields/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_profile/modules/social_profile_organization_tag/config/optional/language.content_settings.taxonomy_term.profile_organization_tag.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/config/static/language.content_settings.taxonomy_term.profile_organization_tag_11201.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.install
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.services.yml
  modules/social_features/social_profile/modules/social_profile_organization_tag/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/social_profile.services.yml
  modules/social_features/social_profile/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_tagging/config/optional/language.content_settings.taxonomy_term.social_tagging.yml
  modules/social_features/social_tagging/config/static/language.content_settings.taxonomy_term.social_tagging_11201.yml
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/ContentTranslationDefaultsConfigOverride.php
  modules/social_features/social_topic/config/optional/language.content_settings.taxonomy_term.topic_types.yml
  modules/social_features/social_topic/config/static/language.content_settings.taxonomy_term.topic_types_11201.yml
  modules/social_features/social_topic/social_topic.install
  modules/social_features/social_topic/src/ContentTranslationDefaultsConfigOverride.php
Labels: team: enterprise, type: feature request, prio: medium

#2882 Issue #3275150 by agami4: Improve title and subtitle on the mobile screen
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
Labels: type: bug, team: enterprise, prio: high

#2611 Issue #3250333 by yaroslav-shandra: The count of enrolled users is not displayed correctly after disabling checkbox ''Allow users to enroll to this event without an account'' at event
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
  phpstan-baseline.neon
Labels: status: needs review, status: needs backport, team: gravitiers, team: support

#2843 Issue #3272483 by chmez: As a LU I want to have the short description added to the profile preview
  modules/social_features/social_profile/modules/social_profile_preview/config/install/core.entity_view_display.profile.profile.preview.yml
  modules/social_features/social_profile/modules/social_profile_preview/config/update/social_profile_preview_update_11201.yml
  modules/social_features/social_profile/modules/social_profile_preview/config/update/social_profile_preview_update_11202.yml
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.install
  modules/social_features/social_profile/modules/social_profile_preview/templates/profile--profile--preview.html.twig
Labels: team: enterprise, type: feature request, prio: medium, optional: review requested

#2846 Issue #3272694 by chmez, agami4: As a User I want to see the short description on full size teasers
  composer.json
  modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.teaser.yml
  modules/social_features/social_profile/config/schema/social_profile.schema.yml
  modules/social_features/social_profile/config/update/social_profile_update_11301.yml
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_profile/src/Plugin/Field/FieldFormatter/SocialProfileTextFormatter.php
Labels: team: enterprise, type: feature request, status: needs review, prio: medium, optional: review requested

#2821 Issue #3270714 by nkoporec: Don't allow setting the created date in the future
  modules/social_features/social_core/social_core.module
Labels: type: bug, blocked: commit cleanup, status: needs review, blocked: release notes, prio: medium, team: gravitiers

#2904 Issue #3063436 by Ressinel: Social landing page gives: Warning: array_flip(): Can only flip STRING and INTEGER values
  modules/social_features/social_landing_page/social_landing_page.module
Labels: type: bug, prio: medium, team: nucleus
