Repository goalgorilla/open_social, pull requests merged in 2022-09, with the labels that each got.

#3090 Revert "Issue #3306207 by navneet0693, robertragas, ronaldtebrake: Tag categories do not appear on add/edit page on multilingual websites"
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/Service/MachineName.php
  modules/social_features/social_tagging/social_tagging.module
  phpstan-baseline.neon
Labels: status: needs review, type: revert, prio: high, team: guardians

#3089 Internal: Implement GitHub Action translation extraction
  .github/workflows/translations.yml
Labels: team: external, status: needs review, prio: high, type: improvement

#3092 Issue #3306207 by navneet0693, robertragas, ronaldtebrake: Tag categries do not appear on add/edit page on multilingual websites.
  modules/social_features/social_core/social_core.services.yml
  modules/social_features/social_core/src/Service/MachineName.php
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, status: needs backport, prio: high, team: guardians

#3077 Issue #3305677: Remove destination in group invites url
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
Labels: type: bug, status: needs review, prio: medium, blocked: mergeable, team: guardians

#3106 Issue #3309232 by zanvidmar: Side menu is broken when RTL language is …
  composer.json
Labels: type: bug, status: needs backport, prio: medium, status: no action needed, team: guardians

#3112 Update socialblue dependency to 2.2.5
  composer.json
Labels: blocked: mergeable, team: guardians

#3113 Issue #3310016: Remove "project" key from social_footer info.yml file
  modules/social_features/social_footer/social_footer.info.yml
Labels: status: needs backport, prio: high, blocked: mergeable, team: guardians

#3065 Issue #3302405 by agami4: Improve profile preview behaviour
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css.map
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.scss
  modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
Labels: type: bug, team: enterprise, status: needs review, prio: medium, optional: review requested

#3117 Issue #3311064: Update socialblue to 2.3.2
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, team: guardians

#3121 Issue #3309222: Assign the right permissions for social_album
  modules/social_features/social_album/social_album.install
Labels: type: bug, status: needs backport, prio: high, team: guardians

#3108 Internal: Move Behat into a single workflow
  .github/workflows/behat-stability-1-basic-installation.yml
  .github/workflows/behat-stability-1-upgrade-path.yml
  .github/workflows/behat-stability-1.yml
  .github/workflows/behat-stability-2.yml
  .github/workflows/behat-stability-3.yml
  .github/workflows/behat-stability-4.yml
  .github/workflows/behat.yml
  tests/behat/README.md
  tests/behat/behat.yml
  tests/behat/features/bootstrap/SocialMinkContext.php
  tests/behat/features/capabilities/administration/flood-edit.feature
  tests/behat/features/capabilities/book/book-create.feature
  tests/behat/features/capabilities/book/book-in-flexible-group.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/install/install.feature
  tests/behat/features/capabilities/landing-page/featured-profile-create.feature
  tests/behat/features/capabilities/notifications/notification-emails.feature
  tests/behat/features/capabilities/post/post-album.feature
  tests/behat/features/capabilities/post/post-modal-comments.feature
  tests/behat/features/capabilities/post/post-photo-create.feature
  tests/behat/features/capabilities/private-message/create-private-message.feature
  tests/behat/features/capabilities/profile/click-avatar.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
  tests/behat/features/capabilities/sharing/share.feature
  tests/behat/features/capabilities/topic/topic-create.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
Labels: team: external, status: needs review, prio: high, type: improvement

#3126 Internal: Refactor behat contexts
  tests/behat/behat.yml
  tests/behat/features/bootstrap/CKEditorContext.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/bootstrap/GroupTrait.php
  tests/behat/features/bootstrap/PostContext.php
  tests/behat/features/bootstrap/ThemeContext.php
Labels: team: external, status: needs review, prio: medium, type: improvement

#3131 Internal: Removed unrequired languages from gpch project.
  translations/gpch/ar.po
  translations/gpch/en_GB.po
  translations/gpch/es_GPI.po
  translations/gpch/it_CH@gpi.po
  translations/gpch/pl.po
  translations/gpch/pt_BR.po
  translations/gpch/ro.po
  translations/gpch/ru.po
Labels: status: needs review, prio: medium, translations, internal, blocked: mergeable, team: guardians

#3127 Internal: refactor book create test
  tests/behat/behat.yml
  tests/behat/features/bootstrap/BookContext.php
  tests/behat/features/bootstrap/ModuleContext.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/capabilities/book/book-create.feature
Labels: team: external, status: needs review, prio: medium, type: improvement

#3125 Internal: Make flood-edit test deterministic
  tests/behat/behat.yml
  tests/behat/features/capabilities/administration/flood-edit.feature
Labels: team: external, status: needs review, prio: medium, type: improvement

#3122 Issue #3309222: Assign the right permissions for social_album
  modules/social_features/social_album/social_album.install
Labels: type: bug, prio: high, blocked: mergeable, team: guardians

#3128 Internal: Rewrite unpublished.feature
  tests/behat/behat.yml
  tests/behat/features/bootstrap/TopicContext.php
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
Labels: team: external, status: needs review, prio: medium, type: improvement

#3119 Issue #3311123 by chmez: Fix fatal error on group content creation (course section)
  modules/social_features/social_core/social_core.module
  modules/social_features/social_group/social_group.module
Labels: type: bug, type: code refactoring, team: enterprise, status: needs review, prio: high, team: finalizer

#3133 Internal: Fix Book in Flexible group test
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.info.yml
  modules/social_features/social_group/social_group.info.yml
  tests/behat/features/bootstrap/BookContext.php
  tests/behat/features/bootstrap/EntityTrait.php
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/bootstrap/GroupTrait.php
  tests/behat/features/bootstrap/ModuleContext.php
  tests/behat/features/bootstrap/NodeTrait.php
  tests/behat/features/bootstrap/TopicContext.php
  tests/behat/features/capabilities/administration/view-filtered-users.feature
  tests/behat/features/capabilities/book/book-in-flexible-group.feature
  tests/behat/features/capabilities/event-management/event-management.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-edit-type.feature
  tests/behat/features/capabilities/group/group-invite-members.feature
  tests/behat/features/capabilities/group/group-mute-notify.feature
  tests/behat/features/capabilities/search/search-all.feature
  tests/behat/features/capabilities/search/search-groups.feature
Labels: team: external, status: needs review, prio: high, type: improvement

#3102 Issue #3308587: Remove social_user update hooks pre-10.0
  modules/social_features/social_user/social_user.install
  phpstan-baseline.neon
Labels: type: code refactoring, team: external, status: needs review, prio: medium

#3099 Issue #3308580: Add `view debug` permission to social_core
  modules/social_features/social_core/social_core.permissions.yml
Labels: team: external, type: feature request, status: needs review, prio: medium

#3095 Issue #3308531: Remove collapsing of privacy settings on profile page
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
  modules/social_features/social_profile/modules/social_profile_privacy/assets/js/collapse.js
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.libraries.yml
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, team: external, status: needs review, prio: medium

#3134 Internal: Re-enable and optimise share topic test
  tests/behat/features/bootstrap/TopicContext.php
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/sharing/share.feature
Labels: team: external, prio:low, type: test, status: no action needed, type: improvement

#3101 Issue #330884: Verified user role weight should be lower than content manager
  modules/social_features/social_core/config/install/user.role.verified.yml
  modules/social_features/social_core/social_core.install
Labels: type: bug, team: external, status: needs review, prio: medium

#3132 Issue #3311816 by tbsiqueira: Caching issues with ajax_comments module
  composer.json
Labels: type: code refactoring, status: needs review, type: performance, prio: high, team: guardians

#3137 Internal: Update drupal/core-recommended package to the latest released version
  composer.json
Labels: status: needs review, status: needs backport, prio: high, type: dependencies, internal, team: guardians

#3130 Issue #3254715 by zanvidmar: Group preprocess error breaks search index and group rendering if referenced group type does not exist
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
Labels: type: bug, status: needs review, status: needs backport, prio: medium, team: guardians
