Repository goalgorilla/open_social, pull requests merged in 2022-06, with the labels that each got.

#2908 Issue #3276411 by tarikflz, Ressinel: SocialCommentBreadcrumbBuilder causes an error loading entities
  modules/social_features/social_comment/src/SocialCommentBreadcrumbBuilder.php
  phpstan-baseline.neon
Labels: type: bug, team: external, status: needs review, prio: medium, team: nucleus

#2971 [Internal] Update necessary patch
  composer.json
Labels: type: bug, team: nucleus, internal

#2938 Issue #3281476 by alex.ksis: Hide path alias field from the approve membership form.
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium, team: finalizer

#2660 Issue #3206166/#3206167 by agami4: Improve album popup behaviour
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--form.scss
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.css.map
  modules/social_features/social_post/modules/social_post_album/assets/css/social-post-album--popup.scss
  modules/social_features/social_post/modules/social_post_album/assets/icons/icon-close.svg
  modules/social_features/social_post/modules/social_post_album/assets/icons/icon-close_white.svg
  modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--popup-slider.js
  modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--post-loading.js
Labels: type: bug, prio: medium, team: nucleus

#2947 Issue #3282058 by chmez: Support visibility for any entity type
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, type: feature request, prio: critical, team: finalizer

#2980 Issue #3282031 by navneet0693: Email subjects in message templates are not translatable.
  modules/social_features/social_activity/config/install/message.template.create_comment_community_node.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_community_post.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
  modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
  modules/social_features/social_activity/config/install/message.template.create_event_community.yml
  modules/social_features/social_activity/config/install/message.template.create_event_group.yml
  modules/social_features/social_activity/config/install/message.template.create_post_community.yml
  modules/social_features/social_activity/config/install/message.template.create_post_group.yml
  modules/social_features/social_activity/config/install/message.template.create_post_profile_stream.yml
  modules/social_features/social_activity/config/install/message.template.create_topic_community.yml
  modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
  modules/social_features/social_activity/config/install/message.template.moved_content_between_groups.yml
  modules/social_features/social_activity/config/update/social_activity_update_11001.yml
  modules/social_features/social_activity/social_activity.info.yml
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_mentions/config/install/message.template.create_mention_comment_stream.yml
  modules/social_features/social_mentions/config/install/message.template.create_mention_post_stream.yml
  modules/social_features/social_mentions/config/update/social_mentions_update_11001.yml
  modules/social_features/social_mentions/social_mentions.install
  translations.php
Labels: type: bug, status: needs backport, prio: high, translations, team: nucleus

#2658 Issue #3254715 by chmez, alex.ksis: Make join methods for groups re-usable
  composer.json
  modules/social_features/social_album/src/Controller/SocialAlbumController.php
  modules/social_features/social_event/src/Plugin/Block/EventRequestEnrollmentNotification.php
  modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.group.field_group_allowed_join_method.yml
  modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11401.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupJoinPermissionAccessCheck.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/modules/social_group_gvbo/src/Form/SocialGroupViewsBulkOperationsConfigureAction.php
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialGroupInviteNotificationBlock.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialInviteLocalActionsBlock.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Join/SocialGroupInviteJoin.php
  modules/social_features/social_group/modules/social_group_quickjoin/src/Controller/SocialQuickJoinController.php
  modules/social_features/social_group/modules/social_group_request/social_group_request.api.php
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
  modules/social_features/social_group/modules/social_group_request/src/Plugin/Block/SocialGroupRequestMembershipNotification.php
  modules/social_features/social_group/modules/social_group_request/src/Plugin/Join/SocialGroupRequestJoin.php
  modules/social_features/social_group/modules/social_group_request/src/SocialGroupRequestConfigOverride.php
  modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/social_group.theme.inc
  modules/social_features/social_group/src/Annotation/Join.php
  modules/social_features/social_group/src/Element/SocialGroupEntityAutocomplete.php
  modules/social_features/social_group/src/Entity/Group.php
  modules/social_features/social_group/src/EntityMemberInterface.php
  modules/social_features/social_group/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/src/JoinBase.php
  modules/social_features/social_group/src/JoinManager.php
  modules/social_features/social_group/src/JoinManagerInterface.php
  modules/social_features/social_group/src/JoinPluginInterface.php
  modules/social_features/social_group/src/Plugin/Action/AddMembersToGroup.php
  modules/social_features/social_group/src/Plugin/Join/SocialGroupAlreadyJoin.php
  modules/social_features/social_group/src/Plugin/Join/SocialGroupDirectJoin.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
  modules/social_features/social_group/src/SocialGroupInterface.php
  modules/social_features/social_group/templates/join.html.twig
  phpstan-baseline.neon
  translations.php
Labels: type: code refactoring, team: enterprise, type: feature request, prio: high, optional: review requested, team: finalizer

#2956 Internal: Added mergeables tool.
  .github/mergeable.yml
Labels: status: needs review, prio: high, type: dependencies, team: nucleus, internal

#2995 Issue #3291105 by vnech: Hide redundant form fields labels if user doesn't have an access to them
  modules/social_features/social_core/social_core.module
Labels: type: bug, status: needs backport, prio: medium, team: falcon

#2982 Issue #3283541 by alex.ksis: Allow to add tags to media entities.
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
Labels: team: enterprise, type: feature request, status: needs backport, prio: medium, team: finalizer

#2880 Issue #3201416 by hotwebmatter, DamienMcKenna, Ressinel: Spelling for "Notification Centre" should be American English
  modules/custom/activity_creator/js/notifications.js
  modules/social_features/social_activity/social_activity.module
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  tests/behat/features/capabilities/like/like-create-event.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
Labels: type: bug, team: external, prio: medium

#3008 Issue #3292017 by Ressinel: Profile organization tag yellow icon is disappeared on People overview page
  modules/social_features/social_profile/templates/profile--profile--name.html.twig
Labels: type: bug, status: needs review, status: needs backport, prio: medium, team: nucleus

#2992 Internal: Replaced dev-dependencies with goalgoriall/open_social_dev.
  .github/dependabot.yml
  composer.json
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
  tests/composer.json
Labels: prio: medium, type: dependencies, team: nucleus, type: test, internal, blocked: mergeable

#3004 Issue #3291633: Update socialblue dependency to 2.2.4 on 11.3.x
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, team: nucleus

#3007 Internal: Optimize tests to use a common setup method close to local developer environment.
  .github/workflows/codingStandards.yml
  .github/workflows/qualityChecks.yml
  .github/workflows/testing.yml
  composer.json
  phpcs.xml
  phpstan.neon
Labels: type: code refactoring, type: performance, prio: medium, team: nucleus, type: test, internal, type: improvement

#3002 Issue #3281618 by zanvidmar: Show enroll button on multi-group event if user is member of at least one group
  modules/social_features/social_event/src/Form/EnrollActionForm.php
Labels: type: bug, status: needs backport, prio: medium, team: gravitiers

#3009 Issue #3292189 by agami4: Improve teaser album on the mobile mode
  modules/social_features/social_album/assets/css/social-album--teaser.css
  modules/social_features/social_album/assets/css/social-album--teaser.css.map
  modules/social_features/social_album/assets/css/social-album--teaser.scss
Labels: type: bug, team: enterprise, status: needs backport, prio:low

#3014 Issue #3293388 by navneet0693: Status Code 429 on YouTube urls on a content page
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
Labels: type: bug, status: needs backport, prio: critical, team: nucleus

#2962 Added GraphQL OAuth module
  composer.json
  modules/custom/social_graphql/social_graphql.info.yml
  modules/custom/social_graphql/src/Plugin/GraphQL/Schema/OpenSocialBaseSchema.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
  phpstan-baseline.neon
  phpstan.neon
Labels: type: feature request, status: needs review, prio: medium, team: nucleus

#2834 Issue #3271758 by vnech: Fix fatal error on "social_profile_profile_view_alter()" function
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, team: enterprise, status: needs backport, prio: medium, team: falcon
