Repository goalgorilla/open_social, pull requests merged in 2022-03, with the labels that each got.

#2789 Issue #3266990 by alex.ksis: Update config override to be compatible with lazy 3.11
  modules/custom/social_lazy_loading/src/SocialLazyLoadingTextFormatOverride.php
Labels: type: bug, team: enterprise, optional: review requested

#2793 Added composer command to remove roave/security-advisories dependency from composer.json as it was conflict with our ugprade branch.
  .travis.yml
Labels: prio: critical, team: nucleus, type: test

#2696 Issue #3258123 by hitesh-jain, tbsiqueira: VBO actions on Group membership not working
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
Labels: type: bug, team: nucleus

#2752 Issue #3263114 by Ressinel: Events maximum for enrollee's has been exceeded.
  modules/social_features/social_event/modules/social_event_invite/src/Controller/UserEnrollInviteController.php
  modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_event/modules/social_event_max_enroll/config/install/field.field.node.event.field_event_max_enroll_num.yml
  modules/social_features/social_event/modules/social_event_max_enroll/config/update/social_event_max_enroll_update_11001.yml
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.install
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.services.yml
  modules/social_features/social_event/modules/social_event_max_enroll/src/Controller/UserEnrollInviteControllerAlter.php
  modules/social_features/social_event/modules/social_event_max_enroll/src/EventMaxEnrollOverride.php
  modules/social_features/social_event/modules/social_event_max_enroll/src/Routing/RouteSubscriber.php
  phpstan-baseline.neon
Labels: type: bug, blocked: commit cleanup, status: needs review, prio: high, team: nucleus

#2800 Issue #3267764 by alex.ksis: Generate a URL instead of adding a prefix.
  modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
Labels: type: bug, team: enterprise, optional: review requested

#2753 Issue #3263120 by yaroslav-shandra: Hide extra fields after enabling Social Profile Manager Notes
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.module
  modules/social_features/social_profile/modules/social_profile_manager_notes/social_profile_manager_notes.services.yml
  modules/social_features/social_profile/modules/social_profile_manager_notes/src/SocialProfileManagerNotesConfigOverride.php
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, prio: medium, team: support

#2779 Issue #3266003 by SV: Fix 'Notice: Undefined index: children in social_profile_privacy_private_fields_list()
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
Labels: type: bug, team: enterprise, prio:low, optional: review requested

#2795 Issue #3267357 by alex.ksis: Replace a patch for group for compatibility with D9.
  composer.json
Labels: type: bug, team: enterprise, prio: high, optional: review requested

#2780 Issue #3265644 by tBKoT: Adds filtration on the comment overview pages
  modules/social_features/social_comment/config/install/views.view.comment.yml
  modules/social_features/social_comment/config/schema/social_comment.schema.yml
  modules/social_features/social_comment/config/update/social_comment_update_11201.yml
  modules/social_features/social_comment/social_comment.info.yml
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_comment/social_comment.module
  modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
  modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentTest.php
  modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentsTest.php
  modules/social_features/social_group/social_group.views.inc
  modules/social_features/social_group/src/Plugin/views/filter/FilterByGroup.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, status: needs review, prio: medium

#2794 Issue #3263649 by Corn696, Ressinel: Fix wrong profile name for event enrollment decline request messages.
  modules/social_features/social_event/src/Form/EnrollRequestDeclineForm.php
  modules/social_features/social_profile/src/SocialProfileNameService.php
  phpstan-baseline.neon
Labels: type: bug, team: external, prio: medium, team: nucleus

#2815 [Internal] - Remove Social Base theme patch since those changes were released in last theme version.
  composer.json
Labels: type: code refactoring, status: needs work, prio: high, team: nucleus

#2817 Revert "[Internal] - Remove Social Base theme patch since those changes were released in last theme version."
  composer.json
Labels: type: code refactoring, prio: high, team: nucleus

#2723 Issue #3260885 by tBKoT: New conent list block for multiple content types
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/install/core.entity_form_display.paragraph.custom_multiple_content_list.default.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/install/core.entity_view_display.paragraph.custom_multiple_content_list.default.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/install/field.field.paragraph.custom_multiple_content_list.field_multiple_content_block.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/install/field.storage.paragraph.field_multiple_content_block.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/install/paragraphs.paragraphs_type.custom_multiple_content_list.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/static/core.entity_form_display.paragraph.custom_multiple_content_list.default_11001.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/static/core.entity_view_display.paragraph.custom_multiple_content_list.default_11001.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/static/field.field.paragraph.custom_multiple_content_list.field_multiple_content_block_11001.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/static/field.storage.paragraph.field_multiple_content_block_11001.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/config/static/paragraphs.paragraphs_type.custom_multiple_content_list_11001.yml
  modules/social_features/social_content_block/modules/social_content_block_landing_page/social_content_block_landing_page.install
  modules/social_features/social_content_block/modules/social_content_block_landing_page/social_content_block_landing_page.module
  modules/social_features/social_content_block/modules/social_content_block_landing_page/src/SocialContentBlockLandingPageConfigOverride.php
  modules/social_features/social_content_block/modules/social_event_content_block/src/Plugin/MultipleContentBlock/EventContent.php
  modules/social_features/social_content_block/modules/social_group_content_block/src/Plugin/MultipleContentBlock/ClosedGroupContent.php
  modules/social_features/social_content_block/modules/social_group_content_block/src/Plugin/MultipleContentBlock/FlexibleGroupContent.php
  modules/social_features/social_content_block/modules/social_group_content_block/src/Plugin/MultipleContentBlock/OpenGroupContent.php
  modules/social_features/social_content_block/modules/social_group_content_block/src/Plugin/MultipleContentBlock/PublicGroupContent.php
  modules/social_features/social_content_block/modules/social_page_content_block/src/Plugin/MultipleContentBlock/PageContent.php
  modules/social_features/social_content_block/social_content_block.module
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/Annotation/MultipleContentBlock.php
  modules/social_features/social_content_block/src/MultipleContentBlockBase.php
  modules/social_features/social_content_block/src/MultipleContentBlockPluginInterface.php
  modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
  modules/social_features/social_content_block/src/Plugin/MultipleContentBlock/TopicContent.php
  modules/social_features/social_content_block/src/Services/MultipleContentBlockManager.php
  modules/social_features/social_content_block/src/Services/MultipleContentBlockManagerInterface.php
  modules/social_features/social_content_block/templates/block--multiple-content-block.html.twig
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, status: needs review, prio: medium

#2806 Issue #3268520 by nkoporec: The destination param is missing when logging in via the social_magic_link and accepting the data policy.
  modules/custom/social_magic_login/src/Controller/MagicLoginController.php
Labels: type: bug, status: needs review, team: gravitiers

#2712 Issue #3260416 by vnech: As a user I should be able to follow another users
  modules/social_features/social_follow_user/config/install/flag.flag.follow_user.yml
  modules/social_features/social_follow_user/config/install/social_follow_user.settings.yml
  modules/social_features/social_follow_user/config/schema/social_follow_user.schema.yml
  modules/social_features/social_follow_user/social_follow_user.api.php
  modules/social_features/social_follow_user/social_follow_user.info.yml
  modules/social_features/social_follow_user/social_follow_user.install
  modules/social_features/social_follow_user/social_follow_user.module
  modules/social_features/social_follow_user/social_follow_user.permissions.yml
  modules/social_features/social_follow_user/social_follow_user.routing.yml
  modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php
Labels: team: enterprise, type: feature request, prio: medium

#2757 Issue #3263200 by vnech: As a group manager I want to be able to send a reminder about invitation to the group
  modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_invitations.yml
  modules/social_features/social_group/modules/social_group_invite/config/schema/social_group_invite.schema.yml
  modules/social_features/social_group/modules/social_group_invite/config/update/social_group_invite_update_11002.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.routing.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.services.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.views.inc
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialGroupInviteResendConfirmForm.php
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialGroupInviteVBOConfirmAction.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Action/SocialGroupInviteResend.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialInviteLocalActionsBlock.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, status: needs review, prio: medium

#2729 Issue #3261567 by tBKoT: Use multiple types in topics
  modules/social_features/social_topic/config/install/field.storage.node.field_topic_type.yml
  modules/social_features/social_topic/social_topic.install
  modules/social_features/social_topic/social_topic.module
  tests/behat/features/capabilities/contentmanagement/node-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished-visibility.feature
  tests/behat/features/capabilities/contentmanagement/unpublished.feature
  tests/behat/features/capabilities/embed/embed-consent.feature
  tests/behat/features/capabilities/embed/embed.feature
  tests/behat/features/capabilities/follow-taxonomy/follow-tags.feature
  tests/behat/features/capabilities/group/group-access-roles.feature
  tests/behat/features/capabilities/group/group-create-closed.feature
  tests/behat/features/capabilities/group/group-create-flexible.feature
  tests/behat/features/capabilities/group/group-create-open.feature
  tests/behat/features/capabilities/group/group-create-public.feature
  tests/behat/features/capabilities/group/group-create-secret.feature
  tests/behat/features/capabilities/group/group-edit-content-in-group.feature
  tests/behat/features/capabilities/group/group-edit-open.feature
  tests/behat/features/capabilities/group/group-mute-notify.feature
  tests/behat/features/capabilities/like/like-create-topic.feature
  tests/behat/features/capabilities/notifications/notification-emails.feature
  tests/behat/features/capabilities/profile/click-avatar.feature
  tests/behat/features/capabilities/profile/restricted-full-name.feature
  tests/behat/features/capabilities/security/private-file-uploads.feature
  tests/behat/features/capabilities/sharing/share.feature
  tests/behat/features/capabilities/topic/topic-create.feature
  tests/behat/features/capabilities/topic/topic-download-count.feature
  tests/behat/features/capabilities/topic/topic-follow-content.feature
Labels: team: enterprise, type: feature request, status: needs review, prio: medium

#2822 Change pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: needs review, team: nucleus

#2826 Issue #3270932 by alex.ksis: Do not recreate alternative frontpages if they exist.
  modules/custom/alternative_frontpage/alternative_frontpage.install
Labels: type: bug, team: enterprise, prio: high

#2823 Add description before preprocessing for files
  modules/social_features/social_core/src/Plugin/Field/FieldFormatter/FileAndImageTableFormatter.php
Labels: status: needs review, team: gravitiers

#2565 Issue #3245778 by chmez, agami4: As a SM I want to be able to filter users by multiple groups in order to send email notifications to right people
  composer.json
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
  modules/social_features/social_user/config/update/social_user_update_11201.yml
  modules/social_features/social_user/social_user.install
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/Controller/SocialUserController.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature request, optional: review requested

#2527 Issue #3233027 : Social tags not applied to search indexes correctly and therefore cannot be used in search
  modules/social_features/social_tagging/social_tagging.info.yml
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  phpstan-baseline.neon
Labels: type: bug, status: needs backport, team: gravitiers

#2836 Updated drupal_social version to 4.0.0 and corrected indentation of travis.yml file.
  .travis.yml
Labels: prio: high, team: nucleus

#2804 Issue #3268100 by nkoporec: Footer block image is not responsive
  modules/social_features/social_footer/assets/css/social_footer.css
  modules/social_features/social_footer/assets/css/social_footer.css.map
  modules/social_features/social_footer/assets/css/social_footer.scss
Labels: status: needs review, team: gravitiers

#2840 Issue #3272386 by Ressinel: Patch for instaclick/php-webdriver is not longer being applied
  composer.json
Labels: type: bug, status: needs review, prio: high, team: nucleus

#2841 Issue #3272432 by robertragas: Only add the social tagging field to the search index if it's not there yet
  modules/social_features/social_tagging/social_tagging.install
Labels: type: bug, status: needs backport, prio: critical, team: gravitiers

#2769 Issue #3264434 by nickmans: Set timestamp to 0 when timestamp is empty
  modules/custom/social_language/social_language.module
Labels: type: bug, status: needs backport, prio: critical, team: gravitiers
