Repository goalgorilla/open_social, pull requests merged in 2022-11, with the labels that each got.

#3192 Issue #3318338: Patches for crop / entity are not applying after update
  composer.json
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3195 Issue #3191622 by tbsiqueira, Kingdutch: Update graphql version to 4.3 from 4.1
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, team: guardians

#3197 Internal: Update search_api to version 1.27.0
  composer.json
Labels: prio: high, type: dependencies, blocked: mergeable, team: guardians

#3205 Internal: Force composer exit on patch failure for our tests/composer.json
  tests/composer.json
Labels: status: needs review, prio: critical, type: improvement, team: guardians

#3206 Internal: Remove deprecated patch for drupal/advancedqueue
  composer.json
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3207 Internal: Updated patch on ctools from https://www.drupal.org/project/ctools/issues/3191286.
  composer.json
Labels: type: bug, status: needs backport, prio: high, team: guardians

#3062 Issue #3307272: Create helper service for Social Mentions module
  modules/social_features/social_mentions/social_mentions.module
  modules/social_features/social_mentions/social_mentions.services.yml
  modules/social_features/social_mentions/src/SocialMentionsHelper.php
  modules/social_features/social_mentions/src/SocialMentionsHelperInterface.php
Labels: type: code refactoring, team: enterprise, team: external, type: feature request, status: needs review, prio: high

#3217 Issue #3321141: Update socialblue to 2.3.4 on Open Social 11.4.x
  composer.json
Labels: blocked: mergeable

#3218 Issue #3321141: Update socialblue to 2.4.2 version on Open social 11.5.x/main
  composer.json
Labels: type: dependencies, prio: critical, status: no action needed, team: guardians

#3214 Issue #3320715 by vnech: Add behat test for "show/hide enrolees" feature
  modules/social_features/social_event/social_event.module
  tests/behat/features/capabilities/event/show-hide-eventenrollments.feature
Labels: team: enterprise, status: needs review, prio: medium, type: improvement

#3220 Issue #3322194: Image style that uses convert and private file system is not working
  composer.json
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3221 Issue #3322858 by zanvidmar: Broken date filter on search
  modules/social_features/social_search/social_search.module
Labels: type: bug, prio: high, blocked: mergeable, team: guardians

#3069 Issue #3302921 by chmez: Support visibility tooltip for any entity type
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.api.php
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.api.php
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/SocialGroupHelperService.php
  modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
  modules/social_features/social_group/templates/visibility.html.twig
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, type: feature request, status: needs backport, prio: medium, optional: review requested, team: finalizer

#3083 Issue #3306287 by chmez: Content tags for any entity type
  modules/social_features/social_book/social_book.module
  modules/social_features/social_core/src/Service/MachineName.php
  modules/social_features/social_core/src/Service/MachineNameInterface.php
  modules/social_features/social_event/social_event.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_node/social_node.module
  modules/social_features/social_page/social_page.module
  modules/social_features/social_profile/social_profile.module
  modules/social_features/social_tagging/social_tagging.api.php
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
  modules/social_features/social_topic/social_topic.module
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, type: feature request, status: needs backport, prio: medium, optional: review requested, team: finalizer

#3224 Social post install update hook number mixes up with Open Social profile
  modules/social_features/social_core/config/update/social_core_update_11405.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_post/social_post.install
  phpstan-baseline.neon
Labels: type: bug, status: needs backport, prio: high, status: no action needed, team: guardians

#3219 Issue #3320482 by kashandarash: Album cover image is not displayed in activity stream
  modules/social_features/social_album/assets/css/social-album--teaser.css
  modules/social_features/social_album/assets/css/social-album--teaser.css.map
  modules/social_features/social_album/assets/css/social-album--teaser.scss
  modules/social_features/social_album/social_album.module
Labels: type: bug, status: needs review, prio: medium, optional: review requested, team: finalizer

#3227 Issue #3324332: Change socialblue requirement on composer.json for 11.4.x
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, team: guardians

#3228 Issue #3324332: Change socialblue requirement on composer.json for main/11.5.x
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, team: guardians
