Repository goalgorilla/open_social, pull requests merged in 2022-02, with the labels that each got.

#2718 Issue #3260835 by SV: User should be able to see a list with the content with the latest comments
  modules/social_features/social_content_block/src/ContentBlockBase.php
  modules/social_features/social_content_block/src/ContentBuilder.php
Labels: team: eci, type: feature request, status: needs backport, prio: medium, optional: review requested

#2727 Added fixes for PHPCS.
  modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
  modules/custom/download_count/download_count.module
  modules/custom/dropdown/dropdown.module
  modules/custom/dropdown/src/Element/Dropdown.php
  modules/custom/social_demo/src/DemoContent.php
  modules/custom/social_demo/src/DemoContentManager.php
  modules/custom/social_demo/src/Plugin/DemoContent/MenuLink.php
  modules/custom/social_lets_connect/modules/social_lets_connect_usage/src/Plugin/ShareUsageDataPlugin/EntityTypeCount.php
  modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/filter/ActivityFilterTags.php
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.module
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_user/social_user.module
Labels: type: code refactoring, prio: critical, team: nucleus

#2590 Issue #3247898 by rolki: Alternative frontpage not multilingual and do not support custom roles
  modules/custom/alternative_frontpage/alternative_frontpage.info.yml
  modules/custom/alternative_frontpage/alternative_frontpage.install
  modules/custom/alternative_frontpage/alternative_frontpage.links.action.yml
  modules/custom/alternative_frontpage/alternative_frontpage.links.menu.yml
  modules/custom/alternative_frontpage/alternative_frontpage.permissions.yml
  modules/custom/alternative_frontpage/alternative_frontpage.routing.yml
  modules/custom/alternative_frontpage/alternative_frontpage.services.yml
  modules/custom/alternative_frontpage/config/install/alternative_frontpage.alternativefrontpagesettings.yml
  modules/custom/alternative_frontpage/config/schema/alternative_frontpage.schema.yml
  modules/custom/alternative_frontpage/src/AlternativeFrontpageInterface.php
  modules/custom/alternative_frontpage/src/Controller/AlternativeFrontpageListBuilder.php
  modules/custom/alternative_frontpage/src/Entity/AlternativeFrontpage.php
  modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
  modules/custom/alternative_frontpage/src/Form/AlternativeFrontpageDeleteForm.php
  modules/custom/alternative_frontpage/src/Form/AlternativeFrontpageForm.php
  modules/custom/alternative_frontpage/src/Form/AlternativeFrontpageSettings.php
  phpstan-baseline.neon
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/capabilities/alternative-frontpage/alternative-frontpage.feature
Labels: type: code refactoring, team: eci, type: feature request, prio: medium, optional: review requested

#2530 Issue #3239820 by nkoporec: Landing page visibility label alignement issues when using the new sky styling
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/node--landing-page--featured--sky.html.twig
Labels: type: bug, team: gravitiers

#2519 Issue #3236705 by tBKoT: As a user I want to invite members to my group
  modules/social_features/social_group/modules/social_group_invite/assets/js/social_group_invite.js
  modules/social_features/social_group/modules/social_group_invite/config/optional/field.field.group.flexible_group.field_group_invite_by_member.yml
  modules/social_features/social_group/modules/social_group_invite/config/optional/field.storage.group.field_group_invite_by_member.yml
  modules/social_features/social_group/modules/social_group_invite/config/static/field.field.group.flexible_group.field_group_invite_by_member_11001.yml
  modules/social_features/social_group/modules/social_group_invite/config/static/field.storage.group.field_group_invite_by_member_11001.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.libraries.yml
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
  modules/social_features/social_group/modules/social_group_invite/src/Routing/RouteSubscriber.php
  modules/social_features/social_group/modules/social_group_invite/templates/invite-to-group-by-member.html.twig
  phpstan-baseline.neon
Labels: team: eci, type: feature request, blocked: commit cleanup, prio: medium

#2525 Issue #3239402 by tBKoT: As a user I want to share the event for other users to join
  modules/social_features/social_event/modules/social_event_invite/assets/js/social_event_invite.js
  modules/social_features/social_event/modules/social_event_invite/config/install/field.field.node.event.field_event_send_invite_by_user.yml
  modules/social_features/social_event/modules/social_event_invite/config/install/field.storage.node.field_event_send_invite_by_user.yml
  modules/social_features/social_event/modules/social_event_invite/config/install/social_event_invite.settings.yml
  modules/social_features/social_event/modules/social_event_invite/config/schema/social_event_invite.schema.yml
  modules/social_features/social_event/modules/social_event_invite/config/static/field.field.node.event.field_event_send_invite_by_user_11001.yml
  modules/social_features/social_event/modules/social_event_invite/config/static/field.storage.node.field_event_send_invite_by_user_11001.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.libraries.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.module
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.routing.yml
  modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc
  modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
  modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteSettingsForm.php
  modules/social_features/social_event/modules/social_event_invite/src/Routing/RouteSubscriber.php
  modules/social_features/social_event/modules/social_event_invite/templates/invite-to-event-by-user.html.twig
Labels: team: eci, type: feature request, prio: medium, blocked: maintainer input

#2692 Issue #3258809 by tBKoT: Invalidate cache when comment deleted
  composer.json
Labels: type: bug, team: eci, blocked: commit cleanup, prio:low

#2693 Issue #3258883: Revoke select account cancellation method permission for authenticate…
  modules/social_features/social_user/social_user.install
Labels: blocked: commit cleanup, status: needs review, team: gravitiers

#2736 [Internal] - Fix bahat test error.
  tests/behat/features/capabilities/private-message/create-private-message.feature
Labels: type: bug, prio: high, team: nucleus

#2732 Issue #3261704 by agami4: Improve expand icon position in RTL mode
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.css
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.css.map
  modules/custom/activity_send/modules/activity_send_email/css/activity_send_email.admin.scss
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.css.map
  modules/social_features/social_profile/modules/social_profile_privacy/assets/css/social-profile-privacy.scss
Labels: type: bug, team: eci, prio: medium

#2740 Issue #3258541 by Irina Matusevich, navneet0693, tbsiqueira: Deprecat…
  modules/social_features/social_user/src/Form/SocialUserPasswordForm.php
  phpstan-baseline.neon
Labels: type: bug, team: nucleus

#2714 Issue #3260579 by chmez: Fix Social Profile Privacy settings
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.services.yml
  modules/social_features/social_profile/modules/social_profile_privacy/src/Service/SocialProfilePrivacyHelper.php
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, team: eci, prio: medium

#2739 [Internal] - Fix bahat test error. (recreated)
  tests/behat/features/capabilities/private-message/create-private-message.feature
Labels: type: bug, prio: high, team: nucleus

#2728 Issue #3261513 by nkoporec: Error: Call to undefined method Drupal\data_policy\DataPolicyConsentManager::hasGivenConsent()
  modules/custom/social_magic_login/src/Controller/MagicLoginController.php
  phpstan-baseline.neon
Labels: status: needs review, status: needs backport, team: gravitiers

#2685 Issue #3257730: Make strings translatable
  modules/custom/grequest/src/Plugin/GroupContentEnabler/GroupMembershipRequest.php
  modules/custom/social_file_private/social_file_private.install
  modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
  modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.install
  modules/social_features/social_content_block/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php
  modules/social_features/social_content_block/social_content_block.install
  modules/social_features/social_content_block/src/ContentBlockBase.php
  modules/social_features/social_core/social_core.install
  modules/social_features/social_embed/social_embed.install
  modules/social_features/social_event/social_event.install
  modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
  modules/social_features/social_group/modules/social_group_request/src/SocialGroupRequestConfigOverride.php
  modules/social_features/social_landing_page/social_landing_page.install
  modules/social_features/social_post/src/Entity/Post.php
  modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Labels: type: feature request, blocked: commit cleanup, translations, team: gravitiers

#2746 Issue #3259107 by Axael, tbsiqueira, navneet0693: Unable to install properly, undefined index warnings.
  modules/custom/social_lets_connect/modules/social_lets_connect_usage/src/Plugin/ShareUsageDataPlugin/ModulesInstalled.php
  modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, status: needs review, prio: high, team: nucleus

#2713 Issue #3260572: Filter groups on access on all-groups page.
  modules/social_features/social_group/social_group.module
  phpstan-baseline.neon
Labels: blocked: commit cleanup, status: needs review, team: gravitiers

#2760 Change order of update hooks
  modules/social_features/social_user/config/static/social_user_update_11006.yml
  modules/social_features/social_user/social_user.install
Labels: status: needs review, team: gravitiers

#2743 Issue #3262831: Remove deprecated Group hero setttings.
  modules/social_features/social_group/config/install/social_group.settings.yml
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  modules/social_features/social_group/src/SocialGroupHero.php
  phpstan-baseline.neon
Labels: status: needs review, team: gravitiers

#2711 Update PR 2710 to match restructure of alternative_frontpage module
  modules/custom/alternative_frontpage/src/Form/AlternativeFrontpageForm.php
Labels: team: gravitiers

#2774 Issue #3265075 by Ressinel: Profile fields that are not available on the platform should also not be visible in the user settings.
  modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
Labels: type: feature request, prio: medium, team: nucleus

#2766 Issue #3264208 by tBKoT: Do not send emails if related content does not exist
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
  modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
Labels: type: bug, team: eci, prio: high

#2756 Issue #3264287 by robertragas, Ressinel: Fix upgrading from Open Social 10 to 11 errors.
  composer.json
  modules/social_features/social_core/social_core.install
  modules/social_features/social_private_message/social_private_message.info.yml
  modules/social_features/social_private_message/social_private_message.install
  modules/social_features/social_private_message/social_private_message.module
  modules/social_features/social_private_message/src/Service/SocialPrivateMessageNotifier.php
  modules/social_features/social_private_message/src/SocialPrivateMessageServiceProvider.php
Labels: type: bug, type: update, status: needs review, type: dependencies, prio: critical, team: gravitiers, team: nucleus

#2782 Updated PHPStan.
  composer.json
  phpstan-baseline.neon
Labels: type: dependencies, team: nucleus

#2754 Issue #3262896 by tBKoT: Make entity_access_by_field type more usefull
  modules/custom/entity_access_by_field/entity_access_by_field.module
  modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php
  modules/custom/entity_access_by_field/src/EntityAccessHelper.php
  modules/custom/entity_access_by_field/tests/src/Unit/EntityAccessTest.php
  modules/social_features/social_group/social_group.module
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, status: needs review, prio: medium

#2764 Issue #3262433 by tbsiqueira: Create a new CM+ "quick access dashboard" for better user experience
  modules/custom/alternative_frontpage/alternative_frontpage.info.yml
  modules/custom/alternative_frontpage/alternative_frontpage.links.menu.yml
  modules/custom/social_gdpr/social_gdpr.links.menu.yml
  modules/social_features/social_comment_upload/social_comment_upload.links.menu.yml
  modules/social_features/social_content_report/social_content_report.links.menu.yml
  modules/social_features/social_core/assets/css/admin-toolbar.css
  modules/social_features/social_core/assets/css/admin-toolbar.css.map
  modules/social_features/social_core/assets/css/admin-toolbar.scss
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/social_core.links.menu.yml
  modules/social_features/social_core/social_core.permissions.yml
  modules/social_features/social_core/social_core.routing.yml
  modules/social_features/social_core/src/Controller/DashboardController.php
  modules/social_features/social_core/src/Plugin/Menu/HomepageConfigurationHeroBlockLink.php
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.links.menu.yml
  modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.links.menu.yml
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.links.menu.yml
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.links.menu.yml
  modules/social_features/social_event/modules/social_event_type/social_event_type.links.menu.yml
  modules/social_features/social_event/social_event.links.menu.yml
  modules/social_features/social_footer/social_footer.links.menu.yml
  modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.links.menu.yml
  modules/social_features/social_group/social_group.links.menu.yml
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.links.menu.yml
  modules/social_features/social_profile/social_profile.links.menu.yml
  modules/social_features/social_swiftmail/social_swiftmail.info.yml
  modules/social_features/social_swiftmail/social_swiftmail.links.menu.yml
  modules/social_features/social_tagging/social_tagging.links.menu.yml
  modules/social_features/social_user/social_user.links.menu.yml
Labels: type: feature request, status: needs work, blocked: release notes, blocked: LGOS documentation, prio: medium, team: nucleus

#2781 Issue #3266049 by Ressinel: Error during the update.php after updating to 11.0.3 with Composer
  modules/social_features/social_private_message/social_private_message.install
Labels: type: bug, status: needs backport, prio: critical, team: nucleus

#2783 Issue #3266096 by NickDaelemans, Ressinel, tbsiqueira, navneet0693: Adjusted update hooks in social_profile module to keep sync between Open Social 11.0.x and Open Social 11.1.x.
  modules/social_features/social_profile/config/static/core.entity_view_display.profile.profile.name_11007.yml
  modules/social_features/social_profile/config/static/core.entity_view_mode.profile.name_11007.yml
  modules/social_features/social_profile/social_profile.install
Labels: type: bug, status: needs review, status: needs backport, prio: critical, team: gravitiers
