Repository goalgorilla/open_social, pull requests merged in 2023-01, with the labels that each got.

#3271 Issue #3329802 by navneet0693: Organization tags display doesn't respect current language
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
Labels: type: bug, status: needs review, status: needs backport, prio: high, team: guardians

#3274 Internal: Removed unrequired if condition as per PHPStan analysis results.
  modules/social_features/social_group/social_group.module
Labels: type: code refactoring, prio: critical, internal, team: guardians

#3273 Internal: Remove redundant highlight dependency
  composer.json
Labels: status: needs review, status: needs backport, type: dependencies, prio: critical, internal, team: guardians

#3073 Issue #3304774 by vnech: Reordering categories in "Content Tags"
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
Labels: type: feature request, status: needs review, prio: medium, optional: review requested, team: finalizer, Hackaton

#3255 Issue #3174548 - revert - Disable the reliance on graphql_oauth as it breaks current implementations
  modules/custom/social_graphql/social_graphql.info.yml
  modules/custom/social_graphql/src/Plugin/GraphQL/Schema/OpenSocialBaseSchema.php
  modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
Labels: status: needs review, type: revert, status: needs backport, prio: high, team: guardians, Hackaton

#3063 Issue #3301508 by ribel: Allow to filter by Flexible groups in custom content list block
  modules/social_features/social_content_block/config/install/field.field.block_content.custom_content_list.field_group.yml
  modules/social_features/social_content_block/social_content_block.info.yml
  modules/social_features/social_content_block/social_content_block.install
Labels: team: enterprise, type: feature request, status: needs review, prio: medium, team: finalizer, Hackaton

#3277 Internal: Enable assertions in PHPUnit tests
  .github/workflows/qualityChecks.yml
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3154 Issue #3315177 by chmez: Extend group selection widget for any entity type
  modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, type: feature request, status: needs backport, prio: high, optional: review requested, team: finalizer

#3279 Update social.info.yml to reflect current Open Social version
  social.info.yml
Labels: prio: critical, blocked: mergeable, team: guardians

#3191 Issue #3318303 by rolki: Add support for allowed_values_function in entity_access_by_field
  modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, team: enterprise, status: needs review, prio: high, optional: review requested, team: falcon, Hackaton

#3283 Internal: Make behat output verbose in the CI
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3272 Issue #3330544 by nkoporec: Social follow taxonomy popup doesn't appear
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: type: bug, status: needs backport, prio: medium, team: guardians

#3292 Revert "Updates: (deps): Update drupal/swiftmailer requirement from 2.3.0 to 2.4.0"
  composer.json
Labels: blocked: mergeable

#3293 Issue #3334848 by zanvidmar: Add patch to fix the Drupal core issue #1236098
  composer.json
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3138 Internal: Ensure upgrade path is tested
  .github/workflows/behat.yml
  tests/behat/README.md
  tests/behat/behat.yml
  tests/behat/features/bootstrap/DatabaseContext.php
  tests/behat/features/bootstrap/LogContext.php
  tests/behat/features/bootstrap/ModuleContext.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/bootstrap/ThemeContext.php
  tests/behat/features/capabilities/account/verified-user.feature
  tests/behat/features/capabilities/administration/check-export-users-to-CSV.feature
  tests/behat/features/capabilities/administration/check-mail-users.feature
  tests/behat/features/capabilities/administration/check-people-page-elements.feature
  tests/behat/features/capabilities/administration/check-revoke-or-grant-administrador-roles.feature
  tests/behat/features/capabilities/event/all-day-timezone.feature
  tests/behat/features/capabilities/event/event-create.feature
  tests/behat/features/capabilities/event/event-invite-members.feature
  tests/behat/features/capabilities/event/lu-homepage-my-events.feature
  tests/behat/features/capabilities/gdpr/create-data-policy.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
  tests/behat/features/capabilities/groups/groups-create-closed.feature
  tests/behat/features/capabilities/groups/groups-create-secret.feature
  tests/behat/features/capabilities/groups/groups-edit-open.feature
  tests/behat/features/capabilities/groups/groups-invite-members.feature
  tests/behat/features/capabilities/groups/groups-mute-notify.feature
  tests/behat/features/capabilities/mention/mention-comment.feature
  tests/behat/features/capabilities/post/post-create-disabled.feature
  tests/behat/fixture/.gitignore
  tests/composer.json
Labels: team: external, status: needs review, prio: high, type: test, type: improvement, Hackaton

#3295 Internal: Update github workflows to make our tests work with development branches
  .github/workflows/behat.yml
Labels: status: needs review, prio:low, blocked: mergeable, team: guardians

#3237 Issue #3325955 by navneet0693: Profile pictures missing on landing page content type.
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, status: needs review, prio: high, team: gravitiers

#3288 Issue #3333919 by vnech: Duplicated messages in "Notification Center"
  modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, status: needs review, prio: high

#3297 Issue #3336391: Allowing content tagging on Profile using the Settings Form incorrectly clears cache tags and could result in Unexpected Error
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
Labels: type: bug, status: needs review, status: needs backport, prio: medium, team: gravitiers

#3257 Issue #3326663 by vnech: Replace default group invite email message
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
  modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
Labels: type: code refactoring, team: enterprise, prio: medium, status: no action needed, type: improvement, Hackaton

#3300 Internal: Improve test asset naming and contents
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio: medium, type: improvement
