Repository goalgorilla/open_social, pull requests merged in 2023-08, with the labels that each got.

#3472 Issue #3378480 by nkoporec: Cannot reply to a comment reply
  modules/social_features/social_mentions/social_mentions.module
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3483 Issue #3378480 by nkoporec: Add tests for #3378480
  tests/behat/features/capabilities/comment/comment-reply-to-thread.feature
Labels: status: needs review, prio: medium, type: test, team: guardians, needs: behat review

#3482 Issue #3342642: Update variables for email template to pass border-radius config
  modules/social_features/social_swiftmail/social_swiftmail.module
Labels: type: bug, team: enterprise, prio: medium

#3475 Issue #3069371: Change preview token for comment and post to fix mentions in emails
  modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
  modules/social_features/social_activity/social_activity.services.yml
  modules/social_features/social_activity/src/EmailTokenServices.php
  modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3487 Issue #3382816: Revert search_api_language filter ID change in search views
  modules/social_features/social_search/config/install/search_api.index.social_all.yml
  modules/social_features/social_search/config/install/views.view.search_all.yml
  modules/social_features/social_search/config/install/views.view.search_content.yml
  modules/social_features/social_search/config/install/views.view.search_groups.yml
  modules/social_features/social_search/social_search.install
Labels: type: bug, team: bananas, status: needs review, prio: critical

#3489 Internal: Allow debugging mail spool for failed tests
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio:low, type: improvement

#3493 Issue #3383704: cache improvements for `hook_entity_extra_field_info()` and `EntityFieldManager::getExtraFields()`
  composer.json
Labels: status: needs review, type: performance, prio: high, team: nucleus, type: improvement

#3494 Issue #3383079: Hotfix: Fix view name for groups search
  modules/social_features/social_search/social_search.install
Labels: type: bug, team: bananas, prio: critical, needs: behat review
