Repository goalgorilla/open_social, pull requests merged in 2023-07, with the labels that each got.

#3442 Issue #3370849 by nkoporec: Can't add an image to the existing album on stream page
  modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
  tests/behat/behat.yml
  tests/behat/features/bootstrap/AlbumContext.php
  tests/behat/features/capabilities/post/post-album-existing.feature
Labels: type: bug, status: needs review, prio: medium, team: guardians, needs: behat review

#3455 Internal: Add a new Behat step that tests for an exact number of times a text is present in a given selector
  tests/behat/features/bootstrap/SocialMinkContext.php
Labels: team: bananas, prio:low, type: test, internal, status: no action needed

#3448 Internal: Fix non blocking error on the Spell Check action
  cspell.json
Labels: prio: high, team: shipsters, status: no action needed, type: improvement

#3458 Internal: Put back the baseline for cspell
  cspell.baseline.txt
  cspell.json
Labels: status: needs review, prio: high, team: shipsters, internal, type: improvement

#3392 Issue #3358171 : Multilanguage: Activity stream items are not showing in the correct language
  modules/custom/activity_creator/activity_creator.module
Labels: type: bug, status: needs review, prio: high, needs: test, team: guardians

#3460 Issue #3373172 by tbsiqueira: Update our tugboat docker image with one supporting PHP 8.1
  .tugboat/config.yml
Labels: status: needs review, prio: high, type: dependencies, needs: test, team: guardians

#3463 Issue #3276434 by v.koval: Add condition if all day is activated and current date is equal to the end date
  modules/social_features/social_event/src/SocialEventTrait.php
Labels: type: bug, team: enterprise, prio: medium, status: no action needed

#3468 Internal: Remove duplicate array key profile_class in EmailTokenServices
  modules/social_features/social_activity/src/EmailTokenServices.php
Labels: team: enterprise, type: revert, prio: high, internal

#3469 Internal: Backport AvoidCleanupTrait to 11.9.x
  .github/workflows/behat.yml
  tests/behat/behat.yml
  tests/behat/features/bootstrap/AvoidCleanupTrait.php
  tests/behat/features/bootstrap/ConfigContext.php
  tests/behat/features/bootstrap/DatabaseContext.php
  tests/behat/features/bootstrap/EmailContext.php
  tests/behat/features/bootstrap/EntityTrait.php
  tests/behat/features/bootstrap/EventContext.php
  tests/behat/features/bootstrap/FeatureContext.php
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/bootstrap/PostContext.php
  tests/behat/features/bootstrap/SocialDrupalContext.php
  tests/behat/features/bootstrap/SocialMessageContext.php
  tests/behat/features/bootstrap/TopicContext.php
  tests/behat/features/capabilities/dev-helpers/fail.feature
  tests/behat/features/capabilities/dev-helpers/pass.feature
Labels: status: needs review, type: revert, prio: high, internal, team: guardians
