Repository goalgorilla/open_social, pull requests merged in 2023-09, with the labels that each got.

#3479 Issue #2924783: Fix error on entity autocomplete widget if entity label contains parentheses
  composer.json
Labels: type: bug, team: enterprise, status: needs review, prio:low

#3518 Issue #3386542 by nkoporec: Update drupal/csv_serialization from 2.x to 3.x
  composer.json
Labels: type: update, prio: medium, needs: test, team: guardians

#3515 Issue #3386141 by nkoporec: Update drupal/config_update from 1.7 to 2.0.0-alpha3
  composer.json
Labels: type: update, prio: medium, needs: test, team: guardians

#3519 Issue #3386579: Update url_embed to 2.0.0-alpha1
  composer.json
Labels: type: update, prio: high, needs: test, team: guardians

#3526 Revert "Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.3"
  composer.json
  modules/custom/gvbo/src/Plugin/views/field/GroupViewsBulkOperationsBulkForm.php
  modules/social_features/social_core/src/Controller/SocialCoreController.php
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/modules/social_group_gvbo/src/Access/SocialGroupViewsBulkOperationsAccess.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
  phpstan-baseline.neon
Labels: status: needs review, type: revert, prio: critical, team: guardians

#3527 Hotfix: Revert wrongly removed views_bulk_operations with commit d1abf916f
  composer.json
Labels: type: revert, prio: critical, status: no action needed, team: guardians

#3513 Issue #3386004 Update dynamic_entity_reference to 3.0.0
  composer.json
Labels: type: update, prio: high, status: no action needed, team: guardians

#3509 Issue #3385634 by nkoporec: Inline images are not displaying in social footer block
  tests/behat/features/capabilities/footer/inline-image.feature
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3476 Issue #3380523 by SV: Fix untranslated CTA token in email notifications for multilingual sites
  modules/custom/activity_creator/src/ActivityFactory.php
  modules/social_features/social_activity/social_activity.tokens.inc
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_content_report/social_content_report.tokens.inc
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
  modules/social_features/social_group/modules/social_group_request/social_group_request.tokens.inc
  modules/social_features/social_group/social_group.tokens.inc
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_mentions/social_mentions.tokens.inc
  modules/social_features/social_private_message/social_private_message.tokens.inc
Labels: type: bug, team: enterprise, status: needs review, prio: high, translations

#3520 Issue #3386735 - Update the Data Policy module to be compatible with D10
  composer.json
Labels: status: needs review, prio: high, type: dependencies, needs: test, team: guardians

#3500 Internal: Restructure EmailContext to provide better debug information
  tests/behat/features/bootstrap/EmailContext.php
  tests/behat/mail-spool/.gitignore
Labels: team: bananas, status: needs review, prio: medium, type: test

#3536 Issue #3388607: Remove social_tour from distribution.
  composer.json
Labels: type: update, status: needs review, prio: medium, type: dependencies, team: guardians

#3504 Issue #3384825 by Kingdutch: Update metatag settings using config/modify
  modules/custom/social_metatag/config/install/metatag.settings.yml
  modules/custom/social_metatag/config/modify/social_metatag.metatag_settings.yml
  modules/custom/social_metatag/social_metatag.info.yml
Labels: type: bug, team: bananas, prio: high

#3507 Issue #3385398 by Kingdutch: Optimize menu link loading for module installs
  modules/social_features/social_activity/social_activity.install
  modules/social_features/social_event/social_event.install
  modules/social_features/social_group/social_group.install
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_topic/social_topic.install
  phpstan-baseline.neon
Labels: type: bug, team: bananas, status: needs review, prio: medium

#3506 Issue #3385341 by Kingdutch: Uninstall admin_toolbar_tools and remove from default installation
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_core/tests/modules/social_core_test/social_core_test.info.yml
Labels: type: bug, team: bananas, status: needs review, prio: high

#3481 Issue #3381157: Deprecate SocialProfileTrait ahead of removal
  modules/social_features/social_profile/src/SocialProfileTrait.php
  phpstan-baseline.neon
Labels: team: bananas, type: code refactoring, status: needs review, prio: medium

#3529 Issue #3382821: Remove deprecated hooks
  modules/custom/entity_access_by_field/entity_access_by_field.module
  modules/social_features/social_core/social_core.module
  modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_profile/social_profile.module
  phpstan-baseline.neon
Labels: type: update, status: needs review, prio: high, team: guardians

#3540 Issue #3390191 by v.koval: Fix error on Event Date filter when Social Geolocation and Event Map is enabled
  modules/social_features/social_event/src/Plugin/views/filter/EventDate.php
Labels: type: bug, team: enterprise, status: needs review, prio: high
