Repository goalgorilla/open_social, pull requests merged in 2023-11, with the labels that each got.

#3593 Issue #3398808: Memory exhausted to search content by tag
  modules/social_features/social_tagging/social_tagging.module
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3594 Issue #3398931: Grant content translate permissions
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.book_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.data_policy_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.event_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.flexible_group_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.landing_page_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.page_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.topic_translation_permissions.yml
  modules/custom/social_language/modules/social_content_translation/social_content_translation.info.yml
Labels: type: bug, status: needs review, prio: high, team: iata

#3583 Issue #3397762: Define entity_access_by_field permissions for all entity types
  modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php
Labels: type: bug, status: needs review, prio: high, team: iata

#3598 Issue #3386542 by nkoporec part 2: Update drupal/csv_serialization to 4.x
  composer.json
Labels: type: update, prio: critical, team: guardians

#3599 Issue #3399456: by ronaldtebrake: Update `drupal/update_helper` In order to support Drush 12
  composer.json
Labels: type: update, prio: high, status: no action needed, team: guardians

#3572 Issue #3396860: Change roles of the selected members in a Group does not change the role from Group Admin to a Group Manager and vice versa
  modules/social_features/social_group/config/install/views.view.group_manage_members.yml
  modules/social_features/social_group/config/update/social_group_update_12001.yml
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Plugin/Action/ChangeGroupMembershipRole.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3596 Issue #3398305 Move view node.book.field_content_visibility:group con…
  modules/social_features/social_book/social_book.install
  modules/social_features/social_group/social_group.install
Labels: type: bug, status: needs review, prio: high, team: iata

#3600 Issue #3399843 by agami4: Improve width of the group filter on the admin/people page
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css.map
  modules/social_features/social_user/assets/css/views-exposed-form--admin-people.scss
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3592 Issue #3398750 by nkoporec: Can't select a group when creating a content list block and using the event content type
  modules/social_features/social_content_block/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_group.yml
  modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.install
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3609 Issue #3402403 - Replying on a Post gives an unexpected error.
  modules/social_features/social_post/src/Controller/PostCommentController.php
  phpstan-baseline.neon
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3585 Issue #3398146: CKEditor 5 isn't respecting width limit
  composer.json
Labels: type: bug, prio: high, status: no action needed, team: guardians

#3611 Internal: Update our `goalgorilla/open_social_docker` images to Drupal 10
  .github/workflows/behat.yml
Labels: type: update, prio: high, type: dependencies, internal, team: guardians

#3605 Issue #3402176: Add Social Media System module (social_media_system)
  modules/custom/social_media_system/README.md
  modules/custom/social_media_system/config/install/field.storage.media.field_media_file.yml
  modules/custom/social_media_system/social_media_system.info.yml
Labels: type: feature request, status: needs review, prio: high, team: iata

#3615 Issue #3402882: Deprecated message for Social GraphQL module for PHP8.1
  modules/custom/social_graphql/src/GraphQL/Violation.php
Labels: status: needs review, prio: high, type: improvement, team: guardians

#3613 Issue #3402841 by SV: Undefined array key "entity" during export of enrolment user data
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserDisplayName.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserEmail.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserFirstName.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserLastName.php
  modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserRegistration.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3584 Issue #3397809: Enter key does not work to send a private message
  composer.json
Labels: type: bug, status: needs review, prio: high, needs: test, team: guardians

#3622 Internal: Analyse GraphQL\Violation with PHPStan
  phpstan.neon
Labels: status: needs review, prio:low, internal, type: improvement, team: guardians

#3621 Issue #3404072: PHP error when has comment on page
  modules/custom/social_ajax_comments/social_ajax_comments.module
Labels: type: bug, status: needs review, prio: high, team: guardians

#3620 Issue #3403980: Add default media teaser view mode
  modules/custom/social_media_system/config/install/core.entity_view_mode.media.teaser.yml
Labels: type: feature request, status: needs work, prio: high, team: iata

#3619 Issue #3403776 by SV: "Unique nicknames" setting should result in error message instead of "unexpected error" during registration
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNickname.php
  modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNicknameValidator.php
  tests/behat/features/capabilities/profile/unique-nickname.feature
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3624 Issue #3404422 by SV: Is not possible to translate a title on the "Add event" page
  modules/social_features/social_core/src/Controller/SocialCoreController.php
  modules/social_features/social_event/social_event.module
Labels: type: bug, team: enterprise, status: needs review, prio:low
