Repository goalgorilla/open_social, pull requests merged in 2023-06, with the labels that each got.

#3414 Issue #3364059 by zanvidmar: Add access check for entity queries
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Labels: type: bug, status: needs review, prio: high, team: guardians

#3411 Issue #3354659 by zanvidmar: Fix status message on "Manage enrollments" actions
  modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
Labels: type: bug, status: needs review, prio: medium, needs: test, team: guardians

#3412 Internal: #3363814 by zanvidmar: Behat step definition to enroll users to event
  tests/behat/features/bootstrap/EventContext.php
Labels: type: feature request, status: needs review, prio: medium, team: guardians, needs: behat review

#3417 Issue #3365299 by vnech: Allow for guest event enrollers add event to iCal calendar
  modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.routing.yml
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3419 Hotfix: Broken behat tests
  tests/behat/features/capabilities/groups/flexible/groups-flexible-views-order.feature
Labels: type: bug, team: enterprise, status: needs review, prio: high, needs: behat review

#3418 Issue #3365307 by agami4: Add improvements to the accordion collapse behavior
  modules/social_features/social_landing_page/js/social_landing_page--accordion.js
  modules/social_features/social_landing_page/social_landing_page.libraries.yml
Labels: type: bug, team: enterprise, status: needs review, prio:low

#3420 Updates: Like & Dislike module from dev to fixed version 1.0-beta3
  composer.json
Labels: team: enterprise, type: update, prio: high

#3416 Issue #3365270 by agami4: Add improvements to the `Unfollow` button on the stream teasers
  modules/social_features/social_follow_taxonomy/assets/css/activity-followed.css
  modules/social_features/social_follow_taxonomy/assets/css/activity-followed.scss
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3421 Issue #3366143 by agami4: Add improvements to the profile preview window
  modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.libraries.yml
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3427 Internal: Separate previous version install in GitHub CI
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3430 Internal: Set Behat CI install dump names depending on job configuration
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio: critical, type: improvement

#3431 Internal: Fix false positives in CIs
  tests/behat/features/capabilities/administration/check-revoke-or-grant-administrador-roles.feature
  tests/behat/features/capabilities/groups/groups-create-closed.feature
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3422 Issue #3366231 by zanvidmar: Profile organization tag with special characters not displayed correctly
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
  phpstan-baseline.neon
  tests/behat/features/capabilities/profile/profile-organization-tag.feature
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3425 Internal: Add Behat tests for "Add to calendar" feature
  tests/behat/features/bootstrap/EventContext.php
  tests/behat/features/bootstrap/FileContext.php
  tests/behat/features/capabilities/event/add-to-calendar.feature
Labels: team: enterprise, prio:low, status: no action needed, type: improvement

#3436 Internal: Ensure the mail-spool directory exists for Behat tests
  .github/workflows/behat.yml
  tests/behat/features/bootstrap/EmailContext.php
  tests/behat/mail-spool/.gitignore
Labels: team: bananas, status: needs review, prio: medium, type: improvement

#3437 Issue #3369035: Notification entity conditions can not rely on other template configuration
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
Labels: type: bug, team: bananas, status: needs review, prio: high
