Repository goalgorilla/open_social, pull requests merged in 2023-10, with the labels that each got.

#3535 Issue #3388559: Apply patch at Private Message module to be compatible with D10
  composer.json
Labels: type: update, prio: high, team: guardians

#3484 Internal: Fix the Add to iCall feature spellchecker quality control
  cspell.words.txt
  modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3551 Issue #3388607: Remove social_tour from distribution.
  composer.json
Labels: type: revert, prio: medium, status: no action needed, team: guardians

#3556 Issue #3393846: Update `drupal/profile` requirement from 1.4.0 to 1.7.0
  composer.json
Labels: type: update, status: needs review, prio: high, team: guardians

#3567 Issue #3396251 by ronaldtebrake: PHP 8.1 will be required, so remove PHP 8.0 checks
  .github/workflows/qualityChecks.yml
Labels: status: needs review, prio: critical, type: improvement, team: guardians

#3568 Issue #3386141 - Hidden dependency for config_update forced php 8.1
  composer.json
Labels: type: bug, status: needs review, type: dependencies, prio: critical, team: guardians

#3563 Issue #3395680: Improve permissions for social_follow_taxonomy
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.install
Labels: type: bug, status: needs review, prio: high, team: iata

#3566 Internal: Update minimal required version of Socialblue to 2.5.4
  composer.json
Labels: status: needs review, type: dependencies, prio: critical, needs: test, team: iata

#3570 Internal: Test hardening: Set a UTC timezone when creating dates in our behat suite
  tests/behat/features/bootstrap/EntityTrait.php
Labels: status: needs review, prio: high, type: improvement, team: guardians

#3569 Issue #3396674 by SV: Error on edit or create events and topics pages
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/SocialTaggingService.php
  modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
Labels: type: bug, team: enterprise, status: needs review, prio: high

#3571 Issue #3388559 - Update `drupal/private_message` to stable 3.0.0
  composer.json
  modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageOwnerFormatter.php
  modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageThreadMemberFormatter.php
  modules/social_features/social_private_message/src/Plugin/Field/FieldWidget/SocialPrivateMessageThreadMemberWidget.php
  phpstan-baseline.neon
Labels: type: update, prio: critical, status: no action needed, team: guardians

#3582 Issue #3391286 - Move to ckeditor4 contrib module
  composer.json
  modules/social_features/social_editor/social_editor.info.yml
Labels: status: needs review, prio: high, type: dependencies, team: guardians

#3581 Issue #3397613 - Replace the ckeditor4 core modules with the contrib one
  composer.json
  modules/social_features/social_editor/social_editor.info.yml
Labels: status: needs review, prio: high, type: dependencies, team: guardians

#3577 Internal: Set stable versions for open_social_upgrade_patches
  composer.json
Labels: team: enterprise, type: update, status: needs review, prio: medium, internal

#3579 Issue #3397252: Moved the color module to out of Drupal-Core
  composer.json
  social.info.yml
Labels: status: needs work, type: update, prio: high, needs: test, team: guardians
