Repository goalgorilla/open_social, pull requests merged in 2023-04, with the labels that each got.

#3366 Issue #3351588 by zanvidmar: Wrong number of items on Custom content list block
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_content_block/src/ContentBuilderInterface.php
Labels: type: bug, status: needs work, prio: high, team: guardians

#3333 Issue #3346912 by zanvidmar: Profile pictures missing on landing page
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, prio: medium, team: guardians

#3373 Issue #3341238: Fix wrong patch url on main
  composer.json
Labels: type: code refactoring, status: needs review, prio: critical, team: guardians

#3371 Issue #3353190 by ribel: Add Header top region to the Landing page template
  modules/social_features/social_landing_page/templates/page--node--landing-page.html.twig
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3362 Issue #3350702 by SV: Update popovers theme configs
  modules/social_features/social_core/config/update/social_core_update_11801.yml
  modules/social_features/social_core/social_core.install
Labels: type: bug, team: enterprise, status: needs review, prio: medium, team: finalizer, internal

#3364 Issue #3350838 by vnech: Error blocked the "Activity Creator" cron job
  modules/social_features/social_group/src/SocialGroupHelperService.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3370 Issue #3351838 by SV: Fix missed filter block on the all-members page
  modules/social_features/social_profile/config/install/views.view.newest_users.yml
  modules/social_features/social_profile/config/update/social_profile_update_11701.yml
  modules/social_features/social_profile/social_profile.install
Labels: type: bug, team: enterprise, status: needs review, prio: medium, team: finalizer

#3365 Issue #3351326 by vnech: Skip activities creation during content migration
  composer.json
  modules/custom/activity_basics/activity_basics.module
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
  phpstan-baseline.neon
Labels: team: enterprise, status: needs review, prio: medium, type: improvement

#3383 Issue #3355958: Improve the stream block on the landing page
  modules/social_features/social_landing_page/css/social_landing_page.section.block.css
  modules/social_features/social_landing_page/css/social_landing_page.section.block.css.map
  modules/social_features/social_landing_page/css/social_landing_page.section.block.scss
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3380 Issue #3355356 by SV: Prevent duplicated logo images on the Files page
  modules/social_features/social_footer/src/Plugin/Block/SocialFooterPoweredByBlock.php
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3385 Issue #3355315 by ronaldtebrake: Ensure we check for the mute notification flag and provide a session id for AN users.
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/GroupMuteNotify.php
  modules/social_features/social_group/tests/src/Unit/GroupNotifyTest.php
  phpstan-baseline.neon
  phpstan.neon
Labels: type: bug, team: external, status: needs review, prio: high

#3386 Issue #3356324 by SV: Fix duplicated names of "Activity Stream: Homepage stream block"
  modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
  modules/social_features/social_activity/config/update/social_activity_update_11701.yml
  modules/social_features/social_activity/social_activity.install
Labels: type: bug, team: enterprise, status: needs review, prio:low, team: finalizer
