Repository goalgorilla/open_social, pull requests merged in 2023-03, with the labels that each got.

#3320 Issue #3344207 by nkoporec: Alternative frontpage settings causes an endless redirect loop
  modules/custom/alternative_frontpage/alternative_frontpage.services.yml
  modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
Labels: type: bug, prio: high, team: guardians

#3330 Internal: Dump pre-update database to GitHub artifact
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio:low, type: improvement

#3331 Internal: Split flexible group content test across multiple GitHub Jobs
  tests/behat/features/capabilities/groups/flexible/content/view/member/groups-flexible-content-view-member.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-anonymous/groups-flexible-content-view-outsider-anonymous.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-authenticated/groups-flexible-content-view-outsider-authenticated.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-contentmanager/groups-flexible-content-view-outsider-contentmanager.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-sitemanager/groups-flexible-content-view-outsider-sitemanager.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-verified/groups-flexible-content-view-outsider-verified.feature
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3325 Issue #3344980 by agami4: Reset extra styles for the Follow tags block
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.css.map
  modules/social_features/social_follow_taxonomy/assets/css/paragraph_tag.scss
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.css
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.css.map
  modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/assets/css/paragraph_tag.scss
Labels: type: bug, team: enterprise, status: needs review, prio:low, team: finalizer

#3317 Issue #3343419 by chmez: Allow few content tags fields per entity
  modules/social_features/social_book/social_book.module
  modules/social_features/social_event/social_event.module
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_page/social_page.module
  modules/social_features/social_tagging/social_tagging.api.php
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/social_tagging.services.yml
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
  modules/social_features/social_topic/social_topic.module
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, type: feature request, status: needs review, prio: high, team: finalizer

#3321 Issue #3344237 by kashandarash: Add notification support for config entity
  modules/custom/activity_creator/src/Entity/Activity.php
  modules/custom/activity_creator/src/Plugin/ActivityActionBase.php
  modules/custom/activity_creator/src/Plugin/ActivityActionInterface.php
  modules/custom/activity_logger/activity_logger.module
  modules/custom/activity_logger/src/Entity/NotificationConfigEntityBase.php
  modules/custom/activity_logger/src/Entity/NotificationConfigEntityInterface.php
  modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
  phpstan-baseline.neon
Labels: type: code refactoring, team: enterprise, prio: medium, type: improvement

#3123 Issue #3311262 by chmez: Better exclude some users from notification recipients
  modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
Labels: type: code refactoring, team: enterprise, type: feature request, status: needs review, prio: high, optional: review requested, team: finalizer, Hackaton

#3305 Issue #3339566 by vnech: Entity access is ignoring in "Custom content list block" block type
  modules/social_features/social_content_block/social_content_block.services.yml
  modules/social_features/social_content_block/src/ContentBuilder.php
  modules/social_features/social_content_block/src/ContentBuilderInterface.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3334 Internal: Only try to move test results if they exist
  .github/workflows/behat.yml
Labels: team: bananas, status: needs review, prio: high, type: improvement

#3336 Issue #3347315 by bramtenhove: Move execution of expensive invitation data to when it is needed for sending notifications
  modules/social_features/social_core/src/EventSubscriber/SocialInviteSubscriber.php
Labels: type: performance, prio: high, team: guardians

#3346 Issue #3348279 - Fix config override for Event Invite
  modules/social_features/social_event/modules/social_event_invite/src/SocialEventInviteConfigOverride.php
Labels: status: needs review, type: performance, prio: medium, team: guardians

#3335 Issue #3346966 by ronaldtebrake: Social Content Translation Config Override runs in unnecessary circumstances.
  modules/social_features/social_core/src/ContentTranslationConfigOverrideBase.php
  phpstan-baseline.neon
Labels: type: bug, status: needs work, type: performance, prio: high, team: guardians

#3347 Issue #3348281 - Fix expensive calls in config override of Social Follow Tag
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagOverrides.php
Labels: type: performance, prio: medium, team: guardians

#3340 Issue #3348274 - Add static caching for the user_format_name_alter hook
  modules/social_features/social_user/social_user.module
Labels: status: needs review, type: performance, prio: high, team: guardians

#3352 Internal: Add CI check to prevent Config Overrides being added
  .github/workflows/bestPractices.yml
Labels: team: bananas, status: needs review, prio: medium, type: improvement

#3342 Issue #3347940 by vnech: Group "/books" and "/albums" pages are visible for non-allowed users
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/src/Controller/SFGBController.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Subscriber/Route.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3338 Issue #3347592 by agami4: Improve layout of the blocks on the landing page
  modules/social_features/social_landing_page/social_landing_page.module
  modules/social_features/social_landing_page/templates/paragraph--custom-content-list.html.twig
  modules/social_features/social_landing_page/templates/paragraph--custom-multiple-content-list.html.twig
Labels: type: bug, team: enterprise, status: needs review, prio:low

#3332 Issue #3346744 by chmez: Activity without a message
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.module
  phpstan-baseline.neon
Labels: type: bug, type: code refactoring, team: enterprise, status: needs review, prio: medium

#3344 Issue #3348269 - Fix config override for Group Invite
  modules/social_features/social_group/modules/social_group_invite/src/SocialGroupInviteConfigOverride.php
Labels: status: needs review, type: performance, prio: medium, team: guardians

#3343 Issue #3348272 - Fix config override cache gets for Social Comment Upload
  modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
Labels: status: needs review, type: performance, prio: medium, team: guardians

#3361 Issue #3350671 by nkoporec: Pager not working in Albums
  modules/social_features/social_album/config/install/views.view.albums.yml
  modules/social_features/social_album/config/update/social_album_update_11471.yml
  modules/social_features/social_album/social_album.install
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3351 Issue #3348717 by SV: Embed Preview throws 403 forbidden - Embed now requires a csrf token
  composer.json
Labels: type: bug, team: enterprise, status: needs review, prio: high
