Repository goalgorilla/open_social, pull requests merged in 2024-05, with the labels that each got.

#3883 Issue #3444422: Display group types taxonomy terms on group teasers
  modules/social_features/social_group/modules/social_group_request/social_group_request.module
  modules/social_features/social_group/social_group.module
  phpstan-baseline.neon
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3889 Issue #3445166: Remove outdated patch from Drupal Core
  composer.json
Labels: type: bug, status: needs review, prio: high, type: dependencies

#3875 Issue #3442690: Rename "Basic Page" content type label into "Page"
  modules/social_features/social_page/config/install/node.type.page.yml
  modules/social_features/social_page/config/update/social_page_update_130001.yml
  modules/social_features/social_page/social_page.install
  tests/behat/features/capabilities/landing-page/custom-content-list.feature
  tests/behat/features/capabilities/page/page-create.feature
Labels: team: enterprise, prio: low, type: repository, status: needs merge

#3890 Issue #3445409: Remove expensive entity loads for the event enrollments counter
  modules/social_features/social_event/social_event.tokens.inc
  modules/social_features/social_event/src/EventEnrollmentStatusHelper.php
Labels: team: enterprise, status: needs review, type: performance, prio: medium

#3884 Issue #3444432: Always display "Type" field on group add/edit pages
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
  phpstan-baseline.neon
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/capabilities/groups/groups-view-overview-filter.feature
Labels: team: enterprise, type: feature, prio: medium, status: needs merge

#3888 Issue #3445024: Change labels of invitations to join a Group
  modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
  translations.php
Labels: type: bug, team: enterprise, status: needs review, prio: low

#3896 Issue #3445981: Solr: Ensure we only run the update hook if the server doesn't exist
  modules/social_features/social_search/social_search.install
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3878 Issue #3420070: Remove Drupal\social_group\Form\SocialGroupAddForm
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.module
  modules/social_features/social_group/src/Form/SocialGroupAddForm.php
  modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
  modules/social_features/social_group/src/Routing/RouteSubscriber.php
  modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
  phpstan-baseline.neon
  phpstan.neon
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/capabilities/activity-stream/create-topic-event.feature
  tests/behat/features/capabilities/groups/groups-edit-join-method-flexible.feature
  tests/behat/features/capabilities/groups/groups-revisions-disabled.feature
  tests/behat/features/capabilities/post/post-create-disabled.feature
  tests/behat/features/capabilities/post/post-group.feature
  tests/behat/features/capabilities/profile/restricted-full-name.feature
Labels: type: refactoring, team: enterprise, prio: medium, status: needs merge

#3833 Issue #3436013: Fix sidebar blocks display in flexible groups
  modules/social_features/social_event/config/update/social_event_update_130001.yml
  modules/social_features/social_event/social_event.install
  modules/social_features/social_topic/config/update/social_topic_update_130001.yml
  modules/social_features/social_topic/social_topic.install
  tests/behat/features/capabilities/groups/flexible/groups-flexible-sidebar-blocks.feature
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3847 Issue #3438906: Add "Edit" link on Album page
  modules/social_features/social_album/social_album.module
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3897 Issue #3446480: Group manager block marking every joined member as manager
  modules/social_features/social_group/config/optional/views.view.group_managers.yml
  modules/social_features/social_group/config/update/social_group_update_13007.yml
  modules/social_features/social_group/social_group.install
Labels: type: bug, status: needs review, prio: high, team: guardians

#3898 Issue #3421348: Remove redundant "Group type" filter
  modules/social_features/social_group/config/install/views.view.newest_groups.yml
  modules/social_features/social_group/config/update/social_group_update_13008.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/social_group.install
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3899 During the update to OS-13 we have added a filter with 'flexible_grou…
  modules/social_features/social_group/social_group.install
Labels: status: needs review, prio: critical, team: guardians

#3895 Issue #3445957: Organization field doesn't appear on registration field settings
  modules/social_features/social_profile/social_profile.module
Labels: type: bug, status: needs review, prio: high, team: guardians

#3880 Issue #3443501: Make the end date of the event required
  modules/social_features/social_event/config/install/field.field.node.event.field_event_date_end.yml
  modules/social_features/social_event/config/update/social_event_update_130002.yml
  modules/social_features/social_event/social_event.install
  tests/behat/features/capabilities/administration/check-export-users-to-csv.feature
  tests/behat/features/capabilities/event/eventenrollment-manage.feature
  tests/behat/features/capabilities/event/eventenrollment.feature
  tests/behat/features/capabilities/groups/flexible/content/edit/group-manager/groups-flexible-content-edit-group-manager.feature
  tests/behat/features/capabilities/groups/flexible/content/edit/member/groups-flexible-content-edit-member.feature
  tests/behat/features/capabilities/groups/flexible/content/edit/outsider-platform-manager/groups-flexible-content-edit-outsider-platform-manager.feature
  tests/behat/features/capabilities/groups/flexible/content/edit/outsider/groups-flexible-content-edit-outsider.feature
  tests/behat/features/capabilities/groups/flexible/content/view/member/groups-flexible-content-view-member.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-anonymous/groups-flexible-content-view-outsider-anonymous.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-authenticated/groups-flexible-content-view-outsider-authenticated.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-contentmanager/groups-flexible-content-view-outsider-contentmanager.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-sitemanager/groups-flexible-content-view-outsider-sitemanager.feature
  tests/behat/features/capabilities/groups/flexible/content/view/outsider-verified/groups-flexible-content-view-outsider-verified.feature
Labels: team: enterprise, type: feature, prio: medium, status: needs merge

#3901 PROD-25979: Remove obsolete test for event enrollment
  tests/behat/features/capabilities/event/eventenrollment.feature
Labels: team: enterprise, status: needs review, prio: low, type: test

#3842 Issue #3437859: Add new implementation for the profile preview
  modules/social_features/social_core/assets/css/preview-el.css
  modules/social_features/social_core/assets/css/preview-el.scss
  modules/social_features/social_core/assets/css/preview-popup.css
  modules/social_features/social_core/assets/css/preview-popup.scss
  modules/social_features/social_core/assets/js/preview-popup.js
  modules/social_features/social_core/templates/preview-popup.html.twig
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.css.map
  modules/social_features/social_profile/modules/social_profile_preview/assets/css/social_profile_preview.scss
  modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
  modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.libraries.yml
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
  modules/social_features/social_profile/modules/social_profile_preview/templates/profile--profile--preview.html.twig
Labels: type: refactoring, team: enterprise, status: needs review, prio: low

#3885 Issue #3444592: Replace permission `administer taxonomy` with `access taxonomy overview` for SM
  modules/social_features/social_core/social_core.install
  modules/social_features/social_event/modules/social_event_type/social_event_type.install
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
  modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.install
  modules/social_features/social_profile/social_profile.install
  modules/social_features/social_tagging/social_tagging.install
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3893 Issue #3445902: Apply static caching to the SocialPrivateMessageService
  modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php
Labels: status: needs review, type: performance, prio: low, team: guardians

#3903 Issue #3444592 - Revert removal of administer taxonomy permission for SM.
  modules/social_features/social_core/social_core.install
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3910 Hotfix: inline images converted to secret file system
  modules/social_features/social_core/social_core.install
Labels: type: bug, scope: community management system, status: needs review, prio: critical, team: guardians

#3909 Issue #3450286: Fix pewview element on the general and hover states
  modules/social_features/social_core/assets/css/preview-el.css
  modules/social_features/social_core/assets/css/preview-el.scss
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3914 Issue #3450914: Prevent fatal error on "Notification center" if flagging entity was accidentally deleted
  modules/custom/activity_creator/src/Entity/Activity.php
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3911 Hotfix: Decode filepath for cached secret file requests
  modules/custom/secret_file_system/src/Controller/SecretFileController.php
Labels: type: bug, scope: community management system, status: needs review, prio: critical, team: guardians
