Repository goalgorilla/open_social, pull requests merged in 2024-04, with the labels that each got.

#3836 Internal: Improve test fixture creation for group references
  tests/behat/features/bootstrap/EntityTrait.php
Labels: prio: high, internal, type: improvement, team: iata

#3844 Issue #3438071: Remove patch with update to Drupal 10.2.5
  composer.json
Labels: team: enterprise, type: dependencies, prio: critical

#3853 Issue #3439600: Update hook social_event update hook 121001 and 121002 not executed because of language issues
  modules/social_features/social_event/config/update/social_event_update_121003.yml
  modules/social_features/social_event/config/update/social_event_update_121004.yml
  modules/social_features/social_event/social_event.install
Labels: type: bug, status: needs review, status: needs backport, prio: high, team: guardians

#3858 PROD-29280: Ban helper OOP pattern
  .github/workflows/bestPractices.yml
  .github/workflows/bestPracticesFeedback.js
Labels: status: needs review, prio: medium, team: nucleus, type: improvement

#3835 Issue #3436775: No results when filtering by User on `admin/content/comments` and `admin/people`
  cspell.baseline.txt
  modules/social_features/social_comment/config/install/views.view.comment.yml
  modules/social_features/social_comment/config/update/social_comment_update_12201.yml
  modules/social_features/social_comment/social_comment.info.yml
  modules/social_features/social_comment/social_comment.install
  modules/social_features/social_user/config/install/views.view.user_admin_people.yml
  modules/social_features/social_user/config/update/social_user_update_12201.yml
  modules/social_features/social_user/social_user.install
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3850 Issue #3439386: Remove extra "to" in enrolees/members form confirmation messages
  modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersViewsBulkOperationsConfirmAction.php
  modules/social_features/social_group/modules/social_group_gvbo/src/Form/SocialGroupViewsBulkOperationsConfirmAction.php
  tests/behat/features/capabilities/event-an-enroll/event-bulk.feature
  translations.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3872 Issue #3442170: Remove outdated patch from Social Blue theme
  composer.json
Labels: status: needs review, prio: medium, type: dependencies, team: guardians

#3856 Issue #3439974: Activity creator breaking down when the referenced entity does not exist
  modules/custom/activity_creator/src/ActivityFactory.php
Labels: type: bug, status: needs review, status: needs backport, prio: high, team: guardians

#3874 Internal: Add Configuration to influence the order of branding features
  modules/social_features/social_branding/config/schema/social_branding.schema.yml
  modules/social_features/social_branding/social_branding.api.php
  modules/social_features/social_branding/social_branding.info.yml
  modules/social_features/social_branding/social_branding.links.menu.yml
  modules/social_features/social_branding/social_branding.module
  modules/social_features/social_branding/social_branding.permissions.yml
  modules/social_features/social_branding/social_branding.routing.yml
  modules/social_features/social_branding/src/Form/SocialBrandingFeaturesForm.php
  modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/PreferredFeatures.php
  modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.info.yml
  modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.install
  modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.module
  modules/social_features/social_branding/tests/modules/social_branding_empty_test/social_branding_empty_test.info.yml
  modules/social_features/social_branding/tests/modules/social_branding_empty_test/social_branding_empty_test.module
  modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.module
  modules/social_features/social_branding/tests/src/Kernel/GraphQL/BrandingGraphQLTest.php
  phpstan-baseline.neon
Labels: type: feature request, status: needs review, prio: high, team: guardians

#3845 Issue #3438139: Add "Group types" to groups migration
  modules/social_features/social_group/social_group.install
  tests/behat/features/capabilities/groups/groups-view-overview-filter.feature
Labels: team: enterprise, status: needs review, prio: high, type: improvement

#3861 Issue #3440298: Deprecate Social Lazy Loading module
  cspell.baseline.txt
  modules/custom/social_lazy_loading/social_lazy_loading.info.yml
  modules/social_features/social_core/social_core.install
  modules/social_features/social_embed/social_embed.install
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedLazyFilter.php
Labels: type: feature request, status: needs review, prio: medium, team: guardians

#3879 PROD-29431: Change link to Review Open Social
  modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml
Labels: prio: high, internal, type: improvement, team: guardians

#3843 Internal: Remove Definition of Done from Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: prio: low, team: nucleus, internal, type: improvement
