Repository goalgorilla/open_social, pull requests merged in 2024-11, with the labels that each got.

#4111 PROD-29995: Implement EDA event for when a user completes the process for account registration
  modules/custom/social_eda/src/Types/Application.php
  modules/social_features/social_event/src/EdaHandler.php
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/social_user.services.yml
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/src/Event/UserEventData.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: high

#4143 PROD-30978: Implement EDA event for when a user profile is updated
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4151 PROD-30974: Implement "user logs in" event for the EDA
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/src/Event/UserEventDataLite.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4162 Issue #348563: Lock Views ef Fieldset module on 1.7.0 version
  composer.json
Labels: type: bug, status: needs review, type: dependencies, prio: critical, team: guardians

#4136 PROD-30972: Implement "user enrolls to event" event for the EDA
  modules/social_features/social_event/asyncapi.yml
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.services.yml
  modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
  modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4149 PROD-30822: Add bootstrap patch for Drupal 11 compatibility
  composer.json
Labels: type: feature, status: needs review, prio: medium, team: guardians

#4148 Issue #3484615: Remove block button from Private Message using hook-entity-view
  modules/social_features/social_private_message/social_private_message.module
Labels: type: bug, status: needs review, prio: medium, team: guardians

#4154 PROD-30973: Implement "user cancels enrollment to event" event for the EDA #4142
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
  modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4157 PROD-30977: Implement "user is unblocked" event for the EDA
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4180 Internal: Remove dependency from specific poackages in behat.yml
  .github/workflows/behat.yml
Labels: team: enterprise, status: needs review, prio: high, type: repository

#4171 Internal: Fix PHPStan errors
  phpstan-baseline.neon
Labels: type: bug, team: enterprise, status: needs review, prio: critical

#4166 PROD-31206: Implement EDA event for when a user's settings and email address are updated
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/src/Event/UserEventEmailData.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4174 Issue #3486730: "View group" button is broken in "group_core_comments" module
  modules/custom/group_core_comments/assets/js/group_core_comments.js
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4141 Issue #3484275: Album feature still visible when disabled in settings
  modules/social_features/social_album/social_album.links.menu.yml
  modules/social_features/social_album/social_album.module
  modules/social_features/social_album/src/Controller/SocialAlbumController.php
  modules/social_features/social_album/src/EventSubscriber/AlbumAccessSubscriber.php
  modules/social_features/social_album/src/Form/SocialAlbumSettingsForm.php
  tests/behat/features/capabilities/album/album-disabled-in-group.feature
  tests/behat/features/capabilities/album/album-enabled-in-group.feature
  tests/behat/features/capabilities/album/album-sm-disabled.feature
  tests/behat/features/capabilities/album/album-sm-enabled.feature
  tests/behat/features/capabilities/album/album-vu-disabled.feature
  tests/behat/features/capabilities/album/album-vu-enabled.feature
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4177 Issue #3298886: Fix group statistics count method
  modules/social_features/social_group/social_group.services.yml
  modules/social_features/social_group/src/GroupStatistics.php
  phpstan-baseline.neon
Labels: type: bug, scope: community management system, status: needs review, prio: high, team: iata

#4183 Issue #3487220: Fix user group list
  modules/social_features/social_group/src/Plugin/views/argument/UserUid.php
Labels: type: bug, scope: community management system, status: needs review, prio: high, team: iata

#4167 PROD-31207: Implement an EDA event for when a user changes its locale information
  modules/social_features/social_user/asyncapi.yml
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4186 PROD-31314: Implement "user is pending" event for the EDA
  modules/social_features/social_user/social_user.module
  modules/social_features/social_user/src/EdaHandler.php
  modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: low

#4190 PROD-31065: [IOSA-SUP] Reported content cannot be seen or deleted from the Report Overview Page
  modules/social_features/social_content_report/config/install/views.view.report_overview.yml
  modules/social_features/social_content_report/config/update/social_content_report_update_130003.yml
  modules/social_features/social_content_report/social_content_report.install
  modules/social_features/social_content_report/src/Controller/ReportController.php
  modules/social_features/social_content_report/src/Plugin/views/field/LinkReportClose.php
Labels: type: bug, prio: medium, team: iata

#4178 PROD-31232: Implement "group create" event for the EDA
  modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.services.yml
  modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Event/GroupEntityData.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Types/GroupMembershipMethod.php
  modules/social_features/social_group/modules/social_group_flexible_group/src/Types/GroupVisibility.php
  modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4201 PROD-30967: Add hux module as core dependency
  composer.json
  modules/social_features/social_core/social_core.info.yml
  modules/social_features/social_core/social_core.install
Labels: status: needs review, prio: medium, type: dependencies, team: guardians

#4202 PROD-31388: Update Drupal core minimum to 10.3.9 for security reasons
  composer.json
Labels: type: feature, prio: medium, team: guardians

#4203 PROD-31404: Add patch to fix Tugboat building issue
  composer.json
Labels: status: needs review, prio: high, type: repository, team: guardians

#4204 Issue #3477793: Fix social_group_flexible_group_update_130006 update
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Labels: type: bug, team: enterprise, status: needs review, prio: high

#4189 PROD-31341: Implement group unpublish EDA event
  modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
  modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4206 PROD-31219: Update broken NL translation
  translations/nl.po
Labels: type: bug, prio: low, team: guardians

#4212 Issue #3490022 - Revert #4183 from `12.4.x` to fix `Column not found: 1054 Unknown column 'gc.plugin_id'`
  modules/social_features/social_group/src/Plugin/views/argument/UserUid.php
Labels: type: bug, status: needs review, prio: critical, team: guardians, backport: not needed

#4182 PROD-31252: Error on EdaEventEnrollmentHandler while deleting users
  modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
  modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium
