Repository goalgorilla/open_social, pull requests merged in 2024-06, with the labels that each got.

#3916 Issue #3451029: Display "followers counter" only for the followers_count view mode
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: type: bug, team: enterprise, status: needs review, prio: low

#3915 Issue #3450999: Group types translations are not visible in teasers and group page
  modules/social_features/social_group/social_group.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3921 Issue #3452925: Fix issue with preview popup element on the group pages
  modules/social_features/social_core/assets/css/preview-el.css
  modules/social_features/social_core/assets/css/preview-el.scss
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3917 Revert secret:// to private:// from field_file field
  modules/social_features/social_core/social_core.install
  modules/social_features/social_node/config/install/field.storage.node.field_files.yml
Labels: type: bug, status: needs review, prio: critical, team: guardians

#3920 Issue #3452660: Grequest compatibility with group v2
  modules/custom/grequest/grequest.services.yml
  modules/custom/grequest/src/Plugin/Group/RelationHandler/GroupMembershipRequestPermissionProvider.php
Labels: type: bug, prio: high, team: guardians

#3925 Issue #3454117: use a post update hook to fix base field override references to GroupContent which is updated in v2 of Groups
  composer.json
Labels: type: bug, status: needs review, prio: critical, team: guardians, backport: not needed

#3926 Issue #3454115: Deny access to unpublished events for enrolled users
  modules/custom/entity_access_by_field/src/EntityAccessHelper.php
Labels: type: bug, team: enterprise, status: needs review, prio: high

#3918 Issue #3452477: Change the title of the Likes pop-up for posts
  modules/social_features/social_like/social_like.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3930 Issue #3454680: Error "GroupMembershipRequestAccessControl" not found
  modules/custom/grequest/grequest.services.yml
  modules/social_features/social_group/modules/social_group_request/social_group_request.install
Labels: type: bug, team: enterprise, status: needs review, prio: high

#3939 Internal: Lock `drupal/search_api_solr`
  composer.json
Labels: type: bug, status: needs review, prio: critical, team: guardians, backport: not needed

#3943 PROD-29920: Bump version of `data_policy` to 2.0.1
  composer.json
Labels: team: enterprise, type: feature, status: needs review, prio: high

#3934 Issue #3454972: Enrolment & Invite pages in Manage Members in Events and Groups does show selected users
  modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
  modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
  phpstan-baseline.neon
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3935 Issue #3455025: Fix type error when users directly goes to `social_group_request.anonymous_request_membership`
  modules/social_features/social_group/modules/social_group_request/social_group_request.services.yml
  modules/social_features/social_group/modules/social_group_request/src/EventSubscriber/RedirectSubscriber.php
  modules/social_features/social_group/modules/social_group_request/src/Form/GroupRequestMembershipRequestAnonymousForm.php
  phpstan-baseline.neon
  tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-anonymous.feature
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3936 Issue #3455400: Move group_admin to group_manager group role only for SM/CM creators
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Labels: type: bug, team: enterprise, prio: high, status: needs merge

#3938 PROD-29890: Update Github workflows to use the new Docker image with `rdkafka`
  .github/workflows/behat.yml
Labels: team: enterprise, status: needs review, prio: low, type: repository

#3949 Updates: socialbase and socialblue themes to the 2.6.0
  composer.json
Labels: team: enterprise, status: needs review, prio: medium, type: dependencies
