Repository goalgorilla/open_social, pull requests merged in 2024-09, with the labels that each got.

#4030 Issue #3468336: SM can receive emails about inappropriate content
  modules/social_features/social_content_report/social_content_report.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4057 Issue #3472091: Add cache context by user for "GroupHeroBlock" block
  modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php
Labels: type: bug, team: enterprise, status: needs review, prio: low

#4058 Issue #3427043: Hide activities about following content tags for non-followers
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: type: bug, team: enterprise, status: needs review, prio: low

#4063 Issue #3472091: Change cache context of "GroupHeroBlock" block from user to user group permissions
  modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php
Labels: type: refactoring, team: enterprise, status: needs review, prio: high

#4070 Issue #3473556: Disable the placeholder for Embed URL when adding or editing content
  modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4071 Issue #3473583: Anonymous event enrollees see their names in emails
  modules/social_features/social_swiftmail/social_swiftmail.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4068 Issue #3473138: Add default permission for Content Tags based in Taxonomy Access Fix
  modules/social_features/social_tagging/config/modify/social_tagging.default_permissions.yml
Labels: type: bug, status: needs review, prio: medium, team: guardians

#4078 Issue #3474659: Fix filters for "All groups" view
  modules/social_features/social_tagging/social_tagging.module
  modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
Labels: type: bug, team: enterprise, status: needs review, prio: high

#4082 Issue #3464465: Prevent "Page not found" for non-translated content pages
  modules/custom/social_language/social_language.services.yml
  modules/custom/social_language/src/PathProcessor/SocialLanguagePathProcessor.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4076 Issue #3474231: Translate the emoji picker search input
  modules/social_features/social_emoji/assets/js/social_emoji_picker.js
  modules/social_features/social_emoji/social_emoji.module
Labels: team: enterprise, type: feature, status: needs review, prio: low

#4045 PROD-30133: Implement test coverage for "event create" EDA event
  cspell.words.txt
  modules/social_features/social_event/src/EdaHandler.php
  modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php
  phpstan-baseline.neon
  tests/composer.json
Labels: team: enterprise, status: needs review, prio: medium, type: test

#4090 Internal: Remove outdated patch after new socialbase theme release
  composer.json
Labels: status: needs review, prio: high, type: dependencies, team: guardians

#4086 Issue #3475568: Add hyperlink to Expertise and Interests profile tags
  composer.json
Labels: type: feature, status: needs review, prio: medium, team: guardians

#4091 Issue #3475825: Remove the UUID null as it can cause issues when config has no UUID
  modules/social_features/social_profile/config/install/views.view.newest_users.yml
  modules/social_features/social_profile/config/update/social_profile_update_130002.yml
Labels: type: bug, status: needs review, prio: high, team: guardians
