Repository goalgorilla/open_social, pull requests merged in 2024-08, with the labels that each got.

#4000 Issue #3464971: Event types are displayed in the default language
  modules/social_features/social_event/modules/social_event_type/social_event_type.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3984 Issue #3463318: Implement the ability to tag groups based on specific bundles.
  modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
  modules/social_features/social_tagging/config/install/social_tagging.settings.yml
  modules/social_features/social_tagging/social_tagging.install
  modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
  modules/social_features/social_tagging/src/SocialTaggingOverrides.php
  modules/social_features/social_tagging/src/SocialTaggingService.php
  modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
Labels: type: refactoring, status: needs review, prio: medium, team: iata

#4001 Issue #3426460: Error to save Account Settings
  modules/social_features/social_user/social_user.install
Labels: type: bug, status: needs review, prio: medium, team: guardians

#4002 #3465292: The Unique Nickname field is enabled without Nickname field
  modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
Labels: type: bug, status: needs review, prio: medium, team: guardians

#4003 PROD-29620: Replace all EDA Handlers with dummies if there is no Publisher
  modules/social_features/social_core/src/EdaDummyHandler.php
  modules/social_features/social_core/src/SocialCoreServiceProvider.php
  modules/social_features/social_event/social_event.services.yml
  phpstan-baseline.neon
Labels: team: enterprise, type: feature, status: needs review, prio: low

#3996 Issue #3464499: Hide Revisions tab for groups
  modules/social_features/social_core/social_core.module
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3995 Issue #3464465: "Page not found" on the content pages that don't have current language translation
  modules/custom/social_language/social_language.services.yml
  modules/custom/social_language/src/PathProcessor/SocialLanguagePathProcessor.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#4015 Issue #3466883: Fix copy in group settings to "Allow verified users to create new groups"
  modules/social_features/social_group/config/schema/social_group.schema.yml
  modules/social_features/social_group/src/Form/SocialGroupSettings.php
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3982 #3456839: Flexible group book update hook 13002 incorrect due to typo and crashing.
  modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.install
Labels: type: bug, status: needs review, prio: critical, team: guardians

#4028 Issue #3468174: Path alias can be set to an internal file path
  modules/custom/social_path_manager/social_path_manager.module
Labels: type: bug, status: needs review, prio: medium, team: iata

#4025 Issue #3468529: Update constraint to be able to use for users
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierUniqueExternalIdConstraintValidator.php
Labels: type: bug, prio: high, team: iata

#4037 PROD-30212: Lock the Social Blue at 2.6.2 version
  composer.json
Labels: type: bug, status: needs review, prio: critical, team: guardians

#4031 Issue #3468340: Hide Revisions tab from Manage members page in the group
  modules/social_features/social_core/social_core.module
Labels: team: enterprise, type: feature, status: needs review, prio: low

#3981 Add treatment to Activities replacement-token to get entity from grou…
  modules/social_features/social_activity/social_activity.tokens.inc
Labels: type: bug, status: needs review, prio: high, team: guardians

#4041 Issue #3469681: Allow to change batch size for activities deletion during user cancellation
  modules/custom/activity_creator/src/Service/ActivityCreatorBatchActivityDeletion.php
Labels: type: bug, team: enterprise, status: needs review, prio: high

#4039 Issue #3469391: Fix profile tag translation
  modules/social_features/social_profile/src/SocialProfileTagService.php
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#4052 Issue #3470967: Account Settings - Copy improvements
  modules/social_features/social_user/social_user.module
  tests/behat/features/capabilities/account/verified-user.feature
  translations.php
Labels: team: enterprise, type: feature, status: needs review, prio: low
