Repository goalgorilla/open_social, pull requests merged in 2024-07, with the labels that each got.

#3942 PROD-29703: Provide external identifier field
  modules/social_features/social_core/config/schema/social_core.schema.yml
  modules/social_features/social_core/src/Plugin/Field/FieldFormatter/ExternalIdentifierDefaultFormatter.php
  modules/social_features/social_core/src/Plugin/Field/FieldType/ExternalIdentifierItem.php
  modules/social_features/social_core/src/Plugin/Field/FieldWidget/ExternalIdentifierDefaultWidget.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierEmptySubfieldsConstraint.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierEmptySubfieldsConstraintValidator.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerIdConstraint.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerIdConstraintValidator.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerTargetTypeConstraint.php
  modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerTargetTypeConstraintValidator.php
  modules/social_features/social_core/tests/modules/social_core_test_entity_provider/social_core_test_entity_provider.info.yml
  modules/social_features/social_core/tests/modules/social_core_test_entity_provider/src/Entity/ExternalOwnerEntityTestProvider.php
  modules/social_features/social_core/tests/src/Kernel/ExternalIdFieldTypeTest.php
Labels: type: feature, prio: high, team: iata, status: needs merge

#3950 PROD-29703: Add an external identifier field to the user entity
  modules/social_features/social_user/config/install/field.field.user.user.field_external_identifier.yml
  modules/social_features/social_user/config/install/field.storage.user.field_external_identifier.yml
  modules/social_features/social_user/config/update/social_user_update_13003.yml
  modules/social_features/social_user/social_user.install
Labels: type: feature, prio: high, team: iata

#3946 Issue #3456218: Revoke Administer taxonomy permission for SM
  modules/social_features/social_content_report/social_content_report.install
  modules/social_features/social_core/social_core.install
  modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
Labels: team: enterprise, type: feature, status: needs review, prio: high

#3892 Issue #3445775: validateEntityFields is not correctly transforming date
  tests/behat/features/bootstrap/EntityTrait.php
Labels: status: needs review, prio: medium, type: test, team: iata

#3919 Issue #3452643: Change uri_scheme of field_media_file to secret
  modules/custom/social_media_system/config/install/field.storage.media.field_media_file.yml
  modules/custom/social_media_system/config/update/social_media_system_update_12103.yml
  modules/custom/social_media_system/social_media_system.install
Labels: type: bug, prio: high, team: iata

#3924 Issue #3453946: Add alternative token with capitalized entity bundle label
  modules/social_features/social_comment/social_comment.tokens.inc
  modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
  modules/social_features/social_group/social_group.tokens.inc
  modules/social_features/social_like/social_like.tokens.inc
  modules/social_features/social_mentions/social_mentions.tokens.inc
Labels: team: enterprise, type: feature, status: needs review, prio: high

#3977 Issue #3460756: Fix behat tests for address
  cspell.words.txt
  tests/behat/features/capabilities/event/all-day-timezone.feature
  tests/behat/features/capabilities/event/event-create.feature
  tests/behat/features/capabilities/groups/flexible/groups-flexible-create.feature
  tests/behat/features/capabilities/profile/edit-profile.feature
  tests/behat/features/capabilities/profile/hide-profile-field-groups.feature
Labels: type: bug, status: needs review, prio: high, team: iata

#3976 Issue #3460734: Define social_core as social_user dependency
  modules/social_features/social_user/social_user.info.yml
Labels: type: bug, prio: low, team: iata

#3972 PROD-30063: Add test coverage for flexible group request to join
  tests/behat/features/bootstrap/GroupContext.php
  tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-anonymous.feature
  tests/behat/features/capabilities/groups/join/groups-join-direct.feature
  tests/behat/features/capabilities/groups/join/groups-join-request-manage.feature
  tests/behat/features/capabilities/groups/join/groups-join-request.feature
Labels: scope: community management system, prio: high, type: test, team: guardians

#3973 Issue #3460260: Missing permissions for social_group_welcome_message
  modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.install
Labels: type: bug, status: needs review, prio: medium, team: guardians

#3979 Issue #3427043: Hide activities about following content tags for non-followers
  modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Labels: type: bug, team: enterprise, status: needs review, prio: medium

#3975 PROD-29755: Implement "event create" EDA publishing
  modules/social_features/social_event/social_event.module
  modules/social_features/social_event/social_event.services.yml
  modules/social_features/social_event/src/EdaHandler.php
  modules/social_features/social_event/src/Event/EventCreateEventData.php
  phpstan-baseline.neon
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3990 Revert mistakenly pushed branch `issue/PROD-30134-move-asyncapi-definition-to-module`
  modules/social_features/social_event/asyncapi.yml
Labels: team: enterprise, type: revert

#3994 Issue #3464394: Improve behavior of the profile preview popup
  modules/social_features/social_core/assets/css/preview-el.css
  modules/social_features/social_core/assets/css/preview-el.scss
  modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
Labels: type: bug, team: enterprise, status: needs review, prio: low

#3991 PROD-30134: Move AsyncAPI definition for "event create" event into the social_event module
  modules/social_features/social_event/asyncapi.yml
Labels: team: enterprise, type: feature, status: needs review, prio: medium

#3988 Issue #3463599: Fix Behat Lint warnings from Social GDPR module
  tests/behat/features/bootstrap/GDPRContext.php
  tests/behat/features/capabilities/gdpr/create-data-policy.feature
  tests/behat/features/capabilities/gdpr/data-policy-agreements-report-filters.feature
  tests/behat/features/capabilities/gdpr/data-policy-agreements-report.feature
  tests/behat/features/capabilities/gdpr/inform-block.feature
  tests/behat/features/capabilities/gdpr/management-data-policy.feature
  tests/behat/features/capabilities/gdpr/user-consent.feature
  tests/behat/features/capabilities/gdpr/view-data-policy.feature
Labels: status: needs review, prio: medium, type: test, team: guardians
